### ISSUE TITLE
Introduce command to control slowmode

### ISSUE THREAD

**Issue by kwzrd** [python-discord/bot#1019]
**Context**
High profile channels such as `#python-general` have slowmode enabled to make chat traffic manageable. The amount of delay is adjusted based on current traffic in the channel.

**Problem**
The Discord GUI only allows `@Admins` to choose from a limited amount of options.

![image](https://user-images.githubusercontent.com/44734341/86116244-66900d00-bacd-11ea-8e8e-688b97112340.png)

The API, however, [allows much more granular control](https://discordpy.readthedocs.io/en/latest/api.html#discord.TextChannel.edit), taking ints in the range `[0, 21600]`. As such, we often use int eval to set custom values, commonly 2 seconds during low traffic times.

**Proposal**
The proposal is to introduce a bot command which will take a channel and a delay, and forward them to the API.

The advantages include:
* Convenience: we no longer need to int eval custom values
* The command can be made available to mods, which otherwise do not have access to the channel control panel

The implementation should be fairly trivial. Command signature takes a text channel (a `d.py` convertor makes this convenient), and an `int` delay. The delay is checked to ensure it fits into the correct range, with an informative message returned otherwise. If the delay is valid, it is passed to the `TextChannel.edit` method (linked above).

**Comment by Den4200** [comment]
I think this would be a very useful command for the mods. I'd be willing to take this issue since it's quite simple 😃

**Comment by kwzrd** [comment]
Excellent, it's all yours. :+1:

**Comment by j03b** [comment]
This may be out of scope but could we integrate with the scheduler to allow slow modes that last a certain amount of time?

For example: `!slowmode #python-general 6h 5s`

**Comment by j03b** [comment]
Also, we can probably use the duration converter to set the slowmode instead of an int argument.

**Comment by Den4200** [comment]
@j03b
> This may be out of scope but could we integrate with the scheduler to allow slow modes that last a certain amount of time?

I don't particularly mind implementing this, but it will quickly become fairly complex. 

Using your example, `!slowmode #python-general 6h 5s`, what would the slowmode delay be after the 6 hours are up? Would the user need to specify another delay, which kicks in after the duration? Or would it reset to some default delay set for the specific channel?

This would also need to be persistent across restarts, so the slowmode delay will become the second delay/default delay after the specified duration. We'd have to use some form of persistent storage for this, which would probably be Redis.

> Also, we can probably use the duration converter to set the slowmode instead of an int argument.

I'd have to create a new converter since the duration converter returns a future date, instead of a timedelta. I think this would be a good idea though and should be pretty trivial to implement.

**Comment by j03b** [comment]
Sounds good to me.

I agree it will become complex so we can drop the persistence/scheduler design.

I don't think a new converter will be necessary. Just taking the current one and then `seconds = (future_date - datetime.now()).total_seconds()` should suffice.

**Comment by Den4200** [comment]
Ah yeah, that's smart. It feels a bit redundant since the converter adds the timedelta to the current time and now we're subtracting it back, but I don't think it matters too much.

**Comment by Den4200** [comment]
I've tested this out, but there's a bit of a delay between conversion and when the function executes.

![image](https://user-images.githubusercontent.com/52584399/86261480-9baf6480-bb8c-11ea-804e-634f290782ae.png)

We could just add 1 to this, but that wouldn't be too reliable. I think I'll just create a new converter.

**Comment by ks129** [comment]
I wrote this idea to #meta too some times ago, but maybe should this have `!slow` to disable slowmode and when adding more `o`s (`!sloooooooow`), then this should activate slowmode (without scheduler, so until disabling/changing), where every `o` except first is 1s of slowmode. Something like `silence`.

**Comment by j03b** [comment]
I don't really think that's a great idea. This feels like something that will typically be used in an internal channel to set a slowmode and in certain situations we may want to go into higher ranges (I don't want a thousand 'o's :smile:)
