### ISSUE TITLE
PIn the opening message in help  channel for the session duration

### ISSUE THREAD

**Issue by OMotornyi** [python-discord/bot#1020]
Following the discussion that happened in [meta today](https://ptb.discordapp.com/channels/267624335836053506/429409067623251969/727504311638294582) I would like to suggest a new feature to the bot: make it pin the first message sent in the newly opened help session, and, of course, un-pin it when the help channel is closed.
Reasoning: some help session tend to drag out for longer time and thus to have lots of messages. This makes it very hard for anyone who's willing to to help but has not been following the discussion from the start like [here](https://ptb.discordapp.com/channels/267624335836053506/696348850981699624/727507952281452576) : having the message pinned to the channel would provide with the fast and easy way to look up the original question.

**Comment by ks129** [comment]
When this is gonna be approved, then I'd like to do this.

**Comment by j03b** [comment]
Approved, go for it @ks129!

**Comment by OMotornyi** [comment]
I forgot to mention that I would not mind to try it myself, but I think it's better that someone who knows bot internals already do it, as I never touched it, so with my workload it can take time :)
