### ISSUE TITLE
Add way to get code block from another message in eval command

### ISSUE THREAD

**Issue by ks129** [python-discord/bot#1022]
## Proposal
Eval command should support passing message or nothing instead code. When you pass the message, this should try parse code block from this message. This should be implemented that way that in the message, there can be text to before and after message: this should ignore it. When passing nothing, then this should try to get the last message and parse this code block.

## Additional ideas
Also, maybe when a message has multiple Python code block, this should ask from the user with reactions which code block this should run.

**Comment by AtieP** [comment]
Here's my implement:

1. Convert `code` parameter to an instance of `int` (if while the process is running ValueError is raised then it's actual code) [Go to 4]
2. Crawl on all channels using a `for` loop to be able to fetch the message. (https://discordpy.readthedocs.io/en/latest/api.html#discord.abc.Messageable.fetch_message) 
3. If the message is found, strip the prefix and convert it to a proper format. Else, display some fancy error message and return. (sanitize it eeeh)
4. Execute the code.

Please don't assign me to this for now.

**Comment by ks129** [comment]
@AtieP I think better converter should `Union[discord.Message, str, None]`? Then you don't have to do so much parsing. When `None`, this should parse **last** message.

**Comment by AtieP** [comment]
Good idea, didn't thought about it.

**Comment by AtieP** [comment]
But what do you mean "last message"?

**Comment by SebastiaanZ** [comment]
> Crawl on all channels using a for loop to be able to fetch the message. (https://discordpy.readthedocs.io/en/latest/api.html#discord.abc.Messageable.fetch_message)

Ignoring the rest of the implementation details for now, in what kind of situation do you expect this command to be executed? I think we'd need a very good reason to try and fetch a message on every channel in our guild and I'm not sure this command is enough reason for such an API call heavy implementation. Wouldn't the command be issued mostly in the same channel as the message containing the code was sent to?

We could extend our search to the bot's message cache, which would include most (recent) messages sent regardless of channel and/or use the `discord.Message` converter (which should allow for a message link).

**Comment by AtieP** [comment]
Your points are right. Personally I don't expect much usage of this feature and this is really heavy for the Discord API, and the bot as well.

**Comment by ks129** [comment]
@AtieP Last message is message that is sent to channel exactly before command execution message.

**Comment by wookie184** [comment]
I agree with comments that this doesn't seem massively useful, so i'll close this.
