### ISSUE TITLE
Purge messages up to given message

### ISSUE THREAD

**Issue by wookie184** [python-discord/bot#1024]
**Problem:**
Currently the purge/clean command takes the number of messages to clean as the only way of specifying how far to clean, this can cause some difficulties when trying to clean lots of messages as you either have to guess roughly how many messages were sent or count them manually, and also makes it easy to go too far and delete messages you didn't want to.

**Proposed Solution:**
We could allow a message ID or link to be given as an argument instead of the number of messages. The bot would then delete all messages up to that message. This would speed up the process of removing messages and reduce the possibility of human error.

I'm not sure what the best way to modify the command to accept the ID as an argument would be so that would need to be discussed.

**Comment by Senjan21** [comment]
I can work on that issue if that's possible.

**Comment by Senjan21** [comment]
Implemented in #1055
