### ISSUE TITLE
Command to time code execution

### ISSUE THREAD

**Issue by wookie184** [python-discord/bot#1025]
It could be useful to have a [timeit](https://docs.python.org/3/library/timeit.html#timeit.timeit)-like bot command to time code execution. Some ideas of features the command could have are:
- The ability to specify how many times the code should be run. It could also be interesting if this was calculated automatically like how the [timeit Command-Line Interface](https://docs.python.org/3/library/timeit.html#timeit-command-line-interface) does.
- The ability to take in multiple snippets of code to compare
- The output could just be the time taken as `timeit.timeit` gives (e.g `0.3018611848820001`) but it would be nicer if the output was in a more human friendly format (e.g. the timeit CLI outputs more like `10000 loops, best of 5: 30.2 usec per loop`)

I would assume it wouldn't be too difficult to implement as it could borrow from/use most of the same code as `!eval` but I am not sure.

**Comment by MarkKoz** [comment]
This sounds pretty easy. It can generate a `timeit()` code snippet and insert the given code into the first argument. It'd need to have a way to escape quotes. That new code can then be sent to Snekbox.

Supporting multiple code snippets is possible, but adds complexity to the input parser. Furthermore, Snekbox still has a time limit which all snippets would share. I think it's best to not support that; it isn't much trouble for users to invoke a separate eval.

**Comment by MarkKoz** [comment]
That being said, it may make more sense to add another endpoint to Snekbox, since it's pretty simple on that side to just invoke `python -m timeit` rather than `python -c`.

**Comment by Akarys42** [comment]
I think the implementation we choose for this feature would depend on if decide to introduce a mypy endpoint; if we already have two endpoints I think it would make sense to have a third one, otherwise wrapping the code in a timeit snippet makes more sense IMO

**Comment by davisschenk** [comment]
Id like to implement this feature

It would be fairly trivial to wrap the code in a timeit snippet to test the time it takes. Currently Snekbox only has one endpoint and im not sure it would make sense to reimplement eval with `python -m timeit <code>` when its easy to just eval `timeit.main([<code>])`

**Comment by MarkKoz** [comment]
@davisschenk That approach sounds fine, though it is noteworthy that `main()` is undocumented. I'm not sure if this is unintentional or if it implies that it's not part of the public API. In any case, I'll assign you to this issue.

**Comment by davisschenk** [comment]
`main([<args>])` is just the equivalent of `python -m timeit <args>` 

Anyone have any opinions on whether or not this should be implemented as a sub-command of `eval` or as a standalone command?

**Comment by MarkKoz** [comment]
Standalone. It's not returning the code's output so it's not strictly an eval of the original input. Furthermore, a subcommand would make it impossible to use the subcommand name at the start of the code for an eval unless it was in a code block. Lastly, I imagine it'd complicate parsing of revaluations.

**Comment by WillDaSilva** [comment]
It seems like this issue has been abandoned. I would like to implement it if there are no objections.

**Comment by wookie184** [comment]
> 
> 
> It seems like this issue has been abandoned. I would like to implement it if there are no objections.

@WillDaSilva 

If @ToxicKidz isn't interested in continuing their PR that sounds fine, although I think part of the reason that PR stalled is because there wasn't much of a conclusion on what the implementation should be. 

Do you have a plan for implementation? Do you want to continue @ToxicKidz's PR (in which case do you have a plan for addressing Numerlor's comment there) or do you have a different idea?

**Comment by WillDaSilva** [comment]
@wookie184  On second thought I would rather not implement this anymore. Sorry for any trouble.

**Comment by wookie184** [comment]
> @wookie184  On second thought I would rather not implement this anymore. Sorry for any trouble.

No worries
