### ISSUE TITLE
Role reminders

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/bot#1026]
We currently have a feature `!remind` which will send the caller a reminder after a certain amount of time has passed.

But sometimes, a moderator or admin will want to create a reminder for his whole team. For example, maybe something needs to be followed up in 7 hours but the moderator or admin will not be available at that time.

It should also be possible to create a reminder for another user than yourself.

## New command syntax
`!remind <optional role mention or user mention> <duration>`.

For example, `!remind @Admins 7H23M` or `!remind @joe 1w`

## Access restriction
- Role reminders should be restricted to Mods+
- Reminders for yourself or for other users should be restricted to Helpers+

## Implementation details
Use a greedy converter. We're already doing this for the `!clean` command to take an optional channel, for instance.

**Comment by ks129** [comment]
> Reminders for yourself or for other users should be restricted to Helpers+
Do you mean that normal users can't create reminders anymore? Only Helpers+ can create reminders?

**Comment by kosayoda** [comment]
@lemonsaurus I'll clarify some implementation details, let me know if it matches what you had in mind.

- Roles/persons to ping are sent to the site using the api and stored in a new field.
- Allow setting reminders for multiple roles/persons (or a combination of the two) in one go.

---
Questions:
- Do we want to set a limit on the number of roles/persons to set a single reminder for?
- Do we want to care about what roles we can set reminders for?

**Comment by lemonsaurus** [comment]
> > Reminders for yourself or for other users should be restricted to Helpers+
> 
> Do you mean that normal users can't create reminders anymore? Only Helpers+ can create reminders?

My mistake, I thought reminders were already restricted to Helpers+. Seeing as they are not, I guess they should just stay the way they are.

> Roles/persons to ping are sent to the site using the api and stored in a new field.
Yes, this will be necessary. Right now we're only storing the `author` in the database, and always sending the ping to them.

The only other alternative I can think of would be that we "bake" the ping into the `content`, but this is probably messier.

> Allow setting reminders for multiple roles/persons (or a combination of the two) in one go.
Sounds ideal.

> Do we want to set a limit on the number of roles/persons to set a single reminder for?
Since this will only be available to Mods+, naw. We trust them not to do anything stupid.

> Do we want to care about what roles we can set reminders for?
Again, I trust mods+ enough not to care about this.
