### ISSUE TITLE
Bot can be abused to @ and alert large amounts of users at once through roles such as 'Developers'

### ISSUE THREAD

**Issue by thaniel-c** [python-discord/bot#1029]
This just happened in the discord server.

**Comment by lyricalpaws** [comment]
It did

**Comment by thisToxiCFlamE** [comment]
Caused a bunch if angry developer spam, so yeah, high priority stuff.

**Comment by woaisthisgit** [comment]
damn thats really helpful thank you lyricalpaws

**Comment by lyricalpaws** [comment]
Also hi discord

**Comment by asleep-cult** [comment]
what the hell

**Comment by justsomeonenamedalex** [comment]
discord say hi

**Comment by andy0dvlpr** [comment]
This happened right now lolmao

**Comment by woaisthisgit** [comment]
put me in the screenshot uwu

**Comment by crazygmr101** [comment]
**We all know it happened right now, guys.** ._.
