### ISSUE TITLE
raw command doesn't trim lines that are too long for the paginator

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#1037]
Sentry Issue: [BOT-6H](https://sentry.io/organizations/python-discord/issues/1757973940/?referrer=github_integration)

The command uses discord.py's default `Paginator`. Can that be replaced with our `LinePaginator`, which automatically moves long text to a new page?

```
RuntimeError: Line exceeds maximum page size 1992
  File "discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "bot/cogs/information.py", line 412, in raw
    add_content(title, transformer(item))
  File "bot/cogs/information.py", line 396, in add_content
    paginator.add_line(content.replace('```', '`` `'))
  File "discord/ext/commands/help.py", line 127, in add_line
    raise RuntimeError('Line exceeds maximum page size %s' % (max_page_size))

Error executing command invoked by <REDACTED>: !raw <REDACTED>
```

**Comment by MarkKoz** [comment]
I got it to work with `LinePaginator` but it the presentation is not very readable, especially since embeds are fixed to a narrow width. How does everyone feel about sending a hastebin link if the content is over 2000 characters?

**Comment by wookie184** [comment]
Sending a hastebin link sounds like a good idea.
