### ISSUE TITLE
Refactor bot.py - Move codeblock detection logics.

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/bot#1040]
Right now, we're handling the codeblock detection stuff inside the BotCog cog. Why are we doing that? That sucks.

Remove all the codeblock parsing stuff from the BotCog cog, and make a new cog with a descriptive name (`CodeBlockDetection`?) where this logic can live. Inside the BotCog cog, we should only be doing the really simple and generic stuff, like `!about`, `!echo` and `!embed`.

**Comment by Numerlor** [comment]
#886 takes care of this, along with improving the behaviour

**Comment by lemonsaurus** [comment]
Excellent. I've linked it to this issue.
