### ISSUE TITLE
Incidents: show report datetime in archive embed

### ISSUE THREAD

**Issue by kwzrd** [python-discord/bot#1059]
As it is, the archive embeds in `#incidents-archive` show the datetime the report was actioned in both the message send time `A` the archive embed footer `B`.

![archives](https://user-images.githubusercontent.com/44734341/87923009-17f6e280-ca7d-11ea-9316-303384ce734b.png)

This means that we're archiving duplicate information and failing to archive the datetime that the incident was reported.

The proposal is to adjust the embed to show `incident.created_at` instead of `utcnow()`. This would be a trivial fix here:

https://github.com/python-discord/bot/blob/65e2c2946ddd4d2dcc6b00ec68c0b456048840db/bot/cogs/moderation/incidents.py#L91-L95

**Pros**

* We would be archiving a possibly useful piece of information, which can be used to calculate interesting stats such as response time w.r.t. time of day or whether the report contains a `@Moderators` pingu.

**Cons**

* I think the embed would be somewhat confusing. It'd be a lot more logical to have `A` and `B` switched around, so that the mod's identity is shown next to the time the report was actioned, and the helper's next to the report time. That sadly isn't possible though. Neither is it possible to have a custom footer format, e.g. `Actioned by X, Reported on: Y` as we're using the timestamp field, which will convert the utc timestamp to the client's local timezone (as it does with the message sent time, so they are in sync).
* If multiple incidents reported by the same user are actioned in succession, the Discord GUI won't show the send datetime for each, but will show the embeds as if they were sent together. This means that we will only see when each incident was reported, but not when actioned. Both pieces of information can still be easily retrieved when accessing the `Message` object programmatically, e.g. via int e though.

**Conclusion**
As shown above the technical side of things is trivial but we should discuss whether this is a change that we'd want. It'd make a lot of sense to archive both datetimes, but using the embed footer doesn't seem very elegant to me for the reason outlined above.

We originally discussed this with @TizzySaurus.

**Comment by MarkKoz** [comment]
There likely isn't much need to see the exact time, so `"Actioned by x#1234 after 53 minutes · 2020-08-06"` sounds like a good alternative.

**Comment by TizzySaurus** [comment]
> There likely isn't much need to see the exact time, so `"Actioned by x#1234 after 53 minutes · 2020-08-06"` sounds like a good alternative.

This seems to be a good solution to the issue. Only think I’d say is perhaps using “6th August [2020]” rather than “2020-08-06” due to the American vs Non-American way of doing dates, although I suppose this isn’t a big deal as long as users are aware of the format being used.

**Comment by MarkKoz** [comment]
That date is formatted by the Discord client. It will use whatever format your computer is configured with.

**Comment by TizzySaurus** [comment]
> That date is formatted by the Discord client. It will use whatever format your computer is configured with.

Then I believe the above method is the best way of proceeding with this.

**Comment by kwzrd** [comment]
> There likely isn't much need to see the exact time, so `"Actioned by x#1234 after 53 minutes · 2020-08-06"` sounds like a good alternative.

This reads fine, but it'd be difficult to work with programmatically if we ever want to crawl the channel to see average times, etc.

I think we should first try to answer the question of what we want this piece of information for.
