### ISSUE TITLE
Add Search Infraction by ID functionality

### ISSUE THREAD

**Issue by MrHemlock** [python-discord/bot#1066]
Currently, we can only look for an infraction either by the username/id of the person who got the infraction or by the content of the reason.  There is no way to search for an infraction or pull up a specific up by the ID number alone.  

This will likely need tweaking on the site repo as well since the search functionality requires an API call.

**Comment by RohanJnr** [comment]
I would like to take this up.
Here is what I believe has to be done:

SITE REPO:
- [The InfractionViewSet](https://github.com/python-discord/site/blob/master/pydis_site/apps/api/viewsets/bot/infraction.py) should have a new query param, i.e, `infraction_id` which I assume is nothing but the `Infraction` model id/pk.

BOT SIDE:
- In the [ModManagement](https://github.com/python-discord/bot/blob/master/bot/cogs/moderation/management.py) Cog, under the `Infraction search group`, a new function called `search_infraction` can be implemented which accepts the `infraction_id`.

**Comment by Den4200** [comment]
@RohanJnr There should be no need for a new parameter on the viewset:

https://github.com/python-discord/site/blob/518a39b3e2b56f942328695d5e44674976317c7c/pydis_site/apps/api/viewsets/bot/infraction.py#L59-L60

**Comment by Den4200** [comment]
I believe @scragly is taking care of this as part of a bigger redesign of the infractions system.
