### ISSUE TITLE
Remove sphinx dependency

### ISSUE THREAD

**Issue by Numerlor** [python-discord/bot#1067]
Intended more as a proposition

Only a handful of functions in sphinx are used by the bot code, specifically it's used for fetching inventories for the doc cog; but sphinx is a large package with the used code being a tiny portion of it.

### Benefits
The benefits of removing it I can think of would  be
- The code could be changed to be fully async (currently uses requests ran in executors)
- Can get rid of behaving as a sphinx app with mocks having to be created to work
- No more breaking changes from updating sphinx (#727)
- Removing one of the largest dependencies from the bot

### Drawbacks
The bot has been using it directly for a long time, mostly without issues and requires almost no maintenance on this side which could be required if it's removed
- Probably having to copy most, or at least some, from sphinx to be compatible
- Code will need to be maintained if the format is changed and sites adopt it

------------------------
The drawbacks here are minimal, but also are the benefits; any thoughts on whether it's worth bringing some of the code over while getting rid of sphinx to get our own async handling of the requests?
Their [license](https://github.com/sphinx-doc/sphinx/blob/3.x/LICENSE) should allow copying the base of the code if I understood it correctly. It's almost a copy of BSD 2-clause, with some format changes and the `All rights reserved.` text added which I don't know the exact meaning of

**Comment by MarkKoz** [comment]
Depends on how much new code we'd need to maintain. Something like 200 lines is reasonable, but if it's in the thousands then probably not.

**Comment by Numerlor** [comment]
A drop in replacement code I tried that copied the needed functions is exactly 200 lines including their longer sphinx docstrings and some comments so it should be manageable to maintain,

**Comment by MarkKoz** [comment]
Fine by me then.

**Comment by Numerlor** [comment]
I've put together a quick implementation at https://gist.github.com/Numerlor/e57096cedd06dd536cdddff86be2661f, since we have control over the output there I've decided to simply ignore the information we don't need during the parsing.
Should we also handle version 1 inventories? The implementation is simple (although I haven't tested it) but none of the bot's current inventories use that version and I've only managed to find one when searching.

**Comment by MarkKoz** [comment]
> Should we also handle version 1 inventories?

I don't mind it; it's not a lot of extra code.

**Comment by Numerlor** [comment]
I'll go ahead and push this into #1014 in the near future if there's nobody against it.
Should the sphinx license be handled like in #886 with the same file?

**Comment by MarkKoz** [comment]
> in the near future if there's nobody against it.

Fine by me. As I said, I'm not against it. Haven't had input from anyone else unfortunately.

> Should the sphinx license be handled like in #886 with the same file?

Yes, in my opinion. I haven't heard any negative feedback about this so far.
