### ISSUE TITLE
Fitting Models on Balanced Samples: 12\800Error: Perfect separation detected, results not available

### ISSUE THREAD

**Issue by Lalla96** [python-discord/bot#1070]
Hello Everyone!
I am quite new to programming and for my project I have to perform Propensity Score Matching with pymatch between some companies (Default and not), matching them according to 3 differrent variables. My code works well when I have samples of default companies larger than 20, while when I have to match fewer treated companies, I get the error attached below: Fitting Models on Balanced Samples: 4\550Error: Perfect separation detected, results not available. (or similar ones). 
Is this only because the number of treated is too small? is there a way to solve this issue?
In addition, I have no idea what 12\800 means... I find no correlation with data in my excel file.
Any help would be appreciated!!!

![cattura errore](https://user-images.githubusercontent.com/68903386/88656894-4efa7300-d0d1-11ea-939c-48e142fc1f48.PNG)

**Comment by scragly** [comment]
Hi Lalla96. Unfortunately, we're unable to help you with this, as these Github issue tickets are for issues or suggestions regarding the respective project hosted here; in this case, the `bot` project, which is the code for our community discord bot that allows us to manage our discord server. 

If you wish to ask for help on python code, you're welcome to ask in our discord server. If you're not already a member, you can join us [here](https://discord.gg/python).

Kind regards.
