### ISSUE TITLE
Should the syncer confirmation be removed?

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#1075]
The current threshold is way too low, but some of us have doubts on its usefulness. The `wait_until_guild_available` solution should prevent the cache from ever being empty. It even explicitly checks that the cache isn't empty and avoids setting the event. That being said, there may be some strange situation in which the bot receives a partial cache from Discord.

If it's not removed, then the thresholds should at least be increased. I also had the idea of only applying the size check to the deleted diffs and not the created or updated ones. What would be good thresholds for roles and users? I think it's currently set to 10 for both. 10 is probably good for deleted roles, but for users, it'd need to be somewhere in the thousands considering we have 70k members.

**Comment by MarkKoz** [comment]
@SebastiaanZ Any thoughts, since you proposed the confirmation?

**Comment by lemonsaurus** [comment]
I think we _should_ remove this. I think it's been made irrelevant by `wait_until_guild_available`.

**Comment by MarkKoz** [comment]
Thanks. I'd like input from a few more people before actioning it, especially from @python-discord/core-developers.

**Comment by SebastiaanZ** [comment]
I'm all for removal of this feature.

Honestly, with you having solved the actual cause of the issue, I don't really see this feature coming into play for legitimate reasons. If something funky does happen in the future, we'll have to a big sync instead. The frequent sync issues we've had no longer occur, though.

**Comment by MarkKoz** [comment]
Okay, it's been a few days and I got 2 "yes" responses. I'm going to start on this.
