### ISSUE TITLE
 PyNaCl library needed in order to use voice

### ISSUE THREAD

**Issue by HackBurger** [python-discord/bot#1076]
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: RuntimeError: PyNaCl library needed in order to use voice
every time i try to make my bot join the channel i get that error even though i have pynacl installed can someone help?
Join function code:
[Join function.txt](https://github.com/python-discord/bot/files/5011792/Join.function.txt)

**Comment by MarkKoz** [comment]
Hello, this place is for issues relating to our own bot. If you need help with your bot, you can ask in the designated discord.py channel in our server.
