### ISSUE TITLE
RedisCache: _redis alias is assigned too soon

### ISSUE THREAD

**Issue by kwzrd** [python-discord/bot#1090]
The `RedisCache` wrapper currently suffers from a bug which can cause an `AttributeError` if a value is looked up before the bot's `redis_session` attribute is set.

### Problem

Let's imagine that a cog using the `RedisCache` schedules a task which will perform a lookup. There is no guarantee that the cache is ready, and so the cache API methods always wait for the ready event to be set.

However, as soon as the cache attribute is accessed, the `__get__` method assigns the `self._redis` attribute:
https://github.com/python-discord/bot/blob/239fa5f43ab79435151657671ebcf21eac706fc6/bot/utils/redis_cache.py#L226-L230

This can happen before the cache is ready, and so there is no guarantee that `self.bot.redis_session` is not `None`.

It defaults to `None` here:
https://github.com/python-discord/bot/blob/239fa5f43ab79435151657671ebcf21eac706fc6/bot/bot.py#L34

And only here will the attribute be set:
https://github.com/python-discord/bot/blob/239fa5f43ab79435151657671ebcf21eac706fc6/bot/bot.py#L76-L83

At this point, the cache will report ready status, but it's `self._redis` attribute has already been assigned the `None`.

Since the cache is now ready, the lookup will proceed, and fail with the following error:
```python
2020-08-05 12:31:15 | bot.cogs.verification | ERROR | Failed to get message
Traceback (most recent call last):
  File "/bot/bot/cogs/verification.py", line 325, in _before_first_ping
    last_reminder: t.Optional[int] = await self.reminder_cache.get("last_reminder")
  File "/bot/bot/utils/redis_cache.py", line 263, in get
    value = await self._redis.hget(self._namespace, key)
AttributeError: 'NoneType' object has no attribute 'hget'
```

### Solution

The solution seems to be fairly trivial: the `self._redis` alias simply cannot be safely set before the cache is ready, and we therefore have to lookup the `redis_session` instance via the `bot` attribute.

For example, instead of:
```python
await self._redis.redismethod(...)
```
we should have:
```python
await self.bot.redis_session.redismethod(...)
```
This delays the `redis_session` resolution until after the cache is ready. The `self._redis` alias should probably be removed.

**Comment by lemonsaurus** [comment]
Makes sense to me. Let's do it.
