### ISSUE TITLE
Leaked bot token still relayed to big-brother if user is watched

### ISSUE THREAD

**Issue by wookie184** [python-discord/bot#1094]
If a user pastes a bot token and the user is currently being watched (big-brother or nomination) then it will relay the message to the watch channel, which is not ideal. The same thing would apply for webhook URLs.
Ideally it would either send nothing, or possibly a message saying that it was removed, to the watch channels.

**Comment by MarkKoz** [comment]
We need to check for the presence of a token in `on_message` before further processing. If I remember correctly, something similar is already being done for the invalid code block detection.

**Comment by AtieP** [comment]
Yeah, I agree wirh Mark. The token check must be made on the bot's `on_message` listener rather than in the cog's `on_message` listener because IIRC, the bot's listener is triggered first and you can stop all the command processing there.
