### ISSUE TITLE
Allow text to be inserted before and after eval codeblocks

### ISSUE THREAD

**Issue by Akarys42** [python-discord/bot#1104]
## Rationale

During an eval demonstration, it'd be nice to be able to insert text before and after the codeblock to comment it, instead of putting actual comments in the code, or sending two messages.

## Specifications

Here is the current regex used to extract the code of a message is this one : 

https://github.com/python-discord/bot/blob/b27c286f2ce648d021eed0c8e07476066b86dd98/bot/cogs/snekbox.py#L22-L32

We could simply insert a `.*` before and after to make it work, as in [this example](https://regex101.com/r/Xac4It/1)

**Comment by MarkKoz** [comment]
Sounds good to me. I don't see a reason to not support this. I'm not worried about cases where people have code that contains backticks.

**Comment by Shivansh-007** [comment]
This would be a great update. I definitely support this.

**Comment by mbaruh** [comment]
@Akarys42 Sounds nice
I wonder though if we'd like to take a step further and allow interleaving code blocks and text. This would allow you to do something such as:
___
!e
This is how you assign:
\```py
x = 1
\```
And then you can print it:
\```py
print(x)
\```
___
By concatenating the code blocks and then running it as usual. This should still be a fairly simple change, and it would include your idea as a private case.
If that's good then I wouldn't mind writing it.

**Comment by Akarys42** [comment]
That's a good idea, yeah.
