### ISSUE TITLE
Smart syncing of users to the site

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/bot#1119]
Currently when we sync the users to the site, we sync all 90,000 users one at a time. This is pretty much the single worst way we could possibly do this, so let's make it smarter.

See the related site-side changes required for this here: https://github.com/python-discord/site/issues/375

## Paginated retrievals
In https://github.com/python-discord/site/issues/375, I propose adding pagination to the user endpoint via DRFs built-in pagination feature. This means we'll need to make a smarter way to handle this on the bot side so that we will make one request per page.

This will be more scalable - right now there's no limit to how large the response from a request for all the users will be, and we don't want to run into issues where it's too big to handle.

## Only update the diff
Currently, we just sync all the users. We don't need to do this, if we just figure out the diff between the users we've retrieved and the users in our cache, we can just update the users who have actually changed. To do this, we can probably use 
[difflib.SequenceMatcher](https://docs.python.org/3/library/difflib.html#difflib.SequenceMatcher) to find the diff between the two and then send the diff to the API.

## Send updates in batches
Instead of updating users one at a time, we should send them in batches. In https://github.com/python-discord/site/issues/375, I propose allowing updates in batches using DRFs built in `many` option for the serializers. This should then allow us to POST big batches of users at a time. I suggest we limit these batches to 10000 at a time, so as not to overwhelm the endpoint.

**Comment by RohanJnr** [comment]
I would like to work on this too as I have been working on the related site issue too
https://github.com/python-discord/site/pull/378
