### ISSUE TITLE
mod-alerts channel doesn't display infractions total

### ISSUE THREAD

**Issue by mbaruh** [python-discord/bot#1127]
When issuing an infraction in `#mod-alerts`, the bot message doesn't display the infractions total - contrary to how it works in `#mods`. Looking at the behavior of the `!user` command on the channel, it does seem to be considered a mod channel, so it's most likely a bug.

**Comment by mbaruh** [comment]
This ties into #1125 as the same should be there after the category is whitelisted

**Comment by MarkKoz** [comment]
It's because it uses the staff channels constant rather than the mod channels constant.
