### ISSUE TITLE
Create an @ everyone recovery mode

### ISSUE THREAD

**Issue by thaniel-c** [python-discord/bot#1129]
# The Situation
The Python Discord is a huge guild and mistakes do happen and can't always be prevented.
However what can be prevented is lack of an explanation or confusion for people when these disruptive messages do get sent out.

![The Pinging Situation](https://user-images.githubusercontent.com/44456832/91388541-94f84300-e805-11ea-855a-05b7fc016068.png) 
(Today has only lasted for 1 hour and 34 minutes so far and there are already 87 mentions way after the ping event)

If you look in the #python-general channel currently, every couple of minutes someone will ask why they were pinged even though it's been hours since then. Friendly people trying to explain what happened tends to clog up the channel and hurts discussion, especially when in slow mode. 

# The Solution
I propose we make a system called "everyone-recovery" mode which upon encountering a message from someone who hasn't posted in the last few weeks, the bot will send them a DM with either a provided explanation or a default one saying that an accidental mass-ping happened and then finally deleting the ping message. 

# Additional Recommendations
We could also do either that or look for keywords in the message like "ping" combined with the time delay. 
The @ everyone recovery mode can also mute channels and lock vc automatically so mods don't have to struggle to quickly close things as they get out of hand. 

P.S. it's been asked 4 more times while writing this

**Comment by Den4200** [comment]
This is an extremely rare event and special case, I don't think we particularly need this.

> The @ everyone recovery mode can also mute channels and lock vc automatically so mods don't have to struggle to quickly close things as they get out of hand.

There's already a similar feature planned for Rattlesnake, our closed source anti-raid bot.

**Comment by Aniperk** [comment]
I agree, this is extremly rare, and very well a waste of resources, if someone wants to make this, go ahead, i just dont see as this being something the primary bot devs should focus on.

**Comment by fadedmax** [comment]
haha this became relevant and i was the last one to comment on it so i am oh fuck my comment was negitive SHIT LETS DO THIS CALL THE DEVELOPERS

**Comment by lyricalpaws** [comment]
Hello python VC hru? Posting before this place gets locked down too

**Comment by lyricalpaws** [comment]
Everyone spam jbated

**Comment by lyricalpaws** [comment]
VC died, sad

**Comment by lyricalpaws** [comment]
@thaniel-c ping me in discord, its Paws <3

**Comment by Den4200** [comment]
Yeah, I'm going to close this now, I don't believe we need this.
