### ISSUE TITLE
Auto-respond to non-mod everyone pings.

### ISSUE THREAD

**Issue by MrAwesomeRocks** [python-discord/bot#1131]
# The issue:
Currently, if someone puts down an `@everyone` ping, a mod has to come and respond to it to tell the person not to ping 95k+ people. Now, this usually works fine, but accidents happen, and things can end up happening like lemon accidentally pinging everyone, because android doesn't have a check for that (we're not upset lemon!).

# Proposed solution:
We add a auto-respond to the bot, sort of like in the attachment auto-respond, that contacts the user to explain why they shouldn't ping 95k people, and maybe even temp-mutes them and/or deletes the message. Here is an example message:
```
Sorry @user, but please don't try to ping 95k people. It will not have good results.
If you want to see what can happen, take a look at this pin: 
https://discordapp.com/channels/267624335836053506/267624335836053506/748352909904969740
```
It should only respond to non-staff too.

**Comment by lemonsaurus** [comment]
- This should be implemented as a filter.
- Automatically deletes the message with the fake everyone ping in it, because we don't want any idiot owners quoting those messages by accident :grin: 
- Mutes the user for 10 minutes, similar to what we do for spam detectors.
- Posts a message to the channel with a ping of the user and a message similar to what's in OPs description.
- Maybe we don't need to link the pinned message, lol.

**Comment by MrAwesomeRocks** [comment]
I just thought linking the pinned message would help people realize what happens when more 95k+ people get pinged :lemon_pleased:.

**Comment by ks129** [comment]
I think this link is not good idea, but yes, this should have filter and I can create it, when someone else don't do this.

**Comment by MrAwesomeRocks** [comment]
The link was more of a joke, but I could also implement this to the bot.

**Comment by lemonsaurus** [comment]
I think since you created the issue, @MrAwesomeRocks, you can handle it if you want it.

**Comment by MrAwesomeRocks** [comment]
@lemonsaurus How does the current spam filter work? Could you send one of the current filter files?

**Comment by lemonsaurus** [comment]
See this cog: https://github.com/python-discord/bot/blob/master/bot/cogs/antispam.py

And these rules: https://github.com/python-discord/bot/tree/master/bot/rules

**Comment by MrAwesomeRocks** [comment]
@lemonsaurus There's a section in the config file talking about ping everyone, is this implemented anywhere?
![image](https://user-images.githubusercontent.com/42477863/91498752-f233d900-e885-11ea-8b3b-642250b8095b.png)

**Comment by MrAwesomeRocks** [comment]
So I have to:
1. Add my rule to the [config file](https://github.com/MrAwesomeRocks/bot/blob/master/config-default.yml).
2. Write my rule to: 
    1. Get relevant messages
    2. Read the everyone role from the config file
    3. Check if the everyone role is mentioned in the config file
3. Add my rule to [this dict](https://github.com/python-discord/bot/blob/04cafc66d2e8067f9c94b111f5dac6e7dd915e1e/bot/cogs/antispam.py#L27)

@lemonsaurus
