### ISSUE TITLE
Evaluate code from website Pastebin.

### ISSUE THREAD

**Issue by ghost** [python-discord/bot#1133]
# Feature Suggestion
The [idea](https://discordapp.com/channels/267624335836053506/429409067623251969/717558622514708500) was suggested, but never implemented. We could implement it like [this](https://discordapp.com/channels/267624335836053506/429409067623251969/748641619842039888).

**Comment by MarkKoz** [comment]
I don't strongly oppose this, but I'd rather not implement this. The purpose of the eval command is to make it convenient for users to evaluate code while they're in the Discord client. If users already leave the client to write code and upload it to a paste site, then they can go through the extra trouble to run their code themselves and paste the output. In this work flow, I doubt someone would have uploaded code without running it first anyway.

This is a relatively incomplex feature, but any additions increase the overall complexity of the code base. I'm not a fan of adding features without strong justifications for them.

**Comment by Joe-Sin7h** [comment]
hey 
Please assign this issue to me .
I would love to work on this issue .
thank you

**Comment by wookie184** [comment]
I agree that this feature seems unnecessary.
