### ISSUE TITLE
ID not displayed in dm_relay when attachment sent

### ISSUE THREAD

**Issue by wookie184** [python-discord/bot#1137]
Currently the dm-relay message username will not include the user ID if only an attachment is sent, so it looks like this:
![image](https://user-images.githubusercontent.com/22353562/91665752-da5f8d80-eaef-11ea-9e91-c710ed977056.png)
Whereas it should look like this:
![image](https://user-images.githubusercontent.com/22353562/91665710-91a7d480-eaef-11ea-9b0e-9a52672647f1.png)

This is because it uses [`bot.utils.messages.send_attachments`](https://github.com/python-discord/bot/blob/1bd5c80e7b2aa90162639b86960c66f6a218022f/bot/utils/messages.py#L53), which by default just sends the message with the ID. Relevant line in `dm_relay` cog [here](https://github.com/python-discord/bot/blob/1bd5c80e7b2aa90162639b86960c66f6a218022f/bot/cogs/dm_relay.py#L93)

Simple solution here would be to add a `username` keyword argument to `send_attachments`. I would be happy to make this change if this all sounds good.

**Comment by MarkKoz** [comment]
How about supporting arbitrary kwargs to pass on to `send()`? An explicit `username` kwarg is kinda odd since it will only be useful if a webhook is given as the destination. It's not too bad though.

**Comment by wookie184** [comment]
Sure, supporting arbitrary kwargs sounds like a good idea to me.
