### ISSUE TITLE
About repetitive help requests.

### ISSUE THREAD

**Issue by adhikariprajitraj** [python-discord/bot#1138]
There are at least 5-6 requests every day in python discord, asking how to install python, which version of python they want to install, why "pip" is not working and someone directly pinging the help channel without doing any research for their errors. While I don't think we can deal with people trying to get spoonfed but at least, we do something about the "pip", python versions, and how to install python and IDEs.

**Comment by AtieP** [comment]
We could create tags for how to install Python, how to install packages... See the issue #810.

**Comment by MarkKoz** [comment]
So what is your proposed solution to this? Is it to create tags as AtieP suggested?

**Comment by Anubhav1603** [comment]
Writing tag will be good for this bcz tag main purpose is for info only

**Comment by Den4200** [comment]
Stale issue, closing for now. Creating a tag for this would be perfectly fine.
