### ISSUE TITLE
Antimalware cog file filter triggers on bot and webhook messages

### ISSUE THREAD

**Issue by wookie184** [python-discord/bot#1140]
Currently the antimalware cog file filter triggers on messages from the bot, and also on webhook messages. So for the example somebody tries to send an attachment from python using `!int eval`, it will be caught by the filter
![image](https://user-images.githubusercontent.com/22353562/91752774-be76ed00-ebbe-11ea-99ac-e1147ca1d2df.png)
Also, if somebody sends a non-whitelisted attachment to the bot, (and it isn't ignored because of #1139), it will be relayed to dm-log but then caught by the filter, which will delete it and then reply to the webhook in the channel.

I think the best thing to do here would just be to ignore all webhook messages and bot messages, I can't think of any problems with this. 

I would be happy to make this change

**Comment by MarkKoz** [comment]
Sounds good to me.
