### ISSUE TITLE
Everyone Ping rule picking up false positives

### ISSUE THREAD

**Issue by MrAwesomeRocks** [python-discord/bot#1142]
The everyone ping rule has been picking up some false positives, such as 
```markdown
`a`@everyone`b`
```
or 
```markdown
Hello`@everyone`
```
The regex needs to be redone.

**Comment by lyricalpaws** [comment]
Star and follow my github pls python discord

**Comment by lyricalpaws** [comment]
MUTE THE CODE JAM PLS ITS SAD
