### ISSUE TITLE
!help output in muted #bot-commands

### ISSUE THREAD

**Issue by gustavwilliam** [python-discord/bot#1146]
When someone uses `!help` in another channel than `#bot-commands`, the output is redirected to `#bot-commands`. 

This is still the case when send message permissions in `#bot-commands` are removed, which could lead to spamming or "drowning" a potential message about what is happening, in the channel.

**Comment by wookie184** [comment]
Us having to disable send message permissions in bot-commands specifically is a rare event, and it isn't the end of the world if this issue happens anyway. Messages with information can be pinned in the channel, and updates on an incident would usually be in `#announcements` or `#changelog` anyway.

I'm not sure changing this behavior is really worth it imo.
