### ISSUE TITLE
Everyone warning picking up nicknames

### ISSUE THREAD

**Issue by Jack92829** [python-discord/bot#1147]
The warning system trying to prevent people from attempting to @everyone is also picking up on people with the nickname 'everyone'
![image](https://user-images.githubusercontent.com/62740006/92300601-81846f00-ef9f-11ea-8431-fbef42081e73.png)

**Comment by Jack92829** [comment]
Although after discussing this with other people in discord and looking at the code, it might just be an issue on discords side

**Comment by SebastiaanZ** [comment]
I'm not sure if the message that you're highlighting is the one that actually triggered this filter. The filter normally also removes the message in question and there's no error that says that the bot was unable to delete a message here. My working hypothesis is that this user sent two messages in a row: the first one (still there) had a member ping and the second one contained an actual everyone-ping.

**Comment by Jack92829** [comment]
Ah yeah that sounds more likely
