### ISSUE TITLE
!reddit command doesn’t filter nsfw subreddits.

### ISSUE THREAD

**Issue by scrazzz** [python-discord/bot#1153]
So yeah, as the title says `!reddit` command doesn’t filter nsfw subreddits ._.

doing: `!reddit top nsfw` displays the direct URL link to the nsfw subreddit.

**Comment by RohanJnr** [comment]
this should be a simple fix as done here
https://github.com/python-discord/seasonalbot/blob/master/bot/exts/evergreen/reddit.py#L57
it's another Reddit command, but for `seasonalbot`

**Comment by scrazzz** [comment]
Nice. Hopefully they implement this 👍

**Comment by jb3** [comment]
We should keep this open until it is implemented.

**Comment by RohanJnr** [comment]
I would like to finish this

**Comment by ikuyarihS** [comment]
@RohanJnr I've assigned the issue to you

**Comment by RohanJnr** [comment]
thanks
