### ISSUE TITLE
Add projects subcommands to source command

### ISSUE THREAD

**Issue by ks129** [python-discord/bot#1154]
Add subcommands for different PyDis projects to `!source` command. For example, SeasonalBot: `!source seasonalbot`. These subcommands should give short description about project and link to GitHub.

I think these projects should have subcommands:
- site
- branding
- snekbox
- public-stats
- django-simple-bulma

**Comment by MarkKoz** [comment]
Sounds nice. Will the descriptions be written and stored in the bot, or will they be fetched from GitHub? In the case of the latter, it may be preferable, but I'd rather not overcomplicate things for such a simple feature. Unless it's a simple unauthorised request to get the description, I don't think we should fetch them from GH.

**Comment by MarkKoz** [comment]
For some reason I feel seasonalbot had a similar feature actually. Can anyone confirm or deny?

**Comment by ks129** [comment]
I think this should be inside Markdown files in bot repo and these should be loaded on startup.

**Comment by Den4200** [comment]
SeasonalBot now has a `source` command - python-discord/seasonalbot#469

**Comment by ks129** [comment]
@Den4200 Removed SeasonalBot from list

**Comment by Shivansh-007** [comment]
We can fetch all the non-archived repositories using GitHub API and then add a pagination to it. With each repository in the following way maybe:
```md
# Repository Name
- Description (from gh)
```

**Comment by wookie184** [comment]
We have the `.github` command on lancebot:

![image](https://github.com/python-discord/bot/assets/22353562/97926267-b31c-47c0-add6-b6a160947234)

I don't think it's worth keeping separate custom markdown descriptions here. I don't think it would add much extra value to the info from `.github`, and could take a decent amount of work to keep up to date.
