### ISSUE TITLE
Links that are autodeleted by the bot are sometimes still visible to some users

### ISSUE THREAD

**Issue by Hasenn** [python-discord/bot#1155]
https://cdn.discordapp.com/attachments/267624335836053506/754823336210727003/Screenshot_20200914_005756_com.discord.jpg

steps to reproduce:
- post a link
- bot fetches the site doc title and description, and deletes the original link
- most users don't see the bot's message but some do regardless of being mods or having privileges

for some reason it's timestamped jan 1 1970

**Comment by kosayoda** [comment]
Thank you for the feedback, but this is very likely an issue on Discord's end. I'm closing this until it's verifiable that it's a bug with our bot.
