### ISSUE TITLE
Remove alias cog

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#1159]
Since the merging of #1124, only 3 alias commands remain, listed below. All usage statistics are since stats have been tracked, which is around April of 2020.

1. `!get docs` - alias for `!docs get`
    * Usage: 4 times
    * Usage of `!docs get`: 793 times
    * Usage of `!docs`: 9240 times (includes all the above and empty arg invocations)
2. `!get tags` - alias for `!tags get`
    * Usage: 0 times
    * Usage of `!tags get`: 4 times
    * Usage of `!tags`: 720 times (includes all the above and empty arg invocations)
3. `!extension` - alias for `!tags get traceback`
    * Usage: 12 times
    * Usage of the `traceback` tag: 194 times

The usages compared to other ways to invoke the commands are ~0.04%, 0%, and 6.19% respectively. Quite low numbers. Regarding the `traceback` alias, the tag search functionality will likely pick up the `exception` keyword and show the traceback tag anyway.

Removing this cog would reduce maintenance costs (granted, not by much). It would also just clean things up a bit. I find the existence of this code to be an anomaly, for lack of a better word, considering #1124. Lastly, it means #844 and #847 would be closed.

Is anyone on board with this proposal?

**Comment by kosayoda** [comment]
Let's do this. Always good to trim unused features.

`!exception` isn't a suitable alias for `traceback` anyway, and we have tags for both.
