### ISSUE TITLE
Fully supporting GitHub codespaces

### ISSUE THREAD

**Issue by Akarys42** [python-discord/bot#1169]
## What are codespaces?

In their latest Satellite, GitHub announced the launch of Codespaces, an online development environment running VSC, fully integrated with GitHub. As the time of writing this, the feature is in public beta. You can read more about it [here](https://github.com/features/codespaces).

## What needs to be done?
I’ve tried this recently to review a PR, it was pretty great, although some manual setup was still required, like installing `pipenv`, syncing it and installing `docker-compose` (The docker engine was already included). Thankfully, GitHub is providing a `.devcontainer` config file, to automate all this process. The documentation is [here](https://docs.github.com/en/github/developing-online-with-codespaces/configuring-codespaces-for-your-project).

**Comment by Xithrius** [comment]
The amount of people who use codespaces is low enough to where it's not necessary for us to implement explicit support.
