### ISSUE TITLE
Infraction subcommand for amending infraction reasons

### ISSUE THREAD

**Issue by PureFunctor** [python-discord/bot#1170]
## Motivation
Currently, the only way to amend an infraction reason is to search and copy the original reason before invoking
```
!infr edit (last|infr_id) {old_reason} (Edit|Context): {amended_reason}
```
An `infr` subcommand that abstracts this action would allow for a nicer interface, at least in my opinion, especially for amending infractions that were needed to be handed out quickly.

## Proposed Implementation
A subcommand that's similar in form to `infraction_edit` to be called `infraction_amend` (à la `git commit --amend`) first looks up the original reason for the infraction (possibly using [this routine](<https://github.com/python-discord/bot/blob/1ae971423ae5fcf3f8a68bcacbf1591c2ccf0aac/bot/exts/moderation/infraction/management.py#L81-L97>)), amending the new reason prefixed with either `Edit: ` or `Context: `, and then invoking  `infraction_edit`. The infraction duration can also be edited by passing the appropriate parameters and the new duration could also possibly be amended automatically to the message.

### Example Usage:
```
> !infr amend last This member had `...`
] Spamming in #python-general. Edit: This member had `...`

> !infr amend 512 1h This member had ...
] Spamming in #python-general. Edit: This member had `...`. Infraction incremented/reduced to `...` from `...`.
```

**Comment by mbaruh** [comment]
That looks good. Maybe we could add an `append` alias

**Comment by SebastiaanZ** [comment]
Sounds like a reasonable feature to me. I've certainly missed it in the past. I'd go with an `append` or `add` subcommand  instead of just `amend`.

**Comment by mbaruh** [comment]
Also.. just... `a`
The more shortcuts we have for infractions management the better
