### ISSUE TITLE
feature suggestion: add url in title instead of description in !pep command

### ISSUE THREAD

**Issue by 15695** [python-discord/bot#1176]
currently the link when you use the !pep command is located in the description, but with the discord.Embed.url parameter, the title is now able to become a link (as shown in second image)

![image](https://user-images.githubusercontent.com/50557523/94292440-34e6e080-ff1a-11ea-8986-4e025379fd73.png)
![image](https://user-images.githubusercontent.com/50557523/94292605-695a9c80-ff1a-11ea-99ef-fc02f83e9d61.png)

**Comment by gustavwilliam** [comment]
That sounds good to me. Can't think of a reason for not doing it.

**Comment by soumitradev** [comment]
I can work on this can I get assigned?

**Comment by jb3** [comment]
Go for it!

**Comment by 15695** [comment]
> I can work on this. can I get assigned?

this should be pretty easy, just replace this line:
description=f"[Link]({self.base_pep_url}{pep_number:04})",
with this line:
url=f"{self.base_pep_url}{pep_number:04}"
