### ISSUE TITLE
Bug: ` chars are not escaped when parsing !source

### ISSUE THREAD

**Issue by neonsea** [python-discord/bot#1177]
![Screenshot](https://arse.ee/zi7A9lec.png)

When responding to faulty `!source` commands, the backticks aren't escaped and a formatting issue occurs.

This _might_ lead to being able to ping roles/users, should Discord ever decide to change the embed ping behavior.

**Comment by AtieP** [comment]
You can't ping people or roles in embeds

**Comment by neonsea** [comment]
I am aware of this. Not particularly relevant regardless.

**Comment by soumitradev** [comment]
I can work on this, can I get assigned?
