### ISSUE TITLE
Error for DMing a user is uncaught in verification

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#1179]
Sentry Issue: [BOT-8Z](https://sentry.io/organizations/python-discord/issues/1901783817/?referrer=github_integration)

As can be seen below, Discord returns a 400 with a specific code rather than a 403 forbidden. Currently, verification attempts to catch this by suppressing a 403 rather than a 400.

```
HTTPException: 400 Bad Request (error code: 50007): Cannot send messages to this user
(1 additional frame(s) were not displayed)
...
  File "bot/cogs/verification.py", line 503, in on_member_join
    await member.send(ON_JOIN_MESSAGE)
  File "discord/abc.py", line 850, in send
    channel = await self._get_channel()
  File "discord/member.py", line 243, in _get_channel
    ch = await self.create_dm()
  File "discord/user.py", line 715, in create_dm
    data = await state.http.start_private_message(self.id)
  File "discord/http.py", line 245, in request
    raise HTTPException(r, data)

Unhandled exception in on_member_join.
```

**Comment by kwzrd** [comment]
Hmm, I guess let's just suppress `discord.HTTPException` then if you're cool with that.

**Comment by MarkKoz** [comment]
That feels too broad. You could catch it and only suppress if it has that specific error code.
