### ISSUE TITLE
Selfmute

### ISSUE THREAD

**Issue by Atharv-Attri** [python-discord/bot#1186]
Please add in a selfmute command that mutes the user on the server for a specific amount of time that they choose. 

The command would work as, well Joe already knows how it works, he just wants me to make an issue, but it's like `!selfmute <time>`. 

Most of the code for this is already written in the tempmute command. The command would need to be cloned from tempmute. It would remove the restrictions on who can use it, and instead of taking in input of who to mute, it would mute the person sending it. It would also need to not add in an infraction every time the user uses it.

Here is an example of how it might work: courtesy of Joe:
![image](https://user-images.githubusercontent.com/48738128/94352595-ed487d80-001b-11eb-9e77-b4dfcf5de51a.png)

Realworld uses: Many times people want to avoid distractions, and keep themselves from talking on the server, however, shutting down discord entirely is not an option. This command would let the user work distraction-free, while still having access to the rest of discord.

**Comment by jb3** [comment]
Joe doesn't just want you to make an issue. You should describe why you 
think this should be a command, and how it should work from a technical 
perspective as well. Otherwise people won't be able to decide whether we 
should have this feature or how to implement it.

**Comment by Atharv-Attri** [comment]
@jb3 You already implemented it, you know how it works! But I have indeed updated the issue to include that information!

**Comment by MarkKoz** [comment]
This isn't justified to me. My proposed alternatives:

1. Temporarily leave the server
2. Have more self control to not visit the server or write in there

**Comment by jb3** [comment]
+1 to Mark’s comments here.

There are many tools which can prevent this. For example, Apple has a screentime tool which allows users to lock app access. This feels out of scope for our bot.

**Comment by Atharv-Attri** [comment]
Acutally, you're right. I'll just create something.

**Comment by AtieP** [comment]
This dude is a bigbrain

**Comment by Akarys42** [comment]
I would just like to add that if you don't want to leave the server for any reason, logging out of discord is also a good option
