### ISSUE TITLE
Voice Gate: Voice gate cog

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/bot#1190]
For our Voice Gate project, we need a new cog which will interact with the endpoints specified in https://github.com/python-discord/site/issues/398.

This issue cannot be solved until https://github.com/python-discord/site/issues/398 is ready.

## Tasks
- A command for verifying, which checks the API from https://github.com/python-discord/site/issues/398 to see if a user qualifies and then grants the appropriate role if it does.
- If the user does not qualify, temporarily display an error message, and delete it after 10 seconds.
- Clean up invocations and all other messages posted in the voice verification channel, to keep it tidy. Basically, do exactly the same thing as we do in #verification 

## Dependencies
This issue cannot be started until a number of the other issues in the project have been solved.
- We need the speaking permission role to exist
- We need the voice gate channel to exist
- The site-side changes need to be done, so we have an API to call.

**Comment by ks129** [comment]
Can I get assigned to here? Is this now possible to get role + channel IDs too?

**Comment by jb3** [comment]
The voice gate requirements we have decided on are:
- The user must have verified over 3 days ago.
- The user must have over 50 messages.

Both of these statistics are reported from the Metricity API located at `api.pythondiscord.com/bot/users/{user_id}/metricity_data`

A sample response looks like:
```js
// GET https://api.pythondiscord.com/bot/users/165023948638126080/metricity_data
{
  "verified_at": "2020-10-06T00:04:37.096203",
  "total_messages": 13664
}
```
