### ISSUE TITLE
Voice Gate: Better `!user` command

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/bot#1192]
To aid our moderators in moderating the voice channels, we'll add two new parameters to the `!user` command:
- Total messages sent on the server
- Time verified, which shows when the user verified that they accepted our rules.

This data will be made available through a new site API, which is specified here: https://github.com/python-discord/site/issues/398

**You cannot work on this issue until this site issue has been solved!**

**Comment by Xithrius** [comment]
> Total messages sent on the server

Would this require having to iterate through all message history sent by the user, or is it automatically stored somewhere that I'm not aware of?

If we did decide to do message history such as the example below, wouldn't this count as a bunch of API calls?
```python
messages = await channel.history(limit=None).flatten()
```

To avoid the possible many message history API calls maybe we should limit how many messages should be iterated through from the user (like `limit=100`).

If I'm wrong about any of this, please correct me.

**Comment by Den4200** [comment]
No, Metricity already tracks this.

**Comment by Xithrius** [comment]
[This issue](https://github.com/python-discord/site/issues/398) will solve these problems.

**Comment by Xithrius** [comment]
I can take this issue when the API endpoints are written.

Also, should we allow users to retrieve data on how many messages they've sent, or should we only allow this in staff channels?

**Comment by jb3** [comment]
Decision here was to keep this to staff channels to prevent users trying to pad their stats and repeatedly running user. Discord provides a search tool for regular users which suffices, this is just a moderation tool.

**Comment by Xithrius** [comment]
Thank you for the clarification.

**Comment by Starbors** [comment]
try to code it yourself

**Comment by mbaruh** [comment]
@Xithrius looks like the API is ready

**Comment by Xithrius** [comment]
@mbaruh Thank you for the update. I will start working on this soon.
