### ISSUE TITLE
Voice Gate: `!voiceban` command.

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/bot#1193]
For the Voice Gate project, we require a new infraction type called `!voiceban`.

This should work exactly like `!tempban` in that it will take a user and a duration using the exact same mechanisms. Do not reinvent any of these mechanisms, just use the existing converters.

## Specifications
- The effect of the command will be to temporarily remove the speaking role for the specified duration.
- The command should have the alias `!vban`.
- This command should not work on a staff member, or on a member that does not have the speaking role.
- This feature should have unit tests.

## Dependencies
- The speaking permission role must exist. This is specified in https://github.com/python-discord/admin-tasks/issues/31

**Comment by Starbors** [comment]
well you kn9ow this is not a problem.

**Comment by ks129** [comment]
I'd like to work with this same time when with #1190
