### ISSUE TITLE
Add fuzzy matching to the role(s) command. 

### ISSUE THREAD

**Issue by Akarys42** [python-discord/bot#1194]
Right now, if you want to use the role name for the `!role(s)` commands, you have to type the *exact* role name, which can be quite frustrating sometimes. 

It would be nice to support fuzzy matching, like we do here with the `Tags` cog.

https://github.com/python-discord/bot/blob/9e95fb0a34733d6ce9d9619e892a860a54567606/bot/exts/info/tags.py#L69-L83

**Comment by Starbors** [comment]
make a pull request
