### ISSUE TITLE
Improving Superstar command

### ISSUE THREAD

**Issue by mbaruh** [python-discord/bot#1224]
Out of the moderation tools we have available, the superstar command is the odd one out.

* It doesn't ping the user being superstarred, instead posting a special embed (albeit a pretty funny one)
* It doesn't send the reason in the DM.

That leads to some confusion for users on what happened and why it happened.
We don't have to remove the special embed, but:
* It should still give a standard "applied superstar to <user>" so that the user is pinged if it's applied in a public channel
* The embed should be sent in a DM as well
* The optional reason should be integrated into the embed to give any additional context provided by the moderator.

**Comment by spitfire-hash** [comment]
Can you assign this to me?

**Comment by Akarys42** [comment]
Done! As always, if you have any question, feel free to ask in #dev-contrib!

**Comment by spitfire-hash** [comment]
Okay, thank you! I'll work on it in 2 days.

**Comment by mbaruh** [comment]
This might clash with https://github.com/python-discord/bot/pull/1204/files so you might want to check that out

**Comment by spitfire-hash** [comment]
@mbaruh what should I do know? wait for merging #1204 and then work on that?

**Comment by mbaruh** [comment]
@spitfire-hash #1204 makes some extensive changes to the command, I think it's best if you waited for it to be merged, yes.

**Comment by mbaruh** [comment]
#1204 is now merged, so this issue is now up for grabs. If anyone wants to be assigned feel free to say so.
