### ISSUE TITLE
Enhancing information within the incidents channel.

### ISSUE THREAD

**Issue by Xithrius** [python-discord/bot#1226]
Given that message links jump to deleted messages sometimes, it's hard to figure out who was the perputrator.

Within the incidents channel, it may be a good idea for the bot to provide a user ID for the message link owner so mods+ can look into their message history. 

If the message is still there, the bot could tell what it contains. If exceeding a certien limit, the bot will give a shortened version of the content.

If the message link returns nothing, then maybe (if it's possible) the bot can send a message to redirect to a deleted message in the message-change-log channel.

**Comment by Shivansh-007** [comment]
I will give this a go!

**Comment by Xithrius** [comment]
@Shivansh-007 I think this should be planned out a bit more before we do something.
