### ISSUE TITLE
403 not being caught in send_attachments

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#1230]
Sentry Issue: [BOT-9V](https://sentry.io/organizations/python-discord/issues/1950241040/?referrer=github_integration)

Perhaps coincidentally, this started appearing once `use_cache` was defaulted to `False`. What's weird is that there is already an `except HTTPException` in the function, of which I'm pretty sure `Forbidden` is a subclass.

```
Forbidden: 403 Forbidden (error code: 0): cannot retrieve asset
  File "bot/utils/messages.py", line 90, in send_attachments
    await attachment.save(file, use_cached=use_cached)
  File "discord/message.py", line 124, in save
    data = await self.read(use_cached=use_cached)
  File "discord/message.py", line 166, in read
    data = await self._http.get_from_cdn(url)
  File "discord/http.py", line 267, in get_from_cdn
    raise Forbidden(resp, 'cannot retrieve asset')

Failed to re-upload attachment unknown.png from message <REDACTED> with status 403.
```

**Comment by Akarys42** [comment]
Yes it is, this is just a warning, although it shouldn’t return us a 403, that’s what we are trying to investigate.

**Comment by awgymer** [comment]
Sorry I guess I'm a bit confused. It says `403 not being caught`,  but if it's logging that warning then it *is* being caught by that `except` no?

**Comment by MarkKoz** [comment]
Sorry, it was not clear that it's coming from a warning log. It likely is a warning though since it uses the `failure_msg`. In that case, does anyone have any idea why we got a 403?

**Comment by Akarys42** [comment]
The Discord API is having quite a lot of issues lately, like all the 500s
we keep getting, my best bet is that it is coming from their end.

Another thing could be because we aren't using cached images but the
original message is deleted, we maybe not have access to the image anymore,
but I kinda doubt it.

**Comment by wookie184** [comment]
Since this doesn't seem to have come up since and I don't see how this should happen I'm going to assume this was a Discord bug. We can investigate further if it comes up again (the sentry issue is deleted now so it's hard to investigate this much further here).
