### ISSUE TITLE
Help command for `eval` contains unnecessary newlines.

### ISSUE THREAD

**Issue by spitfire-hash** [python-discord/bot#1232]
The help command for `eval` contains newlines that they should not be there. That's because there are `\n`s after some words in [docstring](https://github.com/python-discord/bot/blob/master/bot/exts/utils/snekbox.py#L281-L285). And I'm not sure how to fix that. 

![image](https://user-images.githubusercontent.com/66242799/95840549-5424a100-0d55-11eb-94a7-acb7293105ae.png)

**Comment by Den4200** [comment]
We can add a backslash (`\`) to the end of each new line in its docstring
to fix that.

**Comment by davisschenk** [comment]
Could this be handled in the help command instead, so that we could avoid changing every docstring?
