### ISSUE TITLE
Help Channels: Delete pin message notification

### ISSUE THREAD

**Issue by hedythedev** [python-discord/bot#1238]
When the bot pins a message, a 'notification' like `Python pinned a message to this channel. See all the pins.` appears, this could be deleted. 

In reference to [this (review comment)](https://github.com/python-discord/bot/pull/1023#pullrequestreview-457166782), this message was kept to 'advertise the feature', now that most people this exists now, I think it's necessary to remove that message. The main reason for me is that sometimes (or most of the times?) people send something like 'hello' to claim the channel, and then begins typing their question after that, with the bot pinning 'hello' shown there is not quite suitable or rather looks a bit weird (in a sense). The bot can just 'silently' pin the message, and for people who want to check the original question (or jump back to previous discussions), they can click the pins button to look at the pinned message. 

I would like to attempt to implement this feature if it's approved

**Comment by Akarys42** [comment]
I'm okay with that, this feature is here for quite a while now.

I'd like to hear what others think about that first tough.

**Comment by gustavwilliam** [comment]
To me, this sounds reasonable. However, we should keep an eye on if people start writing their questions as the first message less or if people just don’t know that the feature exists. If that happens, we could simply add it back in.

**Comment by hedythedev** [comment]
Maybe we can put a message in the availabe/dormat embed saying that the first message in this channel is pinned so others can jump back to the original question and discussions. 

And in the case of when the user deletes their message after claiming the channel, maybe the bot can say something like `This channel is claimed by @ user it will be moved to dormat after xyz minutes`, it doesn't look like the bot moved the channel to occupied for no reason whatsoever.

**Comment by ks129** [comment]
I think this should still show this message, because newer users may not see it.

**Comment by mbaruh** [comment]
I'm not sure this is necessary. It would make sense for a system with mainly experienced users, but we have a constant stream of new users using the system, so there is never really a point at which we don't need to advertise it anymore.

It might be worth it to reduce noise in the help channel, but it doesn't cause much of it, and it would have to be worth potentially hiding this feature from a lot of users.

**Comment by gustavwilliam** [comment]
You have some good points @mbaruh. It’s not very annoying to have the “pin message” there, while there may be a cost in removing it. I think we should just keep it.

**Comment by Xithrius** [comment]
As of now the notification of the pinned message doesn't make much noise, and I too don't feel the need for it to be deleted. In my mind it serves an important purpose, of sorts.

It is partially bold, which can act as a separator between a large question and the start of the discussion (without having to look at the pins).

**Comment by hedythedev** [comment]
@Xithrius I didn't see your edit sorry :/
Now, come to think of it, I don't think it needs to be removed anymore. It can help promote the feature to new users, even if can be weird when the user deletes the first message. I was going to close it anyway.

**Comment by Xithrius** [comment]
Glad we can come to an agreement. 

Have a good one!
