### ISSUE TITLE
Improving the mute command

### ISSUE THREAD

**Issue by mbaruh** [python-discord/bot#1251]
I propose these changes to the mute command:

* Allow muting off-server users. Sometimes we will apply a mute a moment after a user leaves the server, causing it to fail. This leads us to look for some other measure, such as banning them for the same duration. There shouldn't be a technical problem to apply a mute to someone outside the server, since it's already applied on join. At the same time we can add info about the user not being on the server for infractions applied in mod channels. 
Seems to be related to #1034. #1016 deals with the situation when a mute is invoked, but the user leaves before getting the muted role, however it doesn't deal with invoking a mute on a user not present in the guild.
* Add an option to force a mute on an already muted user. This is helpful for example when a user is already muted by the bot, but we want to extend it and have the additional reason be sent to the user. Currently we have to unmute the user (which sends them a message) and only then reapply the mute, which can be confusing for them. This can be achieved with a subcommand such as `!mute forced ...`

---

After a vote with the moderation team on 17-02-2021, the changes will be as follows:
1. A command to re-DM the user their infraction details.
2. A `forcemute` command to override an active mute. Will only work in mod channels when there isn't an active mute.
3. Ignore active auto-mutes from the bot when issuing a mute.

**Comment by scragly** [comment]
I'm unsure if I'd have used a mute on a member had I known they left even if it did work, instead seeing a reason to provide an appropriate infraction that actually can impact them now that they left (tempban) and as a response/increase in infraction from purposely avoiding taking responsibility for whatever they were about to be muted for. However, if other mods feel differently, then I'm not about to push hard against the tool being added. The only thing I'd ask is that, in the case they did leave, the bot informs us first and asks if we continue with the mute instead. That would ensure it doesn't break the option of cancelling and elevating to a tempban. 

I'm not really a fan of the idea of a forced mute. I think the default behaviour could instead change to ensure we _can_ add longer duration mutes. Either we can make the old one inactive and add the new one automatically, prompt for mod confirmation when encountering an existing mute, or we can allow multiple active mutes and have the unmute task check for any newer active mutes so it can skip it. 

A possibility of multiple mods handling the same situation was brought up in-server as a possible issue, however I feel that this isn't really something exclusive to muting; mods can apply multiple infractions already for any other combination. Instead, if we wish to address that, we should address it globally across all infractions. For example, we could add a ratelimit of 1 (non-bot) infraction per-target within a short span of time (1-5 seconds perhaps) to ensure we give enough time for mods to see each others actions before being able to apply additional ones.

**Comment by mbaruh** [comment]
The thing about users who leave, is that whether we apply a mute or a ban, they will know of neither, because the DM will fail,  and if they choose to come back after being muted, they will still be muted, and currently won't even be able to verify. So I think it would be nice to have the mute succeed either way and call it a done deal. 

Like I mentioned in the original post, we can add information on the success message for whether the user is in the server or not, so a moderator will still be able to elevate the infraction if they so choose. The idea is to just make sure the mute doesn't fail.

As for the forced mute idea, I tried to navigate between different possible scenarios and have it be explicit, but I agree the resulting solution is a bit clumsy. Allowing for longer mutes to succeed by default sounds ok to me.

**Comment by scragly** [comment]
> So I think it would be nice to have the mute succeed either way and being able to call it a done deal.
> .. we can add information on the success message for whether the user is in the server or not, so a moderator will still be able to elevate the infraction if they so choose. 

I don't really agree, since I don't want to unnecessarily add two infraction entries for one event. Things like this is why infraction counts, even when broken down into types, are not really representative of how many situations we've had to deal with for a member. I'm always going to instead lean towards a solution that provides a more useful/accurate glanceable history without rely on mods having to go out of their way to do redo or edit actions already taken, as people by nature will go with the path of least resistance instead and just not consistently do so.

**Comment by mbaruh** [comment]
@scragly Well if it's not a feature we have a consensus on I obviously won't try implementing it.

That said, I'm actually a bit hesitant about allowing longer mutes to go through automatically. If we compare it to bans we have several things to take into account here:
* Longer temporary bans don't automatically go through, only permas.
* Mutes are more common than bans, which brings a higher chance of an accident.
* Once a user is given a tempban, they're out of the server. Any additional bans won't be made known to them. For mutes they will be DMed for every extra mute.

I think declaring intent could be important here.

**Comment by mbaruh** [comment]
Since allowing several mutes could lead to issues, this issue should deal only with mutes applied on users already auto-muted by the bot, which is where this need arises the most.

**Comment by mbaruh** [comment]
Superseded by #1665
