### ISSUE TITLE
Purge tempban/tempmute.

### ISSUE THREAD

**Issue by Xithrius** [python-discord/bot#1254]
Users sometimes like to spam, with having previous activity on the server such as actually contributing to conversations.

In these situations it's not ideal to ban them completely. This would be especially useful if a user is spamming across multiple channels.

I'd like to integrate this.

**Comment by mbaruh** [comment]
I think @scragly had some plans / concerns about that

**Comment by Xithrius** [comment]
Without slash commands, this utility would require many inputs for a moderator. Including the user ID, how many days, messages to iterate through to remove problematic user's messages (if not purging), and reason (already optional).

Until we can utilize slash commands more, this issue will not be relevant.
