### ISSUE TITLE
`!close` should always remove the cooldown role from the channel claimant

### ISSUE THREAD

**Issue by swfarnsworth** [python-discord/bot#1256]
https://github.com/python-discord/bot/blob/afe84f425d244c05993c9a0922877fb70fa33104/bot/exts/help_channels.py#L218

The `!close` command removes the cooldown role from the person who issued the command, but as staff members are able to close any help channel it is not guaranteed that the person issuing the command is the claimant.

This call should be changed to look up who the claimant is and remove the role from them.

**Comment by Den4200** [comment]
Currently, we store a dictionary which maps channels to their claimants. Should we iterate through this dictionary to find a claimant's channel? Or should we be redundant and have another dictionary which maps claimants to channels?

I would say it's a question of performance vs resource usage, but neither of those should matter here since there would only be 32 help channels open at our maximum capacity.

**Comment by swfarnsworth** [comment]
Another consideration is that a user may be the claimant of multiple channels so we wouldn't want to remove the role unless it's the only help channel they have.

(For anyone else reading this, we don't really want people to have multiple help channels, but sometimes it's more difficult to avoid than it's worth.)

**Comment by MarkKoz** [comment]
> Currently, we store a dictionary which maps channels to their claimants. Should we iterate through this dictionary to find a claimant's channel? Or should we be redundant and have another dictionary which maps claimants to channels?

A search is not necessary. The command must always be invoked in the channel being closed, so the claimant may be retrieved with `await self.help_channel_claimants.get(ctx.channel.id)`.

**Comment by SebastiaanZ** [comment]
That's what I was thinking as well, we can use the channel as the reference.

As a side note, if we ever do have to do a search, I'm not that concerned about the performance characteristics. Unless we have a leak condition, the mapping should have at most 32 entries, which means that even a linear search is not going to be an issue.

**Comment by swfarnsworth** [comment]
As I'm in the process of solving this, I believe the code as it stands in the master branch removes the help cooldown role from the claimant even if they should be on cooldown by virtue of another channel they've opened. Unless that's being handled elsewhere and I haven't noticed, is this also something we want to fix?

**Comment by MarkKoz** [comment]
Yes, it should be fixed.
