### ISSUE TITLE
Adding special logic when matching domains (bar.com matches foobar.com)

### ISSUE THREAD

**Issue by decorator-factory** [python-discord/bot#1260]
When a domain like `cookies.com` is added to the blacklist, websites with domains containing `cookies` are triggered as well, for example, `deliciouscookies.com`. (can't link actual example because it's NSFW)

Maybe some special casing can be implemented to prevent `deliciouscookies.com` from triggering? I know that you can do `http://cookies.com` and `https://cookies.com`, but this particular website was linked without the protocol.

**Comment by ks129** [comment]
I will fix it

**Comment by Akarys42** [comment]
This issue is now up for grabs, if anyone is interested.
