### ISSUE TITLE
"!d set" command gets no response from the bot

### ISSUE THREAD

**Issue by anythingapplied** [python-discord/bot#1270]
When I type a bot command `!d set` I expect to get documentation similar to the response for `!d list` or `!d dict`, but instead the bot doesn't respond at all.

**Comment by Den4200** [comment]
This is because `set` is a subcommand for the `!docs` command. Since you do not have permissions to use it, the bot will not respond. If you want the docs for a set, use `!d g set` instead.

**Comment by Mushinako** [comment]
Is it feasible to make `!d set` without other arguments an alias to `!d get set`?
