### ISSUE TITLE
Filtering - New blacklist type that catch all subdomains of domain

### ISSUE THREAD

**Issue by ks129** [python-discord/bot#1276]
There is sites that have a lot of different subdomains and all of them should be banned from PyDis. We should have new blacklist that filter out all subdomains of blacklisted domains to avoid adding them one-by-one.

**Comment by MarkKoz** [comment]
I don't think it should be a separate filter. It could be integrated into the existing one. The way I envision it is that simply specifying the domain will filter all its subdomains too. This would apply to any level. So `b.a.com` will filter itself and any further level subdomains of it like `c.b.a.com` but not `a.com`. Granted, it would then be impossible to filter _only_ all subdomains and not the current level. However, I don't foresee that being required.

**Comment by Shivansh-007** [comment]
This can possibly done with the help of [Wolfram Alpha](http://www.wolframalpha.com/)

1. The domain:

    ![image](https://user-images.githubusercontent.com/69356296/114325557-5625bc00-9b4e-11eb-9ff8-8eff6ae26a93.png)


 2. In the 3rd section, click **Subdomains**

    ![image](https://user-images.githubusercontent.com/69356296/114325550-4ad29080-9b4e-11eb-9ad2-b8e1097af8fd.png)

**Comment by onerandomusername** [comment]
> 
> 
> This can possibly done with the help of [Wolfram Alpha](http://www.wolframalpha.com/)
> 
>     1. The domain:
>        ![image](https://user-images.githubusercontent.com/69356296/114325557-5625bc00-9b4e-11eb-9ff8-8eff6ae26a93.png)
> 
>     2. In the 3rd section, click **Subdomains**
>        ![image](https://user-images.githubusercontent.com/69356296/114325550-4ad29080-9b4e-11eb-9ad2-b8e1097af8fd.png)

This actually can be done with dns lookup on a domain to see all domains registered under a specific domain.

Although, the best solution for this would likely be a regex checking for a subdomain.

**Comment by Akarys42** [comment]
> This can possibly done with the help of [Wolfram Alpha](http://www.wolframalpha.com/)
> 
> 1. The domain:
>    ![image](https://user-images.githubusercontent.com/69356296/114325557-5625bc00-9b4e-11eb-9ff8-8eff6ae26a93.png)
> 2. In the 3rd section, click **Subdomains**
>    ![image](https://user-images.githubusercontent.com/69356296/114325550-4ad29080-9b4e-11eb-9ad2-b8e1097af8fd.png)

Using our wolfram alpha credits for this sounds really silly. It isn't something that we need an external service of any kind for that.

With the new filter system, we want to have a flag on each domain to say if it should flag subdomains, I think that's something we can do with a smart regex, something along the lines of `([a-zA-Z0-9]+\.)*([a-zA-Z0-9]+)\.([a-zA-Z0-9]+)` with the second group being the second layer domain.

**Comment by Akarys42** [comment]
> This can possibly done with the help of [Wolfram Alpha](http://www.wolframalpha.com/)
> 
> 1. The domain:
>    ![image](https://user-images.githubusercontent.com/69356296/114325557-5625bc00-9b4e-11eb-9ff8-8eff6ae26a93.png)
> 2. In the 3rd section, click **Subdomains**
>    ![image](https://user-images.githubusercontent.com/69356296/114325550-4ad29080-9b4e-11eb-9ad2-b8e1097af8fd.png)

Using our wolfram alpha credits for this sounds really silly. It isn't something that we need an external service of any kind for that.

With the new filter system, we want to have a flag on each domain to say if it should flag subdomains, I think that's something we can do with a smart regex, something along the lines of `([a-zA-Z0-9]+\.)*([a-zA-Z0-9]+)\.([a-zA-Z0-9]+)` with the second group being the second layer domain.

**Comment by Shivansh-007** [comment]
Sure, I will go ahead and implement this.

**Comment by Akarys42** [comment]
Superseded by #1530
