### ISSUE TITLE
Command to edit blacklist entries

### ISSUE THREAD

**Issue by bast0006** [python-discord/bot#1277]
At the moment, the only way to edit a blacklist entry is via the api or by removing and then adding an entry. If someone only wants to add a reason or change a specifier it's error-prone and has (trivial) gaps in coverage, especially if you're just adding onto the reason why something is in the blacklist. 

!blacklist edit 

Should work just fine for this, although it might want its own API route in the backend.

**Comment by wookie184** [comment]
This is now possible with the new filtering system using `!filter edit`
