### ISSUE TITLE
Short aliases for infraction editing

### ISSUE THREAD

**Issue by bast0006** [python-discord/bot#1278]
At the moment, !infr edit last or !infr edit l is the fastest way to amend a previous infraction. Similar to #1170, but more limited in scope. Something like `!i e l` would be nice, if doable, if not `!infr e l` or even `!iel`.

**Comment by mbaruh** [comment]
Just making aliases to `infr` and `edit` will allow it to be extendable to the new `append` subcommand, so that seems good to me.
At the same time, the new subcommand might alter the way we use `infr edit last`, so we might want to first limit it to what was said in the previous sentence.

**Comment by MarkKoz** [comment]
`!i e l` is doable as it simply requires an alias each on the group command and the subcommand. Also consider `!ie` using the `root_aliases` feature I added. `last` or an infraction ID could be passed as an argument as normal.
