### ISSUE TITLE
Muted users still are able to talk in Voice Chat

### ISSUE THREAD

**Issue by eivl** [python-discord/bot#1288]
Me and Hem noticed that a muted user still was able to talk in Voice Chat. 
![](https://i.imgur.com/mmNE6T2.png)

I suggest that we change it so that a muted user cant talk in voice.

**Comment by SebastiaanZ** [comment]
This is due to the way we've currently set up the permissions in Discord. I'll look into changing it.

**Comment by SebastiaanZ** [comment]
The permissions are changed.
