### ISSUE TITLE
Filter functionality for emoji-spam messages

### ISSUE THREAD

**Issue by bast0006** [python-discord/bot#1292]
Now that someone's figured out you can cause havok by dumping massive amounts of emojis into a channel, we need a filter to automatically manage this ASAP. Detection should be fairly simple, a very high emoji count is required for the effect (>20/message to >250 for varying impact) but emoji variance is not required. 

Tangentially: This is also likely related to a discord update that went out that has slowed the emoji loading process recently.

I think we can safely filter out and autodelete high emoji messages without significant false positives. 

We may want to handle both unicode emojis and server emojis. 

It's possible for unicode emojis to get a higher "load" because they could as one character for message transmission purposes but server emojis count for more. However, server emojis may be animated, and will apply significant load by that fact as well.

**Comment by MrHemlock** [comment]
So what kinds of emojis does this affect?  Do standard unicode ones trigger it?  Is it specifically Discord or custom emoji?

**Comment by Akarys42** [comment]
FYI we already have [a rule for custom emojis](https://github.com/python-discord/bot/blob/master/bot/rules/discord_emojis.py), we can simply edit this one.

**Comment by ks129** [comment]
I will fix it.

**Comment by ks129** [comment]
I will use `emoji` library (https://github.com/carpedm20/emoji/blob/master/emoji/unicode_codes.py) as Unicode emojis can be made from multiple emojis and this library takes care over parsing them as 1 emoji.
