### ISSUE TITLE
Improving dormant help channel embed

### ISSUE THREAD

**Issue by gustavwilliam** [python-discord/bot#1295]
Following the successful implementation of an updated available help channel embed, I think it's time that we update the dormant help channel embed as well. There are two main reasons and goals for wanting to update this:
- Improving consistency
- Improving the dormant message
  - Telling the user what to do if the question wasn't answered

### Current help channel embeds
Here is the new available help channel embed:
<img width="525" alt="Screenshot 2020-11-21 at 01 14 50" src="https://user-images.githubusercontent.com/65498475/99861634-f591e480-2b96-11eb-8118-079a61c2ad7c.png">

This is the current dormant embed:
<img width="525" alt="Screenshot 2020-11-21 at 01 15 41" src="https://user-images.githubusercontent.com/65498475/99861665-13f7e000-2b97-11eb-8492-0d6b4c2fa659.png">

### Implementation
I'm currently considering the following styling:
- A red embed
- Uses a red `x` icon

**Comment by minalike** [comment]
I actually quite like that the embed is not flashy (no icon, plain black border).

**Comment by vivekashok1221** [comment]
We should link `#how-to-get-help` in the dormant help channel embed.

**Comment by dawnofmidnight** [comment]
> Uses a red `x` icon

I don't think that sends the right message. Channels are often closed with successes (problems were fixed) too, and I don't think that conveys that.

**Comment by minalike** [comment]
> We should link `#how-to-get-help` in the dormant help channel embed.

Is the justification for this because users will click on a channel in the Dormant category?

**Comment by Preocts** [comment]
Thinking about the call to action the embed represents, I think a color could make it more immediately notable to the eye but that color should be neutral. Blurple perhaps?  Happens to align the Zzz emote used presently.

**Comment by gustavwilliam** [comment]
> I actually quite like that the embed is not flashy (no icon, plain black border).

@minalike I agree. My stance today is that we could make the embed less cluttered, but still keep it neutral.

Why was this issue revived all of a sudden?

**Comment by minalike** [comment]
I was just looking for possible issues to put on staff meeting agenda.

**Comment by gustavwilliam** [comment]
What about a simple embed like this?

<img width="538" alt="Screenshot 2022-10-25 at 07 27 09" src="https://user-images.githubusercontent.com/65498475/197689997-a88a11ff-f888-4e81-958e-93380b7b4e33.png">

Here's the raw text:
```
This help channel has been closed and it's no longer possible to send messages here. If your question wasn't answered yet, feel free to ask in a new help channel by checking out <#704250143020417084>. To maximize your chances of getting a response, check out this guide on [asking good questions](https://pythondiscord.com/pages/asking-good-questions/).
```

**Comment by vivekashok1221** [comment]
> > We should link `#how-to-get-help` in the dormant help channel embed.
> 
> Is the justification for this because users will click on a channel in the Dormant category?

Yes.
