### ISSUE TITLE
Add `pydoc` command

### ISSUE THREAD

**Issue by jchristgit** [python-discord/bot#13]
The standard library has a module `pydoc` which can be used for generating and viewing documentation. I suggest a command such as `[prefix] pydoc <NAME>` which calls `pydoc.doc` with the given name to show instant documentation. I feel like this could be useful when referring to a certain method when helping someone - here's an example with `str.find`: 
```py
>>> import io
>>> import pydoc
>>> out = io.StringIO()
>>> pydoc.doc('str.find', output=out)
>>> print(out.getvalue())
Python Library Documentation: method_descriptor in str

str.find = find(...)
    S.find(sub[, start[, end]]) -> int
    
    Return the lowest index in S where substring sub is found,
    such that sub is contained within S[start:end].  Optional
    arguments start and end are interpreted as in slice notation.
    
    Return -1 on failure.
```

for "bigger" documentation such as `help(dict)`, this generates quite the long output. It might be a good idea to truncate this or put it into a "pageable embed" (with reactions to move around). Also, I've yet to figure out if it's somehow possible to include a link to the official docs..

**Comment by martmists** [comment]
You might be interested in using `sphinx.intersphinx` instead. It allows adding .inv files which are harmless to extract the data, contrary to pydocs which requires the modules to be installed.

**Comment by gdude2002** [comment]
Are you guys planning on a PR for this one or would you like us to handle
it? We're ready to approve this ticket and triage it in our tracker if the
latter.

**Comment by martmists** [comment]
I could implement this once I get my new PC set up.

**Comment by gdude2002** [comment]
Perhaps leave it for one of the others, mart - this would be a great PR for someone less experienced to get their feet wet.

**Comment by martmists** [comment]
I can work on one nonetheless, and add it as forever-pending PR as suggestion/inspiration

**Comment by gdude2002** [comment]
That would look awful and reflect poorly on both us and you.

**Comment by JoeBanks13** [comment]
It's not important that only installed modules work, we can add modules in high demand. The majority of questions asked in our guild can normally be answered with python built-in functions. I'd say pydocs is fine.

**Comment by gdude2002** [comment]
No, I think the versatility would serve us well - the command will be _a lot_ more useful if we can expand it out that way.

And it's a great idea to not pollute your environment with packages.

**Comment by hargoniX** [comment]
due to many 3rd modules using readthedocs.io URLs what about adding a google or other search engine feature which searches for something like "{module} docs" and filters the first readthedocs.io URL out of the for example first 10 results and sends that (or maybe even tries to parse and send then)

**Comment by martmists** [comment]
many projects on readthedocs are based on sphinx, so intersphinx would definitely be the way to go if we're taking that approach
