### ISSUE TITLE
Annihilate the `!reddit` command 

### ISSUE THREAD

**Issue by Akarys42** [python-discord/bot#1301]
Once the `#reddit` channel will be managed by Sir-Lancebot (see https://github.com/python-discord/sir-lancebot/issues/530), the [Reddit command](https://github.com/python-discord/bot/blob/master/bot/exts/info/reddit.py#L257-L260) should be removed from Python. 

This is stalled until https://github.com/python-discord/sir-lancebot/issues/530 is completed.

**Comment by RohanJnr** [comment]
I will take care of this along with the lancebot's issue
