### ISSUE TITLE
Alphabetize Default Config

### ISSUE THREAD

**Issue by HassanAbouelela** [python-discord/bot#1312]
The config file can use some cleaning up, just organizing a few things into alphabetical order. I can tackle this if this is a needed fix.

Examples (these are all individual items, categories and sub-categories can also be reorganized):
- [L3-L4](https://github.com/python-discord/bot/blob/0242b4e/config-default.yml#L3-L4)
- [L8-L9](https://github.com/python-discord/bot/blob/0242b4e/config-default.yml#L8-L9)
- [L13-L14](https://github.com/python-discord/bot/blob/0242b4e/config-default.yml#L13-L14)
- [L27-L30](https://github.com/python-discord/bot/blob/0242b4e/config-default.yml#L27-L30)
- ...

**Comment by mudkipdev** [comment]
why though, what does this achieve?

**Comment by HassanAbouelela** [comment]
I was working on another PR, and was asked to alphabetized my additions. A lot of the content in this file, and other constants files are already alphabetized, and this shouldn't be particularly difficult.

**Comment by HassanAbouelela** [comment]
Yeah sure, I can tackle it today.
