### ISSUE TITLE
Add a dynamic message at the bottom of `#how-to-get-help`

### ISSUE THREAD

**Issue by Akarys42** [python-discord/bot#1320]
Actions https://github.com/python-discord/organisation/issues/315. 

We should have a dynamic message at the bottom of #how-to-get-help saying something along the lines of 
“The currently available channels are #help-element1 and #help-element2, feel free to ask in any of those two channels!”, 
to avoid getting anyone getting confused by the currently open channels like we had in the past.

**Comment by mudkipdev** [comment]
How would the #how-to-get-help message be stored? Would the bot just get the latest message from the channel?

I could probably work on this.
