### ISSUE TITLE
Race condition resulting in a double close in help commands

### ISSUE THREAD

**Issue by bast0006** [python-discord/bot#1341]
It's possible for !close to fire at the exact same time as the autodormant check, which runs at a variable amount of time since the last messages. While rare, it results in a desynchronization of the bots internal management of help channel locations, and has in the wild resulted in a double-declaim of a help channel. 

Essentially, the !close command can attempt to deschedule an idle check that is already running at that exact moment, resulting in both the idle check and the close command placing the channel in the idle category AND in the upcoming queue for new available channels. Neither the close command nor the autodormant check to make sure the channel they are operating on is within the in-use channels, and thus they add the channel to be "made available" twice. 

There are several avenues for a fix. First, we could check to ensure a channel is not within the idle channels before scheduling it, which will fix all cases where the idle timer would finish firing before the channel is rescheduled (but would permit the bug to remain in very-high-volume times). Another is to check the available channel queue before moving a channel to the idle category, which will prevent the double-queue, however, it doesn't fix the double-scheduled idle task and could also cause issues during high volume times.

It may be a better idea to use the on_message_lock during !close and the idle timer, to prevent them from running at the same time and stepping on each other's toes, and to prevent potential future race conditions involving the on_message handler and the idle timer and close command.

**Comment by MarkKoz** [comment]
I had intended to work on this after the refractor by using the lock decorator i made. However, it proved to be more complicated than it first seemed so I put it aside.
