### ISSUE TITLE
Embed helper

### ISSUE THREAD

**Issue by gustavwilliam** [python-discord/bot#1348]
Currently, we create embeds from scratch every time we need them (ignoring paginators). I'm proposing that we creat an embed helper, that will help make embed creation simpler and increase the DRYness of our code.

### Use cases
In #1136, I proposed adding a trash icon to bot messages by default, and allowing commands to opt out. With an embed helper, this would be as simple as passing an optional `no-delete` argument set to `True`.

We've also discussed the possibility of making the embed colors more consistent. With an embed helper, we could have a type argument, where we tell the helper if it is info, a warning, error or similar categories. This would auto-apply styling for that case, and could set titles to the correct predefined responses by default.

This would allow us to easily update the color of all embeds in the category, add trash options to all embeds by default and reduce the amount of code needed for creating embeds.

**Comment by SuperMaZingCoder** [comment]
I agree that a system should be put in place to create an embed more easily, but I think there are some other options to consider. For instance, adding specified colors could be done with a new class of colors, rather than an entire helper function.  As for the trash icon, I think that is where an embed helper could be useful. If we do not have any use cases other than that, the question is if it is worth creating an entirely new system for that, as of now. 

Of course, I haven't done any work on the source directly yet; these are my thoughts from your message in the Gurkan discord server. Let me know what you think.

**Comment by gustavwilliam** [comment]
I can see where you're coming from. Creating embeds that specify the color out of a set of colors is already an option today, as we have color constants in `constants.py`. However, it seems like you mean that we could add another layer of abstraction, similar to this:

## Color constants
```py
embed_colors = {
    "error": constants.colors.soft_red,
    "info": constants.colors.yellow,
}
```
This would indeed allow us to achieve something similar to what an embed helper would do, regarding color, and I'm open to keeping it an option.

## Embed helper
However, this does not provide the ease-of-use that an embed helper does. An error message would still have to set the title with error replies, color and description, just like we do it today, but allow the color to be slightly more modular. What I'm proposing would instead let the user do it in a way similar to this:

```py
GetEmbed(
    category="error",
    description="Something terrible has happened!",
)
```

This also means that things like random error replies as the title could be set automatically, without having to import the replies and use them whenever they're needed. It's all about making things more modular and reusable. There would also be the option to se color and title, if the user wants to overwrite the defaults for the category.

**Comment by D0rs4n** [comment]
I read through the issue, I'm not sure about the consensus on using enums, but I think defining the categories with an enum would look a bit more consistent. Also.. I believe to implement the `no-delete` "functionality" we should sort of "hand-over" the control to the embed helper, and it'll handle the logic needed to allow the users to delete the message.
Like:
```python
await embed_helper(ctx, no_delete=False,category=embed_categories.ERROR, description="Something went wrong")
```
That would handle things such as setting embed color, adding error replies, or adding the possiblity to delete the message.
(That's purely an example, and my whole idea is just a suggestion)

**Comment by ChrisLovering** [comment]
I'm not sure what problem we're trying to solve here.

Wouldn't we achieve the same thing by just renaming the constants to when they should be used, rather than describing the colour itself? IE `constants.Colours.soft_red` becomes `constants.Colour.error`

**Comment by D0rs4n** [comment]
Yes, but most of times in the code you choose a random reply(`ERROR_REPLIES`) as well, you set the color, all around the code. Furthermore, making a helper would make it much more easier to generate embeds that could be deleted. (Like mentioned in the issue description)

**Comment by ChrisLovering** [comment]
Following discussions in Discord (from [here](https://canary.discord.com/channels/267624335836053506/635950537262759947/879774378773078077) down) we have decided this is not something we want to implement in the bot.

When discord.py 2.0 comes around, there will definetely be a use in making a generic `ui.View` that handles the delete action with a button, that can be used in any `Messagable.send()` call.
