### ISSUE TITLE
Warning infractions in mod channels should fail if the user has DMs off

### ISSUE THREAD

**Issue by swfarnsworth** [python-discord/bot#1352]
Currently, if a moderator issues a warning to a user in a channel that that user can't see (usually a moderator-only channel), and that user happens to not receive DMs from non-friends, the user won't know that they've been warned and the point of the warning is effectively missed.

In this circumstance, the warning should not be entered into the database and the moderator should be informed that the warning has failed.

This change should not be made until @scragly's proposed changes to the infraction architecture are complete. See #1189.

**Comment by swfarnsworth** [comment]
@Xithrius I'm only proposing a change to warning infractions, since the warning message is the point of that infraction.

I don't think there's currently a solution for permission-reducing infractions (mutes, bans, etc.). If someone has DMs turned off, I suppose part of the trade-off they're making is that they lose the opportunity to know without inquiring why their permissions were reduced.

**Comment by Xithrius** [comment]
Understandable. Good idea you got here, I too think that this should be implemented once #1189 is completed.
