### ISSUE TITLE
Make sure that messages from private channels can't be ducked

### ISSUE THREAD

**Issue by Akarys42** [python-discord/bot#1355]
Since our `#duck-pond` channel can be viewed by all our Helpers and we *apparently* can't trust our Moderators (me included :pensive:), we need to add a check to make sure that messages from channels not viewable by Helpers can't be relayed to the duck pond. 

This can be done by adding a new check function in [`bot/bot/exts/fun/duck_pond.py`](https://github.com/python-discord/bot/blob/master/bot/exts/fun/duck_pond.py) and using it in `on_raw_reaction_add()`.

**Comment by anand2312** [comment]
I'd like to work on this 😄
