### ISSUE TITLE
Upon receiving a non-ban infraction, the DM from the bot should tell them about ModMail

### ISSUE THREAD

**Issue by swfarnsworth** [python-discord/bot#1363]
Currently, users get a message like this one when they get an infraction:

![image](https://user-images.githubusercontent.com/32915757/104851448-0c1c9980-58c3-11eb-98cc-b80f25f9dbbb.png)

For infractions other than bans (regardless of duration), the embed should tell them to use the ModMail bot if they want to discuss or ask questions about the infraction. We might also except Superstarify infractions.

I'm not sure if this should await the redesign of the infraction system or if we can implement it without sabotaging Scragly's efforts.

**Comment by mbaruh** [comment]
Seems like something we can go for
