### ISSUE TITLE
Now that the !user command supports not-in-server members, we might want to add an is-bot field

### ISSUE THREAD

**Issue by bast0006** [python-discord/bot#1365]
Something like https://cdn.discordapp.com/emojis/230105988211015680.png?v=1, perhaps prepended to the username in the results? Or another line in the `Member Information` field: `This user is a Bot.`/ `This user is a Verified Bot.`.

**Comment by mbaruh** [comment]
I wonder if another field is a good idea, the embed is already quite long. I think adding the [bot] emoji at the end of the username to make it look like it does in a bot message would be the most intuitive

![image](https://user-images.githubusercontent.com/18114431/105017294-46fe0900-5a4c-11eb-8c5c-9b9f1e2ca3a2.png)
![image](https://user-images.githubusercontent.com/18114431/105017327-4feeda80-5a4c-11eb-92fe-8b64a2d98d56.png)

**Comment by Akarys42** [comment]
My idea was to add it as a badge, since verified bots will also have a badge provided by discord.

**Comment by mbaruh** [comment]
What if it's not verified?

**Comment by Akarys42** [comment]
Another flag will be set, but it isn't a badge. I think we can just append a bot badge at the beginning of the badge list.

**Comment by mbaruh** [comment]
Hmmm I sill think that just literally saying "bot" after the username is the clearest way to do it

**Comment by Akarys42** [comment]
Can we even set custom emojis in embed titles? I'm not sure if that's even possible.

**Comment by jb3** [comment]
> Can we even set custom emojis in embed titles? I'm not sure if that's even possible. 

We'd have to add it to the badges display below, which is probably fine because a bot shouldn't have any other badges.

**Comment by ChrisLovering** [comment]
it also looks like if you try to get the info of a verified bot, it will cause an error. This is because we don't have an emoji for the badge_verified_bot emoji. Here's an image I pulled off discord for it
![image](https://user-images.githubusercontent.com/9753350/106337243-992efd80-6288-11eb-9b5f-344e212a58bf.png)
