### ISSUE TITLE
Command suggester wrongly invoked for commands under cooldown

### ISSUE THREAD

**Issue by mbaruh** [python-discord/bot#1373]
When a command is under cooldown and is invoked again, the error handler will wrongly try to suggest an alternative as if the command does not exist, when it should not do anything at all.

![image](https://user-images.githubusercontent.com/18114431/105258400-5dae7800-5b92-11eb-9841-c07b06766644.png)

**Comment by rijusougata13** [comment]
can you mention the file path where i have to make changes?

**Comment by mbaruh** [comment]
@rijusougata13 the tag handling and command suggestion starts [here](https://github.com/python-discord/bot/blob/2a31892f2339848e13f3e04fce37e64f5242ab84/bot/exts/backend/error_handler.py#L133), *but* you should do some digging, see how the cooldown on tags work, see what's causing the bug. Once you understand how it works, the fix should be fairly simple.

If you want to take this on let me know and I'll assign it to you.

**Comment by ChrisLovering** [comment]
@rijusougata13 Are you still interested in working on this issue?

**Comment by rijusougata13** [comment]
> @rijusougata13 Are you still interested in working on this issue?

you can assign others
