### ISSUE TITLE
Ignore DiscordServerError within Sentry

### ISSUE THREAD

**Issue by Akarys42** [python-discord/bot#1384]
When a Discord outage occurs, we have a tons of error due to some `DiscordServerError`s all around the codebase, due to Discord itself returning some 500s. We shouldn’t create a Sentry issue when receiving those.

**Comment by MarkKoz** [comment]
I think a filter can be configured from the Sentry website. See https://sentry.io/settings/python-discord/projects/bot/filters/data-filters/

**Comment by Xithrius** [comment]
I've ignored it in Sentry. Unless I've done something incorrect, this shouldn't show up in the dev-core channel ever again.
