### ISSUE TITLE
Redis Startup Error

### ISSUE THREAD

**Issue by HassanAbouelela** [python-discord/bot#1385]
## Description
Make fake redis an environment variable (like it is in sir-lancebot), and possibly have the default fake redis value be true.

## Reasoning
A lot of developers try to start the project, just to be met with a long traceback ending with:
> socket.gaierror: [Errno 11004] getaddrinfo failed

It is unclear that the cause here is a lack of a redis setup, and the main indicator that it is, is to look further up in the traceback to find the call to start redis, then to put two and two together.

A lot of debug time can be saved if we have the default value be true, as there aren't major differences for a developer as far as I know. Additionally, making it an env var (call it `USE_FAKEREDIS` to maintain consistency) makes it easier to debug and deploy the app.

Make sure to add the env var to the [contributing guide](https://pythondiscord.com/pages/contributing/bot/#environment-variables), or get someone to do it for you. You should be able to copy the name and description from the [sir-lancebot guide](https://pythondiscord.com/pages/contributing/sir-lancebot/sir-lancebot-env-var-reference/#debug).

## Possible Alternatives
My main concern here is that it is hard for new comers to the project to figure out the error. One possible alternative is to wrap the redis connection code in a try/except, and to log a more meaningful message to help the user.

This should probably be accompanied by a change in the documentation on the contributing guide, or some other resource to help fix the issue.

**Comment by mbaruh** [comment]
I think it's fine, but maybe we should make it fall back to fakeredis if there's no redis? and log a warning if redis was desired.

Regardless of the approach, making the error more meaningful is desirable.

**Comment by ChrisLovering** [comment]
Fixed in #1436
