### ISSUE TITLE
!infraction edit/append doesn’t properly handle ConversionError

### ISSUE THREAD

**Issue by Akarys42** [python-discord/bot#1387]
When passing a non-existing ID to `!infraction edit` or `append`, such as a string, the bot will throw a `ConversionError: (<class 'bot.converters.Infraction'>, ResponseCodeError())`. This should be properly handled.

**Comment by Xithrius** [comment]
Currently being worked on in #1338. 

The error handler should eventually get the ability to handle the inner error of `ResponseCodeError`, which would be `ConversionError`.

**Comment by ChrisLovering** [comment]
This was fixed in #1388 :D
