### ISSUE TITLE
Show purgebanned in the feedback message of pban 

### ISSUE THREAD

**Issue by Akarys42** [python-discord/bot#1412]
Current when a user is banned or purgebanned this feedback message will be sent:
> :incoming_envelope: :ok_hand: applied **ban** to USER permanently.

It would be nice to have `purgeban` instead of `ban` in the message. 

To achieve that, we can add a `purge: True` entry to the `infraction` dictionary in
https://github.com/python-discord/bot/blob/bafa6a9dbf61ae30ef235537408f0b073a88dd19/bot/exts/moderation/infraction/infractions.py#L327

And append `purge` at the beginning of `infr_type` if `infraction.get('purge')` is True
https://github.com/python-discord/bot/blob/bafa6a9dbf61ae30ef235537408f0b073a88dd19/bot/exts/moderation/infraction/_scheduler.py#L237

**Comment by Xithrius** [comment]
I'll be yoinking this one.
