### ISSUE TITLE
Fix tp list command

### ISSUE THREAD

**Issue by wookie184** [python-discord/bot#1423]
Currently the `talentpool list` command shows invalid-user for lots of the user mentions in the embed, as discord only displays them if they're already in the user's cache.

To fix this we can make it display the username and ID in the embed instead of using a mention. If the user is not in the server, this should also be mentioned (afaik we also may not be able to get the username if this is the case).

This is the command in question:
https://github.com/python-discord/bot/blob/844a1b66fb9b82088c3f1dd03d8b9f61d454c943/bot/exts/moderation/watchchannels/talentpool.py#L41

**Comment by Shivansh-007** [comment]
I would like to work on this.

**Comment by ks129** [comment]
@Shivansh-007 I think you should wait until I finish refactor of nominations schema. These may start conflicting otherwise.

**Comment by Shivansh-007** [comment]
Alright @ks129.

**Comment by mbaruh** [comment]
The command should additionally mention in parantheses that a user was already reviewed (if they weren't no need to add anything).

**Comment by mbaruh** [comment]
Afte discussing it with @Shivansh-007 I'll be handling this issue.
