### ISSUE TITLE
Allow multiple nominations on a member to be active at once

### ISSUE THREAD

**Issue by wookie184** [python-discord/bot#1425]
When a staff member runs the nominate command, if the user is already nominated it should not show an error message, instead it should accept the extra nomination. When a user is unnominated it should mark all current active nominations as inactive.

These changes should be reflected in a few places, `!tp list` and `!user` (in mod channels) should show number of current nominations.

**Comment by Akarys42** [comment]
Stalled by https://github.com/python-discord/site/issues/445
