### ISSUE TITLE
Dynamically add a channel to available pool when others are being typed in

### ISSUE THREAD

**Issue by jb3** [python-discord/bot#1427]
Following on from python-discord/meta#92.

We want to provide a third help channel in the available category so that more people can type their question at once without the channel being claimed halfway through. Please see the original issue for the justification.

The help channels cog must be altered to provide for this and place 3 help channels into the available pool (as opposed to the current two).

**Comment by Den4200** [comment]
It should be as simple as updating the config value.
https://github.com/python-discord/bot/blob/27e60e94bd1fe6784c2b7674433bb175255fa217/config-default.yml#L473

**Comment by jb3** [comment]
Indeed! Alright, let's make that change.

We'll then need to update the documentation for the feature though, so we'll leave this open. I think @SebastiaanZ has previously done work on the how to get help channel.

**Comment by jb3** [comment]
Partially resolves!

**Comment by OpenPiece** [comment]
I'm just curious as to why a static change (a simple bump to 3 channels) was chosen, as opposed to dynamic change, as described in the original issue:
> the bot could detect typing in these channels and if both are being typed into at the same time, send a new channel in

Dynamic change like this could be quite beneficial and wouldn't require further issues with increasing the count, it would also mean that during the more active hours, there would perhaps be more help channels, to satisfy the need. But of course, there should be some minimum/maximum amount of channels, but it should be within discord.py capabilities to do something like this.

Is it because of the amount of API calls it would require or was there some other reason to go with a static bump like this?

**Comment by HassanAbouelela** [comment]
The static bump was only a temporary fix. There are certain problems with the typing solution due to the way discord handles typing events (more detail than is needed right now), so we decided to table that for now while we continue looking for better solutions.

**Comment by jb3** [comment]
Yep, as Scale mentions this is a temporary solution.

We do have some internal issues that were opened after we merged this to talk about this including suggestions such as using reactions. We'll update onto this repo once we've held a discussion.

**Comment by Shivansh-007** [comment]
We should remove `good first issue` label from this issue (#1427) and add a `status: deferred` label since there are problems in `on_typing` event of discord.py.

Context: https://discord.com/channels/267624335836053506/635950537262759947/816596256163496036

**Comment by HassanAbouelela** [comment]
Thanks, done.

**Comment by TizzySaurus** [comment]
I believe the issues we had with the `on_typing` have been resolved on Discord's end, and so this is no longer stalled if someone would like to look into it.

**Comment by zeph-yrus9** [comment]
Correct me if I am wrong! This can be achieved by defining an 'on_typing' event listener?
And according to me there must be some upper limit to the channels that can occur in `available help category` even when added dynamically please do share your thoughts and relatable numbers about that.

**Comment by vivekashok1221** [comment]
I agree, there should be an upper limit. 
With that said, there are plans:tm:  to migrate our help channel system to Discord forum channel. I'm afraid, in that case, work done on this issue will be a waste of effort.

**Comment by zeph-yrus9** [comment]
Makes sense!
then I think we should stall this issue.

**Comment by wookie184** [comment]
Now we're using forum channels this doesn't seem relevant any more.
