### ISSUE TITLE
Delete messages when `!pypi` module is invalid

### ISSUE THREAD

**Issue by TizzySaurus** [python-discord/bot#1443]
When users use the `!pypi` command with an invalid module, you currently get a response saying `"Package could not be found."`. 

What I'm proposing it that after a delay (I believe we have `bot.constants.RedirectOutput.delete_delay` for this) the bot should delete both its response and the invocation message, like [`!d` currently does](https://github.com/python-discord/bot/blob/master/bot/exts/info/doc.py#L363-L365).

This would help reduce channel flooding when someone is trying to remember the name of a module, and since it's not a trivial change I'm happy to try and implement this myself if it's something we decide we want.

**Comment by Xithrius** [comment]
I'll take this up.
