### ISSUE TITLE
Improve help channel closing by differentiating between the OP and other users.

### ISSUE THREAD

**Issue by laundmo** [python-discord/bot#1451]
### Goal
Implement a system that closes help channels more quickly if the OP (the person who originally opened the channel) has not responded in a while. This is to prevent channels from going stale for a very long time.

### Implementation suggestion

The initial implementation suggestion is that 10 minutes after the last user message, and 30 minutes after the last OP message the channel will be closed.

This issue is meant as a place to discuss different implementations and ideas relating to the Goal.

**Comment by Theelgirl** [comment]
Yes +1

**Comment by Akarys42** [comment]
The proposed implementation sounds good to me.

**Comment by ChrisLovering** [comment]
I'm going to give this a go
