### ISSUE TITLE
Remove reactions from users that aren't the OP for pagination and trash can.

### ISSUE THREAD

**Issue by dawnofmidnight** [python-discord/bot#1454]
### Goal
When using pagination or the trash can symbol (the one used to delete embeds), it is set to only be able to use by the OP. It may help clean it up to delete reactions from people that aren't the OP.

### Implementation Suggestion
Python already checks whether the person adding the reactions for pagination or the trash can is used by the OP, so it would be simple to use `remove_reaction` to get rid of the useless reactions.

**Comment by dawnofmidnight** [comment]
I can work on this, but I'll need some time to finish up some branding assets.

**Comment by ToxicKidz** [comment]
Can I take this one?

**Comment by Akarys42** [comment]
Sure thing @ToxicKidz!

**Comment by ToxicKidz** [comment]
Is this just going to be changing bot/pagination.py?
