### ISSUE TITLE
Shorten PyPI Embed

### ISSUE THREAD

**Issue by HassanAbouelela** [python-discord/bot#1457]
## Description
The PyPI embed can take up a lot of vertical space, which can be a little problematic in rapidly moving chat channels, such as python-general. We could maintain most of the embed's functionality while reducing the space it takes up.

## Implementation
There are currently the following fields in the embed: Author, Summary, License, and Python Versions.
One possible implementation would be to limit the number of fields displayed to only include the most helpful ones. For example, we could leave only the description:
| All Fields | ![image](https://user-images.githubusercontent.com/47495861/110365858-962ce700-8056-11eb-852e-78923a9008e7.png) |
| - | - |
| Just Description | ![image](https://user-images.githubusercontent.com/47495861/110365966-bd83b400-8056-11eb-9973-7df24003fe71.png) |

This minified version can be limited to certain channels, such as python general.

Another possible implementation would be to have inline fields. That may work, but we are also limited on horizontal space.

**Comment by Xithrius** [comment]
I like this new embed, and I also agree that the license and author is not necessary when providing info.

Do we want the "**Summary**" field as well, or do we just want the summary below the title?

Either way, I can yoink this one.

**Comment by HassanAbouelela** [comment]
I think the latter sounds better. Feel free to grab the issue 😄.
