### ISSUE TITLE
Feature: !github command

### ISSUE THREAD

**Issue by ToxicKidz** [python-discord/bot#1472]
We have the `!pypi` which is useful, and I think that a `!github` command can be useful to share repositories with others.

## Usage
`!github python-discord/bot` ***Sends info about the `bot` (this one) repo.***
`!github search discord.py` ***Shows search results for the term `discord.py`***
Maybe some other command(s)

## Additional Details
We can use the github api for this.
I would like to implement this command.

**Comment by MrKomodoDragon** [comment]
Like this idea, but maybe it could be a feature of Sir Lancebot, as it isn’t “essential”

**Comment by MarkKoz** [comment]
See #629
