### ISSUE TITLE
Move static content site commands to tags

### ISSUE THREAD

**Issue by Numerlor** [python-discord/bot#1473]
The site commands tools, resources, help and home construct embeds from mostly static strings, with only the site url being variable. The url is already referenced in other tags so this won't bring any additional maintenance in the case it does change for some reason. 
Moving them to tags will also allow the more direct fuzzy matching and per channel cooldowns to take effect.
With the other commands removed the only left will be the rules command; I think we should move it to the Information or Utils cog and get rid of the Site cog

**Comment by MarkKoz** [comment]
I agree. That would be a good refactor.

**Comment by Numerlor** [comment]
Which commands do we want moved?
Looking at it there's the site home/about and site help commands, which don't looks like they'd fit a tag, at least if the names are kept. But I don't think they get much use, what do the usage stats look like for them?

**Comment by MarkKoz** [comment]
Last 6 months:
```
site_resources  4 K
site_rules  4 K
site_tools  84
site_home   72
site_faq    43
site_help   10
```

I don't see why they all can't be tags (except rules). I guess the names should be like `sitefaq`, `sitehome`, etc.

**Comment by Numerlor** [comment]
My main concern here is `site-help`, as a tag I don't think the name really fits it and it may be used in a fashion similar to how the ask tag was used.

**Comment by ChrisLovering** [comment]
I think each of them could be ported across to tags, using their root aliases. I rarely ever see people doing `!site resources`, instead they opt for `!resources`, similar story for the others.

As for the site-help tag specifically, I brought it up with other core devs, and we agreed that it should be dropped entirely.
