### ISSUE TITLE
Opt-out of DMs when opening a help channel

### ISSUE THREAD

**Issue by ChrisLovering** [python-discord/bot#1481]
Some users seem to not like this feature, from DM logs. It might be a good feature to have the ability to opt-out of receiving a DM from the bot when you open a channel.

**Comment by Slushs** [comment]
That could be cool. But its pretty helpful if you forget your channel!

**Comment by ChrisLovering** [comment]
> That could be cool. But its pretty helpful if you forget your channel!

Oh absolutely! My suggestion here is have them on by default, but offer an way to opt-out of the messages for those people who don't want them

**Comment by Slushs** [comment]
That would be a cool idea, welp sadly I have no say in anything so I guess just wait for there response lol. :)

**Comment by jb3** [comment]
How widespread is the dislike of this? I can't imagine people receiving more than 3 or 4 DMs per day for the heaviest help channel users, with others receiving much less.

I'm open to the idea but it's another data point to store and retain, and since we don't guarantee persistence on Redis I'm not sure of the best solution in case we lose persistence and start sending DMs again.

**Comment by Slushs** [comment]
To be 100% honest with you joe I don't think its a widespread dislike. If anything I think it was a good feature that a bunch of people enjoy and use daily. But if it could be implemented without being a pain in the you know what. Then I guess it would add some customization.

**Comment by mbaruh** [comment]
I think if we implement this we have no reason to guarantee persistence. We use redis in places where persistence is arguably more important than here. If for some reason we lose our redis data, they can opt out again. I see it as something similar to when you tell a website to remember your credentials. At some point it asks for them again.

**Comment by hedyhli** [comment]
What are our thoughts with this issue now that we use the forum-based help threads?

It was requested in [`#community-meta`](https://discord.com/channels/267624335836053506/429409067623251969/1214349632830971985) recently, and @swfarnsworth also brought it up [internally](https://discord.com/channels/267624335836053506/551789653284356126/1214378116139450378).

Discord forums supports tracking your own thread natively so it's now less needed as it was when we used the dynamic help-channels system.

Should we just remove this issue altogether with a changelog announcement (for users expecting these DMs), or disable it by default with an opt-in command for users who still want it?

**Comment by ChrisLovering** [comment]
I agree hedy. 

IMO both the help-dm system, and the notifications when you open a new help channel can be deleted.
The forum channel solves both issues that the old system had that are the reasons for these features existing.

**Comment by swfarnsworth** [comment]
I agree that we can just delete this functionality.

**Comment by ChrisLovering** [comment]
See https://github.com/python-discord/bot/pull/2968
