### ISSUE TITLE
Mention #how-to-get-help in default help command.

### ISSUE THREAD

**Issue by AG4lyf** [python-discord/bot#1482]
I have seen people often getting confused !help command to help with their python code.

!help should mention on top, if they want help with python code they go to #how-to-get-help.

**Comment by MrKomodoDragon** [comment]
Can I make a PR for this?

**Comment by MarkKoz** [comment]
I'm not convinced this is a worthwhile trade-off. It would make the help command a "worse" experience for users that use it for its intended purpose. I feel like the situation you describe is the less common case.

**Comment by AG4lyf** [comment]
to be fair. as people are getting to know about discord recently. i have seen this happening a quite bit


i don't  think there is any precious we are losing by adding a single line to help command.

**Comment by AG4lyf** [comment]
you* 
not we

**Comment by Akarys42** [comment]
I share Mark's and Tizzy's concerns, I don't think the tradeoff is worth it. We won't be implementing this.
