### ISSUE TITLE
Show if the user has opted out of metricity in the user embed

### ISSUE THREAD

**Issue by Akarys42** [python-discord/bot#1484]
Currently we have no way of knowing if the message count isn’t accurate because the user opted out of metricity. Once https://github.com/python-discord/site/issues/467 is resolved, the information will be available to the bot under `user_activity["opt_out"]` and can be added here:

https://github.com/python-discord/bot/blob/15c1d321ccd8ff9c7c9b7802ea732e43fcffbf9e/bot/exts/info/information.py#L392-L394

**Comment by Akarys42** [comment]
Stalled by https://github.com/python-discord/site/issues/467

**Comment by jb3** [comment]
Resolved by python-discord/metricity#3. We no longer have opt-out functionality.
