### ISSUE TITLE
Add ability to reference headers in pep command

### ISSUE THREAD

**Issue by dumdoo** [python-discord/bot#1495]
# Python Bot Suggestion
When using the _pep_ command, one should be able to 'reference a header'. For example if someone wants to send info on max line length from _pep8_, they should be able to do

`!pep 8 #maximum-line-length`

This should make the link url be `https://www.python.org/dev/peps/pep-0008/#maximum-line-length`
---
## What if someone wants to reference a channel after the _pep_ command
Example: `!pep 8 #python-general`
Solution:
In order to actually reference a header you could (instead of doing `!pep 8 maximum-line-length`) instead do `!pep 8 ##maximum-line-length`

---
## What to do if the header is invalid

Maybe display an embed of the sort found below and replace the text with something along the lines of
> Header not found, here is the page's link anyways!

![image](https://user-images.githubusercontent.com/51958309/113466883-a15a1380-9458-11eb-8266-45ff947fb4ec.png)
And sends the regular `pep <number>` command's embed

## How to differentiate between a "Header PEP" or "Non-Header PEP" 
![image](https://user-images.githubusercontent.com/51958309/113466927-044baa80-9459-11eb-953c-35f03bcd62ee.png)
Add another field next to `Status`, `Created` and `Type` and name the field `Header` and set its value to the headers name

**Comment by MarkKoz** [comment]
Is anyone actually going to remember the exact names of specific headers? I imagine it would have to be looked up first. At that point, may as well send the link directly (since it's already open in one's browser) rather than through the command.

**Comment by dumdoo** [comment]
> Is anyone actually going to remember the exact names of specific headers? I imagine it would have to be looked up first. At that point, may as well send the link directly (since it's already open in one's browser) rather than through the command.

Maybe the bot will have something like fuzzy search? So then you won't have to remember the exact header

**Comment by MarkKoz** [comment]
That would involve downloading the HTML and parsing it for all available headers. It's just not worth it.

**Comment by wookie184** [comment]
I agree that this isn't worth doing
