### ISSUE TITLE
Don't consider colorless roles for the `!user` embed color

### ISSUE THREAD

**Issue by bsoyka** [python-discord/bot#1496]
A user with any colorless roles such as `Voice Verified` results in the `!user` embed having a black color (rather than blurple), as shown below.

![Screenshot](https://user-images.githubusercontent.com/37779854/113498668-54178980-94cc-11eb-8ca6-e0e14a128039.png)

This should just be an easy fix to a minor visual problem just by replacing this line:

https://github.com/python-discord/bot/blob/c94fdb0fa5db711236ea02b5bb269e5db906c1a8/bot/exts/info/information.py#L287

**Comment by Akarys42** [comment]
Sounds good, thanks for the issue @bsoyka. Would you like to submit a Pull Request?

**Comment by bsoyka** [comment]
Sure, @Akarys42! Please assign this one to me and I should be able to get it done sometime in the next few days.

**Comment by Akarys42** [comment]
Awesome! If you have any question, feel free to ask in `#dev-contrib`!
