### ISSUE TITLE
Show the result of !eval in #bot-commands when it is used in a channel where it is not allowed.

### ISSUE THREAD

**Issue by dawnofmidnight** [python-discord/bot#1498]
## Description
When the command `!help` is used in a channel such as `#python-general`, Python prints out the result in `#bot-commands`. However, when a command like `!eval` is used, Python simply tells the user that they can't do that here. It would be nice if Python showed the results of `!eval` in `#bot-commands` the same way it does for `!help`.

## Reasoning
It would enhance the user experience because they wouldn't have to type it all over again.

## Proposed Implementation
The same way Python currently prints the output of `!help` in `#bot-commands` when it's used in a channel where that's not allowed, it should do the same with `!eval`.

## Alternate Ideas
The only alternate implementation that I can think of is the current one, where someone is forced to do it again in `#bot-commands.`

## Would you like to implement this yourself?
- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by MarkKoz** [comment]
Sounds like a good idea to me.

**Comment by ToxicKidz** [comment]
I'd like to implement this.

**Comment by onerandomusername** [comment]
Would it make sense to implement this throughout the entire bot for all commands?

**Comment by mbaruh** [comment]
No, we should decide on commands individually. It might be that it is okay to be done on all commands, but we should list them first and consider each.

**Comment by dawnofmidnight** [comment]
Agreed. I used `!eval` as an example, because that's one where sometimes you spend a while typing out code. For all of them, it could be fine (I don't know all the commands, so I couldn't tell you), but it's at least worth it to consider each command separately.
