### ISSUE TITLE
Disable TRACE log levels by default, with ability to selectively enable them for certain loggers

### ISSUE THREAD

**Issue by Numerlor** [python-discord/bot#1502]
The trace log level should be used for verbose logging, however because of the current setup where every logger always outputs trace logs, it is hard to properly utilize the log level without adding noise to the logs while that module isn't being worked on.

The root logger should be set to the debug level, with trace logs only being enabled for loggers with names that were specified by the user. These names can be listed in an env var, with the ability to also set the root logger to the trace level.

**Comment by MarkKoz** [comment]
I agree that trace logs can get in the way of development sometimes. This is aggravated by logs coming from event handlers, like the ones in the code block detection cog.

Several people, including myself, were in favour of using an environment variable/config field to set the log level on a per-module basis.
