### ISSUE TITLE
Update YouTube terms in `ytdl` tag

### ISSUE THREAD

**Issue by bsoyka** [python-discord/bot#1505]
The [YouTube Terms of Service](https://www.youtube.com/static?template=terms) have been updated a bit since March 14, 2020 when they were last edited in the `ytdl` tag. (They were last changed March 17, 2021 according to the site.)

Specifically, it looks like we need to fix the wording in restrictions 1 and 3.

https://github.com/python-discord/bot/blob/eeacceae01b95e39eaeecab2fd14f6edfb19b94b/bot/resources/tags/ytdl.md

I'm happy to tackle this one really quick once it's assigned to me. :)

**Comment by Akarys42** [comment]
Sounds good @bsoyka, thanks!
