### ISSUE TITLE
Stop an in-progress stream if a user's role is revoked

### ISSUE THREAD

**Issue by ChrisLovering** [python-discord/bot#1506]
If a user's streaming permission is removed via the revoke stream command, we want to stop any stream that may be in-progress.

If a user's video role drops off due to the normal schedule, then we don't need to do this.

`discord.ActivityType.streaming` shows whether a user is streaming.

This implementation should work even if the member don't have the video role anymore.

Concept approved by @MrHemlock

**Comment by RohanJnr** [comment]
The only way I can think of doing this is by moving the user to a temporary voice channel and then back to the original voice channel. Discord does not even provide a way to stop stream in their UI, maybe this feature is gonna come up in the future version of discord.

**Comment by ChrisLovering** [comment]
Yea, agreed. My first thought was to move them to #AFK and back.
