### ISSUE TITLE
Default duration for !superstar command if no duration is specified

### ISSUE THREAD

**Issue by janine9vn** [python-discord/bot#1515]
## Context
The `!superstar` command currently requires a duration to be specified when invoked. 

Often we want to change someone's nickname from something very noisy or that takes up a lot of room until the user can respond and change it themselves. The duration in these cases is not usually that important as we want it to be a quick change.

## Proposal
It would be useful if there was a short default duration for this command. Something like 5 or 15 minutes. It would function similarly to the `!mute` command where if no duration is given, it opts for a 1 hour duration.

**Comment by doublevcodes** [comment]
I'd be willing to implement this.
