### ISSUE TITLE
Keep deleted messages in cache

### ISSUE THREAD

**Issue by mbaruh** [python-discord/bot#1522]
We want deleted messages to remain in the cache so that the bot can account for them when applying spam rules.

One way of doing that is monkey-patching this part https://github.com/Rapptz/discord.py/blob/master/discord/state.py#L483-L504 but it should be accompanied by proper tests to prevent any funny business on version bumps.

Another way is to cache deleted messages in a separate cache, but well.. it was already cached.

**Comment by MarkKoz** [comment]
Can you provide more context on this? AntiSpam uses an API call to get message history; it doesn't rely on a cache. Are you also proposing to change it to use a cache?

**Comment by mbaruh** [comment]
Seems like I misremembered. Then yes, we should use the cache, unless there is some reason against.

**Comment by MarkKoz** [comment]
That's basically a race condition. See https://github.com/python-discord/bot/issues/1018

If you only care about solving the race condition, then there's possibly a better way than to cache deleted messages. However, if you want to also account for messages that users delete themselves, then caching them is likely the only option.

**Comment by mbaruh** [comment]
What would be a better solution? Sebastiaan's suggestion on the other issue doesn't seem to deal with the filters that apply to multiple messages.

**Comment by MarkKoz** [comment]
Using locks or specifying an order for processing. Anything that involves deleting messages should be done at the end. I don't know if it's actually feasible but it's something to consider.

**Comment by mbaruh** [comment]
I might not be following. Even if you execute all filters in the right order for a specific message, if it is deleted by one of them, it is possible that in a few seconds it will turn out it's part of a larger stream of spam messages that should be punished. At that point, the message is already deleted and will therefore won't be taken into account.

**Comment by mbaruh** [comment]
I guess you could still call it a race condition, but it's one that is caused by the filters not having information on the user's future behavior, thus the reasoning that we need a cache.

**Comment by MarkKoz** [comment]
> 
> 
> I might not be following. Even if you execute all filters in the right order for a specific message, if it is deleted by one of them, it is possible that in a few seconds it will turn out it's part of a larger stream of spam messages that should be punished. At that point, the message is already deleted and therefore won't be taken into account.

You're right; I was just thinking about it the wrong way.

**Comment by Akarys42** [comment]
Superseded by #1530
