### ISSUE TITLE
Docs command listing order

### ISSUE THREAD

**Issue by doublevcodes** [python-discord/bot#1533]
When using the `!docs` command to see a list of all of the available packages, any package that starts with a capital letter seems to be brought to the top of the list. Currently the only package starting with a capital letter is **GitPython**

Image of returned embed when `!docs` is used:
![image](https://user-images.githubusercontent.com/54081925/115163143-5ae2f680-a09f-11eb-8251-48e7d2e83ba5.jpeg)

I would be happy to fix this myself.

**Comment by jb3** [comment]
Go for it! I've assigned you to the issue.

**Comment by Numerlor** [comment]
This shouldn't be necessary, package names with capital letters are refused by the bot and https://github.com/python-discord/site/pull/373 will add it to the site
![](https://i.imgur.com/lyHpeGQ.png)

**Comment by doublevcodes** [comment]
> This shouldn't be necessary, package names with capital letters are refused by the bot and [python-discord/site#373](https://github.com/python-discord/site/pull/373) will add it to the site

In that case, I can either:
- Go ahead with the planned changes to handle capital letters
- Ask one of the admins to remove the docs and add them back with all lowercase letters

**Comment by doublevcodes** [comment]
Since this issue seems to be resolved by the restrictions applied on package names, I'll close this issue.
