### ISSUE TITLE
Negative indexing for the !zen doesn't work as expected

### ISSUE THREAD

**Issue by ToxicKidz** [python-discord/bot#1534]
## Description
The `!zen` command has support for negative indexing. This means that since there are 18 lines of the zen of python, doing `!zen -19` should give the first line (0th index). However, this is not the case; doing `!zen -19` just gives an error. The problem seems to be this line: https://github.com/python-discord/bot/blob/main/bot/exts/utils/utils.py#L112

## Screenshots
![image](https://user-images.githubusercontent.com/78174417/115394933-4f7ff000-a1b1-11eb-89fc-f7b3fd518916.png)

**Comment by mbaruh** [comment]
-18 shouldn't show the first line, it should show the second, because we're using Python list indexing. Meaning -1 is the last line (the 19th line). The error then is that the lower bound should be one number lower, meaning it should accept -19.

**Comment by ToxicKidz** [comment]
> -18 shouldn't show the first line, it should show the second, because we're using Python list indexing. Meaning -1 is the last line (the 19th line). The error then is that the lower bound should be one number lower, meaning it should accept -19.

I right, my bad. I was looking at it like it was 18 lines.
