### ISSUE TITLE
Use embed timestamp in reminder

### ISSUE THREAD

**Issue by ChrisLovering** [python-discord/bot#1536]
When a user sets a reminder, a confirmation embed is sent, to inform the user that the reminder was successfully saved.

In this reminder, we currently include the time at which it is due to be sent. This time is in UTC.

I propose we refactor this part of the code to instead use the timestamp field in the Embed.
https://github.com/python-discord/bot/blob/f2970481e1cd8950dbbb2d3b871df68e90f5a932/bot/exts/utils/reminders.py#L85-L105
 This would mean that the time would automatically get converted to the user's current time zone by Discord.

**Comment by Akarys42** [comment]
Sounds good!

**Comment by ToxicKidz** [comment]
I would like to implement this.
