### ISSUE TITLE
If an edited message becomes a command, execute that command

### ISSUE THREAD

**Issue by discretegames** [python-discord/bot#1540]
## Description
If someone forgets the `!` or misspells a command and they edit their message to fix it, the bot should notice that edit and run that command normally - as if it was originally typed correctly. This would only work for messages that were edited within the past 30 seconds or so.

This could be done automatically upon edit or by adding a repeat emoji reaction 🔁 to the message that the user has to click when the bot recognizes the message is now a valid command. The latter is similar to how editing `!eval` commands works.

## Reasoning
Many times while helping in the help channels I've written a code snipped but forgotten the `!e` at the start to evaluate it. I've seen other people do this too. The only solution at present is to repeat the entire message, remembering the `!e`, leading to clutter and hassle.

Indeed it could be useful for any command in case of typos and such. But at the very least I'm proposing this feature for the `!e` command.

## Screenshots
Currently a repeat emoji reaction 🔁 is used to help re-evaluate edited code:
![repeat reaction on eval](https://user-images.githubusercontent.com/35741644/115300754-345fa280-a115-11eb-8501-d8687ee72b7c.png)
The same thing could be done when a message is edited into a command. (Or it could be automatic.)

## Proposed Implementation

As I understand, it could be done by listen for edits in `on_message_edit` and using the same command logic as `on_message` uses to detect and run commands.

## Would you like to implement this yourself?

I'm interested to try but I'm new to discord.py and open-source contribution (but not to Python).

**Comment by aphkyle** [comment]
To be honest, I quite like this idea.
My way of implementing this is using the `on_message_edit` tag to get the message
and use `bot.process_commands` (Not tested yet I'm not sure will it work or not)
to run the message.

**Comment by aphkyle** [comment]
> To be honest, I quite like this idea.
> My way of implementing this is using the `on_message_edit` tag to get the message
> and use `bot.process_commands` (Not tested yet I'm not sure will it work or not)
> to run the message.

Note that this will also run other edited commands. not just `!eval` if you want it to only run on `!eval` or `!e`
you can check if the message starts with `!e` (`!eval` contains `!e` so it should work on both alias).

**Comment by aphkyle** [comment]
I'll work on this if this is approved :)

**Comment by NIRDERIi** [comment]
From the dpy side, bot.process_commands should work. But, if the edited message would not be a valid one, there might be a chance an error message would be shown. The best way I can think about is:
```py
ctx = await self.bot.get_context(after)
if not ctx.valid:
    return
await self.bot.process_commands(after)```

**Comment by Akarys42** [comment]
First, thank you all for suggesting this idea and implementations!

I'm afraid we decided to reject it. The main reason being if a command gets edited and ran half a minute after the original message has been sent, it is hard to get who used what command. We break this immediate process of invocating a command and getting the answer.

We thought about using replies, but this isn't possible unless a major refactoring is done to add that to *every* command, which doesn't sound worth it. We may experiment with that later with custom context menus and what fun things Discord has for us.

Thanks again!
