### ISSUE TITLE
Use embed timestamp in mod pings off

### ISSUE THREAD

**Issue by ChrisLovering** [python-discord/bot#1547]
When a mods turns off mod pings, a confirmation is sent to inform the user that their pings have successfully been turned off.

In this confirmation, we currently include the time at which it is due to be sent, this time is in UTC.

I propose we refactor this part of the code to instead use an Embed, with a the timestamp field.
https://github.com/python-discord/bot/blob/ce819ade482e82ecbc474bce5fb8ac9dd8b37b40/bot/exts/moderation/modpings.py#L107
This would mean that the time would automatically get converted to the user's current time zone by Discord.

**Comment by Xithrius** [comment]
I think this should be done, given that all information is contained within the embed.

**Comment by mbaruh** [comment]
Yeah, that sounds useful
