### ISSUE TITLE
Feature: Gratitude command

### ISSUE THREAD

**Issue by mesub7** [python-discord/bot#1550]
Vintheruler1#9325* was thinking of a gratitude command which you could run once somebody had helped you with something. It would most likely have to have a cooldown of some sort however to prevent abuse.

* They suggested this and I did point them to here but they were happy for me to suggest it and credit them for it.

**Comment by vcokltfre** [comment]
This seems like it would fit better in sir-lancebot if anywhere

**Comment by anand2312** [comment]
I think this could end up game-ifying the system which isn't something we want

**Comment by Xithrius** [comment]
I agree with @anand2312, people would probably just start asking for points or what-not.

> This seems like it would fit better in sir-lancebot if anywhere
@vcokltfre sir-lance wouldn't have a great time tracking points since there's no database.

**Comment by mesub7** [comment]
I don't believe it should be points-based. Rather, it should be an individual 1 off gratitude.

**Comment by Xithrius** [comment]
One user can give 1 gratitude to another user only once? A user could still unfortunately go around asking for gratitude.

**Comment by ChrisLovering** [comment]
Could you describe exactly what this command would do? I think we're all fairly against there being some form of leaderboard for this, since it promotes undesirable behaviour and adds moderation burden.

However, from your comments, it doesn't seem like that's what you had in mind for this. Could you describe in detail what this proposal is?

**Comment by vcokltfre** [comment]
I think they mean one off as in you just run the command and it thanks them totally statelessly, but i still don't really see how it would fit/be of any use

**Comment by dawnofmidnight** [comment]
> I think they mean one off as in you just run the command and it thanks them totally statelessly, but i still don't really see how it would fit/be of any use

If that's the case, I don't see why you couldn't just thank them yourself. That'd also be much more sincere.

**Comment by mesub7** [comment]
In detail:

User A has a problem.
User B helps them solve the problem.

User A thanks User B with the command.
There would be no points (for reasons you have stated above which I agree with entirely). So yes, it would essentially be stateless.

Sometimes, people (like the person who wanted this suggested) want to appreciate their gratitude, especially if it was a challenging issue. They may feel like a simple thank you is not enough, but they don't want to go out of their way and get something (which is not expected anyway). This may be the middle ground between the two.

**Comment by ToxicKidz** [comment]
How would this be different than just saying thank you?

**Comment by Xithrius** [comment]
Sorry, but I don't think this feature will be necessary as a utility or be much as a fun feature.

I do think the original idea was pretty interesting.
