### ISSUE TITLE
Pagination through eval command

### ISSUE THREAD

**Issue by WeMayNeverKnow** [python-discord/bot#1560]
What if we can paginate through the eval command so we can see many more results if the result cant be seen in one page?

**Comment by MarkKoz** [comment]
What's the justification for needing to see that much code? Put another way, why would one need to execute code that generates more output than can fit in one page? Keep in mind, the command is not meant to be users' personal interpreters.

**Comment by WeMayNeverKnow** [comment]
Nvm then
