### ISSUE TITLE
Add a reason argument to `!unban` 

### ISSUE THREAD

**Issue by Akarys42** [python-discord/bot#1565]
It is pretty common for us to run the `!unban` command with a reason at the end, that is currently just silently ignored, causing a loss of information on the long term. The command should accept this argument and append `**Unbanned:** {reason}` to the end of the active ban infraction.

**Comment by janine9vn** [comment]
This is actually a duplicate issue! #718

**Comment by Akarys42** [comment]
> This is actually a duplicate issue! #718

#718 is about adding another field to the infraction for the unban reason, but it will have to wait until the api rewrite. This issue propose a temporary solution of simply adding the unban reason at the end of the infraction reason.

**Comment by ToxicKidz** [comment]
I would like to implement this

**Comment by Xithrius** [comment]
@ToxicKidz What's your status?

**Comment by minalike** [comment]
Would it be possible to also add the unbanned actor and timestamp?

**Comment by VirdanTheBurden** [comment]
It's alright if I take this issue, yes?

**Comment by VirdanTheBurden** [comment]
I'm just taking it. Sorry, I really wanna fix it!

**Comment by ChrisLovering** [comment]
If we are going to be storing the unban actor and timestamp, those should be added as fields against the infraction in site.
