### ISSUE TITLE
Help Channel DM's For The Person Who Is Helping.

### ISSUE THREAD

**Issue by JakeM0001** [python-discord/bot#1567]
So we already have the help channel DM's that sends the user a DM whenever they claim a help channel. But why not also send a DM to the person who is helping in the channel as well. We could also make this toggleable just incase someone doesn't want to receive the DM's.

**Comment by dawnofmidnight** [comment]
Two things. 1) what kind of information would you want to put in this DM? Is there something specific? 2) How would you know if someone is helping in that channel? It's not uncommon that someone might ask the opener about something to clarify, and then they leave the channel since they don't know.

**Comment by JakeM-Git** [comment]
![image](https://user-images.githubusercontent.com/77035482/117298111-fb2d6f00-ae44-11eb-8bdc-2d057e0fe708.png)
so something similar to this, but it would probably not have the "your message", and the title and description would need to be changed. And for your second question, maybe we could have a command that the person who is helping can use for example something like !remember or something like that, and it would only send the user the DM if they type that command.

**Comment by JakeM-Git** [comment]
Also I would be happy to try to implement this by myself but I will see since I haven't really worked with this repo before.

**Comment by RohanJnr** [comment]
I am not sure if this is actually required. Cuz some help channels only last for a few minutes and it could easily get annoying if a user is involved in multiple help channels.

**Comment by JakeM-Git** [comment]
That's why I think it would be smart to have it as a command so it's optional but if you don't think it's necessary then I respect that 100%.

**Comment by janine9vn** [comment]
So, consensus during the staff meeting is that this is something we want.
- It is an opt-in command that a person has to run
- It will DM the person who ran the command when they post their first message in newly opened help channels

**Comment by dawnofmidnight** [comment]
Is this opt-in command going to be permanent, or per channel?

**Comment by JakeM-Git** [comment]
per channel

**Comment by jb3** [comment]
> Ok, so what should the command be.

My suggestions would be `!helpdm on/off` with nice documentation detailing what it does, though we *could* also hook it into the proposed !recent command do `!recent subscribe` and `!recent unsubscribe`.

> Is this opt-in command going to be permanent, or per channel?

@JakeM-Git @dawnofmidnight I think the proposed feature is permanent per user. You subscribe and anytime you interact with any help channel that is in use you get a DM. I may be misunderstanding though.

Example: I run `!helpdm on` and then any help channel I type in I get a DM about.

**Comment by dawnofmidnight** [comment]
I think that having options for both permanent and non permanent would be nice, but that's just my take on it.

**Comment by jb3** [comment]
Temporary does not make sense, the feature is for *you* interacting with the help channels, not others.

**Comment by jb3** [comment]
Yep, a Redis cache mapping user ID --> boolean is all that is necessary.

**Comment by dawnofmidnight** [comment]
> Temporary does not make sense, the feature is for _you_ interacting with the help channels, not others.

What if you don't want to get DMs for every help channel you send a message in, only a specific one?

**Comment by JakeM-Git** [comment]
> Yep, a Redis cache mapping user ID --> boolean is all that is necessary.

Alright, sounds good.

**Comment by dawnofmidnight** [comment]
> I don't follow how that is useful. The feature is not to receive notifications when there is activity in the channel (though we may revisit that down the line), it's to store a record of which help sessions you interacted with in your DMs.

I'm confusing multiple unrelated projects, my bad.

**Comment by JakeM-Git** [comment]
**Update:**

We decided to add a role that will be added every time some does `helpdm` `on` a role will be added and every time `helpdm` `off` is executed the role will be removed this is easier so we don't have to cache that we will only have to cache the message claimants and stuff like that. If you wanna try it out go use it in the test server the bot prefix is `s!`.

**Comment by jb3** [comment]
Is there a reason that a role has been used? Storing in Redis should be just as simple with Redis Cache and helps reduce role pollution on the server.

**Comment by ChrisLovering** [comment]
I think it was to reuse some of the code that we have for the announcements feature.

**Comment by JakeM-Git** [comment]
Yeah, there really isn't any reason we need to do it. I have the redis cache setup already made so if you would rather use that then we can.
