### ISSUE TITLE
Feature: `!recent` command to find help channels you have been active in

### ISSUE THREAD

**Issue by vcokltfre** [python-discord/bot#1575]
This issue proposes a command that lets you find help channels you have recently been active in: `!recent`

The premise of this command is that if you're helping in the help channels, or have claimed help in one, and you wish to find your way back to that channel/channels, you can run this command and it will list the help channels that you have been active in during the past X amount of time (I'm thinking 10 or 15 minutes currently).

My current thoughts on implementation are:
- On message, check if the message is a non-bot user in a help channel
- If so, update a value in redis following the format `help-{user.id}-{channel.id}` to channel.id (1) with an expiry of [10/15 mins]
- Check which of the channels returned are dormant and only display the active help channels (maybe a toggle for this so people can see dormant ones too if they wish)
- DM the user an embed with the channel mentions

(1): The reason it's structured like this is so that non-expires keys can be easily searched with redis' `keys` command matching the pattern `help-1234-*`, the value of the channel is the key's value as well so it can be easily fetched.

**Comment by dawnofmidnight** [comment]
This seems related to #1567

**Comment by vcokltfre** [comment]
its not

**Comment by JakeM-Git** [comment]
> This seems similar to #1567 to me.

We talked about it during the staff meeting they are 2 different Ideas and I believe everyone voted for this correct me if I am wrong @vcokltfre

**Comment by dawnofmidnight** [comment]
Understood, thanks for clearing that up!

**Comment by vcokltfre** [comment]
Update on this: waiting on #1567 since it adds a bunch of stuff in redis that will be used for this too

**Comment by Xithrius** [comment]
> Update on this: waiting on #1567 since it adds a bunch of stuff in redis that will be used for this too

That issue has been closed, and the PR has been merged.
