### ISSUE TITLE
Temporary infractions don't always get lifted

### ISSUE THREAD

**Issue by ChrisLovering** [python-discord/bot#1581]
The issue is probably our new limit to infractions returned from the site API, combined with the heavy mass ban we recently did. We have probably crossed 100 active infractions since those were applied, and as a result, they don't show up to be rescheduled when the scheduler restarts.

Having >100 infractions active at a time is a reasonable figure for us to have right now with our size, even without the mass bans.

It does appear to have an easy temporary fix though, `reschedule_infractions()` should add a filter to the site query to ignore permanent infractions.

A permanent fix would be to remove the pagination cap for this specific request in the site api.

cc @bast0006 @mbaruh

**Comment by Akarys42** [comment]
> A permanent fix would be to remove the pagination cap for this specific request in the site api.

I think we would be better making the site endpoint an actual paginator and walking through it rather than bypassing the paginator for this specific request.

**Comment by bast0006** [comment]
Another idea, which would also reduce load if we have lots of bot restarts, is to change rescheduling from a "on-startup" to an hourly task. Each hour, grab the infractions that would expire by the end of the hour, and schedule them. That way there's a rolling run where we only schedule soon-to-be-expired infractions. This sidesteps the issue of having to filter out permanents and gives us a lot more headroom under the paginator, and even if there are >100 expiring they'll simply "spread out" over the next few hourly checks

**Comment by ChrisLovering** [comment]
I'd be happy with either implementation. Would this be something you'd be interested in working on Bast?

**Comment by bast0006** [comment]
Yes, if it's not too urgent (I don't see it taking a month but maybe a week if something comes up). I'd like to do the second one, as its more kind to bot restarts and the future.

**Comment by ChrisLovering** [comment]
Yup, sounds good to me. 
We have an interim solution, see https://canary.discord.com/channels/267624335836053506/620607373828030464/845230651854290944 so we can afffored to spend a bit more time on this to make it a good solution.

**Comment by bast0006** [comment]
Will do!

**Comment by bast0006** [comment]
Urgh. I need to adjust `site` to let us filter out permanent infractions. I might as well add a date field there, as well. We also have the option of just scheduling the next X infractions rather than the next X time of infractions to schedule/unschedule, which won't require the time filter (but that's getting into bikeshedding and we probably want that filter anyway).

**Comment by bast0006** [comment]
PR's opened: python-discord/site#510 python-discord/bot#1609
