### ISSUE TITLE
Tag: async-await

### ISSUE THREAD

**Issue by vcokltfre** [python-discord/bot#1585]
This issue proposes a new tag that explains some basics about asyncio and concurrency. Essentially the content would be along the lines of:
- What's an event loop?
- How does it work?
- How do I use it?

If approved I'd like to write this myself

**Comment by Objectivitix** [comment]
AMAZING! I WOULD LOVE THAT BECAUSE WE HAVE A LOT OF ASYNC/AWAIT QUESTIONS

**Comment by ChrisLovering** [comment]
Go for it

**Comment by vcokltfre** [comment]
Awesome, thanks!
