### ISSUE TITLE
Modpings schedule feature

### ISSUE THREAD

**Issue by Akarys42** [python-discord/bot#1588]
# Abstract

Moderators should be able to set a schedule for when their moderator ping role gets removed, to avoid waking up to a ton of unread pings.

# Specification

A new command, `!modpings schedule set [start] [stop]` (with the two arguments being UTC time), should store those two dates in a Redis cache and make sure to remove the role when `start` hits and re-add it when `stop` hits using a scheduler.

`!modpings schedule reset` should clear the cache entry and disable it.

# Reasoning

Currently, a few moderators are using `!modpings off` to not wake up to 20-50 unread mod pings and be able to focus on pings that still require their attention. This command would help by not having to remember (and sometimes forget!) to run the command every day.

**Comment by ChrisLovering** [comment]
This was discussed in the admin meeting, we are happy for this feature to be implemented, as long as there is a 16h limit between the start and stop.

This number was to settled on as a good medium to allow for 8 hours sleeping and 8 hours school/work.

**Comment by Shivansh-007** [comment]
Hey, can I work on this?
