### ISSUE TITLE
Cleaning up config-default.yml and constants.py

### ISSUE THREAD

**Issue by Numerlor** [python-discord/bot#1595]
The default config is rather long (over 500 lines currently) which can be dauting for new users as it's not clear which values have to be set for the bot to run. I'm not sure how smartconfig would affect this but it looks like it's still a bit before it can be used within the bots for configuration.

As the first thign all the unused values from both the default config and constants should be removed, for example `Channels.reddit` or `Free`.

The formatting of the file is a bit all over the place with the alignments of the values so that should be redone to an agreed upon style and followed in the future. The groups should also be rearranged so the file is easier to navigate and the values that need to be configured are clearer.

I think some values could also be moved to python constants instead of being configurable values, for example `mail_lists` from `python_news` or the `branding` `cycle_frequency` as changing them would probably involve a look in the bot's code anyway and they aren't changed often or required to be changed for the feature to run properly locally in the long term. 
But there aren't many values like this which don't already have a key to be under so it wouldn't reduce the complexity of the file too much, and figuring out which ones, if any, would be worth moving around may need some discussion.

**Comment by Xithrius** [comment]
@HassanAbouelela I believe you were planning to clean up the config at some point?

If so, discussion should continue here.

**Comment by HassanAbouelela** [comment]
Hey, I believe you're referencing the reorganization I did. That already happened sometime in January.

That said, a good look at what can be changed is not a bad idea. The file is indeed very terrifying as is.

**Comment by Xithrius** [comment]
I see. Thank you for the confirmation.

**Comment by shtlrs** [comment]
The YAML config file has been deleted in favor of using Pydantic settings. Some unused variables have been deleted as well. 

We also botstrap the config for users automatically now so it's not really daunting anymore. 

That said, I think this issue is resolved so I'll be closing it
