### ISSUE TITLE
Delete Discord Server List Server Links

### ISSUE THREAD

**Issue by Kronifer** [python-discord/bot#1597]
We currently have a ban on advertisement, but I've noticed a few people getting around this by listing their server on disboard and then sending that link instead. I propose we do something similar to how we block discord invites to block these links. (Honestly this might be overkill, but I'm pretty sure advertisement isn't allowed). If given the option, I'd be fine with implementing this.

**Comment by Xithrius** [comment]
I've added `https://disboard.org/` to our blacklist filter, so moderators will be pinged if it is posted.

I don't think it's necessary to hardcode this, as it doesn't happen too often.

Thank you for the suggestion!
