### ISSUE TITLE
Tag: dunder methods

### ISSUE THREAD

**Issue by Objectivitix** [python-discord/bot#1598]
## Description
This would be a tag explaining why dunder methods are special, why we would sometimes override them, and give some examples using `__init__` (constructor), `__str__` (string representation), and `__repr__` (dev-friendly representation).

**Comment by Objectivitix** [comment]
thank you for da like :D

**Comment by Xithrius** [comment]
@Objectivitix If you'd like to, please implement this feature.

**Comment by Objectivitix** [comment]
@Xithrius Thanks! I'll get started on it tomorrow :D
