### ISSUE TITLE
Code Jam Channels Automatic Creation

### ISSUE THREAD

**Issue by janine9vn** [python-discord/bot#1601]
Code Jam preparation is in full swing. To reduce the burden on our organizing team, I'd like a command that will automate almost all of the team channels and role creation. Please ping me here or in server if there are any questions about this implementation. This is fairly high priority as I would like it working by June 14th.

# The Proposal
A single command `!codejam create <csvfile or link to a csv file>` that will create the channels and roles needed for the code jam.
The csv will be structured like so:
| Team Name | Team Member Discord ID | Team Leader |
| ------------ | -------------------------- | ------------- |
|Annoyed Alligators| 165023948638126080 | Y |
|Annoyed Alligators| 306870406697189378 | N |
|Oscillating Otters| 95872159741644800 | Y |
|Oscillating Otters| 172395097705414656 | N |
|Oscillating Otters| 212644551926611969 | N |

Given this csv file the following actions should be completed:
- A code jam category called `Code Jam` should be created. All the below channels will be in this category.
- Team roles for each provided team name should be created
- People associated with the team name should be assigned the correct team role
- Team text channels should be created with overrides for viewing + sending messages for the associated team role
- A single `Code Jam Team Leader` role should be created
- A single `Team Leader Chat` should be created with a role override for viewing + sending messages for the team leader role
- People who are designated as team leaders should have the team leader role applied
- Code Jam Events Team role and Moderation Team role should have viewing + sending messages for all the newly created channels

# Other Considerations
- It would be nice if it could ping the Events Lead role with a status update as this command is running and hits certain milestones
- No voice channels will be created
- You can assume the csv file we pass in is correct. If someone is assigned to two teams or there are two team leaders that's not something this code should worry about.

**Comment by janine9vn** [comment]
cc: @ChrisLovering please assist where you can in terms of implementation details and the like~

**Comment by ChrisLovering** [comment]
Should this command be limited to mods, admins (or just you)?
