### ISSUE TITLE
Small Event Management System

### ISSUE THREAD

**Issue by janine9vn** [python-discord/bot#1603]
# Context
As our server grows we're looking to have more ways for people to engage on the server besides the help channels. One of the ways we do this is with more events. Not all events need to be as large as the code jams though. Some just need a quick announcement, a way for people to subscribe to said announcement, and then a ping when the mini-event starts. I'm hoping to have a system with Python that helps with this. 

# The Proposal
We previously had a PR to introduce a User Events Management system. This is 80% of what I'm envisioning this system to look like, just modified to be staff-only invoked, able to be invoked in specific channels, and some other minor changes. The User Events PR is #1269. 

What I would like this system to do is:
- Someone can schedule an event in a specific channel with a command `!event schedule <name> <date> <details>` or similar.
- The bot will then create an announcement in that channel from the information provided via embed
- The time of the event can hopefully be shown in people's local date & time
- People can react to the bot message to get notified when the event is starting
- The bot will pin upcoming events in the channel the command is invoked in and un-pin once the event starts.
- We should be able to delete and reschedule events somehow

I'm open to the details of how to set-up the event changing for ease of use.

**Comment by doublevcodes** [comment]
This probably won't be a priority but it would be cool to have any events scheduled show up on this website (as I currently understand it the whole events section is being redone).

**Comment by janine9vn** [comment]
With Discord supporting scheduling events natively, I'm going to close this issue. For our bigger events, we'll still post them on our website. But the smaller ad-hoc ones can be run entirely on Discord with the native functionality now. If you're reading this and interested in running a smaller ad-hoc event, talk to Kat in the server.
