### ISSUE TITLE
Command to move users to different voice chats

### ISSUE THREAD

**Issue by JakeM0001** [python-discord/bot#1605]
We talked about this in voice chat(requested by Hemlock) to make a command to move users to different voice chats.

The command would probably be something along the lines of `move`  `user` `channel`

**Comment by jb3** [comment]
Doesn't Discord move functionality cover this? Who is this for?

**Comment by JakeM0001** [comment]
I was just told to make an issue about it lol so I am not to sure

**Comment by jb3** [comment]
Hahahaha, cc @MrHemlock

**Comment by MrHemlock** [comment]
@jb3 Okay so, there's a good reason for this.  When you have a channel that's around 20 odd people, and you're trying to drag someone down to one of the code help channels, you have to deal with the awful drag and scroll issue.  I feel it's at least worth talking about.

**Comment by ChrisLovering** [comment]
You can right-click and move to, which avoids that issue at least.

**Comment by MrHemlock** [comment]
I.... legit didn't know that.

**Comment by JakeM0001** [comment]
Lol, I am gonna close this now.
