### ISSUE TITLE
Allow helpers to update nomination reasons

### ISSUE THREAD

**Issue by gustavwilliam** [python-discord/bot#1617]
Sometimes, you want to add information to a nomination, possibly after getting to know the nominee better. This is currently not possible for helpers.

When a solution involving allowing staff to nominate the same member multiple times was proposed in `#nominations`, @wookie184 pointed out that the `!tp edit` command can be used to edit nomination reasons, but that it is currently restricted to moderators and admins. I propose that helpers should be allowed to use the command to update their own nominations as well.

It might also be worth considering allowing helpers to delete their own nominations (if this is not already possible), if they change their minds on a candidate.

**Comment by JakeM0001** [comment]
Definitely agree, helpers are already allowed to add people to the talent pool so why not edit. If we really wanted to we could only allow helpers to edit their own nominees. But that's just an idea.
