### ISSUE TITLE
Unittest Parallelization & Pytest

### ISSUE THREAD

**Issue by HassanAbouelela** [python-discord/bot#1622]
## Description
Over time, this project's test suite has grown to be very large, and so too has its operation time. On my machine, the test suite currently takes about 80s to complete. You can see a full breakdown [here](https://hassanamr.dev/pydis/tests.html).

This issue proposes parallelization to help shorten the run time of tests.

## Approaches
Naturally, there are many ways to go about doing this, each with varying degrees of difficulty.

**Approach 1:** [`unittest-parallel`](https://pypi.org/project/unittest-parallel/)
unittest-parallel is a pypi plugin for unittest. It theoretically should be the least effort required to get parallelization working, yet, I could not get it to work after a lot of testing. Random tests were failing, I could not get it to work at all.

Other complaints include:
- Can't kill the test runner. No combination of `ctrl+combo` would stop the tests after they started.
- It was not faster than plain unittests from the looks of it. I obviously couldn't get the entire test suite to run, but the part that did took much longer than plain unittests.
- There were other various formatting complaints, but they'll take a lot of space, and they're completely moot if the points above are not addressed.

**Approach 2:** [`pytest-xdist`](https://pypi.org/project/pytest-xdist/)
Alright, hold your horses. Don't start typing out how terrible this idea is yet. Yes, this idea relies on pytest, but we'll get to that later. The possibility of adding pytest is a large part of this issue. Now, back to xdist:

It's a pytest plugin that parallelizes your code. I don't really have anything else to say about that. It worked really well out of the box, and I didn't run into any problems. Here are some numbers:

|                              | Unittests | Pytest | xdist |
| ------------------- | ---------- | ------ | ----- |
| **No Coverage** | 60s           | 71s     | 45s  |
| **Coverage**       | 79s           | 130s   | 75s  |
| **CI Coverage**   | 91s           | ~       | 52s   |

## Pytest
This is the next large part of this issue. Using pytest has a few benefits, which we can get into in a second. There are two approaches however: using pytest as a runner, and using it as a framework.

**Using as a runner:**
We could use pytest exclusively to run the tests. That would give us access to pytest plugins, without requiring we use pytest. It's the least work since pytest has native support for unittest suites, and the only changes needed are installing the dependencies.

**Using as a framework:**
Alternatively, we could use pytest in full. That will give us access to all the things mentioned above, as well as other pytest features, such as fixtures. This could be a much larger job depending on how it's approached. There is no requirement to immediately refractor all old tests into pytest format, we could have a mix of both. We could stop accepting any more non-pytest test suites, and slowly update old suites as they are worked on. Not the most ideal solution because it would require maintaining two test suites, but it's an idea.

**Comment by MarkKoz** [comment]
I'm fine with using it as just a runner.

As for using pytest fully, I'll paste what I wrote before in Discord:

> We have developed a bunch of utilities that are tightly coupled to unittest, so we would have to maintain pytest equivalents where necessary unless we rewrite all existing tests. Maybe they would still work with pytest, not sure.
>
> I think it'd be awkward to have tests written in two different libraries. Also my point about maintaining utilities (mostly mocking stuff) for two different libraries. Not sure how much of the mocking stuff would work fine across libraries.
>
> If someone wanted to undertake the enormous effort to port everything to pytest, then I'd be more inclined to switch.
>
> I don't mind unittest too much, but in hindsight maybe we should have just stuck to pytest from the start.
>
> I don't feel a strong need to switch.

**Comment by Akarys42** [comment]
Agreed with Mark, while pytest would have been perhaps nicer at first switching now sounds pointless, having parallel tests would be quite handy.

How does the output looks with `pytest-xdist`? If if doesn't look like an hot mess because of parallelization, it should be good to go in my opinion.

**Comment by HassanAbouelela** [comment]
@Akarys42 I included that in my original discord writeup, but omitted it here for brevity. In short, it really doesn't matter because the current output isn't all that great tbh. The only thing that truly sucked was `unittest-parallel`, but I won't be including it in this report. (You should really be looking to integrate some sort of proper test result display tool into your dev workflow regardless of the test runner)

Current unittest output is `.` to represent success, some other character to represent failure. The long block are warnings which are spat out mid-text:
> ................................................................................................................................................................c:\python\python39\lib\unittest\mock.py:491: RuntimeWarning: coroutine 'Infractions.apply_voice_ban.<local
s>.action' was never awaited
Coroutine created at (most recent call last)
  File "c:\python\python39\lib\unittest\async_case.py", line 88, in _callMaybeAsync
    return self._asyncioTestLoop.run_until_complete(fut)
  File "c:\python\python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "c:\python\python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "c:\python\python39\lib\asyncio\base_events.py", line 1882, in _run_once
    handle._run()
  File "c:\python\python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\python\python39\lib\unittest\async_case.py", line 102, in _asyncioLoopRunner
    ret = await awaitable
  File "c:\python\python39\lib\unittest\mock.py", line 1354, in patched
    return await func(*newargs, **newkeywargs)
  File "C:\GitHub\PyDis\bot\tests\bot\exts\moderation\infraction\test_infractions.py", line 134, in test_voice_ban_mod_log_ignore
    self.assertIsNone(await self.cog.apply_voice_ban(self.ctx, self.user, "foobar"))
  File "C:\GitHub\PyDis\bot\bot\decorators.py", line 217, in wrapper
    await func(*args, **kwargs)
  File "C:\GitHub\PyDis\bot\bot\exts\moderation\infraction\infractions.py", line 401, in apply_voice_ban
    await self.apply_infraction(ctx, infraction, user, action())
  for attr in dir(spec):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
............................................................................................................c:\users\hassa\appdata\local\pypoetry\cache\virtualenvs\bot-n7qlku8b-py3.9\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python Sequen
ceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')  ......................................................................................................................................................
>
> ----------------------------------------------------------------------
> Ran 418 tests in 108.922s
>
> OK


Plain pytest is a little better, doing something along the lines of:
> ============= test session starts =============
platform win32 -- Python 3.9.4, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: C:\GitHub\PyDis\bot
plugins: forked-1.3.0
collected 418 items
>
> tests\test_base.py ......................                                                                                                                                  [  2%]
tests\test_helpers.py ............................                                                                                                                            [  8%]
....
>
> ====== 418 passed, 3 warnings in 70.84s (0:01:10) ======


And finally xdist, which by default does something similar to:
> ============= test session starts =============
platform win32 -- Python 3.9.4, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: C:\GitHub\PyDis\bot
plugins: forked-1.3.0, xdist-2.2.1
gw0 [418] / gw1 [418]
.................................................................................................................................................................................................................................................................. [ 61%]
................................................................................................................................................................                                                                                                   [100%]
>
> ====== 418 passed, 5 warnings in 48.10s ======

Adding the `-v` flag to get more fine-grained reporting back would spit out:
> ============= test session starts =============
platform win32 -- Python 3.9.4, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: C:\GitHub\PyDis\bot
plugins: forked-1.3.0, xdist-2.2.1
gw0 [418] / gw1 [418]
>
> ...
[gw1] [ 99%] PASSED tests/bot/utils/test_time.py::TimeTests::test_until_expiration_with_duration_custom_units
tests/bot/utils/test_time.py::TimeTests::test_until_expiration_with_duration_none_expiry
[gw1] [ 99%] PASSED tests/bot/utils/test_time.py::TimeTests::test_until_expiration_with_duration_none_expiry
[gw0] [ 99%] PASSED tests/bot/utils/test_services.py::PasteTests::test_url_and_sent_contents
tests/bot/utils/test_time.py::TimeTests::test_format_infraction
[gw0] [100%] PASSED tests/bot/utils/test_time.py::TimeTests::test_format_infraction
>
> ====== 418 passed, 5 warnings in 48.73s ======

This has become a gigantic message with a bunch of meaningless copy-paste (see my point above about display tools). There are endless output config options for both unittests and pytest.

**Comment by HassanAbouelela** [comment]
For the purposes of not anihlating this discussion thread, I've hidden my reply to Akarys' comment, but it's still there.

**Comment by Akarys42** [comment]
The output seems decent enough, it is better than our current one for sure
