### ISSUE TITLE
Do not delete !docs/!pypi invocation if it contains a ping

### ISSUE THREAD

**Issue by Akarys42** [python-discord/bot#1624]
# Current behavior
If a `!docs` invocation cannot find the appropriate symbol, the invocation and the bot answer is deleted after a few second, even if the message was a ping reply or contained a ping, which lead to a ghost ping.

# Suggested behavior
The bot answer is or is not deleted (maybe we can just have a :x: reaction instead?) but the message stays to avoid getting a ghost ping (only if it contained a ping).

**Comment by TizzySaurus** [comment]
The `!pypi` command has the same issue so will work on that too and link to this issue. Will also edit title to reflect this.
