### ISSUE TITLE
Update docs for clarity that two projects are required to run the bot locally. Site and bot 

### ISSUE THREAD

**Issue by swordysrepo** [python-discord/bot#1631]
While setting up locally I  didn’t see there are two projects that need to be cloned and initialized for the bot to initialize. Initially I thought it was one project (the bot) that would also include the site.. and the site would require additional parameters added to the .env file .  i understood that after adding those environment variables to the .env the bot would also initialize the site with it .  

can suggest adding a link to the correct repository to this page [site repo page](https://pythondiscord.com/pages/guides/pydis-guides/contributing/site/) on the site contributing guide . and adding the respective repo page to the bot contributing guide . (for clarity that two are required and they are not the same)
Haven’t been familiar with the repositories to know there were two separate project repositories to clone and execute . 

this is the full log of the information given while initializing the bot without the site repo initialized . I see that it's not clear in the log that site connection has failed for the bot. 
https://paste.pythondiscord.com/ofopiwoten.sql

Suggesting an addition in the logger that says “are you sure you have initialized the site project? If you haven’t , check here [the documentation page saying that you need the second project] and clone and initialize the project from here [the GitHub clone link]” . Scaleios and I were on this for a while.. and I misunderstood for a good 10+ minutes that I needed to run the (additional) site project first , and that’s why the browser wasn’t loading  :smile:

initial confusion
https://discord.com/channels/267624335836053506/303906556754395136/851600431465627688

I would make the changes to both the bot repo and the site repo and then pr on each

**Comment by Kronifer** [comment]
If you review the more in-depth contributing guide on the website, this is listed and can be avoided by using Docker.

**Comment by swordysrepo** [comment]
> 
> 
> If you review the more in-depth contributing guide on the website, this is listed and can be avoided by using Docker.

please provide a reference to where it shows the repository links in the contributing guide for the bot and the site. 
When i used these guides i was between the pages for 4 hours , and i am sure there are not repository links directly on the contributing guide pages. 

As i said, this is where i see the confusion stems from .



these are the pages 
https://pythondiscord.com/pages/guides/pydis-guides/contributing/bot/
https://pythondiscord.com/pages/guides/pydis-guides/contributing/site/

i see it says "fork the project" and then directs the user to this page
https://pythondiscord.com/pages/guides/pydis-guides/contributing/forking-repository/

for an example of how to fork a project . But it doesn't clarify which project is being forked on either the bot contributing page or the site contributing page . And otherwise the pages look nearly exactly the same , i see it's been templated' for efficiency . Simply including which repository is being forked and creating more distinct differences between the pages makes it more clear that it's two different repos.  The change i propose doesn't do that in full , It just provides a direct link to the github repository of the currently guided project installation .

**Comment by Shivansh-007** [comment]
> please provide a reference to where it shows the repository links in the contributing guide for the bot and the site.

![image](https://user-images.githubusercontent.com/69356296/121978206-50925f80-cda5-11eb-8651-7d5ff292c7f6.png)

**Comment by swordysrepo** [comment]
> > please provide a reference to where it shows the repository links in the contributing guide for the bot and the site.
> 
> ![image](https://user-images.githubusercontent.com/69356296/121978206-50925f80-cda5-11eb-8651-7d5ff292c7f6.png)
i almost thought i missed this . 
but 
this hyperlink brings you to this page https://pythondiscord.com/pages/guides/pydis-guides/contributing/site/ 
that page doesn't have a link to the github repo, showing that it's two seperate projects. 


can go back to see the conversation .. the main confusion is that they're two seperate projects/repos. 

https://discord.com/channels/267624335836053506/303906556754395136/851600431465627688

i used both pages during install and i see it's still confusing to those that "Haven’t been familiar with the repositories to know there were two separate project repositories to clone and execute ."

**Comment by swordysrepo** [comment]
I saw the site was tied into the Bot repo and having the site "enabled" required additional steps that are listed on https://pythondiscord.com/pages/guides/pydis-guides/contributing/site/

**Comment by wookie184** [comment]
The bot guide now mentions that site is required if the user isn't using docker https://www.pythondiscord.com/pages/guides/pydis-guides/contributing/bot/#with-more-things-running-locally

I can't identify anything else that needs to be done here so i'll close this. In general we do recommend using docker as it's much simpler though, so our documentation of how to set up bot on host isn't as good.
