### ISSUE TITLE
Allow `!poll` functionality for Partners

### ISSUE THREAD

**Issue by janine9vn** [python-discord/bot#1632]
Since we now have Partners more integrated into our server and our spaces, I'd like to provide them access to some of the more useful bot functionality such as `!poll`. The main driver of this is to allow the `black` maintainers the ability to run quick polls in their dev channel.

This should be a fairly simple change since it's adding another role to the decorator.

**Comment by ChrisLovering** [comment]
Yup! we already have the `python_community` role in the constants file `bot.constants.Roles.python_community`. it would be a case of adding that to the `has_any_role()` call in the poll command.

If anyone wants to pick this up, post here and we can get you assigned!

**Comment by ToxicKidz** [comment]
Isn't this issue for the `partners` role, not the `python_community` role? Regardless, `Roles.partners` exists as well.

**Comment by HassanAbouelela** [comment]
It's probably a good idea to enable it for both.

**Comment by Xithrius** [comment]
I shall yoink this one.
