### ISSUE TITLE
 !paste command - token detection and notification 

### ISSUE THREAD

**Issue by swordysrepo** [python-discord/bot#1645]
thought it'd be cool to have token detection added to the !paste command . So if someone pastes a token , and clicks save .. before it is saved it reads the whole text looking for the word "token" ... and then checks with the user before confirming save .

**Comment by dawnofmidnight** [comment]
The service we use for https://paste.pydis.com isn't one PyDis made themselves. It's simply a hosted version of [Hastebin](https://hastebin.com/), so implementing this could be rather expensive to do.

**Comment by swordysrepo** [comment]
continued conversation here .. 
https://discord.com/channels/267624335836053506/635950537262759947/854993990914670592
 
heard there will be a new issue created for "adding workers to add token filters" 
 
 will post the issue link here and close this issue

**Comment by jb3** [comment]
Yeah, we'll open an issue over on [python-discord/workers](https://github.com/python-discord/workers) :smile:

**Comment by Akarys42** [comment]
See https://github.com/python-discord/workers/issues/9
