### ISSUE TITLE
Make mutes override auto-mutes

### ISSUE THREAD

**Issue by mbaruh** [python-discord/bot#1665]
Various behaviors might cause the bot to mute a user.

When a moderator deals a mute, it should disable a pre-existing bot mute.

**Comment by MarkKoz** [comment]
There are several approaches I can think of. Which one should be chosen?

1. Go through the normal unmute process, then apply a new mute as a separate infraction.
2. Unmute without sending them a DM for being unmuted, then apply a new mute as a separate infraction.
3. Edit the existing mute infraction (and maybe send a new DM).

I am leaning towards option 2.
