### ISSUE TITLE
Adding a "leads" role to the server information embed.

### ISSUE THREAD

**Issue by Xithrius** [python-discord/bot#1667]
Currently when the `!server` command is used, we get an embed like the one below. Since a stage channel has been added recently, the roles/channels listing is now uneven.

I suggest that we combine the project leads and domain leads role into a singular role called "leads", then place it somewhere within the left listing of roles.

![image](https://user-images.githubusercontent.com/15021300/124256424-213b5c80-dae0-11eb-8cab-1549c34ca6b3.png)

**Comment by ChrisLovering** [comment]
This is the part of the code based this role list is currently generated, as a hint for whoever picks this up https://github.com/python-discord/bot/blob/6b6a291625ce01517df29dc0d0f6170cbe8f3044/bot/exts/info/information.py#L44-L53

**Comment by D0rs4n** [comment]
Hey! I'd like to grab this issue! :)

**Comment by Akarys42** [comment]
Go for it! If you have any question, feel free to ask in `#dev-contrib`!
