### ISSUE TITLE
Restrict internal eval command to bot owner when in debug mode

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#1683]
It's a security risk to let anyone in a test server have essentially full access to the host machine. Thoughts on this? Does it need to be configurable or should it always be on when in debug mode?

**Comment by Akarys42** [comment]
I think it is a good idea. Some people are using test bots in larger servers where not everyone could be trusted. Also, it is possible to accidentally expose your bot.

I would say it should be easy to disable, maybe even from inside the internal eval itself (ie. run the int e `bot.get_cog("Internal").allow_everyone_eval = True`)? But either way, it should be disabled for non-owners by default and if it is disabled I feel like it should be reset back on restart and have a big red message on the terminal.
