### ISSUE TITLE
Enable charinfo command in discord_py channel.

### ISSUE THREAD

**Issue by NIRDERIi** [python-discord/bot#1684]
In order to add a reaction in discordpy, we need the emoji's unicode. For most emotes/emojis we can do \:emoji: , but for some of them (such as numbers and letters) this option is not possible. The best replacement for it is the charinfo command, which currently isn't allowed in discord.py, but I feel should be for the above reason.

**Comment by Akarys42** [comment]
Sounds good to me, do you want to PR it @NIRDERIi ?
