### ISSUE TITLE
Python class code error

### ISSUE THREAD

**Issue by sweetpundir** [python-discord/bot#1699]
class School:
    def __init__(self,rooms,floor,staff,students):
        self.rooms=rooms
        self.floor=floor
        self.staff=staff
        self.students=students
    def myfunc(self):
        print("This school having"+self.rooms)
s1=School(4,15,85,2500)
s1.myfunc()

**Error**
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-536442d24c20> in <module>
----> 1 s1.myfunc()

AttributeError: 'School' object has no attribute 'myfunc'

**Comment by HassanAbouelela** [comment]
Hey! Seems this is just a general python question, not related to the actual repository.

We do answer python questions, just not here. Check out our [discord server](https://discord.gg/python) to get help.
