### ISSUE TITLE
Tag: `!venv` explaining virtual environments

### ISSUE THREAD

**Issue by Zedeldi** [python-discord/bot#1701]
### Description

Add a `!venv` tag to explain the purpose, creation and activation of virtual environments.

It should outline the following:
- Purpose: keeps system clean, dependency management, etc.
- Creation: `python -m venv .venv`
- Activation for both PowerShell and Bash

### Notes

On Windows systems, the [execution policy](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies) needs to be set before activating from PowerShell:
```powershell
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
```

### Resources

- [Python docs](https://docs.python.org/3/library/venv.html)

**Comment by NIRDERIi** [comment]
I have to say, I have no idea what is venv or what it's used for. I think you should write some explanation that you think is good to be a tag about it, and let users review and suggest more things. Waiting to see the tag soon!

**Comment by HassanAbouelela** [comment]
You can submit a draft if you’d like, but I’m not sure a tag is the right medium for this. With the execution policy extension, the content would probably be longer than what’s ideal for a tag, and may be better suited to site content.
