### ISSUE TITLE
Send message when help channel closed.

### ISSUE THREAD

**Issue by NIRDERIi** [python-discord/bot#1717]
Whether you are the help-channel owner(the one who claimed the channel) or the helper, if the helpdm is on(for the helper), than dm when the channel is closed for any reason to detect wether the channel is closed or not

**Comment by JacobMonck** [comment]
@NIRDERIi So just to be clear if you have help dms on or you are the channel claimant you should receive and dm when the channel is closed?

**Comment by NIRDERIi** [comment]
Yes, keeping track of channels you helped with, can be really helpful if you don't know where the channel went. If you were helping, maybe a message will be sent: `#channel-mention is not closed, Thank you for helping` and for the channel claimant it'll be `Your help channel was closed due to inactivity` or something like that

**Comment by MarkKoz** [comment]
Why would anyone but the channel's claimant care about the channel being closed? If anything, I think this DM should only be sent to claimants.

**Comment by NIRDERIi** [comment]
I know that when I help, I go back and see if the other user still needs help, and if the user closed the channel, I will kinda have to search for the channel. I think it's a nice feature, and again, if you didn't really care, you can just turn DM help off in a simple command

**Comment by MarkKoz** [comment]
> I know that when I help, I go back and see if the other user still needs help, and if the user closed the channel, I will kinda have to search for the channel.

But won't they receive a notification for the new message? Receive a DM for a new message = this person still needs help. Don't receive a DM = they probably don't need any more help.

> if you didn't really care, you can just turn DM help off in a simple command

What if the helper cares about the current notifications but not about a channel closed notification?

**Comment by NIRDERIi** [comment]
Wdym for the new message? And what current notifications? Isn't help dms only for when you write the first message to help in a channel?

**Comment by MarkKoz** [comment]
> 
> 
> Wdym for the new message? And what current notifications? Isn't help dms only for when you write the first message to help in a channel?

You're right. I misread the code.

Still, I don't see this as particularly useful for helpers but then again I never though the helpdm command was that useful to begin with. I think you should shove aside by opinion and instead gather thoughts from people who actually use that feature.

**Comment by NIRDERIi** [comment]
A) Not related, but how do you respond to a specific line?
B) The same thing could be said about if we did the channel closed instead of the initial message, which is why both seem to be same importance level because they both keep you tracking the help channels. Personally, the channel closed is a much important feature, because you know when you type a message in a certain channel.

**Comment by MarkKoz** [comment]
> A) Not related, but how do you respond to a specific line?

Copy and paste that line, then prepend a `> ` to it.

**Comment by NIRDERIi** [comment]
And for example, while commenting here, I helped three people with their problems. Took me a little while to find out where the channel is, because I first tried to look in open channels, and only then go to the dm and see the channel.

**Comment by NIRDERIi** [comment]
Copy and paste that line, then prepend a > to it.>
Thanks

**Comment by NIRDERIi** [comment]
Does anyone want to say their opinion about it?

**Comment by Bluenix2** [comment]
Sending a new message when a channel is closed has no use, but if we could keep the DM message in cache and then edit when a channel is closed that would be the best.

Sending a new message will trigger a notification, which would get the person helping's attention, just to tell them that their help is no longer needed.

Editing the message will allow someone to look back over all channels they've helped in, and quickly get a nice status of who still needs help.

**Comment by NIRDERIi** [comment]
But the entire purpose of this is that when a channel is closed you'd get notified about it, not a message edit, because than you can easily know when a channel was closed. Tho your idea can also be great

**Comment by Bluenix2** [comment]
Why would you want to be notified when a channel was closed? There is nothing needing your attention, and nothing more you can do.

Editing the message would be the best for the scenario you explained here:
> I know that when I help, I go back and see if the other user still needs help, and if the user closed the channel, I will kinda have to search for the channel.

**Comment by NIRDERIi** [comment]
Oh ok then ig, nice idea!

**Comment by wookie184** [comment]
I don't think this is still relevant now we use a forum channel, since there are lots of indicators that a thread is closed (lock in name, closed in discord UI, and message in the thread), and it's easier to navigate in general.
