### ISSUE TITLE
New tag suggestion

### ISSUE THREAD

**Issue by Diabolical5777** [python-discord/bot#1728]
**Tag Name- VPS**
The tag covers what is a VPS and some examples of good ones
**Tag content:**
If you need to run your bot 24/7 (with no downtime), you should consider one a cheap VPS.
The following is a list of recommended services that many people on the server have used.
They are reliable and good value for money. Their specs should be sufficient for running Discord bots.

https://www.scaleway.com/
   - Cheap VPS
   - Based in Europe.

https://www.digitalocean.com/
   - Cheap VPS
   - US-based.
   - Considered by many to be the gold standard.
   - Locations available across the world.

https://www.ovh.co.uk/
   - Cheap VPS, used by many people.
   - France and Canadian locations available.

https://www.time4vps.eu/
   - Cheap VPS.
   - Seemingly based in Lithuania.

https://www.linode.com/
   - Cheap VPS.

https://www.vultr.com/
   - Cheap VPS.
   - US-based, DigitalOcean-like.

https://galaxygate.net/
   - Cheap VPS.
   - A reliable, affordable, and trusted host.

If you would rather not pay for a hosting service, consider one of the following options:
Self-hosting:
Any modern hardware should be sufficient for running a bot, as long as you're not working under ridiculous conditions like less than 1GB of RAM.
An old computer you have could be suitable and a Raspberry Pi (any model, except perhaps one of the particularly less powerful ones) can also run a bot.

Free hosting:
There is no good or reliable free method for VPS hosting
It is highly suggested not to use services like Heroku or repl.it. There are a number of problems with them which make them highly unreliable.

**Comment by swfarnsworth** [comment]
I believe we have a pin to this effect in the discord-bots channel.

**Comment by Diabolical5777** [comment]
I see, yeah there is indeed one, though, well, this is more informative in my opinion.

**Comment by swfarnsworth** [comment]
I've pinned a variation of this in the discord-bots channel. Thank you for the suggestion!
