### ISSUE TITLE
Monkeypatch discord.py to understand Annotated typehints

### ISSUE THREAD

**Issue by Numerlor** [python-discord/bot#1730]
The project currently enforces typehinting, but discord.py uses annotations for its own purposes which makes some annotations on command callbacks invalid typehints.

@MarkKoz proposed in #dev-contrib that converters could inherit from the type they return to alleviate this issue, but this is more limited than normal typehinting (although still better than the current hints which are just wrong and cause warnings during development).

The `typing.Annotated` type allows us to attach metadata do a typehint, where for converters we'd use `typing.Annotated[type_hint, Converter]` where a static checker would understand the argument to be of type `type_hint`. 
This makes typing commands with converters easy to do properly for all tools, but discord.py currently can't handle the Annotated type.
Locally I patched discord.py with https://paste.fuelrats.com/evoyazixaq.py which seemed to work fine from testing with a custom converter and a forward ref

**Comment by MarkKoz** [comment]
Very cool; I like this approach. I'm fine with patching discord.py since the precedent has already been set (implementing root aliases). This patch isn't that bad anyway because it's not really dealing with any internal/private APIs. That being said, we would have to ensure the setter is in sync for all the special cases (like the greedy converter).

How do you think we should name the `typing.Annotated` aliases and the converters? I'm thinking that call converters should be named like `DateConverter` and the alias can be `Date = typing.Annotated[datetime.date, DateConverter]`. I suppose it might still be useful to keep the converter classes public and accessible, though I cannot think of anything off the top of my head that uses them manually.

**Comment by Numerlor** [comment]
> That being said, we would have to ensure the setter is in sync for all the special cases (like the greedy converter).

I don't anticipate any more cases like that as we're really just modifying what's in the loaded params, with the greedy being some kind of an early fail according to a comment in the source. When I looked at the current master branch it looked like it was still the only piece that immediately acts on the changed annotation. But if something does pop up it shouldn't be hard to address

> How do you think we should name the `typing.Annotated` aliases and the converters? I'm thinking that call converters should be named like `DateConverter` and the alias can be `Date = typing.Annotated[datetime.date, DateConverter]`.

That sounds good, most converters are named similarly already so we can replace those with the Annotated type and add the converter suffix to the class. However I think some converters like `UserMentionOrID` could use a rename so the return type is more obvious from the name (e.g.`UserFromMentionOrID`)

> I suppose it might still be useful to keep the converter classes public and accessible, though I cannot think of anything off the top of my head that uses them manually.

I noticed a few filter lists converters being used directly when quickly going through some of them, although the functionality those offer may be a good candidate to be taken out of the converter

**Comment by MarkKoz** [comment]
Do you want to go ahead with a PR or wait for some more voices?

**Comment by decorator-factory** [comment]
Is there any way to enforce the annotated type to be correct, such as preventing `Annotated[int, DateConverter]`? Not sure if that's necessary, but would be nice.

**Comment by decorator-factory** [comment]
I found this hack: https://gist.github.com/decorator-factory/718a6b6bf514c496baf385f0c0cfcdaa
It doesn't require monkey patching discord.py, and it makes sure the converter class actually produces the desired type.

But unfortunately, it only works on pyright. If anyone could make it work with mypy, that would be great

**Comment by Numerlor** [comment]
> Do you want to go ahead with a PR or wait for some more voices?

I'll start working on it tomorrow. 
What module would be the most fitting place to define and apply the patch in? The bot module's init?

**Comment by MarkKoz** [comment]
Yeah, that's where the other patch is., though some are not fans of having significant amounts of code in init. You could consider creating a patch module and defining functions like "apply_x_patch" that get called from init. We used to have a similar system to patch a bug in d.py, but it was all removed once it got fixed upstream. You could also try to find that for inspiration. I don't have a concrete idea of the best approach.

**Comment by Numerlor** [comment]
When going through the code I realized we should be able to redefine the types under a `typing.TYPE_CHECKING` guard, which ought to work for everything apart from `allowed_strings`

**Comment by MarkKoz** [comment]
Oh, that's much simpler.
