### ISSUE TITLE
Dynamically insert help categories into DORMANT_MSG

### ISSUE THREAD

**Issue by TizzySaurus** [python-discord/bot#1736]
As [suggested by Lemon](https://discord.com/channels/267624335836053506/429409067623251969/874919321283993631) in #community-meta, this will insert the correct category names into the DORMANT_MSG that's sent when a channel is moved to the dormant category.

**Comment by NIRDERIi** [comment]
By the solution you showed in #dev-contrib, it seems ok to me!
