### ISSUE TITLE
Reply to the original message where the reminder was invoked instead of using a jump url

### ISSUE THREAD

**Issue by D0rs4n** [python-discord/bot#1741]
I believe, replying to the original message where the reminder was invoked is more consistent than using a jump url.
For that we would have to modify `jump_url` to be `message_id` instead
```python
        reminder = await self.bot.api_client.post(
            'bot/reminders',
            json={
                'author': ctx.author.id,
                'channel_id': ctx.message.channel.id,
                'jump_url': ctx.message.jump_url,
                'content': content,
                'expiration': expiration.isoformat(),
                'mentions': mention_ids,
            }
        )
```
Although, that would involve a small modification on the site. So that should be discussed more in depth.

**Comment by D0rs4n** [comment]
Indeed. however... it should be
```python
partial_message = channel.get_partial_message(message_id)
```
(As get_partial_message is neither a staticmethod nor a classmethod)
And then in a try except block we could actually try to reply to this message, as it's guaranteed that it's the same channel.

**Comment by NIRDERIi** [comment]
Oh yeah you are correct, forgot about that.

**Comment by MarkKoz** [comment]
I like this enhancement. An API changing can be avoided by making the bot parse the message ID from the URL. However, I think it's better to adjust the API to store a message ID. It should be possible to make a migration that preserves extant reminders since, as mentioned, the message ID can be extracted from the URL.

**Comment by D0rs4n** [comment]
Yes, that's true. Didn't think about it. I was told to put this issue on halt, until they approve the change in the API, but extracting the ID from the URL would make the process faster. So I think we could go with that method.
(Also I'd like to pick up this issue )

**Comment by NIRDERIi** [comment]
> I like this enhancement. An API changing can be avoided by making the bot parse the message ID from the URL

You mean because it is in that format:
https://discord.com/channels/guild id/channel id/message-id
And than somehow `jump_url.split('/')[-1]`? Tho I think that we should just store the message-id so it'll be more clear for other users who look at the source.

**Comment by D0rs4n** [comment]
That would involve changes in the API, that might not be approved.

**Comment by MarkKoz** [comment]
I'm fine with an API change if someone wants to tackle it. As I said, it would ultimately be better to store the ID than a URL, since it's the more direct piece of data that we need. However, URL parsing is fine for now; changing the API can happen at any time down the road.

**Comment by D0rs4n** [comment]
The API will be ported to FastAPI anyways, from then it'll be way easier to change on such things.
Until then I'd gladly implement this URL parsing method.
