### ISSUE TITLE
Delete detected webhooks

### ISSUE THREAD

**Issue by ChrisLovering** [python-discord/bot#1747]
I propose that when we detect a webhook that's been posted in the guild, we call `DELETE` on that URL, so that the webhook is deleted.

This is to protect users against themselves, since there is the chance that their message was scraped before we deleted it, and someone now has that webhook url.

Implementing this would be as simple as calling DELETE on any webhook URLs that we detect.

If we do this, we should update the message in the channel to tell them that we did as much.

**Comment by Bluenix2** [comment]
I am in support of this, but just wanted to add that we should also let the user know that this happened through a message in that channel.

*Alternatively or additionally*, we could send one message with the webhook that explains what has happened.

**Comment by ChrisLovering** [comment]
I'm against executing the webhook ourselves, but yea we should update the message that gets sent in the channel.

**Comment by Akarys42** [comment]
I am in favor of deleting the webhook. We can update our DM message (do note it falls back to being inside the channel if the user has DMs disabled) to say it has been deleted and a new one should be generated.

**Comment by janine9vn** [comment]
> 
> 
> Our channels are often rather crowded, if we send a message with the webhook they can read the message clearly themselves without scrolling.
> 
> It can also prove as a better lesson, "Look, we were able to send this message because you leaked the url!", rather than talking hypothetically.

I'm going to be very against anything other than deleting the webhook and adding information in our normal DM/in-channel message. It's not our responsibility to provide lessons to users about keeping webhooks safe, especially if it's us doing something that's pretty much against ToS.

**Comment by ChrisLovering** [comment]
On top of what's in the original issue description, we should also change the alert that's posted in mod-alerts to include whether the DELETE was successful or not.

i am not sure if this is current behaviour, but we should also run this filter against staff posting webhooks, since a mod may want to delete a webhook found in a grabber script.

**Comment by ChrisLovering** [comment]
It seems we're in agreement on this. I'll approve the issue.

**Comment by D0rs4n** [comment]
I'd like to try to solve this issue.
