### ISSUE TITLE
Use DAY_TIME or DATE_TIME  timestamp format for reminders

### ISSUE THREAD

**Issue by Numerlor** [python-discord/bot#1750]
The reminders display the relative time when the reminder is scheduled, but the relative duration was already given by the user when they scheduled the reminder. It's also unlikely that someone will look at the reminder scheduled message in the past (apart from jumping to it when the reminder is sent) so in most cases the relative timestamp only restates what the user already knows; I think using the DAY_TIME (F) or DATE_TIME (f) would make more sense in this case

This is how they compare to each other, with DATE_TIME being the second format and DAY_TIME the last
![](https://i.imgur.com/i7wyP2n.png)

**Comment by MarkKoz** [comment]
I agree. I don't have a preference for which of the two proposed formats to use. I suppose it doesn't hurt to throw in the weekday.
