### ISSUE TITLE
Python community & partners get same access as staff

### ISSUE THREAD

**Issue by ChrisLovering** [python-discord/bot#1758]
I'd like to propose that everywhere in the bot (barring talent pool) that uses `STAFF_ROLES` as a check is changed to also include both python community and partners as passing that check.

These places would be:
- Duck pond (for seeing if a message was from a staff member)
- Help command (Posts output in channel, rather then being relayed to bot-commands)
- Role list (a command to list all roles)
- Role info (a command to get info on a given role)
- User info (Posts output in channel, rather then being relayed to bot-commands)
- Raw command (Bypasses cooldown, and allows them to run it in any channel)
- List stream (Ignores them in output of list stream, as they have explicit stream permissions like staff anyway
- Ping (Allows them to run it in any channel)
- Reminder (Allow them to run it in any channel)
- Charinfo (Allow them to run it in any channel)

**Comment by Akarys42** [comment]
I agree with all of this, except for `#duck-pond`, since they don't have access to that channel, I don't think it would make sense to be able to duck their messages.

**Comment by ChrisLovering** [comment]
> I agree with all of this, except for `#duck-pond`, since they don't have access to that channel, I don't think it would make sense to be able to duck their messages.

Yup, that sounds good. Seems like 3 core devs are in agreement, I'll approve this :)

**Comment by TizzySaurus** [comment]
I'd be interested in working on this, but need to know what approach we'd like to take.

Would it simply be a case of changing `has_no_roles_check(*STAFF_ROLES)` to `has_no_roles(*STAFF_ROLES, partners, python_community)`, or do we want to add some sort of separate roles-category for this?

**Comment by Akarys42** [comment]
> I'd be interested in working on this, but need to know what approach we'd like to take.
> 
> Would it simply be a case of changing `has_no_roles_check(*STAFF_ROLES)` to `has_no_roles(*STAFF_ROLES, partners, python_community)`, or do we want to add some sort of separate roles-category for this?

What I would do is add the two roles to the existing `STAFF_ROLES` constant. You can then explicitly list all of those roles except partners and community members in the duck pond cog.

**Comment by ChrisLovering** [comment]
Hhmm, we may want to add a new constant, that's staff + the two new roles, since the staff roles constant will still be used in some places (duck pond and talent pool)

**Comment by Akarys42** [comment]
Right, I forgot about talent pool. Let's do that then.

**Comment by TizzySaurus** [comment]
What do we want to call the constant? Perhaps `STAFF_PARTNERS_COMMUNITY`?

**Comment by ChrisLovering** [comment]
Probably want to put `_ROLES` on the end too, for consistency with other constants.

**Comment by TizzySaurus** [comment]
True. `STAFF_PARTNERS_COMMUNITY_ROLES` seems good I think.

**Comment by TizzySaurus** [comment]
Although I have just realised I have no clue how to configure constants. I'm assuming it's just a matter of editing the `constants.py`, or do I need to adjust the `default-config.yml` too?

**Comment by ChrisLovering** [comment]
The classes marked with `metaclass=YAMLGetter` read directly from the yaml file(s).

For this, i think it should be fine to just do `STAFF_PARTNERS_COMMUNITY_ROLES = STAFF_ROLES = [Roles.partners, Roles.python_community]` after the `STAFF_ROLES` definition, without changing any of the yaml files.

**Comment by TizzySaurus** [comment]
@ChrisLovering Do we want to allow partners + python community to have member-pings in the `!remind` command?

**Comment by TizzySaurus** [comment]
Also in terms of commits, do we want "Allow partners + python community to use x" for each "x" or just one overall "Allow partners + python community more access"

**Comment by TizzySaurus** [comment]
And do we want to allow partners + python community to use the snowflake command anywhere?

**Comment by wookie184** [comment]
> Do we want to allow partners + python community to have member-pings in the !remind command?

I think that would be fine, although I wouldn't mind.
> Also in terms of commits, do we want "Allow partners + python community to use x" for each "x" or just one overall "Allow 
partners + python community more access"

I think one overall commit would be good.
> And do we want to allow partners + python community to use the snowflake command anywhere?

Sounds fine to allow that.

**Comment by TizzySaurus** [comment]
Okay :+1:

I'm doing individual commits right now but can rebase and squash at the end.

**Comment by TizzySaurus** [comment]
bot#1776 is now ready for reviews :+1:
