### ISSUE TITLE
Remove restriction on snowflake command

### ISSUE THREAD

**Issue by ChrisLovering** [python-discord/bot#1759]
Now that the output of the snowflake command is paginated, I see no reason to limit non-staff members to only invoke it with 1 snowflake at a time.

I think we should remove the staff role check in this command and allow anyone to run it with as many snowflakes as needed.

**Comment by D0rs4n** [comment]
I would be glad to do this! :)

**Comment by ChrisLovering** [comment]
> I would be glad to do this! :)

Assigned!
