### ISSUE TITLE
Update to remove unmaintained d.py dependency

### ISSUE THREAD

**Issue by parafoxia** [python-discord/bot#1789]
[discord.py has been discontinued](https://gist.github.com/Rapptz/4a2f62751b9600a31a0d3c78100287f1), so a rewrite may be necessary in order to implement new features. [Hikari](https://github.com/hikari-py/hikari) is the best option for Python libs -- there is no stable release right now, but dev101 is the last majorly breaking release planned, and stable planned for release in November. It also has full support for slash command via the [Tanjun](https://github.com/FasterSpeeding/Tanjun) command handler.

**Comment by ChrisLovering** [comment]
We're in no rush to do a re-write. This new means a large number of people are now looking for an alternative, so we're planning to take it slowly and see what emerges in the coming weeks and months, we've got time to wait.

**Comment by jb3** [comment]
For the aforementioned reasons, we're going to see what happens in terms of emerging forks in the coming weeks.
