### ISSUE TITLE
Making a specific resource command, like !books or !resources books

### ISSUE THREAD

**Issue by KittyBorgX** [python-discord/bot#1797]
Many a times when users ask for resources, the `!resources` command comes handy 
However when a user asks for a specific resource like, `where can i find a good python book` , using the `!resources` command is out of context even though it has a section for books

My idea is to implement a specific resource command, like !books or !resources books which links to https://pythondiscord.com/resources/reading/ 

This feature is not just for books but for all categories which is part of the resource.

**Comment by Xithrius** [comment]
This will be possible after the merging of https://github.com/python-discord/bot/pull/1663.

**Comment by KittyBorgX** [comment]
Oh okay!

**Comment by dawnofmidnight** [comment]
This should probably also wait until the site's smarter resources project is complete, as that fully redesigns the resources page and allows you to pass in query strings for different filtering parameters. Here's what some of those categories are:
![image](https://user-images.githubusercontent.com/78233879/131599345-73b59331-b25e-40e9-b7ac-3069bb151d2e.png)

**Comment by KittyBorgX** [comment]
kk, closing this issue

**Comment by wookie184** [comment]
Closing this as it's very similar to #1324, and once smarter resources is complete I don't think this would be necessary, although the idea mentioned in the other issue of a subcommand to search for specific resource items sounds like a nice idea.
