### ISSUE TITLE
Correct "Expires" field for permanent infraction searches

### ISSUE THREAD

**Issue by TizzySaurus** [python-discord/bot#1801]
Currently when you search for an infraction which is permanent, it'll say "Expires: Expired" even though it hasn't expired (because it's permanent).

This should be corrected to say "Expires: Never".

I'll do this later today as it's a quick fix.

**Comment by TizzySaurus** [comment]
This is something that may get fixed by @MarkKoz's PR (#1680). Are you planning to do this Mark?

**Comment by MarkKoz** [comment]
It's already fixed by 28f24313c45c237dfd8562be4ca7cae6873fd3c8 in #1721

**Comment by TizzySaurus** [comment]
Perfect, thanks :+1:

I'll close this issue then
