### ISSUE TITLE
Replace bot.loop.create_task usages with scheduling.create_task

### ISSUE THREAD

**Issue by Numerlor** [python-discord/bot#1807]
Since 0b726398d2135ab414374412fa85f791569e3640 we accept a loop kwarg to `scheduling.create_task` which can be used to create a task with a not yet running loop where `asyncio.create_task` doesn't work directly.

Because the created tasks currently don't have any error handling they can hide errors in development until the task object is destroyed (if that occurs at all) which logs the exception. The scheduling alternative attaches a callback which logs exceptions to prevent this.

For every task the call should look something like this:
```py
self.placeholder_task = scheduling.create_task(coro, event_loop=<the loop previously used to create the task>)
```

**Comment by ChrisLovering** [comment]
Yup, I like this interface, we should do it!

**Comment by Numerlor** [comment]
I'll get this done if nobody else wants to grab it as it's annoying to work with the hidden errors
