### ISSUE TITLE
Delete command usage once trashcan reaction is pressed for the "eval" command

### ISSUE THREAD

**Issue by Diabolical5777** [python-discord/bot#1816]
For the "eval" command, once you press the trashcan reaction for your evaluation, it would delete your message that invoked it.
Right now, it just deletes the response when the trashcan is pressed

**Comment by mbaruh** [comment]
It's possible that you evaluated your code and it came out wrong, but you still want it in the chat, e.g to patch it and try to evaluate again, or to discuss it with someone. Ultimately this is your message so you can just delete it yourself via Discord UI, so all in all this doesn't seem like desired behavior to me.

**Comment by mbaruh** [comment]
Following what I previously said, the suggestion reduces flexibility, so I'll close this issue.
