### ISSUE TITLE
Lower spam filter strictness in bot command channels

### ISSUE THREAD

**Issue by TizzySaurus** [python-discord/bot#1847]
There has been a number of instances recently where users have been getting auto-muted by the bot for "spamming" bot commands / messages in response to commands.

This had lead to multiple discussions of reducing the strictness of our filters within the two bot command channels, and it seems no one is strongly against this -- after all, the bot command channels are meant to be semi-spammy (that's why they exist).

In terms of what exactly should be done, I think the duplicates filter max should be increased to say 6 messages (from 3), and the newlines filter increased to say 120 (from 100) -- the latter for the `!eval` command. The exact new limits are up for discussion.

It should be noted that as a downside, people who are actually spamming etc. may go "under the radar" even more than they currently do in the bot channels (mods generally aren't watching that general).

**Comment by dementati** [comment]
A short-term solution seems like it would require making channel-specific overrides for the antispam config, which sounds kind of complicated for something that'll get removed soon anyway. If the new filter system will subsume the antispam functionality and can adequately cover this use case, we should mark this issue as stalled waiting for it to be implemented.

**Comment by TizzySaurus** [comment]
> A short-term solution seems like it would require making channel-specific overrides for the antispam config, which sounds kind of complicated for something that'll get removed soon anyway. If the new filter system will subsume the antispam functionality and can adequately cover this use case, we should mark this issue as stalled waiting for it to be implemented.

I spoke to @mbaruh about this yesterday and he confirmed this will be possible with the rewrite. Will add the "stalled" label :+1:

**Comment by mbaruh** [comment]
This is done now
