### ISSUE TITLE
Always create a log if filtered messages have attachments.

### ISSUE THREAD

**Issue by mbaruh** [python-discord/bot#1850]
Currently, when creating a mod alert, the bot will not create a log of the messages if there is only one message involved, and will display it in the alert embed directly instead.

That should not be the case when there are attachements. If there are any, it should always create a new log and link to it instead of trying to display the contents of the message (which might not exist).

Example of an alert with no content (because it's a single message with only attachments):
![image](https://user-images.githubusercontent.com/18114431/135753152-46a4a8cb-d4da-49f7-bbe4-434b541c5c8a.png)

How it looks like when it's several messages:
![image](https://user-images.githubusercontent.com/18114431/135753145-6d5a0db9-3b8d-43e2-a4a2-608abc5e7f15.png)

**Comment by TizzySaurus** [comment]
I'll be working on this over upcoming days.

Current plan is to change [L86](https://github.com/python-discord/bot/blob/main/bot/exts/filters/antispam.py#L86) to the following, as discussed with Zig internally:
```py
if any((
    len(self.messages) > 1,
    self.messages[0].attachments,
    self.messages[0].count('\n') > a_reasonable_amount
)):
```Will do some testing to figure out what exactly `a_reasonable_amount` is.
