### ISSUE TITLE
`!doc setdoc` gives malformed request error when setting a package that already exists

### ISSUE THREAD

**Issue by wookie184** [python-discord/bot#1858]
If you run, for example
```python
!doc setdoc pygame https://www.pygame.org/docs/objects.inv
```
twice, you'll get a message saying `According to the API, your request is malformed.` and this error:
```python
bot_1        | 2021-10-05 18:04:59 | bot.exts.backend.error_handler | DEBUG | API responded with 400 for command docs setdoc: {'package': ['documentation link with this package already exists.']}.
```
We should handle this and give the user a better error message

**Comment by ichard26** [comment]
I'd like to fix this issue as my first code contribution to the repo ^^ ... I suppose I should just assign this to myself or is that not how this works?
