### ISSUE TITLE
Change `!subscribe` to Buttons for sub-roles

### ISSUE THREAD

**Issue by janine9vn** [python-discord/bot#1866]
This is coming from python-discord/meta#150. 

## Context
For recurring events where users might want to be notified about happenings, I'd like to add roles where we can ping people about information. The most notable application here is for PyWeek! Considering this functionality is *very* similar to the `!subscribe` command, we've determined the best UX would be to utilize the Discord Button Components and change how the `!subscribe` command works.

## Details
This should have a button for each type of role subscription (e.g. Announcements, PyWeek). Each button will act as a toggle to either subscribe or unsubscribe from the role. This should be made clear from the text and button appearance. 

## Concerns
Currently, I'm only proposing this functionality for roles that we manually ping for information. It was brought up that this could be used for some of Sir Lancebot's features like Advent of Code. But that brings in additional complexities of the interplay between Python and Sir Lancebot. I'll defer to Core Devs on the approach for this.

Implementation of this feature is blocked until python-discord/bot#1815 is merged.

**Comment by ChrisLovering** [comment]
I'd like to add to this that the implementation should be extendable. IE adding a new role would just be the case of adding an ID to a list.

**Comment by onerandomusername** [comment]
Was this implemented with #1868?

**Comment by ChrisLovering** [comment]
Yup
