### ISSUE TITLE
Helpers can’t mention others in reminders

### ISSUE THREAD

**Issue by gustavwilliam** [python-discord/bot#1869]
Helpers (and partners/python community) should be able to mention other users, but not roles, in reminders. In late June, this was still possible, but it currently isn't.

While looking through the source code and git blame (looks *calmly* at @TizzySaurus), I think I managed to locate the issue to the `Reminders._check_mentions` method. For a non-mod helper, the error message when mentioning another user in a reminder (should be allowed), is the error message that should be used when trying to mention a role (defined at https://github.com/python-discord/bot/blob/06e90af5e19d9dd83ae44ac2ae0eb3eeb43349e2/bot/exts/utils/reminders.py#L120).

It basically seems like the user is getting blocked due to not being a moderator, while they should be allowed to mention others. If someone could look at this a bit more extensively than I did today, and fix it, that would be much appreciated 😄

**Comment by gustavwilliam** [comment]
@TizzySaurus where are you saying that we're checking if the mention is for a role? To me, it looks like we just return `False` whenever (1) the user isn't staff or (2) the user isn't a mod.

How would it ever return true if it fails on the "elif not mod" line?

**Comment by ChrisLovering** [comment]
It seems like the reason that this fails is that even though the mentions are converted to `mentions: t.Iterable[Mentionable]` if a user id is passed into the command, it gets converted to a User object within the iterable, which fails the `isinstance(mention, discord.Member)` condition.

**Comment by TizzySaurus** [comment]
> Yea that should work

Will make a PR then :+1:
