### ISSUE TITLE
Add Consistency Checks

### ISSUE THREAD

**Issue by HassanAbouelela** [python-discord/bot#1903]
Every now and then, the help channel cog will desync (mostly due to unavoidable issues from the discord API). This desync takes many forms, most prominent being:

- Decrease in number of help channels available (#1941)
- Desync of dynamic help message in `#how-to-get-help`
- ~~Pins not being removed after a channel is closed~~ Fixed
- Cooldown roles not being removed after a session ends (#1940)

These happen often enough that I think we should spend some effort to get them to automatically figure themselves out. I've divided this issue into three separate sub-problems, one for (mostly) each of the points above.

## Pins
This one is relatively straightforward. We should [get all pins](https://discordpy.readthedocs.io/en/master/api.html#discord.abc.Messageable.pins) when a channel is moved into dormant, and unpin them. I've checked the rate limit for that endpoint, and it appears to be 1 request / 5s / channel, so I think we're fine.

## Cooldown roles
We already keep a list of which authors currently have a channel open, and I believe that does not desync in line with the cooldown roles (though it can be difficult to test). I think that means we can compare the [list of people with the role](https://discordpy.readthedocs.io/en/master/api.html#discord.Role.members), against the list of channel claimants, and remove any outliers. We should probably run this in some sort of periodic task, possibly every hour? That implementation detail can be left up to the author.

## Channels & Channel Names
For the two desync patterns not mentioned yet, a simple cog reload seems to mostly do the trick. It's the go-to method for staff whenever we see a desync, and I estimate we run it bi-weekly right now. It only takes a few seconds (5 according to Akarys), so we should be fine to periodically just reload. Perhaps every hour as well.

@Akarys42 has brought up concerns about redis race conditions, we can discuss those here.

## Closing Remarks
None of the mentioned fixes depend on each other, so we tackle each in separate PRs asynchronously.

I'm going to say that if no one has concerns within the next couple days, I'll be approving this issue for the cooldown role and pin fixes. I'll hold off on the last one till we figure out the race issue, but I'll update the issue once it's approved.

**Comment by dementati** [comment]
The pins issue is solved by #1909 and #1936.
