### ISSUE TITLE
Don't trigger filters on pin

### ISSUE THREAD

**Issue by mbaruh** [python-discord/bot#1934]
The filters are re-run on messages that are edited and pinned. Because of the help channel system, This can cause a filter to trigger twice if the opening message contains a trigger.

We should check what causes the filters to trigger on pins and see if there's a way to disable that.

**Comment by Qwerty-133** [comment]
This happens because we re-run our filters whenever an `on_message_edit` event fires, which happens to fire when a message is pinned. Checking whether the `pinned` attribute's value changed should be enough.
