### ISSUE TITLE
YTDL tag does not state the same as rule 5

### ISSUE THREAD

**Issue by kkrypt0nn** [python-discord/bot#1957]
The current YTDL tag says that, as per rule 5, we should not provide with *questions related* to YTDL. However, the rule 5 says we should not help with **projects** that breach Terms of Services (in that case, YouTube).

An example where you are against the rule 5 but not against the YTDL tag:

> Someone asking a general question not related to YTDL in a project that contains YTDL and therefore breaches YouTube's terms of service.

In that example people will help as the question is not related to YTDL, but the rule 5 says we should not help at all when it comes to **projects** that breaches terms of services.

The current YTDL tag also says *"as per rule 5"*, which is wrong. As per rule 5 we should not help on **projects**, and not just *questions*, that may breach terms of services.

Pull request #1952 closes this issue.

**Comment by JacobMonck** [comment]
I don't think we refuse to help people with projects that contain ytdl as long as the question doesn't involve it then it's fine.

**Comment by kkrypt0nn** [comment]
We actually do. The rules channel clearly says so:

> Do not provide or request help on **projects** that may break laws, **breach terms of services**, or are malicious or inappropriate.

`youtube_dl` breaches the terms of services of YouTube, so according to rule 5, we should not help anyone that uses `youtube_dl` in the project they're asking help for.

**Comment by wookie184** [comment]
The ytdl tag is still accurate, and I think it's fine to leave as is. It shouldn't really be used other than in cases where it's obvious the person is working on ytdl as in more non-obvious cases (e.g. if they were working on a project using ytld earlier and you think they still are) the decision on whether it's ok should probably be left to a moderator.
