### ISSUE TITLE
Remind from reply

### ISSUE THREAD

**Issue by Shivansh-007** [python-discord/bot#1958]
## Description
Get the remind content from the replied message

![Screenshot from 2021-11-15 17-30-20](https://user-images.githubusercontent.com/69356296/141778616-f8b2f7cc-e590-46d5-9ae1-d2c9f0d3e2e0.png)

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [X] Anyone can implement this feature

**Comment by TizzySaurus** [comment]
I was actually planning to do this myself soon:tm: so if this is something that gets approved I'll work on it :+1:

**Comment by Akarys42** [comment]
Sure, I don't see any harm. Go for it @TizzySaurus!
