### ISSUE TITLE
[Meta] Bot Core Refactor

### ISSUE THREAD

**Issue by sco1** [python-discord/bot#198]
Wanted to open up a discussion related to some of the things we've been chatting about in the developer channels recently. All put together I think it ends up being a significant effort & rearchitecting that will need a lot of feedback & planning (https://github.com/orgs/python-discord/projects/2).

**TLDR**: There seems to be a good amount of technical debt building up as Python's features have expanded. It hasn't gone unrecognized, as proposals have already been made for multiple bots (fun bot, seasonal bot, recruitment bot) to handle some of the more distinct functionality and take some burden off of the singular bot (see: #161). I don't think the current architecture well supports such a distribution.

A couple starting points for discussion, in no particular order:

1. Refactor and thoroughly document shared utility functionality (e.g. authentication, constants, API links, logging, etc.) into a core codebase that can be used by all bots. This alleviates a lot of the copy+paste that would be necessary to unify core functionality across bots, and also eliminate the need for certain functionality (e.g. warning embeds, command role restriction) to be recreated in multiple cogs. This should help with some of the things brought up in #160.
2. Related to #132, a more developer-friendly testing framework so issues can be caught before the MR. While self-hosted testing can catch a good amount of development issues, it's a bit of large task to test new features within our current framework.

**Comment by MarkKoz** [comment]
I think an API wrapper would be a major component of this and I may tackle it, but it may need to wait until django rewrite is done. I'm not sure how consistent the API in django will be with the current API.

**Comment by jchristgit** [comment]
I am working on an API wrapper, it is more or less just a very thin interface to `aiohttp`. The new endpoints all more or less follow unified format, and the endpoint-specific logic has been removed so far. See #95.

**Comment by MarkKoz** [comment]
Ah, I didn't realise that was an API wrapper. Anyway, I was thinking of something nicer, like deserialising responses into data classes.

**Comment by jchristgit** [comment]
I don't think that's necessary. The API responses are easy enough to work with as dictionaries.

**Comment by heavysaturn** [comment]
yeah, I think API wrapper, Tasks wrapper and constants might be nice to keep in some sort of core repo that all bots use if we're gonna have more than one bot. And it seems like a good idea to split our bot into at least two bots - one for fun stuff and one for serious stuff. I see no reason why we'd need more than two, but I do think we should have two, for two important reasons.

1. Because moderation and event handling needs to be online 24/7, and it's less likely to crash if we don't merge stuff like snake_movies or whatever into it.
2. Because it allows us to maintain two different policies. We could be very, very careful with merge requests on the serious bot and only allow key contributors to work on it, while being very lenient and open on the fun bot. We could run off-site backup instances of the serious bot, but there's no need for backup instances of hacktoberbot features.

We should probably figure out how we would do that, though. @gdude2002 has been suggesting we make a pypi release and just pip install it on the bots. Submodules has also been mentioned. I'd like to hear discussion about it.

**Comment by sco1** [comment]
I was thinking the same: having a distinct bot-core repository that Python & any other bots depend on. This could just be a source dependency vs. releasing to pypi, but that's an easy decision to make.

**Comment by MarkKoz** [comment]
It'd have to be fairly generic to merit a PyPI release. Wouldn't that also mean we have to worry about versioning and releases? 

If it's still specialised to our community, we should just use submodules. I think that's a simpler approach.

**Comment by heavysaturn** [comment]
Apparently PyPI is frequently used for non-generic releases.

**Comment by heavysaturn** [comment]
(consider that it has 160k packages on it)

**Comment by MarkKoz** [comment]
Point is, it seems like more effort (if we want to properly maintain it) compared to a submodule when it doesn't really make sense since specialised packages wouldn't benefit many others.

**Comment by MarkKoz** [comment]
Actually, I don't like the idea of a git submodule either. We should just add the repo as a link to our Pipfile.

**Comment by heavysaturn** [comment]
probably isn't much more effort - we could handle builds and deployment via CI. And considering submodules are absolutely _hated_ in our community...

Adding the repo as a link in our pipfile seems like a good third option. I might vote for that one.

**Comment by MarkKoz** [comment]
Yeah I just realised submodules don't fit in well with Python.

**Comment by heavysaturn** [comment]
if simply having the repo URL in the pipfile is a viable option, I think it makes all the other suggestions seem wildly overcomplicated in comparison.

**Comment by gdude2002** [comment]
Here's what I would do.

- Have a bot "core" repository, potentially on PyPi. This core would contain several things:
    - The main bot code. Everything internal to the bot - shared constants, plugin loading logic, all the nuts and bolts that can be dealt with in a central manner.
    - A mechanism for loading cogs or extensions - preferably with a base class system. This would be our plugins.
    - All the utilities you would need
- Have extra repositories for each bot, or a second repository with sub-project (folders)
    - These would simply contain the cogs/plugins that provide the functionality of that bot
- Have a third repository containing a library for interacting with the API exposed by our site, as far as we can possibly go with that. This almost certainly should be on PyPi.

This seems like the ideal mix of easy of development (Non-core contribs only have to care about cogs), separation of concerns, and keeping useful stuff available to the public, IMO.

**Comment by heavysaturn** [comment]
I can't see any reason why any of these would be on PyPI when the alternative that's been suggested is still on the table. Builds and deployment for PyPI would be far more work. What advantages would PyPI have over the alternative that makes up for this extra work?

**Comment by gdude2002** [comment]
PyPi provides a central repository for people that aren't intimately involved with our development process but may want to use our tools, it requires that we adhere to healthy versioning practises, and it backs everything up with a hash verification system - which means we don't get any nasty surprises.

And the overhead is pretty minimal. Twine is super easy to use, and Azure even provides [a short guide](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/pypi?view=vsts&tabs=yaml) on how to use it. What we should really do to solve that is to just automate it using Git tags, or by promoting builds to releases on Azure.

**Comment by heavysaturn** [comment]
why would anyone except us want our API wrapper? I guess if we wrote our bot core super generic it might possibly be useful to someone else, but even that strikes me as an incredibly long shot. hash verifications are supposed to prevent exactly _which_ nasty surprises? It sounded like we could do versioning with direct repo linking too. 

These advantages seem incredibly remote and slight to me, and my vote would be firmly in the "fuck PyPI then" camp.

**Comment by MarkKoz** [comment]
It wouldn't make sense for us to put an API wrapper on PyPI given that the site is specialised, meaning it is unlikely anyone else would host there one (thus there's no point on putting the site on PyPI either in case that was ever an argument). Furthermore, we aren't handing out API keys to the site we host, so who else but us would ever use the API?

**Comment by MarkKoz** [comment]
That being said, the API wrapper being a separate package is still a good idea. It will allow us to write tools which use the API that aren't bots and don't need the core.

**Comment by jos-b** [comment]
I think Azure artifacts is a better solution to this. Quite a few of us have expressed concerns with putting a package like this on PyPi. I've been told it's a thing people do but so far I've only been shown one example of this. Azure artifacts feels like a better solution to be since we can still host wheels on there and get them in a Pipfile without them being stored on PyPi.

**Comment by heavysaturn** [comment]
I can see the value in that, although it's a very hypothetical potential future value instead of an immediate one, which isn't my favorite thing. We have no projects planned where this might be useful as of right now.

As for hosting a wheel on artifacts, I still don't see why this is better than just linking directly to the git repo in the pipfile. it just seems like more work for almost no benefit.

**Comment by jos-b** [comment]
I think wheels would be a nice method of distribution and it's pretty standard now for external packages, but git or zip would be fine solutions as well.

**Comment by MarkKoz** [comment]
Was that first paragraph directed at my comments? @heavysaturn 
If so, I see your point but I don't feel like there's much of a downside to just having a separate repo. I don't have strong feelings for this though; if we design things well we should be able to move it a later time as needed so it's no problem keeping them together for now.

**Comment by heavysaturn** [comment]
there's not much of a downside to splitting it into 8 repos either but it's inconvenient and needlessly complex.

**Comment by heavysaturn** [comment]
basically my take is that in the interest of keeping this as simple as possible, putting the entire bot core in a single repo (yes that includes the API interface) and linking to it from the bots in the pipfile is by far the most straight forward solution. these other ideas have some merit but I don't think any of the advantages seem to outweigh the added complexity. I'm just trying to protect us from needless feature bloat.

**Comment by heavysaturn** [comment]
Making the API interface a standalone service would probably be a great idea if we ever did need it for anything else, though. but I can't imagine what that would be. maybe it's just my lack of imagination. Anyone have any actual ideas for what that might be?

**Comment by MarkKoz** [comment]
Maybe doing some number crunching on the data in the API? I'm clueless on that subject though so perhaps there are better ways of doing that than through the API.

**Comment by jos-b** [comment]
If we ever do decide to make another service which isn't a bot then we have immediate access to the API without having to copy-paste/write a new interface for it. I can't think of specific use cases though.

**Comment by MarkKoz** [comment]
Like I said, we always could move it out later if needed if we have loose coupling with the rest of the core.

**Comment by heavysaturn** [comment]
Most of the interesting stuff we've got planned that aren't bots would probably be happening on the site anyway, so an API interface wouldn't be useful for that. I mean unless we're making a mobile app or something I just don't see what it might be that needs the API interface.

Besides, like Mark said, if this eventuality did come to pass, we could always turn it into a standalone system then.

**Comment by heavysaturn** [comment]
loose coupling sounds like a good idea, though.

**Comment by MarkKoz** [comment]
We should just treat it as if it's a separate package to the greatest extent we can even though it'll be in the same repo.

**Comment by jos-b** [comment]
Yeah that's true, just don't make it rely on anything else apart from itself. ezpz.

**Comment by gdude2002** [comment]
> why would anyone except us want our API wrapper?

> we aren't handing out API keys 

In my initial discussion with Volcyy about the django branch, I mentioned that we were planning on building a proper API. We offer a lot of things already, and some of that data would be useful for other people to interact with, but that list of things is only going to expand. I explained that we would likely need a system that allows us to assign API keys or allows users to request them.

I don't know if Volcyy actually got around to doing this, though.

While there isn't much value in an API wrapper for _the current site_, that is definitely not going to always be the case.

---

Also, I disagree with the "do it later" mentality when there's such a small amount of technical debt in doing this properly.

**Comment by heavysaturn** [comment]
I don't like it one bit, nor do I like that you're dismissing what I feel are legitimate concerns as "do-it-later mentality", but I'll compromise in the interest of moving forward. Sure, let's have three repos, but no PyPI. We just link'em together using git repo URLS and release tags, as in something like `bot-core = {git = "git://github.com/python-discord/bot-core.git", editable = true, ref = "1.5"}`

**Comment by sco1** [comment]
To back up a bit, is there agreement on splitting generic utilities into a core repository? If so, what cogs go into the core and which ones stay with the current repo?

**Comment by heavysaturn** [comment]
I absolutely agree that we need to have a core repo. I'm not sure which cogs to put in it off the top of my head, but we should definitely fill it with our config system, our decorators, our utils.. One cog that's an obvious candidate for a core repo would be the cog loading cog.

**Comment by sco1** [comment]
While it seemed like a good idea at the time, this issue seems to have grown beyond its original intent into something negative that nobody is really keen on doing, so I'm going to close my request.

It looks like there is some consensus on some of the more specific points, so issues can be opened against those instead.
