### ISSUE TITLE
Allow uploads of `.csv` and `.json` files.

### ISSUE THREAD

**Issue by janine9vn** [python-discord/bot#1983]
This was brought up internally and voted on on the staff meeting today. We've decided we'll allow the uploading of `.csv` and `.json` files!
I won't include the reasoning here, but if you're curious feel free to ask in server.

We need to adjust our python bot to not automatically delete those files.

**Comment by bsoyka** [comment]
Resolved by @ChrisLovering with a couple commands, turns out the filter for this is dynamic. 😄
