### ISSUE TITLE
Not allowing cdn discord image links in #python-general

### ISSUE THREAD

**Issue by Shom770** [python-discord/bot#1998]
A way to bypass posting an image is posting an image link, and a problem with that is that people can post image links and since they don't embed in that channel, users may open that link thinking it's code or something like that when in reality it's an inappropriate image and the likes

**Comment by DMFriends** [comment]
Hmm, that sounds like a good idea, @Shom770 . But I feel like anyone could post images via CDN discord links in any channel, so I think it might be a good idea to not allow CDN Discord links at all. What do you think?

**Comment by DMFriends** [comment]
Also, as far as I remember, CDN Discord links don't embed at all through Discord, not just in our server, and not just in #python-general. But correct me if I'm wrong.

**Comment by dawnofmidnight** [comment]
> Hmm, that sounds like a good idea, @Shom770 . But I feel like anyone could post images via CDN discord links in any channel, so I think it might be a good idea to not allow CDN Discord links at all. What do you think?

I don't like that idea personally, since that makes it harder to copy an image from one server to another (especially on mobile), which does happen rather often. Imo, this is really only a problem in channels where embedding permissions are not enabled.

> Also, as far as I remember, CDN Discord links don't embed at all through Discord, not just in our server, and not just in #python-general. But correct me if I'm wrong.

Images from the Discord CDN embed as long as a user has embed privileges in that particular channel afaik.

**Comment by DMFriends** [comment]
> > Hmm, that sounds like a good idea, @Shom770 . But I feel like anyone could post images via CDN discord links in any channel, so I think it might be a good idea to not allow CDN Discord links at all. What do you think?
> 
> I don't like that idea personally, since that makes it harder to copy an image from one server to another (especially on mobile), which does happen rather often. Imo, this is really only a problem in channels where embedding permissions are not enabled.
> 
> I'm not for or against this idea, but to me, that seems like the only place it can make a difference to disallow it.
> 
> > Also, as far as I remember, CDN Discord links don't embed at all through Discord, not just in our server, and not just in #python-general. But correct me if I'm wrong.
> 
> Images from the Discord CDN embed as long as a user has embed privileges in that particular channel afaik.

I see what you mean, @dawnofmidnight . Thanks for your response.

**Comment by Kronifer** [comment]
a possibility to stop people from doing this could be to refine the URL filter to grab these links and delete them if they are posted in pygen

**Comment by wookie184** [comment]
This seems like a fair suggestion to me, although the bot should tell them why the message was deleted. I think in this case it might be best to just post a really short message where it happened, otherwise they might not see it. Something like:
`@user You are not allowed to post discord cdn links in this channel`

Thoughts?

**Comment by DMFriends** [comment]
> This seems like a fair suggestion to me, although the bot should tell them why the message was deleted. I think in this case it might be best to just post a really short message where it happened, otherwise they might not see it. Something like:
> `@user You are not allowed to post discord cdn links in this channel`
> 
> Thoughts?

Lol I completely forgot of this issue's existence, it's been 5 months 🤣

Yeah sending a message like that would be a good idea for sure.

> Hmm, that sounds like a good idea, @Shom770 . But I feel like anyone could post images via CDN discord links in any channel, so I think it might be a good idea to not allow CDN Discord links at all. What do you think?

Thoughts on this @wookie184 ?

**Comment by minalike** [comment]
I think this idea may be a bit too restrictive. While yes some users use cdn links to post inappropriate images, that isn't their only use case. 

Though embed permissions are disabled in python-general, occasionally users will post links to images, which while not often ideal for getting code help, can be useful in sharing images of their IDE or visual output of their code. These are a few of the examples I observed after searching python-general for such messages.

I don't think there's much benefit to zapping cdn links in python-general, and believe regular means of reporting to moderation covers our needs.

**Comment by DMFriends** [comment]
> I think this idea may be a bit too restrictive. While yes some users use cdn links to post inappropriate images, that isn't their only use case. 
> 
> Though embed permissions are disabled in python-general, occasionally users will post links to images, which while not often ideal for getting code help, can be useful in sharing images of their IDE or visual output of their code. These are a few of the examples I observed after searching python-general for such messages.
> 
> I don't think there's much benefit to zapping cdn links in python-general, and believe regular means of reporting to moderation covers our needs. 

Yeah, honestly you might be right. I guess you can close this issue, unless anyone else has thoughts.

**Comment by wookie184** [comment]
On second thoughts I agree this is probably unnecessary.
