### ISSUE TITLE
Subtract replies in mentions rule

### ISSUE THREAD

**Issue by mbaruh** [python-discord/bot#2015]
The purpose of the mentions rule is to catch people spamming user mentions, but `message.mentions` shows the user being replied to, if the reply is pinging, which is out of scope for what the rule is trying to catch.

The replies should be subtracted when counting the number of mentions, and messages with only a reply but no mentions should not be returned.

**Comment by onerandomusername** [comment]
if no one else wants to do this tonight, I can see about taking a look in a few hours.

**Comment by onerandomusername** [comment]
I'd like to add to this.. while there, also don't count the author's own mention, if for some reason they mention themselves.

**Comment by onerandomusername** [comment]
I can implement this if someone assigns me.
