### ISSUE TITLE
Help Channel Tag System

### ISSUE THREAD

**Issue by gamingbuddhist** [python-discord/bot#2029]
So my idea is for helpees (channel claimer) and helpers (role: helper+) to be able to tag a help channel with the helpee's needed topic/s of help. An example would be if a user had a question about pandas, they could tag it "pandas" using "!tag pandas".

To link the tag system with the help channels, we could have a help summary channel above all the help channels that displays all open channels (with #links) with their help tags or an unknown tag if no tags have been added. The channel could display them in a single embed that gets updated on changes to tags or if a channel opens/closes.

- Tags could be predetermined or created on the spot. 
- The ability to remove tags would also be needed in cases of mislabeling. 
- Users can sign up to receive notifications about a certain tag

**Comment by shtlrs** [comment]
@gamingbuddhist I think we have this now thanks to the new help system.
Unfortunately, we're a bit limited when it comes to the number of tags allowed (I think it's 10)

**Comment by wookie184** [comment]
I think this can be closed
