### ISSUE TITLE
Anti-Malware Cog

### ISSUE THREAD

**Issue by GhostofGoes** [python-discord/bot#203]
Occasionally, users will upload malicious files that slip past Discord's fairly limited protections. Thus far, thanks to the sharp eyes of the staff, we've been able to catch most of these before they had a chance to be downloaded. However, as the server grows, the risk increases of something being available and potentially downloaded before the staff notices it. The goal of this cog is to eliminate that risk by checking message attachments for malicious or other undesirable content.

Features
* Checking of files for malicious content (Current approach is to use the [VirusTotal](https://developers.virustotal.com/v2.0/reference) database API for this purpose)
* Automatic removal of bad files
* Alerting of the moderator team of incidents (much like the current `antispam` cog)
* Optional ability to filter by extensions (e.g. warn if someone uploads a non-malicious zip file)
* Stretch: plug in other file identification services, such as NSFW/hatespeech content detection, "shitpost"-grade memes, etc (like `antispam`, but for content, and ideally more reliable than the (IMO) unreliable garbage Discord uses)

Current working name for the cog is "sentinel".

**Comment by sco1** [comment]
Relevant meta: https://github.com/python-discord/meta/issues/16

**Comment by GhostofGoes** [comment]
Ah, there's the issue I was looking for! Was positive there was an issue for this, but I couldn't find it, so figured I'd just make a new one.

**Comment by sco1** [comment]
Having it live in `./bot/utils/` seems like a good middle ground

**Comment by jos-b** [comment]
Yeah that sounds reasonable, just don't know if we need another cog for it, feels like there could be a lot of duplicated code when there is already a filtering system implemented.

**Comment by GhostofGoes** [comment]
I'll take a look and see if I can fit it into the filtering cog. The logic is a bit more complicated, since it's making API requests and caching results.

**Comment by jchristgit** [comment]
I disagree that this shouldn't be its own cog. See my comment on https://github.com/python-discord/bot/issues/160

**Comment by GhostofGoes** [comment]
Yeah, the arguments you made in #160 are spot-on. If there's a bug in the anti-malware scanning, it would be good to be able to unload it without losing filtering completely.

**Comment by GhostofGoes** [comment]
Moving here: https://github.com/python-discord/bot/issues/471
