### ISSUE TITLE
Users can break out of superstar prison by leaving the server!

### ISSUE THREAD

**Issue by heavysaturn** [python-discord/bot#205]
A user who really wants to change their nickname while in superstar prison can simply leave the server, change it, and come back. We should solve this by checking new arrivals for active superstar prison sentences and enforcing them at the door.

**Comment by sco1** [comment]
Ahhhh, the oldest trick in the book. oops...

**Comment by ByteCommander** [comment]
I would like to look into this issue, if you haven't already fixed it in the meantime.
