### ISSUE TITLE
Add Moderator pings for filtered usernames when they are active

### ISSUE THREAD

**Issue by minalike** [python-discord/bot#2068]
Currently, moderators receive a non-pinging alert in `#mod-alerts` when a username containing a filtered word sends a message. The moderators would like to add a Moderators ping to this alert.

https://github.com/python-discord/bot/blob/2f64912bf4fd0d8bf1f55cf97cb4d4aef5ea81a3/bot/exts/filters/filtering.py#L236-L268

We also want to add the same ping for when such a user joins a voice channel. However, this type of alert is not currently in the code and would require another listener.

**Comment by TizzySaurus** [comment]
Looking over the file, there's also some inconsistencies in imports which could be addressed in the same PR:

[L690](https://github.com/python-discord/bot/blob/2f64912bf4fd0d8bf1f55cf97cb4d4aef5ea81a3/bot/exts/filters/filtering.py#L690) uses the [`from discord import NotFound`](https://github.com/python-discord/bot/blob/2f64912bf4fd0d8bf1f55cf97cb4d4aef5ea81a3/bot/exts/filters/filtering.py#L15) import, whilst [L356](https://github.com/python-discord/bot/blob/2f64912bf4fd0d8bf1f55cf97cb4d4aef5ea81a3/bot/exts/filters/filtering.py#L356) uses the [`import discord.errors`](https://github.com/python-discord/bot/blob/2f64912bf4fd0d8bf1f55cf97cb4d4aef5ea81a3/bot/exts/filters/filtering.py#L9) import.

I'd personally solely use the `discord.errors` variant, meaning `NotFound` can be removed from the import on L15. Should probably also remove `HTTPException` in favour of `discord.errors.HTTPException` too, for consistency.
