### ISSUE TITLE
Do not ignore invocations of `!voiceverify` in `#voice-verification`

### ISSUE THREAD

**Issue by minalike** [python-discord/bot#2076]
Once in a blue moon (that day was today) a user somehow gets the Voice Verified role but the event is not logged by Discord's audit log nor in our `#user-log.`

Currently, the messages in `#voice-verification` that get deleted by the bot are logged in `#message-change-log` with the exception of invocations of the `!voiceverify` command.

We would like to see the bot not ignore these messages, and still log them.

The relevant sections of code (thanks @ChrisLovering)

https://github.com/python-discord/bot/blob/ee5a2166e08805a31dd6141db663ccacfde0b551/bot/exts/moderation/voice_gate.py#L194

https://github.com/python-discord/bot/blob/ee5a2166e08805a31dd6141db663ccacfde0b551/bot/exts/moderation/voice_gate.py#L242-L243

**Comment by ChrisLovering** [comment]
The further this, my opinions are that we should either remove these two mod_log.ingore calls, or we should log.info() these events, so that when investigating we have an avenue to go down that isn't trawl through Discord's audit logs.

**Comment by ChrisLovering** [comment]
In the linked PR I decided to only remove the ignore for the role assignment. I didn't think there was any point in logging the deleted message too.

**Comment by minalike** [comment]
Presently the bot has logic to exclude logging of both the member role update and the `!voiceverify` invocation. While removing the ignore for the role assignment does solve my issue of not knowing when a user had verified previously, I find the current behavior (prior to your PR) very odd and not intuitive. 

Why have code to ignore `!voiceverify` invocations at all? It goes against my expectations as an end user of the bot as a moderator, since we log all other deleted messages in #voice-verification
