### ISSUE TITLE
Show user ID outside embed for `#mod-alerts`

### ISSUE THREAD

**Issue by minalike** [python-discord/bot#2088]
Many moderators moderate from iOS and Android mobile devices. As of today, Discord iOS doesn't allow for copying embed text *at all*, and Android iOS allows copying of embed text as a whole (not selectively).

One of the biggest pain points for moderators is not being able to grab the user's ID from the mod-alert embed, neither from the embed itself nor from the mention of the user (because the mention doesn't resolve properly).

A quick easy fix for this is to simply add the user ID outside the embed as plain text so that moderators can copy/paste that text and research and infract the user easily. There are other proposed ideas such as buttons and such, but that can all be planned later, whereas this is a very quick easy change with a lot of immediate benefit.

I would like the user ID to be added for all mod-alerts, even non-pinging ones (such as for those sent to bot via DM)

![image](https://user-images.githubusercontent.com/75038675/153898580-9769aa5a-fbc2-444b-923a-77e19c6f3db8.png)

**Comment by HassanAbouelela** [comment]
I like. If you don’t get any further discussion by the end of the week, consider it approved.

**Comment by TizzySaurus** [comment]
There was some discussion on this internally, and we've decided that for now we'll take the approach mentioned in the OP.

Once the filters rewrite has been implemented, we'll most likely change this in favour of a button which sends a new ephemeral message consisting of only the user id (making it easier to copy since you're not also copying the Moderator's ping).

**Comment by TizzySaurus** [comment]
@minalike would you like to implement wht's in the OP yourself? If not I'm happy to do so.

**Comment by onerandomusername** [comment]
>  but this will probably be a temporary solution 

will you be making an issue to track the permanent solution?

**Comment by minalike** [comment]
At the moment I think we shouldn't, as it's too far out. I'd rather we wait til we have new filter system merged and running.
