### ISSUE TITLE
Limit users interaction on mod embeds

### ISSUE THREAD

**Issue by Nipa-Code** [python-discord/bot#2104]
When someone from moderation team uses ``!help sm`` non staff member or user who did not send the command is able to interact with buttons. I think it should be limited to not allow users interaction on mod help embed if they are not the author. 
The paginator wont show up when non staff member uses the `!help sm` command but I think it would make sense that if moderator runs the command in some general channel, the interactions would be limited to author of message.

Link to message: https://discordapp.com/channels/267624335836053506/267624335836053506/947082166020501524
<img width="409" alt="image" src="https://user-images.githubusercontent.com/60810623/155845114-32b193d8-a53d-4c3a-8642-9d5a355393d5.png">

**Comment by an-dyy** [comment]
Hey, I'd like to implement this feature.

**Comment by ToxicKidz** [comment]
Sounds good, I've assigned you now.
