### ISSUE TITLE
Create a greetings.yml file

### ISSUE THREAD

**Issue by ragr07** [python-discord/bot#2106]
### Hello!
I would like to create a yml-file with greetings for new visitors on this repository. I have already used this action in my own projects.

**Comment by ragr07** [comment]
Do you can help me?

**Comment by wookie184** [comment]
We used to have something similar https://github.com/python-discord/bot/pull/1028#issuecomment-653923366, not sure what happened to it though.

If we add this I think it should be to give useful information. It does add some clutter to the issue/PR so i'm not sure it's worth it.

On sir-lancebot we use issue/pr templates instead https://github.com/python-discord/sir-lancebot/tree/main/.github.

**Comment by ragr07** [comment]
Okay.

**Comment by wookie184** [comment]
I don't see much of a reason for adding this at the moment, so i'll close this
