### ISSUE TITLE
Update CONTRIBUTING.md with commit quality expectations

### ISSUE THREAD

**Issue by heavysaturn** [python-discord/bot#211]
We should update `CONTRIBUTING.md` with a section that explains our expectations towards commit message quality and what should constitute a commit.

For example:
- You should write a good commit message for every commit. Not just `maybe it'll work now`.
- You should not be committing linting fixes because the build failed, just use a git hook and lint on pre-commit! There is info on how to do this in the wiki. Refer to it.
- You should not commit tiny changes at a high frequency. Commit a meaningful amount of work at a time.

This needs to be done on all three of our major projects - site, bot, and seasonalbot.

See https://github.com/python-discord/site/issues/157 and https://github.com/python-discord/seasonalbot/issues/84

**Comment by GhostofGoes** [comment]
@sco1 I looked at pre-commit a few weeks back, but couldn't find many configuration examples. Do you know of any?

**Comment by heavysaturn** [comment]
yeah we've discussed this, I remember hearing about that framework on Talk Python To Me. It definitely looks interesting.

**Comment by sco1** [comment]
@GhostofGoes I haven't yet. It's been on my list of things to investigate for my personal & work stuff but I haven't gotten to it yet.

**Comment by sco1** [comment]
Another nice addition would be which logging level to use for various things. Our current guidance (from March 2018) is the following:

> TRACE: Use this for tracing every step of a complex process. That way we can see which step of the process failed. Err on the side of verbose.
INFO: Something completely ordinary happened. Like a cog loading during startup.
DEBUG: Someone is interacting with the application, and the application is behaving as expected.
WARNING: Someone is interacting with the application in an unexpected way or the application is responding in an unexpected way, but without causing an error.
ERROR: An error that affects the specific part that is being interacted with
CRITICAL: An error that affects the whole application.
