### ISSUE TITLE
Autoformat messages that contain code but aren't using MD

### ISSUE THREAD

**Issue by IsaiahSama** [python-discord/bot#2116]
When a user sends a message which contains python code but isn't marked down, instead of simply letting them know about it, will also format the message, and send it as an embed, deleting the user's original message.
May also send the same "Now you know for next time" message to the user.

**Comment by MaskDuck** [comment]
i would like to implement this when this is approved.

**Comment by MarkKoz** [comment]
This has been suggested several times over the years. It has been rejected (e.g. [here](https://discord.com/channels/267624335836053506/429409067623251969/637733500031729672)) on the grounds of defeating the educational purpose of the message — to teach users how to format code themselves; automatic formatting removes incentive to learn.

I'm still in agreement with this view. I can't speak for others, but based on history, it is likely other developers and staff also agree. However, you're still welcome to make a convincing argument for the opposite.

**Comment by MaskDuck** [comment]
@MarkKoz 
imo maybe create an embed and also ping them to tell them about formatting code spaces

**Comment by IsaiahSama** [comment]
The main idea with it was that 3/4 of the time, the actual message from the bot alerting the user about their lack of backticks, is often larger than the code snippet itself.
And then 1/2 the time, the user either ignores it, or says that they don't understand.
Then there's also when a user asks a question, and like 3 or 4 people respond with !code.

The purpose of this was to avoid all of that by actually showing their code as an example as to how it is to be formatted.

I understand that that may also promote a bit of laziness with some people that may just continue to send unformatted code, and rely on the bot, but for the most part, I also hope that it will improve the flow of the chat as well. Instead of spending about 4 or so minutes explaining the difference between a backtick and a quote, despite the bot already specifying it.

As for the editing of messages, that can be done by use of either a command or by having them delete the original via the trashcan reaction and resend their updated snippet.

**Comment by IsaiahSama** [comment]
I like your idea wookie, using the ephemeral message and I do think that solution is a lot cleaner when compared to what I was suggesting.
I haven't been bothering with dpy after it went down, and I haven't looked back at it since it came back up, so I was not entirely aware of how the new system will work, so it slipped my mind that it was a thing. But yes.

As for the disadvantages that you listed:
- People not reading the message may be rectified if the bot also mentions them to get their attention. But sometimes when people want to be stubborn they will be stubborn regardless 😅
- About the message being deleted, it can either be that they have the option of deleting it when they press the "show me my code", or the message could be auto-deleted, but then resent as an ephemeral message. Most average users may not immediately notice the difference 🤫. Both of these should be able to mitigate this problem. Perhaps, but my earlier statement of stubbornness still stands.
- In terms of storage of the code, I personally don't see any reason why the code may have to be resent, and as such, no reason why it should be stored. But if for some reason it is decided that it will be better if they have access to it, then something simple like an SQLite database should suffice.

These are my thoughts on the issue. Let  me know what you think

**Comment by GDWR** [comment]
For me, I agree with Mark's initial point about "defeating the educational purpose of the message". However, I do see another use case for this.

When I am writing code on my phone in help channels (because I am sometimes an "on-the-go" helper), it is really annoying to find backticks and to format code correctly in comparison to PC. If this were an opt-in feature, much like our [help DM notifications](https://github.com/python-discord/bot/blob/main/bot/exts/help_channels/_cog.py#L596), it would improve my experience with writing code on the phone and maybe on PC too. So when opted in, the bot checks your messages for obvious Python code, deletes and then reposts them as a code block (maybe even formatted with [black](https://github.com/psf/black)).

This proposed functionality would have to be opt-in, because getting your messages deleted would be surprising to newcomers.

**Comment by wookie184** [comment]
I think the point griff made about getting your messages deleted is a dealbreaker, so I don't think this is something we'll want to do at the moment.

I don't think the opt-in proposal is great as it would not be clear who the message was initially from (we could add it in the message, but i'd imagine it would still confuse some people, and breaks some other things like being able to mention the user). I don't really see this going anywhere so i'll close this issue.
