### ISSUE TITLE
Help channel that should have gone dormant stayed occupied

### ISSUE THREAD

**Issue by minalike** [python-discord/bot#2124]
On Mar 31, 2022 around 03:00 UTC there were a couple help channels that should have closed due to lack of activity but stayed open for several hours until they were closed by a staff member.

#help-dumpling: https://discord.com/channels/267624335836053506/696348850981699624/958989575437578250

#help-mushroom: https://discord.com/channels/267624335836053506/776184670794678303/958920620459036692

As of now I'm not sure what may have caused this. Sometimes users will "bump" their help channels (and delete the "bump" messages) in order to keep their channel active, but that was not the case for the above 2 channels. 

I tried checking Grafana service logs today but I think March 31 logs might be too old to view. 

We had an outage with Linode the day after on April 1 around 19:00 UTC but I don't believe it's related.

**Comment by MarkKoz** [comment]
Without logs it is unfortunately very challenging to debug this. Even with the existing logging, I think it would be difficult. It would require much more detail, most of which is under trace logging. Maybe we should increase the log level?

**Comment by ChrisLovering** [comment]
Yes, it's already configurable in dev, via the use of our trace loggers and debug flag.

What Mark was referring to was the logging level in production, since we pin it to info only. We could bump this down to debug/trace but it would mean a *lot* of logs would come in for the bot, and log rotation would be far quicker than before.

This is a hard one to debug since we need the extra logging, but also don't know what causes it to happen, so don't know when to enable the extra logging.

**Comment by minalike** [comment]
On [Apr 10, 2022 03:01:49](https://discord.com/channels/267624335836053506/696432394974265374/962910317543817266) an occupied help channel was made available again without it going dormant. As a result the original claimant never got the Help Cooldown role removed. 


Service logs:
```
2022-04-11 03:31:47 | bot.exts.help_channels._cog | INFO | Moving #help-lollipop (696432394974265374) to the In Use category.
2022-04-11 03:13:20 | bot.exts.help_channels._cog | INFO | Making #help-lollipop (696432394974265374) available.
2022-04-11 03:01:49 | bot.exts.help_channels._cog | INFO | Moving #help-lollipop (696432394974265374) to the In Use category.
2022-04-11 02:39:16 | bot.exts.help_channels._cog | INFO | Making #help-lollipop (696432394974265374) available.
2022-04-11 01:51:53 | bot.exts.help_channels._cog | INFO | Moving #help-lollipop (696432394974265374) to the Dormant category.
```

Adding as a comment to this issue because it's help channel-related; not necessarily because these 2 incidents are related.

**Comment by ChrisLovering** [comment]
Closing this as we have not seen an occurrence of this with the new system.
