### ISSUE TITLE
Make wording for !or-gotcha more explicit

### ISSUE THREAD

**Issue by mustafaquraish** [python-discord/bot#2128]
Currently the `or-gotcha` tag embed looks like:

<img width="517" alt="image" src="https://user-images.githubusercontent.com/9910883/163674268-061fd6c6-9906-4246-ad64-13c51343ae55.png">

While the embed is helpful, the first thing the eye is drawn to the first code block, and not the actual text around it. It's very tempting to just look at just the code examples, so I think adding a comment to the first code block to the following might make it clear at a glance that it's meant to be the _incorrect_ way to do it:

```py
# Incorrect
if favorite_fruit == 'grapefruit' or 'lemon':
    print("That's a weird favorite fruit to have.")
```

Should be a very trivial change, I'm happy to make a PR if you all agree it's worth it

**Comment by wookie184** [comment]
Sounds like a fine change to me, feel free to open a PR!
