### ISSUE TITLE
Allow `0s` as a valid argument for `!slowmode` command

### ISSUE THREAD

**Issue by minalike** [python-discord/bot#2132]
The proper way to remove a slowmode from a channel is to use `!slowmode reset [channel]`

However, many moderators often go for `!slowmode [channel] 0s`

It would be nice to allow this, as it's quite intuitive for most mods. 

The current error:
<img width="398" alt="image" src="https://user-images.githubusercontent.com/75038675/163726420-d4c821ba-0206-4a29-81db-2f2ae98da640.png">

**Comment by novialriptide** [comment]
Can I work on this issue?

**Comment by D0rs4n** [comment]
> Can I work on this issue?

Absolutely, Assigned!
Good luck! If you have any questions, don't hesitate to ask!
