### ISSUE TITLE
Eval with iOS quotes

### ISSUE THREAD

**Issue by LukeHankey** [python-discord/bot#2147]
It’s currently not possible to use the eval command when you write some code that includes quote marks. A small but beneficial enhancement would be to automatically convert these special quote types to ones the bot will parse so iOS users can use the eval commands for quick use.

**Comment by minalike** [comment]
I use iOS and the quote marks I get are " and '

Do you get something different?

**Comment by LukeHankey** [comment]
> I use iOS and the quote marks I get are " and '
> 
> Do you get something different?

“ and ‘ for me. Idk whether they are the same or not.

See [here](https://discord.com/channels/267624335836053506/267659945086812160/966998968083042384)

**Comment by LukeHankey** [comment]
For anyone else, you can turn off smart punctuation in the settings > general > keyboard

Ty Mina for the suggestion.
