### ISSUE TITLE
Show full date & timestamp in  `!modpings off` message

### ISSUE THREAD

**Issue by minalike** [python-discord/bot#2168]
Currently when using `!modpings off` the bot responds with an embed showing when the Moderators role will be re-applied. 

Example:
![image](https://user-images.githubusercontent.com/75038675/166488185-73309615-ddcb-4f0d-89b0-db32b64950d4.png)

This information is shown in the footer. However, we could take advantage of Discord's formatted localized timestamps and show full date and time in the body of the embed, similar to our `!reminder` command

![image](https://user-images.githubusercontent.com/75038675/166499278-c205fc5a-73d6-4d36-8f06-76238ab64cb6.png)

The simplicity of the current embed is nice, and if we want to emulate that we could skip the title and footer and only do a description. 

If approved anyone can be assigned to this issue.

**Comment by mbaruh** [comment]
It doesn't really have to stay an embed either, the rest of the messages in the cog aren't. We switched to an embed so that we could utilize the localized time in the footer before timestamps were a thing.

**Comment by minalike** [comment]
True! Let's just make the bot's response say: 

✅ Moderators role has been removed until <timestamp>.

**Comment by TizzySaurus** [comment]
As per discussion with @minalike in dev-contrib, I'll be working on this :)
