### ISSUE TITLE
Show new timestamp in confirmation embed after editing reminder duration

### ISSUE THREAD

**Issue by vivekashok1221** [python-discord/bot#2172]
<img width="370" alt="image" src="https://user-images.githubusercontent.com/37447267/167283377-73a2f2c6-72c7-4726-98c1-b440cd6e1f9e.png">

When setting a reminder with the `!remind` command, the embed contains a timestamp which states the time at which the reminder will arrive. Same should be done for the embed you get when you edit a reminder, i.e, a timestamp of the newly edited time should be added to the embed.

Anyone can implement.

**Comment by wookie184** [comment]
> If possible I would like to work on this!

I've assigned you. Check out our [contributing page](https://www.pythondiscord.com/pages/guides/pydis-guides/contributing/bot/) if you haven't already, and feel free to ask if you have any questions!

**Comment by DMFriends** [comment]
@mtkumar123 Could you post this in the #dev-contrib channel on the Discord server? Questions like that are better to post in that channel than on GitHub.

**Comment by TizzySaurus** [comment]
Hey @mtkumar123, were you able to resolve this, and are you still looking to work on the issue?

**Comment by HassanAbouelela** [comment]
Hey I'll reassign this issue to Tizzy now. Feel free to reach out if you want to discuss this, or pick up another issue from the tracker.
