### ISSUE TITLE
Replacing !subscribe with reaction roles

### ISSUE THREAD

**Issue by shenanigansd** [python-discord/bot#2216]
Several popular bots have the capabilities for "reaction roles", where a bot will send a message in a channel, with one reaction per role, and when a user reacts with a reaction, they will be assigned the specified role.

Here a couple of examples:
https://dyno.gg/docs/en/modules/reactionroles
https://mee6.xyz/tutorials/allow-users-to-self-assign-roles-in-discord-with-the-mee6-bot-reaction-roles

Replacing `!subscribe` with reaction roles will greatly reduce the amount of spam and confusion when lots of users are trying to subscribe to a new event.

**Comment by DMFriends** [comment]
This is something I remember suggesting before but it was denied I'm pretty sure but I can't remember the reason...

**Comment by ChrisLovering** [comment]
A benefit of using a persistent view/slash command is that we can send the user an ephemeral message telling them whether the role was assigned or removed.

**Comment by wookie184** [comment]
Implemented by https://github.com/python-discord/bot/pull/2341
