### ISSUE TITLE
!matchcase tag

### ISSUE THREAD

**Issue by HRLO77** [python-discord/bot#2221]
As of python 3.10 I believe, matchcase is supported in python. It would make sense to create a tag command for it outlining the purpose and an example on how to use it.

**Comment by MarkKoz** [comment]
I think the feature is fairly complex; it has 7 different patterns, for example. What aspects do you expect to be covered that would still fit within the scope of a tag?

**Comment by HRLO77** [comment]
It should have a short summary such as 
"Match case is a 3.10+ feature that allows you to execute statements based on the result of an operation"
`resp_code = requests.get('https://pythondiscord.com')
match int(str(resp_code)[0]): # get the first letter of the response
    case 2: # resp_code started with 2
        print('Request was successful!')
    case 3: # resp_code started with 3
        print('You are being redirected.')
    case 4: # resp_code started with 4
        print('Client error.')
    case 5: # resp_code started with 5
        print('Server error.')`
    case _: # this is for any other possible case
        print('Unknown response code.')

**Comment by HRLO77** [comment]
Listing all of the patterns is not practical for a tag, basic usage of match seems more reasonable.

**Comment by HRLO77** [comment]
To include all of that in a single, quick tag would be difficult. Maybe it's best to leave it be.
