### ISSUE TITLE
Add support for embedding images/videos in tag responses

### ISSUE THREAD

**Issue by sid-maddy** [python-discord/bot#2222]
Closes https://github.com/python-discord/meta/issues/187

**Comment by sid-maddy** [comment]
Unfortunately, it seems like [Discord doesn't support sending videos in embeds](https://github.com/discord/discord-api-docs/issues/1253#issuecomment-564794170).
Trying to call the `Embed.set_image` with a video URL results in the embed just showing a loading animation.

Since the point of this feature was to add support for images _and_ videos, we'll have to go with the other approach of adding a new command instead.

Would it be a good idea to rework the tags command to send a media link instead of an embed for tags with, say, `media: true` in their metadata?

**Comment by HassanAbouelela** [comment]
We discussed some of the general plans and attribution for this feature [on discord](https://discord.com/channels/267624335836053506/635950537262759947/997889192866627664), and I think we have a decent idea. Issue is approved.
