### ISSUE TITLE
Make `users` argument of purge command required

### ISSUE THREAD

**Issue by vivekashok1221** [python-discord/bot#2238]
When `user` argument is not provided to the `!purge` command, the greedy convertor returns an empty list. This results in the bot deleting messages of ALL users in the last 10 minutes.
Some kind of a check should be added to prevent this from happening.
Also applicable to the `!clean users` command.

**Comment by vivekashok1221** [comment]
This issue may or may not be inspired by real life events.

**Comment by HassanAbouelela** [comment]
Is this not intentional behavior? Sometimes you want to clean up a channel, especially when it goes off the rails.

**Comment by vivekashok1221** [comment]
You can't specify a single channel when using the purge command. Only users and age of the messages to be purged.

**Comment by wookie184** [comment]
I don't think this is possible to do with a custom Converter, so we should just check that the list of users isn't empty in the function. Maybe we could suggest the user might want `!clean` instead in the error response. 

The command is defined here: https://github.com/python-discord/bot/blob/2a825b234e0f23a901bb78343b1ff36ce85eaa5d/bot/exts/moderation/clean.py#L627-L636
