### ISSUE TITLE
Modify bot's automute messages to indicate that moderators role has already been pinged

### ISSUE THREAD

**Issue by minalike** [python-discord/bot#2247]
Currently, automutes by the bot ping the Moderators role in a mod-alerts channel, and also send a public message indicating the user has been muted:
![image](https://user-images.githubusercontent.com/75038675/183454102-9adc0a26-2020-4020-a1b1-9ad5827e2636.png)

Well-meaning bystanders then ping moderators to have them unmuted, which is usually redundant. (If the user wasn't already unmuted, then that means either a moderator decided to leave the mute, extend it, or, there is no moderator online to action the incident anyways.)

We would like to change the message to more clearly indicate that the moderators have already been alerted. Something to the effect of: "Moderators have already been alerted and will review."

**Comment by mbaruh** [comment]
sgtm

**Comment by SinfulPhantom** [comment]
So are you saying there should be that additional message appended to the original message?

**Comment by mbaruh** [comment]
@SinfulPhantom yes
