### ISSUE TITLE
Automatically close help channel if the claim message is deleted

### ISSUE THREAD

**Issue by n0Oo0Oo0b** [python-discord/bot#2248]
If someone claims a help channel but then deletes the message that claimed the channel the help channel stays claimed but there isn't anything useful going on, the bot should detect when this happens and automatically make the channel dormant.

The message(embed) saying that the channel is dormant can also be changed to tell users to edit the message instead if the message was deleted to fix a typo or otherwise change it instead.

This should only happen within a short period of time after claiming a channel (20-30 seconds or so) because anything more than that would be pretty unnecessary anyway. Also, it shouldn't happen if the channel has other messages after it in case something is already happening in the channel.

**Comment by ChrisLovering** [comment]
This already exists, it's currently set to 5 minutes.

So if no one else sends a message inside a channel where the opening message was deleted, the channel will close after 5 minutes.

It's set to 5 minutes as there is a valid case where someone deletes their original message to re-word it, so closing it while they are rewording their question would be very annoying.

**Comment by wookie184** [comment]
One thing we could do is reduce the time (maybe to 2 minutes), and send a warning message that the channel will close in that time unless a message is sent. 

That could also encourage people helping to leave the channel empty (rather than saying "Hello?" or something), so it closes sooner.

I'm not sure it's a big enough issue to be worth doing this though.

**Comment by shtlrs** [comment]
I think this one is irrelevant now since our help system has been fully migrated to the forum one.

**Comment by ChrisLovering** [comment]
Help posts with deleted messages and no further messages from the opener are closed faster than normal posts.

You can see the logic [here](https://github.com/python-discord/bot/blob/main/bot/exts/help_channels/_channel.py#L172-L182).
