### ISSUE TITLE
Invite filter doesn't work for Group DMs

### ISSUE THREAD

**Issue by sco1** [python-discord/bot#225]
Because the invite filter [looks at guild information](https://github.com/python-discord/bot/blob/730ff3b22e323062e6ce1d46e8d3adf56ba52150/bot/cogs/filtering.py#L218) (for whitelisting purposes), it will silently fail if the invite is for a group DM because they don't have a Guild attribute.

The filter should be tweaked to accommodate this.

**Comment by sco1** [comment]
Closed in #226

**Comment by jos-b** [comment]
nice
