### ISSUE TITLE
Hello, I'm having a bot of trouble

### ISSUE THREAD

**Issue by lazurs1** [python-discord/bot#2262]
Hello, This code returns a message.content = 0/empty
Can you point me in the right direction?

client = discord.Client(intents=discord.Intents.default())

@client.event
async def on_ready():
    print('We have a logged as {0.user}'.format(client))

quote='test response'

@client.event
async def on_message(message):
    print(message)
    print(len(message.content))
    print('Content' + str(message.content))
    print(message.author)
    if message.author == client.user:
        print('Author Message')
        return
    elif message.content == "Hi":
        await message.channel.send("Hello!")

client.run(TOKEN)

Output:
We have a logged as dbot1#7222
<Message id=1010718511494090893 channel=<TextChannel id=1010691873091899446 name='general' position=0 nsfw=False news=False category_id=1010691873091899444> type=<MessageType.default: 0> author=<Member id=466621014336602112 name='lazurs01' discriminator='2046' bot=False nick=None guild=<Guild id=1010691873091899442 name='DetroitCode' shard_id=0 chunked=False member_count=3>> flags=<MessageFlags value=0>>
0
Content
lazurs01#2046

**Comment by shenanigansd** [comment]
Hey! Seems this is just a general Python Discord bots question, not related to the actual repository.

We do answer questions about Discord bots in Python, just not here. Check out the #discord-bots channel our [discord server](https://discord.gg/python) to get help.
