### ISSUE TITLE
Remove italics from !help text

### ISSUE THREAD

**Issue by shenanigansd** [python-discord/bot#2263]
Currently, the text output of the help command is entirely italicized.
Removing these italics would make the text easier to read.

Raised by @dawnofmidnight in #dev-contrib [here](https://discord.com/channels/267624335836053506/635950537262759947/1010613903283191829)
@Ibrahim2750mi has requested to be assigned if approved in #dev-contrib [here](https://discord.com/channels/267624335836053506/635950537262759947/1010881523102261389)

Here is screenshot showing the current output with the italics
![image](https://user-images.githubusercontent.com/54628770/185793588-1b6a3eca-4e5c-49da-ba01-d57e4af1e448.png)

**Comment by wookie184** [comment]
I think I agree, the italics don't seem necessary. It's at least worth having a PR so we can try out removing it.

**Comment by Ibrahim2750mi** [comment]
Will soon open a pr for it.
