### ISSUE TITLE
Add triggering filter to alert embed title

### ISSUE THREAD

**Issue by Etzeitet** [python-discord/bot#2266]
The current alert embed for a triggered filter puts the filter type in the main body, where it's easily missed - especially for those of us who have higher-res screens.

Having the triggering filter in the embed's title will give instant access to that information at a glance. Below image is a mockup of what I propose:

<img width="513" alt="image" src="https://user-images.githubusercontent.com/5340057/187549902-3868ea2b-fbb7-4190-96fc-84afc930ac98.png">

I am not precious about the exact formatting of the title, as long as the information is in there.

**Comment by minalike** [comment]
I am in favor.

**Comment by shtlrs** [comment]
All of our filters are prefixed with `filter` right ? 

If you want, I could send a PR for this @Etzeitet.

As for implementation we could split based on the underscore then build the title and the type of filter from there.
OR, we could add a key that can hold a descriptive name for each filter.
What do you think ?
