### ISSUE TITLE
Convert voice verification to a button

### ISSUE THREAD

**Issue by mbaruh** [python-discord/bot#2271]
We designed the verification system before we had components and interactions. Discord has changed quite a bit since, and we should revisit the current setup. 

## Current State
Users have to run a specific command, and if they ran it correctly they'll get a response. The invocation and response disappear after a bit, and if they didn't run it correctly their message disappears almost immediately.

## Proposal
This setup can be converted to a button that is added to the explanation message in #voice-verification. The button can say something like "I understand, verify me!". The response (whether they passed or not) can be sent as an ephemeral message, and the send messages permission can be removed in that channel.

This has the following benefits:
- No chance to mistype the command (there's no command), and the UI is clearer overall.
- No need for the bot to listen to and delete spam messages.
- No need to delete the response message, since it's visible only to the invoker.

**Comment by MrHemlock** [comment]
100% has my blessing.  That's a great idea

**Comment by VirdanTheBurden** [comment]
I can give this a go, if nobody minds.

**Comment by VirdanTheBurden** [comment]
Out of stall now; should be done sooner than later.

**Comment by MrHemlock** [comment]
Here's what I'm planning for the implementation:

The bot's rules message will hold the verify button.  It will respond upon clicking with three potential outcomes:

1. The user is already verified, it will tell them that they're good to go via ephemeral message.
2. The user is not verified but meets the requirements, the role will be granted and they will be informed via an ephemeral message.
3. The user is not verified and does not meet the requirements.  The user will be told what conditions they do not meet via an ephemeral message.

Along with this change, I'll also be changing the newcomer to voice chat ping/dm into an ephemeral message.  


Open to any thoughts, comments, or improvements on this idea.
