### ISSUE TITLE
`!pypi` command TypeError on packages without description

### ISSUE THREAD

**Issue by ionite34** [python-discord/bot#2278]
As shown, type error if a PyPI package is inquired and has no short description to render

![img](https://cdn.ionite.io/img/gNmjeT.jpg)

May be related to https://github.com/python-discord/bot/blob/main/bot/exts/info/pypi.py#L57

**Comment by shenanigansd** [comment]
Looking at https://pypi.org/pypi/base2048/json, the `summary` attribute is `null`.

We're passing this `summary` attribute straight into `discord.py`'s `escape_markdown`, which is passing into `re.sub`, which can only take `str|bytes` -
https://github.com/python-discord/bot/blob/4dc9a952a71d03959e302434e8e9941e9bd3b577/bot/exts/info/pypi.py#L57

PyPi doesn't require the summary - we don't want to fail every time sometime forgets to add one...
Can we just fix this by converting the `None` to an empty string first? For example -
```py
if info["summary"] is None:
  info["summary"] = ""
```

**Comment by TizzySaurus** [comment]
> Can we just fix this by converting the None to an empty string before attempting to escape it? For example -
>
>```python
>if info["summary"] is None:
>  info["summary"] = ""
>```
I personally would go for 
```python
summary = escape_markdown(info["summary"] or "")
```
but ofc both work.
