### ISSUE TITLE
Async function remove_cog not awaited

### ISSUE THREAD

**Issue by shtlrs** [python-discord/bot#2281]
If you take a look at this line
https://github.com/python-discord/bot/blob/71fbd5aa7ef8fdf3547dbae845cf7e6b9bc08277/bot/exts/moderation/watchchannels/_watchchannel.py#L131

You'll see that the remove_cog async func isn't awaited.

**Comment by shtlrs** [comment]
Can someone assign this to me? I'll include it in the PR for the other bug ino working on.

**Comment by mbaruh** [comment]
Looks like a remnant of the move to discord.py 2.0.

I'm not sure awaiting it works. iirc raising an error will cause it to unload. Worth checking.

**Comment by shtlrs** [comment]
@mbaruh do you mean the fact that it isn't awaited will throw and thus would still unload the cog?

I noticed it upon unloading a cog actually, and I thought it was ugly to have that exception in our logs.

BTW, couldn't this have been avoided if we used something like mypy? Why don't we actually have that in our project?
