### ISSUE TITLE
Zen command not using integer line when followed by words.

### ISSUE THREAD

**Issue by ionite34** [python-discord/bot#2294]
<img width="550" alt="image" src="https://user-images.githubusercontent.com/13956642/196326926-b0cbe815-a670-4585-8573-6c6c97bc3bc2.png">

## Proposed fix
Parse string for potential integer before using word search.

**Comment by shtlrs** [comment]
![image](https://user-images.githubusercontent.com/48383734/196664861-1c080030-22f4-429f-b505-d3b457ae823b.png)

Doesn't that mean that there's a dev branch for this bug ? 
Also, looking at the name, I thought it made sense, unless there's something I'm missing

**Comment by ChrisLovering** [comment]
Interesting, I don't see that.
![image](https://user-images.githubusercontent.com/9753350/196665520-5d624919-e65a-4c3b-aa50-8a49ec7e1701.png)
@minalike could you self assign if you're working on this

**Comment by minalike** [comment]
Hm? No I am not working on this issue.

**Comment by ChrisLovering** [comment]
Alright cool, your creation of this branch made it seem like you were https://github.com/python-discord/bot/tree/zen-args-fix

**Comment by shtlrs** [comment]
@ChrisLovering I can take this if you'll assign it to me
