### ISSUE TITLE
Nominations: Take into account activity when reviewing

### ISSUE THREAD

**Issue by wookie184** [python-discord/bot#2302]
We should check that a user has been active in the past 7 days before choosing them to review.

This will require an endpoint on site that queries metricity for a user's message count.

I don't think we need to worry about clearing out users that stop being active completely in this issue, it might be better to update the `!tp list` command to display activity information somehow so they can be cleared out every now and again.

**Comment by mbaruh** [comment]
Something else that can be done automatically is unnominate anyone who hasn't been active in the past ~3 months (with a suitable message in chat).
