### ISSUE TITLE
Tag fuzzy matching and aliasing

### ISSUE THREAD

**Issue by sco1** [python-discord/bot#231]
As discussed briefly in #118 and at least a few times on the server in the recent past, I believe tags could stand to gain from fuzzy matching and possibly from aliasing as well.

In short:

- Fuzzy Matching
  - Allows for solving of the plurals problem, like `codeblock` vs `codeblocks` and `f-string` vs `f-strings`
  - Potentially solves things like `fstring` vs `f-string`
  - Embed should indicate to the user that a fuzzy match was used (e.g. `"Did you mean ... ?"`)

- Aliasing (See #187)
  - Requires adding a field to the backend tag model
  - Allows for things that fuzzy matching may not realistically be able to hit, like `ytdl` vs `youtube-dl`

**Comment by jos-b** [comment]
I believe that the previous idea was supporting plurals of all tags automatically and then having aliases in place to handle cases that weren't just about the plurals. Fuzzy matching could help but I don't know if it essential.

**Comment by jchristgit** [comment]
With the site migration to PostgreSQL, I can look into using `pg_trgm` which supports a very nice way to search for similar items using the `%` operator ("x is similar to y"):
```sql
postgres=# SELECT 'f-strings' % 'f-string';
 ?column? 
----------
 t
(1 row)

postgres=# SELECT 'ask' % 'f-strings';
 ?column? 
----------
 f
(1 row)
```

The threshold is configurable, but this should be able to return accurate results.
