### ISSUE TITLE
Update d.py intents tag to clarify that privileged intents require activation in d.py 2.0

### ISSUE THREAD

**Issue by shenanigansd** [python-discord/bot#2313]
Raise by `Roie#0089` here: <https://discord.com/channels/267624335836053506/267624335836053506/1035515307818754129>

As of Discord.py 2.0, privileged intents are now required to be explicitly activated.
We would like to add something in the tag body to help clarify this - for example -
> Starting from version 2.0, all intents must now be passed into the bot constructor as a required keyword argument intents and privileged intents must also be explicitly enabled on the developer portal.

**Comment by shtlrs** [comment]
Discord.py itself has good [docs](https://discordpy.readthedocs.io/en/stable/intents.html#privileged-intents) about this.

I think that we could use those to clarify how they should be activated from portal, then we could add a snippet detailing how to pass them to the bot upon instantiation, while making it explicit that's its only needed for version 2.x

**Comment by HassanAbouelela** [comment]
Don't focus too much on differentiating between v1 and v2, for all intents and purposes just consider v1 defunct and focus on tailoring the tag content for v2. This is especially important with such a long tag.

**Comment by thegamecracks** [comment]
@TizzySaurus Only partially. The current tag does explain that privileged intents have to be enabled in the dev portal before it can be used in code. However, due to v2.0's breaking API changes, the tag should also say that intents must be defined in code regardless of whether those privileged intents are needed.
