### ISSUE TITLE
Safeguards against accidentally banning staff members

### ISSUE THREAD

**Issue by ionite34** [python-discord/bot#2314]
To avoid any more situations like these:
<img width="501" alt="image" src="https://user-images.githubusercontent.com/13956642/198676115-4e6d6747-95df-46f2-8908-a579304a0f51.png">

Propose to add:

>### :warning:  This action will apply **ban** to a staff member, `@user` (User Name #8405). To confirm, rerun the command with `--force`

**Comment by vivekashok1221** [comment]
We could have the confirmation as a button instead of a flag.

**Comment by CaedenPH** [comment]
What about instead of rerunning the command with `--force`, which may be abused, a confirmation dialog that you click to confirm?

**Comment by ChrisLovering** [comment]
I like the idea of the button. if the user has one of `constants.STAFF_PARTNERS_COMMUNITY_ROLES` reply to the user with a warning message and a confirmation button.

**Comment by Robin5605** [comment]
I would be willing to take this up

**Comment by ChrisLovering** [comment]
> I would be willing to take this up

Sounds good, feel free to self assign

**Comment by Robin5605** [comment]
yoinked

**Comment by ChrisLovering** [comment]
FYI, https://bot-core.pythondiscord.com/main/output/botcore.utils.interactions.html#botcore.utils.interactions.ViewWithUserAndRoleCheck might be a good view to subclass as it comes with some nice checks out of the box

**Comment by Robin5605** [comment]
Maybe. In this case the command itself (`!ban`) will only run if the use is authorized. After that it's only a simple matter of checking if the interaction user is the same as the one who triggered the command

**Comment by ChrisLovering** [comment]
Yea, this just adds a nice helper function to remove the button from the message on timeout
