### ISSUE TITLE
Logging forum post deletions

### ISSUE THREAD

**Issue by lxnn** [python-discord/bot#2336]
A couple of changes are required to [modlog.py](https://github.com/python-discord/bot/blob/23f4592710853f8cb814fce2bba2f1871a508d68/bot/exts/moderation/modlog.py) for forum post deletions to be logged properly.

First of all, thread deletion doesn't seem to be getting logged at all. This may simply be a matter of using `on_raw_thread_delete` rather than `on_thread_delete`.

Second, for moderation purposes, it would be useful to log the content of the post itself. The ID of the initial message of a forum thread is the same as the ID of the thread itself, so we may be able to acquire the content of this message from the message cache.

I'll start putting together a PR with these changes.

**Comment by lxnn** [comment]
I didn't get around to making the PR for this. I did look into it, but I couldn't actually figure out what was causing thread deletions not to be logged. I think my assumption about replacing `on_thread_delete` with `on_raw_thread_delete` was wrong. This probably need someone who understands `discord.py` and the bot better to look at it.

**Comment by wookie184** [comment]
Haven't looked into this fully but one potential issue could be that we use `is_channel_ignored`
https://github.com/python-discord/bot/blob/23f4592710853f8cb814fce2bba2f1871a508d68/bot/exts/moderation/modlog.py#L832-L837

which will ignore the post if the post isn't in the cache (`get_channel` would return `None`)
https://github.com/python-discord/bot/blob/23f4592710853f8cb814fce2bba2f1871a508d68/bot/exts/moderation/modlog.py#L546-L550

This wouldn't really explain why normal thread deletions *are* logged correctly, but it could be that discord.py's behaviour of keeping stuff in the cache is different for forum posts? It doesn't seem great to rely on the post being in the cache after being deleted anyway though.

**Comment by ChrisLovering** [comment]
If it's just been deleted then the cache is the only thing we can rely on, since fetching will just 404. Not sure the best approach to fixing this, outside of keeping our own cache or looking to improve upstream.

**Comment by wookie184** [comment]
We have the thread in the `on_thread_delete` function, but we're trying to get it from the cache again in the `is_channel_ignored` function. If we passed the thread directly to `is_channel_ignored` rather than the ID we could avoid this.

That is, unless the `on_thread_delete` function isn't being called at all, but I can't see why this would be the case without some discord.py bug.

**Comment by ChrisLovering** [comment]
Ahh right, that makes sense. An easy thing to check opened https://github.com/python-discord/bot/pull/2375 for this

**Comment by wookie184** [comment]
seems that worked, nice (tested with normal channel threads + forum channel posts)
![image](https://user-images.githubusercontent.com/22353562/212402605-a093415f-ea27-4ebd-b093-f54708342a25.png)
