### ISSUE TITLE
Terminate nominations when members are not found

### ISSUE THREAD

**Issue by shtlrs** [python-discord/bot#2343]
This is a continuation of #2323

Soon enough, we will be tracking nominations that have been sitting for more than 2 weeks.

When tracking these nominations, we can run into the case where a particular member is no longer part of our server, which leads to asking the question: what needs to happen then ?

I think that closing the nomination & archiving the thread (if it exists) would do the job, as there's no need to keep it open.

We could potentially track if there's an open issue for it in Github as well & close it.

**Comment by wookie184** [comment]
We'll remove inactive members from the talent pool in https://github.com/python-discord/bot/issues/2302#issuecomment-1287221089. That, and ensuring we don't post vote threads for users not on the server should be enough IMO. This also avoids a user from being unnominated if they accidently left and rejoined or something similar.

**Comment by shtlrs** [comment]
I see, then i guess your other PR should take care of all of that since it'll be activity based, right?

**Comment by wookie184** [comment]
Yeah, if a user isn't on the server then they can't send any messages of course, so it should have a similar effect.

For things like the github issue / active vote I think it's better for it to be handled manually if a user leaves so it doesn't just "disappear". We could send a message or something to let people know, although I don't think it's worth the added complexity for something so rare.

I'll close this, although thanks for thinking about this and making the issue!
