### ISSUE TITLE
Mark threads as solved in help forum

### ISSUE THREAD

**Issue by shtlrs** [python-discord/bot#2348]
I think having a thread tagged with Solved will give better Overview on whether the issue has been actually solved or not.

This allows potential users who are searching for a question to know whether they'll potentially find the answer or not.

Executing !solved (and *maybe* !close) will do just that.

**Comment by shtlrs** [comment]
I can take this if approved

**Comment by wookie184** [comment]
I'm not sure this is worth doing. It would be hard to get people to consistently use the tag, and I don't think the forum search feature is good enough to make searching for a question that easy anyway.

**Comment by shtlrs** [comment]
Yeah after a second thought, it's not.
I'll close this
