### ISSUE TITLE
Infraction notifications are sent before the infraction is carried out.

### ISSUE THREAD

**Issue by jos-b** [python-discord/bot#235]
As of now we send the notification to users about their infraction before we actually get Discord to add the muted role or kick them. This is fine as long as the site and the infraction are actually carried out. If they are not carried out then the user gets the notification about the infraction but then it is not logged to the site or it is not applied on Discord.

https://github.com/python-discord/bot/blob/master/bot/cogs/moderation.py#L111-L115

The behaviour of bans must remain the same, because when we ban a user the bot cannot message them anymore (no common servers), but maybe for the other infraction types we can move the notification to the users to the end of the process, after we are sure that the site knows about the infraction and the actions have executed successfully.

EDIT: As stated by Hemlock below, kicks would have to be the same as the bot would not have a mutual guild in the event that they were kicked from the server, mutes & warns are fine to send notifications after actions.

**Comment by LordHemlock** [comment]
The behavior would still need to be the same for kicks as well.  Anything that removes them from the server would need to have a "message first boot second" thing going on.
