### ISSUE TITLE
Add confirmation step when deleting or modifying someone else's reminders

### ISSUE THREAD

**Issue by minalike** [python-discord/bot#2353]
Once upon a time, an admin who shall not be named [modified](https://discord.com/channels/267624335836053506/635950537262759947/957013405494038558) a reminder which was not her own. Apparently admins can do this! 

Let's put in a button confirmation prompt when messing with reminders that don't belong to the command invoker, so that future admins can be prevented from making such heinous mistakes!

**Comment by Canttuchdiz** [comment]
Can I implement this feature?

**Comment by wookie184** [comment]
Sure! I've assigned you.

**Comment by minalike** [comment]
Hi there @Canttuchdiz, are you still interested in writing this feature?

**Comment by wookie184** [comment]
Putting this up for grabs again.

Also marking as a good first issue, not completely trivial, but if anyone knows some discord.py they could probably give this a go. The edit function is here: https://github.com/python-discord/bot/blob/113b4e33c04dfbc9e827046c3cf4992f9ef4bed5/bot/exts/utils/reminders.py#L453

**Comment by n0Oo0Oo0b** [comment]
I would like to implement this.

**Comment by shtlrs** [comment]
@n0Oo0Oo0b Sure thing, it's yours !
