### ISSUE TITLE
Update discord.py dependancy ref to allow IDs in role related checks.

### ISSUE THREAD

**Issue by scragly** [python-discord/bot#236]
The discord.py library has had a few new commits, but the primary benefit is that they added support for IDs in `has_role` and `has_any_roles`, which allows us to remove the custom decorator `with_role`.

While none of the other changes should be breaking for anything we use, it'll still be good to test things to make sure before we update the Pipfile's ref for this dependency.

[Click here to see the full diff between the dependent rewrite version and the up to date one.](https://github.com/Rapptz/discord.py/compare/860d6a9ace8248dfeec18b8b159e7b757d9f56bb...rewrite)

The noticeable changes include:
- [Add channel category cooldown buckets](https://github.com/Rapptz/discord.py/commit/5a585ebf20fdf346fdd46af35df11cfc3dd85665)
- [Support IDs in role related checks](https://github.com/Rapptz/discord.py/commit/016963500b6f19b5c8978f135fce9dd264872007)
- [Add support for referencing](https://github.com/Rapptz/discord.py/commit/1ac432d9f053812a1caab8330d14d4a9ba526289) and [editing Guild default notification levels](https://github.com/Rapptz/discord.py/commit/8b18fa307b5e4a9acc6c057b7489c4d11de359b4)
- [Support discordapp.com invites](https://github.com/Rapptz/discord.py/commit/1f2602d11edf932d7b331e31a1ecbb9dd5c91c8e)
- [Spoiler attachment support](https://github.com/Rapptz/discord.py/commit/93d576a65bce7a8ea13dc87331ef5c7c224e9770)
- [Add support for mobile indicators and per-client statuses](https://github.com/Rapptz/discord.py/commit/c7396dc8acb1270ad6fbdb0607ca2d03c7ddb3a7)
- [Support editing explicit_content_filter](https://github.com/Rapptz/discord.py/commit/648e62031df69222b08c284d03b0491f55b8e24a)
- [Rate limit logs are WARN level instead of INFO](https://github.com/Rapptz/discord.py/commit/dec14faea90b57d34245b17e58438ee91990764c)

**Comment by sco1** [comment]
Related: #217

**Comment by MarkKoz** [comment]
Given #217 was closed, is there anything else to do on this issue?

**Comment by lemonsaurus** [comment]
it was closed and then reopened again.

**Comment by MarkKoz** [comment]
Oh, I did not scroll down enough. Anyway, I've actually been using `cog_check` to check for roles and that uses the check function we have instead of the decorator. Can these decorators from d.py be used as functions inside `cog_check`?

**Comment by MarkKoz** [comment]
Also, if there's nothing else from here then we can close this and focus on #217.

**Comment by kosayoda** [comment]
I think everything that's still relevant can go in #217.
