### ISSUE TITLE
`!in-place` tag

### ISSUE THREAD

**Issue by n0Oo0Oo0b** [python-discord/bot#2360]
A fairly common problem asked in the help channels involves in-place operations like `list.sort()` which return `None`. A simple tag could be used to explain the difference in behaviour between in-place and out-of-place functions (with examples such as `sorted()` vs `list.sort()`) and how common issues involving them can be fixed.

**Comment by wookie184** [comment]
Sounds like a good idea, I don't think we have a tag like this currently.

**Comment by brodycritchlow** [comment]
Im interested in implementing this

**Comment by wookie184** [comment]
> Im interested in implementing this

👍 I've assigned you
