### ISSUE TITLE
Remove 3.10 as an option to run as.

### ISSUE THREAD

**Issue by brodycritchlow** [python-discord/bot#2363]
Leaving 3.10 as an execution option is just wasting space, as 3.10 has lost all of its libraries and packages:

> 3.10 offers functionally no difference from 3.11 and will probably be removed eventually. [Source](https://discord.com/channels/267624335836053506/635950537262759947/1050697858413756456)

Seems as if this was already discussed in: #2324

**Comment by wookie184** [comment]
This was done somewhere, currently we only support 3.12
