### ISSUE TITLE
discord.ext

### ISSUE THREAD

**Issue by Goddessesunveiled** [python-discord/bot#2397]
import openai
import discord
from discord.ext import commands

# Initialize OpenAI API key
openai.api_key = "YOUR_OPENAI_API_KEY"

# Initialize Discord client
client = commands.Bot(command_prefix='!')

# Define a command for the bot to generate an image
@client.command()
async def generate_image(ctx, *, prompt: str):
    # Use OpenAI's GPT-3 API to generate an image based on the prompt
    response = openai.Image.create(
        prompt=prompt,
        n=1,
        size="1024x1024"
    )

    # Send the generated image to the Discord channel
    await ctx.send(response.url)

# Run the bot
client.run("YOUR_DISCORD_BOT_TOKEN")

**Comment by wookie184** [comment]
Issues are for reporting problems or requesting features or changes to the bot.
