### ISSUE TITLE
Add a auto-reply for people that ask for help/if someone knows xyz

### ISSUE THREAD

**Issue by e1pupper** [python-discord/bot#2399]
I see a lot of people join the server and go to #python-general and not #how-to-get-help and instead of just asking the question they ask people if they are familiar with xyz module or can anyone help me?

I propose we add a auto-reply to redirect the person to either ask the question directly or to read the #how-to-get-help. (ghost ping them inside #how-to-get-help) then delete there original message on general and the bot message.

**Comment by wookie184** [comment]
It was mentioned in `#community-meta` that it seems very difficult to detect these cases. Also, other suggestions involving deleting people's messages have been rejected since it's quite confusing and means the person will lose their message content.

**Comment by wookie184** [comment]
Closing as I don't think this is feasible or something we really want.
