### ISSUE TITLE
Reminder details in confirmation message.

### ISSUE THREAD

**Issue by scragly** [python-discord/bot#241]
The reminder command currently only replies with `Your reminder has been created successfully!`. 

This can be improved by providing the actual reminder contents in the confirmation and the datetime / humanized timedelta the reminder will be due to ensure the intended duration was processed. 

For the message sent once the reminder is due, a jump url to the original command message so we can jump back into context of the conversation when the reminder was made would be good to add. (Previously had mixed up wording for this section).

This would do well as a first issue if it's not gotten to in short time.

**Comment by jos-b** [comment]
Maybe it would be more beneficial to include the jump to command URL in the actual reminder so when a user gets a reminder they can jump back to when they set it.

**Comment by scragly** [comment]
Sorry, yes I definitely got some wires crossed while writing the Issue. My intention was to have the jump_url not in the initial reply but the eventual notice. Thanks @jchristgit for correcting me.

Regarding the timestamp, it's best to have some of confirmation on it due to the confusion that can occur. You're assuming that everyone knows exactly 100% for sure what formatting they're meant to be using, when the reality is that people can easily assume things or mistaken things. The recent change with `m` vs `M` is a good example of this. It would be best for the user to be aware immediately that it was processed as 30 months if their intention was to be only 30 minutes.

**Comment by LordHemlock** [comment]
I'm confused as to what we're actually wanting to implement here.  Currently the reminder itself gives the reason why you set it, correct?  What were we needing the link URL for?  To look at the context for when it was originally made?

And regarding the timestamp thing, are we wanting to just update the !help for it to make things clearer?  Or a link to the standard formatting for such things?

**Comment by sco1** [comment]
Yes, a jumplink to the message where the reminder was set for additional context.

For the timestamp, here's what's currently given when you set a reminder:
![image](https://user-images.githubusercontent.com/5323929/50850943-60422a00-1349-11e9-96fa-bf00cbc050e0.png)
Which doesn't give us any indication of when the reminder is going to come. So something like "it will arrive in 3 hours" would be helpful to confirm that the correct duration was input.

**Comment by Akarys42** [comment]
I've added the humanized timedelta and the reminder content, but I have no idea how I should had the jump url. Should it be a link inside the embed content ?

**Comment by scragly** [comment]
Yep, it's cleanest to add it as an inline link within the embed.
