### ISSUE TITLE
software abused....

### ISSUE THREAD

**Issue by ForkInABlender** [python-discord/bot#2416]
Wilder and Kutiekatj9 have been caught abusing the software already to victimize people and talk smack about the people they just victimized in a pattern. They've done this before to anyone they assume to be retarded and if discredited enough people will just disbelieve said retarded individual.

**Comment by mbaruh** [comment]
@ForkInABlender this repository is for discussing the development of the bot. If you have an issue with other users you're welcome to write to Modmail.
