### ISSUE TITLE
Better error message for `!eval` when using input

### ISSUE THREAD

**Issue by Ibrahim2750mi** [python-discord/bot#2420]
Currently snekbox returns this error message
![2023-02-28_17-01](https://user-images.githubusercontent.com/74553450/221841648-2a8eaa6c-7b1f-4ecf-8c06-51b232aa292a.png)
Which is not descriptive enough to show that we don't explicitly support `input()` and it can be just replaced by a string.

#2255
> I think that's a separate issue that could be opened on this repo though. Even if we did support input users would get an EOFError if they forgot to supply it, so improving that response would make sense anyway.

**Comment by wookie184** [comment]
I think the nicest way would probably be to leave the error message as is and insert a message above/below it with information, something along the lines of:

![Screenshot_2023-02-28-22-10-26-435-edit_com.discord.jpg](https://user-images.githubusercontent.com/22353562/221993339-8c760e9f-2fcc-4933-96ac-e465e757b44a.jpg)

**Comment by Ibrahim2750mi** [comment]
Sure, I also think the same. Assign the issue to me and I will make a quick pr.
