### ISSUE TITLE
No such file: main.py

### ISSUE THREAD

**Issue by topogamer** [python-discord/bot#2435]
when I try to start the bot it says it can't find the main.py file

**Comment by Ibrahim2750mi** [comment]
Are you following this [guide](https://www.pythondiscord.com/pages/guides/pydis-guides/contributing/bot/)?

If yes then, you have to start the bot like this.
```python
$ docker-compose up web -d
$ poetry run task start
```

If not then you should try following the guide from the start.

**Comment by shtlrs** [comment]
Hi @topogamer 👋 

Thanks for opening up the issue.

Runtime errors like these and issues that might come up when you're setting up the bot can happen, and we'de rather discuss them in a channel called [dev-contrib](https://discord.com/channels/267624335836053506/635950537262759947) on our Discord server ( [Join Us](https://discord.gg/python) if you haven't already :p)

We usually open issues for bugs, new feature proposals, enhacements etc.

I'll close this for now, but please
1. Make sure you follow the guide Ibrahim has recommended as it should have the necessary steps to get bot up & running.
2. Feel free to take it to the channel if you still have issues with it & we'll gladly help you :D
