### ISSUE TITLE
HTTP client session is not properly closed

### ISSUE THREAD

**Issue by jchristgit** [python-discord/bot#244]
```py
bot/__main__.py:89: RuntimeWarning: coroutine 'ClientSession.close' was never awaited
  bot.http_session.close()  # Close the aiohttp session when the bot finishes running
```

`aiohttp` will warn in `__del__` if the session was not closed, we need to find a way to clean this up properly.

**Comment by MarkKoz** [comment]
On which branch is this bug?

**Comment by jchristgit** [comment]
On Django for sure. I have not tested with master.

**Comment by MarkKoz** [comment]
All right, we don't need to worry about master.

**Comment by scragly** [comment]
Closing in favour of #468 which encompasses the fix for this.
