### ISSUE TITLE
Notify user on invite filter

### ISSUE THREAD

**Issue by sco1** [python-discord/bot#245]
Currently, when the bot detects an invite link it's just deleted without notifying the user, often leading to them trying multiple times until they either realize it's being deleted intentionally or a staff member steps in. 

How about adjusting the cog so it notifies the user, either in-channel or via a DM, that the invite is being removed per Rule 10? 

For invites DMed to the bot we could either use this same notification, or just defer it to staff action.

**Comment by heavysaturn** [comment]
love this idea. let's do it!
