### ISSUE TITLE
Disable slash commands in DMs

### ISSUE THREAD

**Issue by mbaruh** [python-discord/bot#2450]
So far we've had https://github.com/python-discord/bot/blob/bf8f8f4c1f9522a942c88ca69a2d48427d2bbc28/bot/exts/backend/security.py#L21
Which makes sure that prefix commands are run in the server and not in DMs.

This doesn't seem to work for slash commands so we're getting bugs for various features which don't work in DMs.

We should either have a check which handles slash commands, or find some other way to deal with it.

**Comment by shtlrs** [comment]
Can't we use [interaction_check](https://discordpy.readthedocs.io/en/stable/interactions/api.html?highlight=interaction_check#discord.app_commands.CommandTree.interaction_check)  on `bot.tree` ?

I'll test & confirm this

**Comment by mbaruh** [comment]
That might work yeah. It would be great if we could keep all of these checks in one place. I wouldn't mind dismantling the Security cog if adding the new check there doesn't work.

**Comment by shtlrs** [comment]
I suggest to do this differently & move the issue to `bot_core`

This could be as simple as:

```diff
    async def _sync_app_commands(self) -> None:
        """Sync global & guild specific application commands after extensions are loaded."""
        await self._extension_loading_task
        await self.tree.sync()
        await self.tree.sync(guild=discord.Object(self.guild_id))
+      for command in self.tree.walk_commands():
+           command.guild_only = True
```

**Comment by Ibrahim2750mi** [comment]
We could inherit the `CommandTree` and overwrite its `interaction_check` method
and pass it for the keyword `tree_cls` in https://github.com/python-discord/bot/blob/main/bot/__main__.py#L56
