### ISSUE TITLE
Make rules a slash command

### ISSUE THREAD

**Issue by shtlrs** [python-discord/bot#2460]
We have recently added keyword support for the rules command which enables people to invoke it more easily without having to remember what each number refers to.

This can be further simplified thanks to the `autocomplete` feature that comes with slash commands, and would then help people find the rule they intend in a more easier fashion.

**Comment by Ibrahim2750mi** [comment]
@shtlrs If this gets approved can I please implement it?

**Comment by ionite34** [comment]
Can slash commands suggest arbitrary text based on an integer and actually show the rule details in-line?

Also since the rules command is frequently used conversationally (with other messages appended afterwards) I'm not sure if this might hurt usability.

**Comment by shtlrs** [comment]
> Also since the rules command is frequently used conversationally (with other messages appended afterwards) I'm not sure if this might hurt usability.

Why would it hurt usability ?

**Comment by ionite34** [comment]
> > Also since the rules command is frequently used conversationally (with other messages appended afterwards) I'm not sure if this might hurt usability.
> 
> Why would it hurt usability ?

![Screenshot_20230310-070623.png](https://user-images.githubusercontent.com/13956642/224312428-8707f9a2-ba9b-4959-960b-c4efcb344938.png)

![Screenshot_20230310-070634.png](https://user-images.githubusercontent.com/13956642/224312436-53d4e30d-577d-4b76-a022-65608cc5fc0b.png)

most use cases of rules either include a message after the command, and reply to some other user. Current state of slash commands seem to support neither. Making the rules an auto complete field will also make it easy to mistype the command on mobile where you need to click the field before it will register the auto complete, or else you just send the raw command in chat without interactions.

**Comment by shtlrs** [comment]
Humm, i'll have a look at the replying feature & see if there's a way to support that.
As for the message after the rule, i personally have never used it like that, and when I do see it being used in that fashion, i tend to jump directly at the rule embed.

But you're right, it's a different scenario, and might not be what we want.

**Comment by wookie184** [comment]
I don't think there's a good workaround for the replying and including extra text issues, which is a dealbreaker for me.

**Comment by shtlrs** [comment]
Yes, i agree.

I'll close this for now
