### ISSUE TITLE
Keep jump link in infraction edit logs

### ISSUE THREAD

**Issue by minalike** [python-discord/bot#2495]
![image](https://user-images.githubusercontent.com/75038675/228259214-7de09123-4ef1-45a1-b1c6-ee71683cc178.png)

Currently when an infraction edit is logged the jump URL field is not mentioned.

I think it would be helpful to have it mentioned even on edit logs. I frequently check #mod-log after appending or editing an infraction and find myself looking for the jump link.

**Comment by vivekashok1221** [comment]
SInce I added jump URL field to mod log embeds can I assign myself to this issue?
