### ISSUE TITLE
Add infraction context to BB log header

### ISSUE THREAD

**Issue by sco1** [python-discord/bot#254]
Now that logs have been cleaned up with a nice header embed and a watch note has been made mandatory (see: #201), there's been a good suggestion that some context on the infraction be added to this header so folks don't have to search through infractions and/or chat history to figure out why the user is being watched.

While we can assume that all watches will have an associated note infraction going forward, some fallback will need to be in place for those added prior to this PR.

**Comment by SebastiaanZ** [comment]
@heavysaturn suggested in chat that it may fit nicely into the footer of the header embed. I think I agree with that. 

We may want to think about the text length, as in, if the provided reason is very long, will it harm the readability of BB if it gets repeated all the time? Currently, I don't think it's an issue, as headers are posted on a relatively infrequent basis, but if more users are added to the watch list and they start alternating their conversation, the headers may start to take up a lot of space. Although, maybe it won't really matter. We can always revert it if we really don't like it later.
