### ISSUE TITLE
Have !rules (and other alternatives of rules) return the specific rule if a number is provided

### ISSUE THREAD

**Issue by tagptroll1** [python-discord/bot#257]
`!rules 3` returns a shortwritten version of the rule.  
For even more flavor let it handle "slicing" of rules like `3,5,7` to print the rule titles of rule 3, 5 and 7, or a syntax like `3-6` to get rule 3 to and including 6

**Comment by Refisio** [comment]
I'll take this issue up.

**Comment by GhostofGoes** [comment]
For some pizazz, make it handle Python list slicing syntax as well, e.g. `!rules [2:5]` for rules 2, 3, and 4.

**Comment by heavysaturn** [comment]
I don't like the slicing idea, which has been brought up multiple times. "There should be one - -  and preferably only one - - obvious way to do it" , pretty sure I read that somewhere.

**Comment by Refisio** [comment]
Hi, I've already added support for non-indexed slicing.
`rules 2-6`
Or
`rules 2:6`
These should both work when I am finished.

**Comment by heavysaturn** [comment]
those both seem fine. it's when you start putting square brackets around it that I start killing people left and right in response.
