### ISSUE TITLE
Add reopen button to closed help

### ISSUE THREAD

**Issue by brodycritchlow** [python-discord/bot#2587]
**Suggestion:** Add a reopen button to the closed thread embed for the thread owner to easily reopen their thread. This will address the annoyance of having to create a new thread when wanting to reopen a closed one. 

[Here's](https://discord.com/channels/267624335836053506/267624335836053506/1105532533732552784) an example of the annoyance caused by the current system.

**Comment by ChrisLovering** [comment]
We discussed this when designing the new help system, and did not come up with a solution that works with the restrictions within Discord, and doesn't open it up for abuse.

For this specific request, it wouldn't work as you can't interact with buttons when posts are locked.

**Comment by brodycritchlow** [comment]
> We discussed this when designing the new help system, and did not come up with a solution that works with the restrictions within Discord, and doesn't open it up for abuse.
> 
> For this specific request, it wouldn't work as you can't interact with buttons when posts are locked.

Ah, thats very sad. Welp thank you, didn't know that detail about discords interactions.
