### ISSUE TITLE
!pypi should include publish date in response

### ISSUE THREAD

**Issue by import-pandas-as-numpy** [python-discord/bot#2613]
In many cases, users have been utilizing out of date packages. This would make the !pypi tag substantially more useful in visually parsing whether or not a package could be out of date for the current version of Python. 

https://github.com/python-discord/bot/blob/main/bot/exts/info/pypi.py#L48-L67

Example snippet: 

```py
ver = info["version"]
releasedate = info["release"][ver]["0"]["upload_time"]
embed.description += f"\n Release Date {releasedate}"
```

Should fall within the `if 200` response block. May want to consider prettying up the timestamp a bit to just the date portion.

**Comment by Robin5605** [comment]
I would be willing to work on this if approved.

**Comment by shtlrs** [comment]
This would be a nice addition, thanks for proposing it.

However, aren't we always getting the latest version for each package? So how would it be out of date?

The pypi command takes no arguments and is agnostic to python/package versions.

I'm not saying this shouldn't be added as it would only be a nice addition, but more like to make sure I understand correctly.

**Comment by import-pandas-as-numpy** [comment]
We always obtain the latest (non-dev release) version of a package with the !pypi command as I understand it now. Supplying a date in the embed serves to simply reconcile this date against our current understanding of what is considered 'outdated'.

A recent example of when this was relevant: An individual was seeking assistance with a "Jarvis" package on PyPI, specifically implementing it within their own code. !pypi was invoked to retrieve information regarding the package, and further links had to be followed to discern whether or not the package's latest version was out of date or not. In this case, the package had not been updated in the last decade. Since this information is available on the JSON endpoint, it seems fairly straightforward to me to suggest the inclusion of it in the embed response itself. 

Realistically, it only really serves to save a couple of clicks/following a URL in this case, but I can see it being a reasonable metadata inclusion just for quick referencing.

**Comment by shtlrs** [comment]
I wasn't opposing you as I think it is indeed reasonable to include.

@Robin5605 Want me to assign you?

**Comment by Robin5605** [comment]
Sure, thanks.
