### ISSUE TITLE
Remove seasonality of roles from subscribe button

### ISSUE THREAD

**Issue by minalike** [python-discord/bot#2630]
As per @janine9vn it's fine for us to remove the season lock on assigning the below roles:

- Advent of Code
- Lovefest
- Revival of Code

<img width="482" alt="image" src="https://github.com/python-discord/bot/assets/75038675/ff430426-cbb8-404c-97e5-6c8635c9d4a8">

This will mean people can subscribe to the above 3 roles all year round.

Approved by @ChrisLovering during an admin meeting.

I'm fine with anyone implementing this.

**Comment by ChrisLovering** [comment]
One question I have is whether we think that we'll want to lock roles like this at any point in the future?

If not, we could remove that code entirely, making it easier to maintain.

**Comment by wookie184** [comment]
Looks like this was done by https://github.com/python-discord/bot/pull/2650
