### ISSUE TITLE
Use new markdown features in messages

### ISSUE THREAD

**Issue by DownDev** [python-discord/bot#2646]
The bot should use new markdown features instead hard coded unordered lists for example:

![image](https://github.com/python-discord/bot/assets/52790953/e35fda3d-63df-4ea3-b23d-ea46a55b1f45)

uses `•` it can be replaced by `-` and markdown would format it same way

**Comment by DownDev** [comment]
Before: <img width="592" alt="image" src="https://github.com/python-discord/bot/assets/52790953/0bfe56af-d863-42be-a785-68a622d1e707">

After: 
<img width="597" alt="image" src="https://github.com/python-discord/bot/assets/52790953/8718907d-ed4b-4d18-b9b2-fd66f2a491c7">

**Comment by novialriptide** [comment]
This looks much nicer.

**Comment by HassanAbouelela** [comment]
I'm giving this issue a limited approval. Switching lists to markdown seems fine, however please comment here if you wish to change something else with examples as shown in previous comment.

**Comment by HassanAbouelela** [comment]
You've been assigned, feel free to reach out in the dev-contrib channel if you have any questions. Good luck!

**Comment by HassanAbouelela** [comment]
I'm aware, I'm asking for examples if they decide to change something else.
