### ISSUE TITLE
Rich Embed Filter False Positives

### ISSUE THREAD

**Issue by sco1** [python-discord/bot#270]
Looks like the rich embed filter (introduced in #259) can be triggered by embeds added by Discord:

![image](https://user-images.githubusercontent.com/5323929/51041399-d8962e80-1587-11e9-8b4b-9d86a284c8c4.png)

Due to this serious avenue for false positives I've disabled the filter until it can be investigated whether or not there's a way to discriminate between embeds sent by a self-botting user and those added by Discord.

**Comment by sco1** [comment]
If a general fix is identified, it probably also makes sense to also switch this to a `"watch"` rather than a "`filter`" to add a layer of moderator discretion before any further action is taken.

**Comment by SebastiaanZ** [comment]
I agree. 

I'm looking into a fix right now and I have some ideas. I've also realized that the double trigger prevention now relies on the message being deleted by the first filter run, so that needs a different approach as well.

Suggestions are welcome.

**Comment by jchristgit** [comment]
since the embeds from Discord are loaded in after the message it posted, they fire a separate message_update event. I think if we only look for embeds in message creation we should be able to ignore the built-in embeds.
