### ISSUE TITLE
Move PEP link to title in pep command

### ISSUE THREAD

**Issue by DownDev** [python-discord/bot#2722]
Im reffering to [this pep command](https://github.com/python-discord/bot/blob/main/bot/exts/info/pep.py#L140-L160)

Current look:
![image](https://github.com/python-discord/bot/assets/52790953/6b3b0c0f-a8f6-4890-bb0a-49782ab19b0a)

After change:
![image](https://github.com/python-discord/bot/assets/52790953/8243c490-eb10-4ede-8299-d0b66731f9c2)

I can work on this (not like i already did it)

**Comment by wookie184** [comment]
Sounds sensible, feel free to open a PR
