### ISSUE TITLE
`!src` command for tags results in 404.

### ISSUE THREAD

**Issue by brodycritchlow** [python-discord/bot#2770]
When doing the `!src` command on any tag, it results in the following image. I believe it is because we are missing another `bot` in the path? (`bot/bot/resources/tags/...` instead of `bot/resources/tags/...`)

![IMG_8657](https://github.com/python-discord/bot/assets/24994624/9a5f388f-81b9-4f0a-8951-27feace19b9f)

**Comment by Robin5605** [comment]
https://github.com/python-discord/bot/blob/main/bot/exts/info/source.py#L70-L72

I'm not sure what "in some cases" refers to here, but I think that removing that relative to should fix it
