### ISSUE TITLE
Review RMQ's log embeds

### ISSUE THREAD

**Issue by sco1** [python-discord/bot#279]
Now that we've separated out the mod event & user event logs, it's surfaced that RMQ is currently using the modlog channel for its own logging information:

https://github.com/python-discord/bot/blob/fc0d8fb1eff4d18c11da8340d8bd8f5941c4f196/bot/cogs/rmq.py#L109-L114

![image](https://user-images.githubusercontent.com/5323929/51292473-cf1e2380-19d8-11e9-9a8a-83ca5c88302f.png)
![image](https://user-images.githubusercontent.com/5323929/51292481-d6ddc800-19d8-11e9-95cb-1cc1bf870378.png)

Do we still want these here, or should they go into a different channel?

**Comment by GhostofGoes** [comment]
They should go in a separate channel, since they're related to the bot's health, not the server's.

**Comment by heavysaturn** [comment]
I don't think site deployment alerts have _ever_ worked.

**Comment by scragly** [comment]
I might have a squiz at this. See if I can get it working at moved to `#dev-logs`.

**Comment by sco1** [comment]
Closing this as RMQ is getting removed
