### ISSUE TITLE
Change snekbox to not use RMQ.

### ISSUE THREAD

**Issue by scragly** [python-discord/bot#281]
With the removal of RMQ, snekbox currently won't be able to receive public code evals for running and returning.

An alternate system needs to be put in place beforehand so we can safely and smoothly proceed with the RMQ removal.

**Comment by scragly** [comment]
PR #289 is actioning this.

**Comment by heavysaturn** [comment]
As mentioned in #289, let's do this in the `django` branch instead. We are preparing for feature freeze.

**Comment by MarkKoz** [comment]
Addressed by #372
