### ISSUE TITLE
Recognise `pyi` snippets as `py` snippets when sharing github/gitlab links

### ISSUE THREAD

**Issue by ad-chaos** [python-discord/bot#2843]
Useful when referencing stubs

**Comment by shtlrs** [comment]
Sounds like a good idea

This should be done in the [following function](https://github.com/python-discord/bot/blob/8a887beb4af62a24676bf2a0698f814d510222be/bot/exts/info/code_snippets.py#L173)

Let me know if you'd like to work on this and someone we'll assign you.

**Comment by ad-chaos** [comment]
I've made a PR :)
