### ISSUE TITLE
Django API: Nominations cog

### ISSUE THREAD

**Issue by jchristgit** [python-discord/bot#292]
The Django API now has a `/bot/nominations` endpoint that can be used to obtain nominated helpers, and basic bigbrother-like functionality is implemented. What's missing is support for updating existing nominations and proper unique validations.

**Comment by SebastiaanZ** [comment]
This looks very nice.

Just for my information, the other issue on the !nominate command for the current implementation, #290, is still open (and assigned to me). What's the consequence of this new implementation on that? Should I put in the time and effort of rewriting that one or is it better to wait for the Django rewrite to implement that?

**Comment by jchristgit** [comment]
Thanks
well the django implementation is now done. I really think it would be a better use of time to implement it on the Django branch, but it's up to you. Nomination reason is not implemented yet, implementing it in the bigbrother cog should be sufficient.
