### ISSUE TITLE
Improvements to the filters/watchlists

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/bot#293]
There are two improvements I'd like to make to the filter:

1. Filter slack invites analogous to Discord invites;
2. Tweak the rich embed filter to decrease the number of false positives

**Note on number 2:**
As it turns out, twitter isn't the only domain that gets specialized rich embeds with additional fields. While it doesn't seem to be a frequent problem, links to the Steam store also create rich embeds and will therefore trigger the embed watchlist. 

Since I don't think adding more and more exceptions to the filter is the way to go, I'm proposing an alternative implementation that should eliminate these kind of false positives: Check if the `Message.content` is empty, since empty messages should not trigger a rich embed. This will decrease/eliminate the number of false positives, but it also increases probability of false negatives. Still, I think it's worth a try and it's an easy fix.

**Comment by SebastiaanZ** [comment]
I can't remember the last time we've seen a slack invite being spammed in our server. Do we still want to add a specific filter for it?

**Comment by scragly** [comment]
There's no harm keeping it and I see no benefit in removing it.

**Comment by SebastiaanZ** [comment]
We don't have one, I believe.

**Comment by SebastiaanZ** [comment]
Okay, I'm going to close this for now, then.
