### ISSUE TITLE
Making the behavior of the red cross emoji consistent for all embed control interfaces

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/bot#297]
(As requested by @tagptroll1)

Some of our embeds use an emoji reactions interface to allow the user to interact with them. However, the behavior of one of the emojis, the red cross (:x:), is inconsistent across different type of embeds. In some cases (e.g., `!help`), the cross will have the bot delete the entire embed; in other cases (e.g., `!infr search`), the bot just deletes the reactions/interface, but leaves the embed visible.

It may be a good idea to synchronize the behavior of the red cross (:x:) so the user knows what to expect when clicking it. 

Potential solutions:
- Choose one for all (deleting the entire embed/just deleting the interface)
- Introduce alternative emoji for deletion (e.g., 🗑), keeping ❌ for removal of emoji reactions.

**Comment by gdude2002** [comment]
Trashcan emoji? **Sign me up!**

**Comment by MarkKoz** [comment]
#625 addressed this. it just didn't close properly due to a colon in the "closes #xxx".
