### ISSUE TITLE
Remove `rich_embed` filter

### ISSUE THREAD

**Issue by wookie184** [python-discord/bot#2977]
Discord seem to have fixed the bug that allowed user accounts to send embeds. Things that make me think this:
- I can't find a valid triggering of the filter in over 2 years
- This reddit post says they patched it https://www.reddit.com/r/Discord_selfbots/comments/sa0hc2/discord_embeds_patched/

This makes the rich embed filter no longer necessary. It's had quite a few bugs (mostly relating to twitter) and gives some false positives, so it would be helpful to have it removed.

**Comment by Hashed0719** [comment]
@wookie184 Just deleting the file will do it? I am unable to find any other reference to the filter.

**Comment by wookie184** [comment]
> @wookie184 Just deleting the file will do it? I am unable to find any other reference to the filter.

Yes, that should be all that's required. (the filter's settings will need to be deleted from the database before merging but I can do that using the `!filter delete` command)

**Comment by Hashed0719** [comment]
@wookie184 can you review the PR and delete the filter settings.
