### ISSUE TITLE
Add message link to replied message to the embeds sent in #message-change-log

### ISSUE THREAD

**Issue by vivekashok1221** [python-discord/bot#3077]
When a deleted message is logged in #message-change-log, also add a link to the message it was replying to. This will provide better context about the deleted message and is a trivial addition.
(originally proposed by @bj0key in #mod-tools)

This is what the embed looks like currently:
![image](https://github.com/python-discord/bot/assets/37447267/30c115b5-8195-47b0-985c-14d71a54b77d)

**Comment by typhonshambo** [comment]
Hi @vivekashok1221 i would like to work on this issue. I went through [modlog.py](https://github.com/typhonshambo/bot/blob/main/bot/exts/moderation/modlog.py) I guess we need a bit changes in it to make this work.

**Comment by vivekashok1221** [comment]
Hey @typhonshambo !
Our [contributing guideline](https://www.pythondiscord.com/pages/guides/pydis-guides/contributing/contributing-guidelines/) states that an issue should be approved and assigned by someone with the core-dev role before a pull request can be made (I'm not a core-dev btw)
For getting approval, drop a message in the [`#dev-contrib`](https://discord.com/channels/267624335836053506/635950537262759947) channel of our server.

**Comment by typhonshambo** [comment]
alright @vivekashok1221! ill message there thanks for your response
