### ISSUE TITLE
Use the new bulk ban feature

### ISSUE THREAD

**Issue by shtlrs** [python-discord/bot#3101]
Dpy has just released1 new guild.bulk_ban feature, i think this can be used in multiple places to replace usage of internal eval to iterate over users and ban one by one.

There are other places that further need to be identified like compban, since it allows you also to delete message history from the past n seconds.

**Comment by wookie184** [comment]
Changed the status to planning as it's not clear to me what needs to be done here. AFAIK there's nowhere in the bot where we ban in a loop, so there's nowhere obvious to replace.

For manual bans using int eval we could use it, but I'm not sure it'd be worth it for a few reasons:
- We've managed so far using the single ban api, even for very large raids.
- Normally we intentionally put in a sleep between bans to make them run slower so we can cancel if we made a mistake.
- It would be complicated to integrate this into our current system, as we still need to update the database (and handle any errors etc) per ban.

**Comment by shtlrs** [comment]
Ok, i'll close this then.
