### ISSUE TITLE
Some users seem to be ununwatchable by bigbrother.

### ISSUE THREAD

**Issue by tagptroll1** [python-discord/bot#315]
I attempted to unwatch someone I put up ages ago and got an error by the convert itself saying it couldn't find the User.  This is going to fill up our list of watched users with ununwatchable Users eventually.  

I propose a force unwatch command that just erases it as best as possible from storage.

**Comment by SebastiaanZ** [comment]
So, to me it looks like the UserConverter throws this error when the user cannot be found. Since I think we should keep the converter (it's very handy when users can be converted), I think we should add a `force_unwatch` subcommand that unwatches by ID. For the API, only an ID is needed, not a full user object.

**Comment by sco1** [comment]
I don't see why we need an entirely new command when we could just use a `Union` on the existing command.

**Comment by SebastiaanZ** [comment]
Oh, didn't know about that, sounds like the better option.

**Comment by sco1** [comment]
Docs: https://discordpy.readthedocs.io/en/rewrite/ext/commands/commands.html#typing-union

It goes left to right, so if the `Member` conversion fails it would convert to `str`/`int`

**Comment by SebastiaanZ** [comment]
Thanks for the link, I'll get a fix in.

**Comment by SebastiaanZ** [comment]
I have a fix waiting; I'll put a PR in once #307 is merged, since the code conflicts and that PR seem close to merging anyway (two positive reviews; but @heavysaturn needs to accept the changes they've requested).

**Comment by MarkKoz** [comment]
Fixed by #376
