### ISSUE TITLE
Have @Python add @everyone pings to checkpoint on a monthly basis

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/bot#320]
We've noticed that adding an @everyone message to the checkpoint channel every once in a while triggers a flood of users accepting our rules to gain the Developers role. Currently, those @everyone messages are added manually every once in a while, but it should be very straightforward to automate the process.

I would leave the current welcome message untouched, since it's a message from a human, but do it like this:

1. Remove previous @everyone message from @Python in that channel
2. Post message that says something like:
    - @everyone Please ping `@Admins` if you encounter any problems during the verification process.

I'm not sure what frequency is best for this. I wouldn't mind it once a month or even once a week. If people get bothered by it, they either accept and join for real or leave the server in some kind of self-purge (they've not accepted our rules anyway).

**Comment by kraktus** [comment]
What do you think is the best approach to set this command? Adding a 

```python
asyncio.sleep(xxx)
``` Does not seems a reliable to do so.

**Comment by MarkKoz** [comment]
Probably the [tasks](https://discordpy.readthedocs.io/en/latest/ext/tasks/index.html) extension.

**Comment by MarkKoz** [comment]
Though that may be problematic if the bot restarts... something could be stored in the database to keep track of the last time it was muted. I don't know how well that'd work with the tasks extension then. But we do have an API endpoint for storing miscellaneous settings in the database as key-value pairs (currently only used for DEFCON I believe).

**Comment by kraktus** [comment]
Yes, basically using the tasks extension raise the same problems than using a simple sleep. 'll look at the API endpoint.

**Comment by sco1** [comment]
I don't know if there's a reason why we can't just have a short-circuit check of the timestamp of the existing message in the channel, in theory there's only ever going to be one message in the channel so iterating over the channel history to get it isn't going to be expensive.

**Comment by lemonsaurus** [comment]
That's alright, I'll assign the issue to you.

Meanwhile, I would like to see the message include something about how they haven't verified yet.

**How about this:**
`@everyone` To verify that you have read our rules, please type `!accept`. Ping `@Admins` if you encounter any problems during the verification process.

For frequency, I think weekly sounds about right.

**Comment by MarkKoz** [comment]
I don't think they have any way of pinging admins, since they only have access to the verification channel and that channel removes all messages IIRC. They'd have to DM, wouldn't they?

**Comment by sco1** [comment]
We still get the notification, which alleviates the burdeon of the user searching for someone to DM, but it can be a pain to find it in the message logs.

It's probably beyond the scope of this PR, but providing a message for this ping in `#mod-logs` could be a useful enhancement.
