### ISSUE TITLE
No embed is send when a user gets "auto-unwatched" after a ban

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/bot#321]
When we ban a user that's currently being watched, they are automatically unwatched and Python is supposed to send an embed notifying us of that to the relevant watch channel. See [line 141 of the BigBrother cog](https://github.com/python-discord/bot/blob/master/bot/cogs/bigbrother.py#L141).

However, at the moment, no such embed is being send, although I do think the user is getting unwatched. We should probably look into that and fix it. While we're at it, we may want to consider adding an unwatch note to the user as well, just like we do when we unwatch someone manually.

At the moment, I don't know what's causing the bug. A quick review of the code revealed nothing obvious.

**Comment by sco1** [comment]
The last time the notification was sent to the log channel was on 06 January. I was messing around with the emoji constants around that time, but even before this it seems like the behavior was inconsistent. There is at least one instance where the user was banned from within the log channel without the feedback message.

From a quick glance, it seems like the last time this was working consistently was back in October.

**Comment by SebastiaanZ** [comment]
As @jchristgit mentioned on server, there's already a new implementation for BigBrother in the Django-rewrite. It also includes an [on_member_ban listener](https://github.com/python-discord/bot/blob/django/bot/cogs/bigbrother.py#L60), but it may not suffer from the same bug.

I'll keep this issue open so we'll remember to check it post-django-rewrite, but it may just go away with the move.

**Comment by sco1** [comment]
Unless I'm missing it, it looks like this functionality was removed with the watchchannel rewrite.

When this gets added back in, I'd like to propose that a user is only unwatched for permanent bans & keeps their watch in place if they're tempbanned.

**Comment by MarkKoz** [comment]
What would be sent now and to where? The unwatch command currently only sends a simple message confirming the command succeeded.

**Comment by sco1** [comment]
The previous behavior was something along the lines of “this user has been I watched because they were banned” in the watch channel. I think it’s fine to keep it simple and just start here. Generally this would happen around their related messages so it maintains context.
