### ISSUE TITLE
Watchlist Tokens & Watchlist Words merge and bug

### ISSUE THREAD

**Issue by scragly** [python-discord/bot#322]
Tokens and Words watchlist filters really should be just be combined I think. The name of `watch_tokens` being shown in mod alerts makes one think of bot tokens, not a character/word list. If there's any particular reason why it was done like this in the beginning though, feel free to let us know.

There's also a bug where if the `retarded` expression gets triggered but it matches one of it's exceptions such as "sorry for all the retarded questions", it'll return `False` right there and then, failing to process any other expressions after it. So technically "what's with the retarded question you dumb cunt" may not trigger the filter since `(re+)tar+(d+|t+)(ed)? questions?` is an exception and `cunts*` comes after it in the list of expressions to be processed.

This can be resolved by replacing `return False` with `continue`:
```diff
                    # stuff like "sorry for all the retarded questions"
                    elif re.search(RETARDED_QUESTIONS_RE, text, re.IGNORECASE):
-                       return False
+                       continue
```

As a side note, this is going to make for an interesting github history check if someone looks it over in the future.

**Comment by heavysaturn** [comment]
re tokens and words, I copied it off Rowboat, basically. But we could just use words and manually stick word boundary signifiers in the expressions I guess.

**Comment by fiskenslakt** [comment]
Now that we filter for all usages of the r-word, can we close this issue? Or is this bug still alive?

**Comment by lemonsaurus** [comment]
the second part of the bug is probably fixed now, yes, but the first point about how we shouldn't have tokens and words at all but just make it one thing is still very much relevant.

**Comment by MarkKoz** [comment]
How about leaving the regex lists separate in the config but combining the filters in the code? Would keep the convenience of not requiring manual word boundaries.
