### ISSUE TITLE
Tweaking the attachment filter for better relevance/accuracy.

### ISSUE THREAD

**Issue by scragly** [python-discord/bot#323]
With mobile, you're able to send up to 10 images in one message. This feature often ends up triggering the filter even at lower attachment counts due to it counting as lots of attachments in a small amount of time. 

Often we're finding that we're unmuting people for this because they weren't intentionally spamming, only adding resources relevant to the question they want help on. Since it's not being super relevant in these cases, it's probably better to adjust the attachment cap to 10, and adding special handling for questionable formats, especially `exe` files so they trigger it regardless of time or qty.

**Comment by sco1** [comment]
Due to the number of false positives popping up for this, this issue is exempt from the feature freeze and can be worked on.

**Comment by fiskenslakt** [comment]
This issue has come up again, and should probably be set to 10. Looks like the threshold is currrently a measly 3, set here:

https://github.com/python-discord/bot/blob/63bfe37bb2c3d05bc9e40589988952a705fb7e2e/config-default.yml#L282-L285
