### ISSUE TITLE
Nominate and BB watch allows the bot to be watched, causing loop.

### ISSUE THREAD

**Issue by scragly** [python-discord/bot#324]
Nominate and BB watch allows Python, the bot, to have it's messages sent to the respective watch channels, causing a loop of all it's messages to be sent continuously to the watch channel over and over again.

Just needs to check it's not self (or maybe any bot) and deny.

**Comment by SebastiaanZ** [comment]
I can add this to the WatchChannel rewrite (#317) or we can implement it as a quick fix in the mean time (after the feature freeze). I don't think it's that critical, but it should be fixed.

**Comment by MarkKoz** [comment]
Fixed by #376
