### ISSUE TITLE
Repeating the reason in the confirmation message for infraction commands is redundant

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#325]
When an infraction command is invoked, the bot replies with a message confirming success of the command (with the 👌). An infraction's reason is repeated in this message, but I find that to be redundant, especially when the confirmation is in the same channel as the one in which the command was sent. 

I bring this up because it stems from reasons being long. For short reasons, I think it's OK. The reason could either get truncated and have an ellipses appended, or it could just be entirely removed from the confirmation.

**Comment by sco1** [comment]
I don't think I'd miss it if it went away.

**Comment by heavysaturn** [comment]
This seems like a no-brainer, we should just implement it. but it'll have to wait until after the feature freeze.
