### ISSUE TITLE
Raffle Cog

### ISSUE THREAD

**Issue by sco1** [python-discord/bot#326]
As our community grows, so to do the opportunities for our sponsors, partners, rockstars, and other members of the Python community to give away cool stuff.

This cog (and channel) would provide a method for users to enter a raffle, provide staff with a method to randomly choose the winner(s), and notify the folks who have won.

Related Site Issue: https://github.com/python-discord/site/issues/189

**Comment by RohanJnr** [comment]
ill work on this

**Comment by sco1** [comment]
This is not approved

**Comment by RohanJnr** [comment]
okay,can you let me know when i can work on this? cuz im really confused with the stuff happening around 😅

**Comment by RohanJnr** [comment]
can i work on this now?

**Comment by Den4200** [comment]
It's been a while, and we don't want these raffles anymore.
