### ISSUE TITLE
Move the Snake Cog to Seasonalbot

### ISSUE THREAD

**Issue by sco1** [python-discord/bot#327]
Since there's no API support for the [Snakes cog](https://github.com/python-discord/bot/blob/master/bot/cogs/snakes.py) in the Django rewrite, this cog should be moved to [Seasonalbot](https://github.com/python-discord/seasonalbot) and refactored to use static resources rather than API calls.

The cog's components can be found in the [site's migration tables](https://github.com/python-discord/site/tree/master/pysite/migrations/tables)

**Comment by MarkKoz** [comment]
Is this done now that those two PRs are merged?

**Comment by scragly** [comment]
Yep.
