### ISSUE TITLE
REPL tag

### ISSUE THREAD

**Issue by GhostofGoes** [python-discord/bot#329]
Explaining the REPL is a common occurrence for helpers. This issue proposes adding a `repl` tag that contains a succinct explanation of the REPL.

Commands: `!tags repl`, `!repl`

**Comment by jos-b** [comment]
This should be on the meta issue for tag suggestions.

**Comment by sco1** [comment]
https://github.com/python-discord/meta/issues/22

**Comment by GhostofGoes** [comment]
Whoops, my bad
