### ISSUE TITLE
Completing the move to flake8-docstrings

### ISSUE THREAD

**Issue by AnonGuy** [python-discord/bot#335]
We've decided to add `flake8-docstrings` to project requirements for this repository.
We've agreed on the following list of errors to ignore:
```sh
ignore=
    P102,B311,W503,E226,S311,
    # Missing Docstrings
    D100,D104,D107,
    # Docstring Whitespace
    D203,D212,D214,D215,
    # Docstring Quotes
    D301,D302,
    # Docstring Content
    D400,D401,D402,D405,D406,D407,D408,D409,D410,D411,D412,D413, D414
```

**Comment by lemonsaurus** [comment]
We've decided not to ignore D202 and D204. I've edited the OP to reflect this. See https://github.com/python-discord/organisation/issues/53#issuecomment-486371508 for more info.

**Comment by sco1** [comment]
Closing in favor of the more overarching issue here: https://github.com/python-discord/bot/issues/384
