### ISSUE TITLE
Provide current nickname in embed for infraction search

### ISSUE THREAD

**Issue by fiskenslakt** [python-discord/bot#337]
Will reduce confusion when someone does an infraction search since most users have a nickname completely different to their actual username.

Potential duplicate to [this issue](https://github.com/python-discord/bot/issues/125), not sure if it would be better to just comment on that one.

**Comment by kraktus** [comment]
I think I can do that, using `Member.nick` I would like to claim the issue.

**Comment by kraktus** [comment]
Hard to test because the infraction database is host on the website, so I cannot test my changes only running the bot.

**Comment by lemonsaurus** [comment]
Assigned to @kraktus

**Comment by lemonsaurus** [comment]
the bot's `docker-compose` does spin up a site container for you, so it makes it quite trivial to test this.

All you gotta do is create a few infractions. just mute yourself a few times and then do a search.

**Comment by scragly** [comment]
This ticket is open to anyone wishing to claim it.

**Comment by MarkKoz** [comment]
This is blocked until https://github.com/python-discord/bot/issues/533#issuecomment-586673988 is figured out.
