### ISSUE TITLE
Add infraction count to !user output for mods

### ISSUE THREAD

**Issue by fiskenslakt** [python-discord/bot#339]
When doing `!user` on a mod, display the amount of infractions they've handed out to users by type.

Something like:

Bans: 3
Warnings: 21
Notes: 42

etc..

I would say that probably the shadow versions of an infraction should combine with the non-shadow version, and maybe for extra points make a verbose option to display them separately.

**Comment by ilysia** [comment]
I'm looking into this issue. #Oiry on discord
I'm now basically setting up versions and dependencies...

**Comment by SebastiaanZ** [comment]
@ilysia What's the status on this pull request?

**Comment by SebastiaanZ** [comment]
Hey @ilysia,

Some other things related to the `!user` command have come up for which I'm implementing a fix. Since this issue hasn't seen any activity in three weeks, I'm going to include these requested features in that PR and unassign you from this issue.
