### ISSUE TITLE
Add appeals email address to ban infraction dm

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/bot#358]
As discussed, we want to add the appeals email address (appeals@pythondiscord.com) to the infraction DM people get from the bot after receiving an infraction. That way, they can appeal the infraction.

The email is forwarded to the admin team (including owners).

**Comment by RohanJnr** [comment]
More info plz, like what is this infraction dm and how it works

**Comment by MarkKoz** [comment]
@RohanJnr When someone receives an infraction, they may get a dm which notifies them of the infraction and the reason.

I've already done this in #370 and #371 so this can be closed.

**Comment by RohanJnr** [comment]
oki
