### ISSUE TITLE
Offensive word filtering

### ISSUE THREAD

**Issue by AnonGuy** [python-discord/bot#364]
Once the bot's word filters are triggered, we will need to call a site endpoint to store the ID of the offending message, along with a "delete time" of one week after the authored time.

The bot will pull a list of offending message IDs daily, and delete the messages that have reached the allotted delete time.

**Comment by AnonGuy** [comment]
The corresponding site issue for this feature can be found [here](https://github.com/python-discord/site/issues/222).

**Comment by Akarys42** [comment]
Hi, I would like to work on this please.
