### ISSUE TITLE
!tags command does not show up in the !help command

### ISSUE THREAD

**Issue by LordHemlock** [python-discord/bot#385]
For some reason, the tag command is not listed in the !help command's list of stuff.  This applies to all levels of help, not specifically just the developer role.

**Comment by scragly** [comment]
Yes, it was made hidden, meaning it won't show in help.

```py
    @group(name='tags', aliases=('tag', 't'), hidden=True, invoke_without_command=True)
    async def tags_group(self, ctx: Context, *, tag_name: TagNameConverter = None):
```
https://github.com/python-discord/bot/blame/master/bot/cogs/tags.py#L105

**Comment by LordHemlock** [comment]
So it's intentional? Fair enough then. I do feel like it would benefit our
users to know of them so they can at least look at them

**Comment by scragly** [comment]
I'm unsure if it's intentional, we would have to ask the person who wrote it.
I don't disagree with your point though in that it would be handy to be able to view the tags command in the help listings, and think it really probably shouldn't be hidden. Thankfully it's simple to set.
