### ISSUE TITLE
Token remover and auto codeblock response conflict

### ISSUE THREAD

**Issue by tagptroll1** [python-discord/bot#389]
When a user posts code that's not formatted correctly with a discord.py token the bot deletes their message cause there's a token in it.  However it proceeds to repost their code **with** their token in a "how to format your code" response.

**Comment by MarkKoz** [comment]
I think the fix would be to somehow ensure all filters run first. Ideally they would have priority over _anything_ else that processes messages.

**Comment by SebastiaanZ** [comment]
It's not that difficult to do, but we'd have to change the set-up slightly by adding a general `on_message` event handler first triggers the filters and, if the message doesn't need to be filtered, calls the processing of commands.

**Comment by kraktus** [comment]
I think it should be doable by calling the `token-remover` function before calling the `on_message` function (the one that is used to fix posts code that's not formatted correctly).

**Comment by ikuyarihS** [comment]
There was another incident today
![image](https://user-images.githubusercontent.com/19921765/69494784-2e4e9d80-0ef2-11ea-87b4-73c567218826.png)

I had to remove the embed manually, and asked user to change their token.

How's the progress on the issue? Are we still waiting for a reordering / restructuring of the order of `on_message` events across all cogs? Or are we going to implement a specific fix for this one listener?

**Comment by kraktus** [comment]
The PR is finished, waiting for review for more than a month.
