### ISSUE TITLE
!free command breaks if 2 or more channels have same timestamp

### ISSUE THREAD

**Issue by fiskenslakt** [python-discord/bot#401]
When the last messages in 2 or more help channels have the same timestamp as each other, the `sorted` function will try and reconcile this tie by comparing the channel objects themselves. 

![Screenshot of error](https://i.imgur.com/LfjeqKU.png)

Relevant code:

https://github.com/python-discord/bot/blob/40f39877b522d8d19025f25b536cdc1afe1d2596/bot/cogs/free.py#L85

https://github.com/python-discord/bot/blob/40f39877b522d8d19025f25b536cdc1afe1d2596/bot/cogs/free.py#L63

The occurrence of this bug appears to be inconsistent when this particular edge case happens, which has made it difficult to pin down until now.

**Comment by sco1** [comment]
Closed by #455
