### ISSUE TITLE
Using BB watch should show info about any previous unwatch reason.

### ISSUE THREAD

**Issue by scragly** [python-discord/bot#404]
We provide a reason when unwatching someone, which should be info that is displayed in case someone goes to watch them again. This could be particularly helpful for nominations also.

**Comment by MarkKoz** [comment]
Would like to work on this. Can you clarify where the info should be displayed? I was thinking right after the command is invoked e.g. "This user has previously been watched for the following reason:". It could display the most recent reason or perhaps display them all.

**Comment by sco1** [comment]
The most recent watch & a count of total watches is probably an ok start.

**Comment by MarkKoz** [comment]
That is good to know. Do you agree with my proposal to display it after the command is invoked then?

**Comment by sco1** [comment]
Yes, that seems reasonable
