### ISSUE TITLE
Implement a search command for !otn

### ISSUE THREAD

**Issue by kosayoda** [python-discord/bot#408]
With hundreds of off-topic names in our list, looking for one by clicking through the paginator with the bot is tedious.

Let's have a `!otn search <name>` command!

#### Implementation Ideas
- Use the text search functionality in postgres 
- Fuzzy search (`fuzzystrmatch` maybe?)
- Ranked list based on similarity to query

**Comment by lemonsaurus** [comment]
Love this idea.
