### ISSUE TITLE
Misconfigured AntiSpam rule will "crash" the bot

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/bot#410]
The current implementation of the `validate_config()` function in the [AntiSpam cog](https://github.com/python-discord/bot/blob/django/bot/cogs/antispam.py) of the Django branch will "crash" the bot if it finds a misconfigured setting. The reason is that it's a plain function and it's not being called within the event loop/from an `asyncio.Task`, which means that raising an exception has the normal behavior of stopping the interpreter, as it's not being caught:

https://github.com/python-discord/bot/blob/a019df5969b1a8f22d66c9405983808a83fc4a96/bot/cogs/antispam.py#L156-L169

I don't think it's desirable for the bot to be completely unstartable in the case of a relatively small misconfiguration, so we need a different approach here. One option would be to log the issue instead of raising an exception; however, that would mean we'll only notice it if we check the logs. 

Another approach would be to send an alert to the server, like the bot does when `defcon` settings cannot be retrieved from the API. However, we can't do this directly at this point, since this is a plain function that's being run before the bot has connected and is not part of the cog. A possible way around this is to set a flag and have the AntiSpam Cog check that flag in an `on_ready`.

Other suggestions are welcome, too, obviously.

---

For those testing this, since this exception happens very early in start-up, it will trigger an unrelated exception in `aiohttp` that may confuse you. Basically, `aiohttp` will try to log things when the interpreter is shutting down and the name `open` has already been deleted. This will result in tracebacks like [this](https://paste.pythondiscord.com/urekevegag.py) with the interesting exception `NameError: name 'open' is not defined`. They are not directly related to this bug, but a side-effect of having the interpreter close down because of the `ValueError` we raise.

**Comment by jchristgit** [comment]
This is intentional.

We already have tons of logging noise and I don't think it makes sense to try to adjust every piece of configuration that's wrong, or send alerts externally.

**Comment by lemonsaurus** [comment]
Resolved in 14a67c1
