### ISSUE TITLE
Prevent double error handling for unknown members in the moderation cog (and others?)

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/bot#414]
With moderation commands, if the conversion to a (pseudo-)User/Member object fails, the bot will output two error messages to the user:

![2019-09-14_15-11](https://user-images.githubusercontent.com/33516116/64908540-ec3ef980-d701-11e9-83ac-9354b25de9c1.png)

In this *specific* case, it's probably better to mention that the user can't be found, instead of showing the `help` response that's generated by the general error handler as well. Outside of this specific case, the `help` response is probably precisely what we want.

Everything still works, though, and this is just cosmetics, so I've labeled this as an enhancement instead of an issue blocking the migration.

(Note for testers: this only happens for user arguments that can't be converted to an `int` if the `UserProxy` type is part of the `Union`. So, use a string.)

**Comment by MarkKoz** [comment]
I inadvertently solved this in 4a5ea8cd1fc13de8c419ef48b42dc11f5bba6705
