### ISSUE TITLE
tag names with specific quotation marks are not caught by the space filter in the bot, only in the api

### ISSUE THREAD

**Issue by jchristgit** [python-discord/bot#415]
- `!tag set '   ' something`
- `!tag set '' something`

**Comment by Zer0897** [comment]
It appears `'` is treated as punctuation.

`!t set ' '` succeeds with:
```
tag_name: '
tag_content: '''
```

This works with any character besides `"`. We could ignore punctuation entirely but that would cause issues with current tags that use `-` as a separator. 

Explicitly allowing separators like `-`, `_`, and ` ` while ignoring everything else could be an option.

**Comment by Numerlor** [comment]
Was fixed in #797 through requiring tag names to require a letter and will become irrelevant after #777 is resolved
