### ISSUE TITLE
How should the global error handler handle errors when a command/cog has its own error handler?

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#416]
Currently, if a command or its cog has a local error handler, the global error handler will ignore that error. However, most handlers are typically only concerned with a handful of errors. Therefore, if the global handler is ignoring these errors, they will get silently consumed. 

The local handler would have to have some catch-all (and some do). A catch-all isn't ideal because it wouldn't provide nearly as detailed information as deferring to the global handler would. But in order to defer to the global handler, the handler would need to be able to distinguish handled and unhandled errors. One solution is to set some attribute on the context or the error itself for which the global handler could check.

**Comment by MarkKoz** [comment]
It was decided adding an attribute is an adequate solution but it can fall victim to a forgetful programmer. An automated test can ensure these attributes are added. The implementation of this idea would need to be fleshed out. Is it feasible? If the test is to automatically discover all local error handlers, how will it know for which errors it should expect the handled attribute to be present?

**Comment by MarkKoz** [comment]
Adding attributes was addressed in 4a5ea8cd1fc13de8c419ef48b42dc11f5bba6705 and c020004cb75414865583d1c200cc9a6df1a49cbb.

**Comment by lemonsaurus** [comment]
@MarkKoz can this be closed?

**Comment by MarkKoz** [comment]
Yes. I don't strongly feel that testing it is necessary. If someone forgets to add the attribute, it's not a big problem. It's not hard to notice or fix.
