### ISSUE TITLE
Change Dockerfile base image

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/bot#420]
We're currently using `alpine` for the bot Dockerfile, and it sucks. It's super slow to install the pipenv dependencies, apparently because alpine has a weird C compiler which makes it compile every pip library from scratch instead of using the wheels.

Let's change it to something like `minideb` or even `ubuntu`. They're still pretty lean images, but they don't have this problem so build times should be reduced _significantly_ just by using a different image.

**Comment by scragly** [comment]
Volcyy has already started using https://hub.docker.com/r/bitnami/python/ for site, which is based on minideb, which is what we will likely go with for this repo also.

**Comment by jchristgit** [comment]
why not the default `python`?

**Comment by scragly** [comment]
Because the default python docker image doesn't have a variant that uses minideb as a base as far as I can tell.

**Comment by scragly** [comment]
`python:python3.7-slim` does exist though for default python which could be a fine enough alternative. I think it'll be best to just end up comparing build times between the two and picking the fastest one to decide.
