### ISSUE TITLE
Escape discord markdown in detected poorly formatted python code before sending correction

### ISSUE THREAD

**Issue by Numerlor** [python-discord/bot#434]
Currently if an user sends a message like this:
````
```
class Example:
    def init__(self):
        ...
```
````

The bot won't escape the underscores in the escaped codeblock part of the message which will cause underlining. The underlining will continue until the other pair of the underscores is reached which are in the resulting example codeblock, making the codeblock underlined until then and in practice escaping it.

![](https://i.imgur.com/WVR9VX2.png)

**Comment by SebastiaanZ** [comment]
I'll look into this, I think we can solve this by using `re.sub` to escape all the mark-up characters.
