### ISSUE TITLE
The off-topic channel name updating task fails on non-success API response

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/bot#442]
The background task we create to update off-topic names at midnight UTC fails if it receives a non-success API response. The reason is that our `bot.api_client` will raise the `bot.api.ResponseCodeError` exception on non-success response status codes. This means that the off-topic channel names won't be updated again until either the bot is restarted or the task is started manually again by an admin.

The relevant lines of code:
https://github.com/python-discord/bot/blob/e70c96248bd7b548412811a4f1ffe88bed41f815/bot/cogs/off_topic_names.py#L59-L61

To handle it, we could simply include a `try-except` block and log the exception in the `except` block. I'm not sure if we want to log the entire exception, since the exception text could be a [massive HTML-response generated by cloudflare](https://paste.pythondiscord.com/ohibicedif). Logging the failure with the response code should generally give us enough to determine the cause of the failure.

**Comment by Akarys42** [comment]
working on it :)

**Comment by SebastiaanZ** [comment]
@Akarys42 Can you make sure you're working from an up-to-date fork? I noticed that your fork is quite some commits behind `master`. That will make sure we don't run into a lot of merge conflicts and other problems.
