### ISSUE TITLE
!reminders list returning all reminders in DB

### ISSUE THREAD

**Issue by sco1** [python-discord/bot#445]
The reminders cog is currently returning a list of all reminders in the DB rather than those specific to the user.

For example, if I have no reminders created I still get a list of reminders:

![image](https://user-images.githubusercontent.com/5323929/65425255-90e4c980-dddb-11e9-813f-4638c8c9f7e9.png)

**Comment by sco1** [comment]
I *think* I might have an idea of what's going wrong, but would welcome folks more django-knowledgable than I to confirm.

Our reminder viewset is currently filtering on [`user__id`](https://github.com/python-discord/site/blob/2cbc302f3bea9e3930859b644cdf093ee8973e99/pydis_site/apps/api/viewsets/bot/reminder.py#L69), which isn't a field in our reminder model:

Changing the references from `user__id` to `author` in the site & bot repos seem to fix the issue

**Comment by MarkKoz** [comment]
The `author` field is a foreign key in the model which means it's referencing another record. So the double underscore syntax allows you to do [lookups than span relationships](https://docs.djangoproject.com/en/2.2/topics/db/queries/#lookups-that-span-relationships). That being said I'm not sure if this is necessary for filters with `django-filter`.

**Comment by sco1** [comment]
Ok, with that in mind it seems like changing `user__id` to `author__id` in the reminders cog seems to fix the problem, with site untouched.

**Comment by SebastiaanZ** [comment]
Yes, in these lines:

https://github.com/python-discord/bot/blob/f58c578940e4bde74e54b6005160cfba90d1eaac/bot/cogs/reminders.py#L149

https://github.com/python-discord/bot/blob/f58c578940e4bde74e54b6005160cfba90d1eaac/bot/cogs/reminders.py#L187

The provided `param` should be `author__id` not `user__id`.

**Comment by sco1** [comment]
Since this seems to be all that's needed & is fairly minor, will include in #444
