### ISSUE TITLE
Help command raises AttributeError when argument is a cog name

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#456]
For example, `!help Moderation` returns

```
AttributeError: 'Command' object has no attribute 'instance'
```

Have not looked into the cause of this yet.

**Comment by sco1** [comment]
This looks like an artifact of async that disappeared when rewrite was merged into master. Our previously pinned version [had this attribute](https://github.com/Rapptz/discord.py/blob/860d6a9ace8248dfeec18b8b159e7b757d9f56bb/discord/ext/commands/core.py#L179), but it's [not present in 1.0.0+](https://github.com/Rapptz/discord.py/blob/d37839f38acd79d49bc19ae06d3067a455695e9b/discord/ext/commands/core.py#L228).

**Comment by MarkKoz** [comment]
Good catch. It looks like the attribute was just renamed to `cog`.
