### ISSUE TITLE
Subclass Bot

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#468]
This allows us to do some backend QoL stuff:

* Override `add_cog()` so that it logs the loading of cogs
* IDEs will recognise additional attributes, such as the API client
* Override `load_extensions()` so that it automatically prepends `bot.cogs` to the name given

And there's maybe more stuff I'm forgetting.

**Comment by SebastiaanZ** [comment]
Yes, we should. I think it would also be a good idea to override the `close` method to close the `aiohttp` session correctly.

**Comment by mathsman5133** [comment]
Another idea for this one is to dispatch a `cog_ready` event inside `add_cog`. Right now most of the cogs use the `on_ready` listener to do any async stuff (or not) that needs doing when loading cogs, however, this fails if:

1. Something needs to be re-done once the cog has been reloaded (eg. fetching + setting a channel/webhook attribute)
2. The cog is not loaded on startup (for whatever reason) and is loaded later
3. A background loop is started before `on_ready` has completed.

**Comment by MarkKoz** [comment]
@mathsman5133 With #488 practically done, I don't think this is needed. Also, I feel `__init__` is basically the same as the proposed `cog_ready` would be anyway.

**Comment by mathsman5133** [comment]
Sure 👍 the difference being `cog_ready` could be a coro so fetching webhooks and the like would be simple, but seems like that PR does the same job

**Comment by SebastiaanZ** [comment]
@MarkKoz Are you currently working on this?

**Comment by MarkKoz** [comment]
No, not currently. I was waiting on other PRs and eventually forgot about this. If you would like to work on this now, you can. Otherwise, I will try to get started today or tomorrow.

**Comment by SebastiaanZ** [comment]
I don't think we're in a hurry, but I was reminded of it from people having some issues with their IDE not recognizing some of the attributes we set dynamically (e.g, `api_client`). Having a custom `Bot` class would solve that.

I can work on it, but if you like to work on it, that's fine as well.

**Comment by MarkKoz** [comment]
🤔 Where should it go? `__main__` would be weird to import from. `__init__` already cluttered. `bot.py` would be weird to import from (cause the package is also named `bot`).

**Comment by scragly** [comment]
Define it in `bot/bot.py`. Sure it might feel a little odd but it's the most appropriate place for it.
