### ISSUE TITLE
Automatic deletion of executable files

### ISSUE THREAD

**Issue by GhostofGoes** [python-discord/bot#471]
Remove executable or potentially executable files that may be malicious (malware, spam, zip bombs, etc.). 

Per Lemon: "Staff meeting consensus is that we can start simple by whitelisting certain extensions and deleting everything else. If people try to get around this with malicious hybrid filetypes or whatever, we will discuss maybe using ClamAV to scan files, but for now, we'll keep it simple. This should just be another filter, like mentionspam."

Org issue: https://github.com/python-discord/organisation/issues/142

Implementation
* Implement rule method (similar one that exists is [`bot/rules/attachments`](https://github.com/python-discord/bot/blob/master/bot/rules/attachments.py)
* Determine an appropriate whitelist (can probably push something reasonable then hammer it out during a meeting or review)

**Comment by bendiller** [comment]
Hi! Is anyone working on this? I'd like to, take care of it if it's open. I already threw together a quick prototype to make sure I understood how to implement this - I should be able to submit a PR pretty quickly.

**Comment by lemonsaurus** [comment]
Nobody is working on this, feel free to have a go at it!

**Comment by sco1** [comment]
Merged by #528
