### ISSUE TITLE
Superstarify prison does not release user when it expires

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/bot#472]
While the [superstarify command](https://github.com/python-discord/bot/blob/71a3ac9382851845dcb26609d64299bd69b0f0f5/bot/cogs/superstarify/__init__.py#L148-L219) correctly sends the expiration date of the superstarify prison to the API, it does not schedule a task make sure the infraction is actually deactivated when we reach the expiration date. This means that **the user will be kept in superstarify prison until we manually release them** with the `!unsuperstarify` command.

The most obvious solution is to have a superstarify infraction schedule a task like other temporary infractions do. We also need to confirm that this task is recreated if the bot restarts before it was actioned. 

Additionally, it's probably a good idea to confirm that the expiration date is in the future before sending a DM to notify a user of their imprisonment [when they try to change their nickname](https://github.com/python-discord/bot/blob/71a3ac9382851845dcb26609d64299bd69b0f0f5/bot/cogs/superstarify/__init__.py#L63-L83) or [when they rejoin the server](https://github.com/python-discord/bot/blob/71a3ac9382851845dcb26609d64299bd69b0f0f5/bot/cogs/superstarify/__init__.py#L109-L123). It also wouldn't hurt to add that the datetime string is in UTC.

Context: This notified me of an expiration date in the past (08:21 in my local time):
![2019-10-01_08-45](https://user-images.githubusercontent.com/33516116/65940665-53122180-e429-11e9-81fb-713e64d7e8c7.png)

Since @MarkKoz is currently working on the related moderation cog, I've assigned him for now, but I have not yet confirmed that he wants to work on this. Regardless, since we need to schedule this just like regular temporary infractions, it's probably a good idea if he's involved in the discussion.

**Comment by MarkKoz** [comment]
Yup, I can work on this.
