### ISSUE TITLE
Aliasing for !resources command.

### ISSUE THREAD

**Issue by TizzySaurus** [python-discord/bot#478]
Currently the !resources command links to both the [PyDis resource](https://pythondiscord.com/pages/resources/
) page, and the [PyDis tools](https://pythondiscord.com/pages/tools/) page.

I feel that the alias of !tools should be added to the command, or the links should be separated into two commands, to both make it easier for users to access the tools page, but also increase awareness of the page.

**Comment by lemonsaurus** [comment]
I think I would prefer for us to separate them. I'm claiming this and I'll solve it tonight.
