### ISSUE TITLE
The "Cogs" cog does not support loading of extensions which are packages instead of modules

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#479]
What "packages instead of modules" means is that the extension is an `__init__.py` of a sub-package i.e. the `setup()` function is in  `__init__.py` (this is what `watchchannels` is doing right now).

The culprit is this code https://github.com/python-discord/bot/blob/341fb5200acbf24ab1220339b6ce7cf6816561a5/bot/cogs/cogs.py#L28

It's just an overcomplicated and inaccurate way to accomplish this, especially since the [`Bot.extensions`](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.Bot.extensions) attribute exists (perhaps it didn't when this code was written).

**Comment by MarkKoz** [comment]
Also the entire cog is a misnomer since it's really loading _extensions_ and expects names of extensions, not cogs.

**Comment by SebastiaanZ** [comment]
You can still load/unload/reload the extension by providing the full Python path: `!cogs reload bot.cogs.watchchannels`, but this is a hassle. Some of our files also have `_` in them, so they need to be reloaded with the complete import path as well. Not exactly a usable system.
