### ISSUE TITLE
Make auto code encoding more simple, complete and easier to read

### ISSUE THREAD

**Issue by kraktus** [python-discord/bot#497]
While trying to fix #389 , I just found that there was a feature to detect and remove the embed message if the author did fix his previous code. Nice, but it is not displayed **at all**. The embed message should display it clearly. Currently the message is:

> "It looks like you're trying to paste code into this channel.  Discord has support for Markdown, which allows you to post code with full syntax highlighting. Please use these whenever you paste code, as this helps improve the legibility and makes it easier for us to help you.  To do this, use the following method:"

I suggest to add somewhere: "you can edit your message" in bold. It will make `#help`channel easier to read.

More globally, I find this feature too complicated. Why not simply delete the code and repost it correctly encoded (with something like: `@This user posted:`) ? It should also include at the end a message/DM explaining how to encode well code on discord.

I this is approved I could work on it

**Comment by kraktus** [comment]
May be combined with #439 and #389

**Comment by scragly** [comment]
> Why not simply delete the code and repost it correctly encoded
A few reasons:
- They'll be lazy and never correctly do it in the first place
- There may be a purposeful reason for someone to not use the expected formatting even if the filter triggers. 
- The code may be only part of the original message and the rest of the content would be weird to be posted by the bot, and shouldn't be left out.

I don't see an issue with adding the "you can edit your message" section in with emphasis though.

**Comment by MarkKoz** [comment]
No progress for 5 months so I'm unassigning. This is open for anyone to work on again.
