### ISSUE TITLE
Refactor "Help" Command

### ISSUE THREAD

**Issue by mathsman5133** [python-discord/bot#502]
Discord.py redesigned and created how help commands work - some helpful links:
- https://gist.github.com/Rapptz/288294ca99fa1f042f0e39a92ddd88eb#news-post
- https://discordpy.readthedocs.io/en/latest/migrating.html#helpformatter-and-help-command-changes
- https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#help-commands

This was way back before rewrite was released. Since then there has been at least 1 (`ctx.send_help`) helper added that works with an updated implementation of help, but not with ours.

A refactor to subclass the `HelpCommand` class and friends shouldn't have any outward-facing changes, but it will clean-up and update the code to be compatible with any future helpers or releases, as well as `ctx.send_help` and any others I've forgotten

I'd like to work on this if it's approved.

**Comment by MarkKoz** [comment]
This sounds good. You can work on it. I think @scragly may have had some ideas for how to improve it too.
