### ISSUE TITLE
Standardized format instead of Slow-mode in show-your-projects

### ISSUE THREAD

**Issue by eivl** [python-discord/bot#513]
[org-issue-137](https://github.com/python-discord/organisation/issues/137) talks about how we should make a slow mode for multi-message projects.
Slow mode is engaged and set to a 6-hour cooldown.

We need to implement a standardized format system to replace this with.

The format should be like this
```
Title:
GitHub:
Description:
```

**Comment by MarkKoz** [comment]
This is what the C# server does for example:

![bild](https://user-images.githubusercontent.com/1515135/66682915-11545880-ec2b-11e9-949a-af02ac7fa957.png)

**Comment by eivl** [comment]
In retrospect I kinda like `Source:` better then `Github:`
not sure that Main contributor fits, since show your projects is suppose to be done with the main maintainer.

**Comment by MarkKoz** [comment]
I agree. It should also be last so it looks better next to the embed.

**Comment by scragly** [comment]
Slowmode has been implemented and while formatting isn't perfectly consistent, people have indeed been going much better in the past with adding in all required info into a single message.

I'd like to ask, is it worth the effort of enforcing the above proposed format?

If it is, how would the format be enforced? Filter checking messages posted or maybe having the bot post it on their behalf through a command that asks for info for each part?

**Comment by MarkKoz** [comment]
I don't think a strict format is necessary, especially when the format would be so simple anyway. Keeping it free form and simple makes it more approachable to make a post. Alternate idea: send a mod alert if the message doesn't have a URL. Sometimes people use code blocks which we could try to detect too (we already have code written to do that elsewhere).

**Comment by lemonsaurus** [comment]
No longer relevant, as this channel has been archived.
