### ISSUE TITLE
Custom Trash can reaction to replace red X

### ISSUE THREAD

**Issue by eivl** [python-discord/bot#514]
[org-issue-141](https://github.com/python-discord/organisation/issues/141) talks about how certain members are confused about the red X that is added to embeds. 
Like the one that !eval uses
![eval output](https://i.imgur.com/pdSimjS.png)

The consensus is that we change it for a nice trashcan 🗑

**Comment by MarkKoz** [comment]
Ideally we'd have a custom emote that resembles a trash can, but looks nicer than twemoji's.

**Comment by Numerlor** [comment]
I was thinking something like this with simpler lines would look good
![](https://www.shareicon.net/data/48x48/2016/10/11/842408_trash_512x512.png)

**Comment by lemonsaurus** [comment]
yeah, I was also thinking something like that @Numerlor

**Comment by kraktus** [comment]
Duplicate of #297

**Comment by scragly** [comment]
Closing due to duplicate.
