### ISSUE TITLE
Prepend emojis indicative of success for !eval

### ISSUE THREAD

**Issue by eivl** [python-discord/bot#515]
Comments on [org-issue-141](https://github.com/python-discord/organisation/issues/141) suggests something quite useful. 

Add emojis indicative of success when you use !eval. 

- ✅ - if no error.
- ❌ - if exception.
- ❗ - for other cases, as it runs but there's no output

![bild](https://user-images.githubusercontent.com/1515135/66685485-90e52600-ec31-11e9-9f42-d9c0da31a5c3.png)
![bild](https://user-images.githubusercontent.com/1515135/66685492-95114380-ec31-11e9-9154-77da46f11cde.png)
![bild](https://imgur.com/l10DMcQ.png)

**Comment by MarkKoz** [comment]
I think ⚠️ is better for the third one since it's yellow rather than red. More distinct from the :x: that way.

**Comment by ikuyarihS** [comment]
I'd like to work on this, since I personally use this more often than not. Unless you are working on it with other plans like bringing 3.8 to `snekbox` @MarkKoz

**Comment by MarkKoz** [comment]
You can go for it. My plans are only concerned with CI.

**Comment by kosayoda** [comment]
I had this assigned and was working on this, you can have it though.

**Comment by ikuyarihS** [comment]
Ah no no, it has been quite a while and so I thought no one has taken it, @kosayoda 
If you are already on it please dont mind me

**Comment by MarkKoz** [comment]
Sorry I was on mobile at the time of commenting and wasn't aware it was already assigned.
