### ISSUE TITLE
Alternative to tempmute for too many new lines

### ISSUE THREAD

**Issue by LordHemlock** [python-discord/bot#516]
Currently, when a user posts a message with far to many lines (usually a long code block between a couple messages), the user will receive a temporary mute from the bot.  I propose that we change that behavior slightly.  We keep the check for too many lines, however we add in the check for formatting that the bot also uses to inform them about the Discord formatting.

By doing this, we can instead point users to the hosted hastebin rather than punishing them for not knowing about it.

**Comment by Numerlor** [comment]
Seems to focus on the same issue as the second part of #439

**Comment by LordHemlock** [comment]
Closing Reason: Duplicate of #439
