### ISSUE TITLE
Display nickname as plain text in infraction mod logs instead of user id

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#533]
The Discord client will not be able to resolve the name of a mentioned user if the user is not in the cache so it ends up just displaying the ID. Furthermore, the user ID can be copied by right clicking a mention. Therefore, the text in parenthesis should be the user's nickname as plain text instead of their ID.

This will need to account for working with the proxy user object which only has an ID - no name or nickname. In such case, don't display anything in addition to the mention; I don't think it's worth doing `fetch_user()` or whatever.

**Comment by ikuyarihS** [comment]
It's been 7 days since the issue was raised, so I'd like to work on this

**Comment by Numerlor** [comment]
addressed in #651

**Comment by Numerlor** [comment]
unassigning myself after #651 was closed

**Comment by MarkKoz** [comment]
Let's figure out exactly what the member and the actor should be displayed.

## Information

These questions need to be answered for both the member and the actor separately:

1. Should the ID be displayed alongside a username/nickname?
    * ID will still always be the fall-back when no name data is available
2. Should the nickname be displayed?
    * Is it worth an API call to get the data or should it rely solely on the cache?
        * Should it use the latest data from Discord or use the last-seen data stored in our database? Mainly relevant for users which have left the guild.
3. Should the username be displayed?
    * With the discriminator?
    * Even if the nickname is already displayed?
    * Is it worth an API call to get the data or should it rely solely on the cache?
        * Should it use the latest data from Discord or use the last-seen data stored in our database? Mainly relevant for users which have left the guild.

## Format

Which format should each use? Keep in mind plain text can be displayed alongside the mention, of course.

1. **Mention**
    * Discord's search feature will show these in search results when searching by ID but not by name
    * The member's nickname will be prioritised when showing this. If they're not in the guild, their username is displayed
        * Dynamically updates the name when the user changes it
        * Discriminator is never displayed
    * Has a right-click context menu which, among many other options, includes the ability to copy the user ID
        * No way to do this on mobile
    * Works with just an ID, which is always available; no API calls required to get name data
    * Invalid users or ones not in the client's cache show as `<@475073629399547905>`
        * Not easy to tell who someone is in this case.
        * This is still searchable by ID 
        * It behaves like normal text rather than a mention with a right-click context menu
            * The ID can be copied by highlighting the it in the same manner as one would select any other text
2. **Plain Text**
    * Shows up in search results the same way any other text would (e.g. if displaying a username, can search logs by the username)
    * Discriminator can be displayed
    * May require additional API calls to retrieve name data.
    * Name is static
        * Will not change if a user changes their name
        * Will remain the same regardless of cache or a user being deleted
    * No way to get the ID unless it's displayed alongside a name
        * Still wouldn't be a way to directly copy it on mobile

**Comment by lemonsaurus** [comment]
@MarkKoz 
Okay, this does need figuring out I guess.

I think we should use mentions both on actor and on User, and that on User, we could probably include the display_name instead of the user ID. 99% of the time when you're viewing the result of an !infr search, you typed in the ID to get there, so I really don't think displaying the ID is that crucial.

It's also quite unlikely the actor won't be cached.

So, I think mentions on both and display_name (with descriminator) strikes a nice balance between better usability on mobile (where caches are most commonly unfilled) and convenience on desktop.

**Comment by MarkKoz** [comment]
Thanks for your input. What do you think about the following regarding the username + discriminator?

>- Is it worth an API call to get the data or should it rely solely on the cache?
>    - Should it use the latest data from Discord or use the last-seen data stored in our database? Mainly relevant for users which have left the guild.

**Comment by lemonsaurus** [comment]
Yeah I think we can make an API call, it's not like !infr search is used that often, we're talking about maybe a couple dozen times a day at most. I think having the most up-to-date info here has actual moderator utility, and that we don't need to skimp on this particular part of the code.

**Comment by MarkKoz** [comment]
@lemonsaurus To be clear, this change will apply to **all** mod logs, not just infraction searches. Infraction searches may not be common but infraction logs are relatively more common. Still, I think your point stands that they don't happen frequently enough for the API calls to be a huge hit. But on the other hand, it may not be as important to have logs with the most up to date name compared to when a staff member is explicitly trying to retrieve information like with `!infr search`. I remember there was talk about reducing API calls to alleviate rate limits. I'm not sure if such API call would be affected by the same rate limits as adding reactions and whatnot.

**Comment by lemonsaurus** [comment]
hm. well yeah, it's less relevant for mod log items. if possible, I suppose we could do lookups only for infr search?

**Comment by MarkKoz** [comment]
@lemonsaurus I'm working on this and using API calls for infraction searches is proving to be concerning. It can result in a lot of API calls depending on the search query.

* Fetched users would need to be cached somehow. This would be slightly awkward API, and, more importantly, it'd be more work to have to implement some custom caching logic.
* If not cacheable (like for reason queries), API calls are done sequentially. `asyncio.gather` could be used, but I'm concerned about rate limits (maybe d.py handles this OK). Ideally the requests could be done lazily, but the paginator doesn't support async generators.

I'm inclined to use the username and discriminator in our database, as it would be much simpler to implement client-side. We already have to make the infraction requests anyway since we need infraction info. Our expanded infraction API calls probably also have some performance hit, but surely extra DB queries are nowhere near as bad as making a lot of HTTP requests to Discord.

The disadvantage is that the data is not fresh, since we do not sync users that aren't in our guild. However, maybe this is better. The name last used when in the guild is likely more recognisable than whatever the user currently has for a name. I figure easy recognition is the primary point of including the username to begin with. For accurately referencing the user, the ID is still available.

**Comment by lemonsaurus** [comment]
What the you're saying seems reasonable to me. :+1:
