### ISSUE TITLE
Don't ping actor when an infraction DM fails to send

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#534]
Would anyone miss this functionality?

**Comment by sco1** [comment]
Kill it with fire

**Comment by SebastiaanZ** [comment]
We're still discussing whether or not we should actually remove this internally.

**Comment by SebastiaanZ** [comment]
We have discussed this with the moderation team and no one seems to be opposed to removing the "actor ping".

To still get *explicit* feedback about DMs failing to be delivered to the user, we would like to add an emoji to the infraction confirmation message in a similar style to the "swooshing" envelope we use to signal that a DM was successfully sent:

![infraction_confirmation_message](https://user-images.githubusercontent.com/33516116/66835835-817f1900-ef60-11e9-819c-a0b28c4cab0a.png)

An initial design for the "fail" emoji is:

![failmail2](https://user-images.githubusercontent.com/33516116/66836216-3f0a0c00-ef61-11e9-87ae-7db4847660ac.png)

**Comment by SebastiaanZ** [comment]
The emoji has been added as `:failmail:` (ID of `633660039931887616`) to the emoji server.
