### ISSUE TITLE
Restrict ModManagement commands to moderation channels

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/bot#535]
The [`ModManagement` cog](https://github.com/python-discord/bot/blob/master/bot/cogs/moderation/management.py) contains commands to search for and edit infractions stored in our database. Since we'd like to keep that data confidential, we want to restrict these commands to the following channels:

- #mods (ID: `305126844661760000`)
- #mod-spam (ID: `620607373828030464`)
- #admins (ID: `365960823622991872`)
- #mod-alerts (ID: `473092532147060736`)

Since this restriction should hold for all the commands in the cog, the implementation should be straightforward by modifying the `cog_check` method:

https://github.com/python-discord/bot/blob/8040724d1b452b79a16c7df073bd2a8f546570a5/bot/cogs/moderation/management.py#L257-L260

Please make sure to add this check in addition to the moderation roles check; it's not a replacement. 

#### Additional info
A constant with the channel id already exists in `constants.py`/`config-default.yml` for the #admins and #mod-alerts channels, but you will need to add a constant for the other two channels. 

It may also be a good idea add a `MODERATION_CHANNELS` constant in a similar way to the `MODERATION_ROLES` constant we have. That makes it easier to modify the specific channels we want to include and as well as it making it easier to use the same set of channels in the future.

**Comment by atmishra** [comment]
I would like to work on this. Thanks!

**Comment by scragly** [comment]
@atmishra I've assigned you to this task, so feel free to start work on it. If you need any assistance with dev environment setup, feel free to ask questions in the `#meta` channel in the discord server.

**Comment by atmishra** [comment]
Thanks! for assigning it to me. I will start working on it.

**Comment by atmishra** [comment]
Hi, I have raised a PR for this ticket https://github.com/python-discord/bot/pull/543 
This is my first PR so I am not sure how to test this. I tried to do the local setup using docker, but its failing.

**Comment by kosayoda** [comment]
Hello and thank you for contributing, are you in the Discord server? We'll be very glad to help you get your local setup working, since manual testing is important for Discord bots.

**Comment by atmishra** [comment]
Thank you! Yes I am on the server, my username is `atmishra#0512`
