### ISSUE TITLE
Docs command refinements

### ISSUE THREAD

**Issue by Numerlor** [python-discord/bot#538]
With how the `symbol`s are currently loaded to the inventories dict, earlier entries get overwritten by newer ones.
This can have negative impact, most notably when loading the 2to3 tool which overrides things like `print`, `zip` or `input` and returns mostly useless docs to them.
It could be solved by never overwriting existing dict entries, or by defining a list of modules that won't override existing dict entries, to keep cases where it's better to not do it (object as an example)

Second issue is how the parsing is handled when a module is fetched from the docs.
The whole page, also containing the module functions, gets parsed into the `signature` which is put into a codeblock without any newlines between paragraphs, making it hard to read.

**Comment by atmishra** [comment]
I would like to work on this.

**Comment by Numerlor** [comment]
I was planning to get to it if it's approved

**Comment by scragly** [comment]
Sounds good to me, feel free to start work on it @Numerlor

**Comment by Numerlor** [comment]
If I were to use the list of symbols/doc module names to specify which can overwrite and which cannot, where should I put it? Skimming through it, it looks like a dozen or so will be needed
