### ISSUE TITLE
Don't show infraction total outside staff channels.

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/bot#540]
Currently, when we deliver an infraction, it will show the infraction total in the bot's response.

![image](https://user-images.githubusercontent.com/2098517/66942037-70113c00-f048-11e9-8867-114b2339a1ac.png)

This is a cool feature, but should not happen in public channels. So let's do something about that.

### Infraction total should be allowed in the following channels:
```
#admins        ID: 365960823622991872
#admin-spam    ID: 563594791770914816
#mod-spam      ID: 620607373828030464
#mods          ID: 305126844661760000
#helpers       ID: 385474242440986624
#organisation  ID: 551789653284356126
#defcon        ID: 464469101889454091
```

If the command is called in any other channel, **do not show the infraction total**. This applies to all moderation commands that currently show the total.

If any of the above channels are not currently registered as constants, please create new constants for them. The above list of channels can be stored as a group constant called `STAFF_CHANNELS`. Make use of [YAML node anchors](https://yaml.org/spec/1.2/spec.html#&%20anchor//) when you do this.

**Comment by Akarys42** [comment]
Hi, I would like to work on this please.

**Comment by Akarys42** [comment]
Done in #547.
