### ISSUE TITLE
Write unit tests for `bot/cogs/moderation/__init__.py`

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/bot#556]
Write unit tests for [`bot/cogs/moderation/__init__.py`](../blob/master/bot/cogs/moderation/__init__.py).

## Implementation details
Please make sure to read the general information in the [meta issue](553) and the [testing README](../blob/master/tests/README.md). We are aiming for a 100% [branch coverage](https://coverage.readthedocs.io/en/stable/branch.html) for this file, but if you think that is not possible, please discuss that in this issue.

## Additional information
If you want to work on this issue, **please make sure that you get assigned to it** by one of the core devs before starting to work on it. We would like to prevent the situation that multiple people are working on the same issue. To get assigned, leave a comment showing your interesting in tackling this issue.

**Comment by ArduinoidIOT** [comment]
I'd like to work on this please.
