### ISSUE TITLE
[Feature Request] Link GH Account

### ISSUE THREAD

**Issue by RohanRadia** [python-discord/bot#557]
The command lets people link their github to their discord. For example I wanted to see Icemans (Rohan's) PR's but couldn't remember his Github. If this command existed then I could just do .github @icemanjr and it would return his github username.

## Additional information

You would have a database (perhapse JSON) to store discord handle and github name pairs.

The included commands would be:

`.github link [GitHub Name]` - Links the invoking users account name to their Discord name
`.github unlink [optional: GHAccountName]` - Unlinks the invoking users GitHub account. Can also be used as: `.github unlink [@user]` by moderators only to unlink a spam/suspicious account.
`.github` - Sends the users current linked GitHub acount name back
`.github [@user]` - Sends the specified users current linked GitHub account name back
`.github [user]` - Not using a mention makes it search for a Github Username and tries to resolve a matching Discord User
`.github list` - Paginates all users along side their GitHub names who have any data stored.

**Comment by MarkKoz** [comment]
1. Why was this transferred from seasonalbot to here?
2. I don't think the site's functionality of linking a GH account is necessarily useful because those users did not specify that they want to make the association publicly available.

**Comment by Senjan21** [comment]
This feature is now a thing within the discord client thus the issue isn't needed anymore.
![SmartSelect_20200918-220422_Discord](https://user-images.githubusercontent.com/53477086/93640567-1c973300-f9fb-11ea-9757-6eb606662412.jpg)
