### ISSUE TITLE
Write unit tests for `bot/rules/duplicates.py`

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/bot#599]
Write unit tests for [`bot/rules/duplicates.py`](../blob/master/bot/rules/duplicates.py).

## Implementation details
Please make sure to read the general information in the [meta issue](553) and the [testing README](../blob/master/tests/README.md). We are aiming for a 100% [branch coverage](https://coverage.readthedocs.io/en/stable/branch.html) for this file, but if you think that is not possible, please discuss that in this issue.

## Additional information
If you want to work on this issue, **please make sure that you get assigned to it** by one of the core devs before starting to work on it. We would like to prevent the situation that multiple people are working on the same issue. To get assigned, leave a comment showing your interesting in tackling this issue.

**Comment by alberthdev** [comment]
Would like to attempt to tackle this unit test, if possible!

**Comment by kwzrd** [comment]
Hi @alberthdev, are you still planning to work on this? I currently have a #733 open which adds test cases for antispam rules. I could sneak this one in as well.

**Comment by kwzrd** [comment]
@alberthdev I've decided to include this issue in #733, as this PR addresses all other antispam rule unit tests and we haven't heard from you regarding this since October.

I hope this is ok with you.
