### ISSUE TITLE
Monitor the new custom status with our filters

### ISSUE THREAD

**Issue by eivl** [python-discord/bot#620]
With the new custom filters, we should be able to monitor them as we do messages for blocked words and other mischiefs.

**Comment by syntaxaire** [comment]
Should this be closed as per python-discord/organisation#157? As per lemon,
> staff meeting consensus is that we can moderate these when we see them, but that we don't implement any filtering or alert systems targeting the status messages

**Comment by scragly** [comment]
Closing for the above reason.
