### ISSUE TITLE
Python 2 code detection.

### ISSUE THREAD

**Issue by scragly** [python-discord/bot#623]
With python 2 coming up to end-of-life, there was an idea to detect when python 2 code being used eventually in order to inform the user of it's impending doom.

One suggestion was to easily detect py2 print statements, due to their differing syntax from the py3 print function.

**Comment by MarkKoz** [comment]
I'm not a fan of this idea - it seems like a nuisance to users. It's not a big enough issue to warrant automated notices. Furthermore, keep in mind some are stuck with Python 2. I think other users can be diligent enough to inform of the EOL with the added power of the human mind to assess the context of the situation.

**Comment by Senjan21** [comment]
Considering Python2 is EOL since January of this year, we don't really need this feature.
