### ISSUE TITLE
Helper for editing most recent infraction.

### ISSUE THREAD

**Issue by scragly** [python-discord/bot#624]
For the command `!infraction edit`, the argument to specify the infraction requires an ID. It would be useful to have a special argument you could provide instead of the ID that would indicate the infraction you most recently gave out.

**Comment by scragly** [comment]
The site API endpoint may need to be adjusted allow for the option to fetch a moderators latest infraction.

**Comment by MarkKoz** [comment]
> The site API endpoint may need to be adjusted allow for the option to fetch a moderators latest infraction.

I don't think so. Looks like it already supports filtering by actor and ordering by any field (in this case it'd be `inserted_at`).
