### ISSUE TITLE
Support applying infractions to users who are not in the database

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#627]
For example, trying to ban a user (via ID) who has never joined the server before will currently error out because the syncer never got a chance to create the user in the database. Therefore, the user will have to be manually created with `in_guild=False` after their details are fetched with `fetch_user`.

I _think_ this can all be done inside `proxy_user` (if it's turned into a `Converter` subclass so it can be async), but not sure.

**Comment by manusaurio** [comment]
If that's okay, I'd like to work on this.
