### ISSUE TITLE
Log voice channel events

### ISSUE THREAD

**Issue by fiskenslakt** [python-discord/bot#645]
# Abstract

Start logging whenever a user changes their voice state to a new channel called `#voice-log`. Depends on issue: [#161](https://github.com/python-discord/organisation/issues/161) being actioned.

# Specification

Relevant d.py event [here](https://discordpy.readthedocs.io/en/latest/api.html#discord.on_voice_state_update)

* Ignore Staff voice channel
* Ignore Admins voice channel

The format of this log has not yet been discussed, and thus is largely up to the person who implements this feature. I suggest taking the format of the logs in `#user-log` as inspiration.

# Motivation

We think it could be useful information to have. The issue #644 was discussed at the same time as this one.

**Comment by MarkKoz** [comment]
Please provide the ID of the admin voice channel.

**Comment by MarkKoz** [comment]
Need opinions on an icon:

![voice_state_changed_mic_75_24](https://user-images.githubusercontent.com/1515135/70607348-2742b300-1bb3-11ea-879e-6386f3defb33.png)
![voice_state_changed_phone_75_24](https://user-images.githubusercontent.com/1515135/70607364-2b6ed080-1bb3-11ea-9864-6d8c7d8c9f1e.png)

I prefer the second one. I'm open to trying to make other too if these aren't cutting it.

**Comment by scragly** [comment]
I don't mind the mic icon, however I'd suggest instead picking the same icon type as the voice channels already use: the volume icon.

![image](https://user-images.githubusercontent.com/29337040/70690156-d2fa1900-1d01-11ea-8a1a-8641a41d9ad6.png)

```xml
<svg xmlns="http://www.w3.org/2000/svg" width="200" height="100" viewBox="0 0 24 24">
<path fill="currentColor" fill-rule="evenodd" clip-rule="evenodd" d="M11.383 3.07904C11.009 2.92504 10.579 3.01004 10.293 3.29604L6 8.00204H3C2.45 8.00204 2 8.45304 2 9.00204V15.002C2 15.552 2.45 16.002 3 16.002H6L10.293 20.71C10.579 20.996 11.009 21.082 11.383 20.927C11.757 20.772 12 20.407 12 20.002V4.00204C12 3.59904 11.757 3.23204 11.383 3.07904ZM14 5.00195V7.00195C16.757 7.00195 19 9.24595 19 12.002C19 14.759 16.757 17.002 14 17.002V19.002C17.86 19.002 21 15.863 21 12.002C21 8.14295 17.86 5.00195 14 5.00195ZM14 9.00195C15.654 9.00195 17 10.349 17 12.002C17 13.657 15.654 15.002 14 15.002V13.002C14.551 13.002 15 12.553 15 12.002C15 11.451 14.551 11.002 14 11.002V9.00195Z"></path>
</svg>
```

**Comment by MarkKoz** [comment]
Here it is

![voice_state_changed_speaker_75_24](https://user-images.githubusercontent.com/1515135/70692453-40f60000-1c70-11ea-95ac-dcaa9cb1a78d.png)

**Comment by scragly** [comment]
Looks good. Others will need to obviously give feedback too, but I like that one. 

As a note, the final image will need to be 128x128px.

Should we use a red one for when they leave, a green one for when they join and a blue one for other information?

**Comment by MarkKoz** [comment]
> As a note, the final image will need to be 128x128px.

No problem; I make them as SVGs anyway. I just export to 24x24 because that is it's actual display size.

> Should we use a red one for when they leave, a green one for when they join and a blue one for other information?

I don't mind implementing that but it does honestly feel like too minute of a detail. That doesn't mean it's a bad thing though, I suppose. Maybe yellow for switching channels.

**Comment by LordHemlock** [comment]
I think having a blue icon for all is fine enough.  If it becomes needed later, we can do it later.

**Comment by lemonsaurus** [comment]
I like the speaker. We've color coded everything else, so I kind of think @scragly's suggestion to use red and green for suitable events is a good one.

Historically we've used red for anything negatory (leaving, getting banned, removing), green for anything affirmative (joining, being unbanned, adding), and blue for anything that falls inbetween (edits, information, etcetera). We've never used yellow because white on yellow has poor legibility.

**Comment by MarkKoz** [comment]
I'll take that thumbs up as 3 votes for a speaker, so that is what I'll go with. I will create the red and green icons too. Thanks.
