### ISSUE TITLE
New custom user statuses should appear in !user

### ISSUE THREAD

**Issue by syntaxaire** [python-discord/bot#647]
Related to #620, we must moderate the new custom statuses, but they don't appear when we issue a !user command. These should be included to form part of the channel record for moderation purposes.

**Comment by kosayoda** [comment]
appy aperture is working on this

**Comment by AnonGuy** [comment]
> appy aperture is working on this

can confirm

**Comment by SebastiaanZ** [comment]
There's currently a PR that changes quite a bit in regards to the `!user` command, so we may want to determine a merge order to avoid conflicts. See #637.

**Comment by syntaxaire** [comment]
See also python-discord/organisation#157 - consensus was "we moderate these when we see them"

**Comment by AnonGuy** [comment]
@SebastiaanZ I just merged the two branches locally, and there don't seem to be any merge conflicts.

**Comment by AnonGuy** [comment]
That being said, it might be wise to merge #648 first, since the PR's pretty much done and the diff's fairly small.
