### ISSUE TITLE
Adding extra functionality and refinements to !remind

### ISSUE THREAD

**Issue by scragly** [python-discord/bot#663]
Possible improvements have been discussed for the reminder command:

- Repeating reminders
  e.g. `!remind "@Admins meeting in 5 minutes" every Sunday at 20:55`
- More natural time parsing
- DM reminders
- Allowing reminders in functional channels such as #dev-contribs which currently is disallowed for non-staff.

**Comment by sco1** [comment]
Adding a couple more enhancements:

- Add reminder ID to the confirmation embed
- Add the target datetime to the confirmation embed (in addition to the currently provided timedelta)

**Comment by scragly** [comment]
I seem to have forgotten to add also:
- Jump link to original invoke msg

**Comment by sco1** [comment]
That was added by #466

**Comment by scragly** [comment]
Oh, very nice.

**Comment by sco1** [comment]
For scoping I'm going to split this into a couple discrete chunks:

Chunk the first (low hanging fruit)
  * Reminder ID in confirmation embed
  * Target datetime in confirmation embed
  * Expand whitelist for non-staff

Chunk the second (requires backend changes)
  * Repeating reminders
  * DM reminders

Chunk the third (converter change has broader implications)
  * More natural time parsing

**Comment by Shivansh-007** [comment]
For the more language time parsing feature, can we make use of [`parsedatetime`](https://github.com/bear/parsedatetime)?

**Comment by ChrisLovering** [comment]
we already have [`arrow`](https://arrow.readthedocs.io/en/latest/) as a dependency, so maybe we can make use of that?

**Comment by Shivansh-007** [comment]
> we already have [`arrow`](https://arrow.readthedocs.io/en/latest/) as a dependency, so maybe we can make use of that?

That would do it too! Yes 👍

**Comment by wookie184** [comment]
The points here other than "Repeating reminders" and "DM reminders" seem to have been completed or have their own tracking issues. I don't think repeating/dm reminders are super important so i'll close this and let anyone create separate issues for them if they have a use case.
