### ISSUE TITLE
Help channel cross-post filter

### ISSUE THREAD

**Issue by kosayoda** [python-discord/bot#664]
Users posting the same question in all the help channels at once is a problem that can easily be solved by the bot. Thus, let's add a filter to catch and notify those users.

**Implementation details:**
- [ ] Cache one message-user pair per help channel (the latest sent message)
- [ ] Add a filter that checks if the message and user matches any in the cache
- [ ] Remove all but one message, then automute the user for a short duration
- [ ] Notify the user about posting the same question to multiple help channels

**Comment by ikuyarihS** [comment]
If the question spans across multiple messages ( For example, message 1 2 and 3 ), would this means we would only cache the 3rd message? What if the user goes to another channel and paste only the 1st and 2nd messages and/or copy paste everything into a new message ( 4th ) and post that 4th in another channel?

In this case would checking for contents and check for similarities across most recent messages ( most recent 3 ) be a better case? For example above 70% from `difflib`?

**Comment by Den4200** [comment]
This is irrelevant with our new help channel system.
