### ISSUE TITLE
Support Anti-Spam Checks Across Channels

### ISSUE THREAD

**Issue by MrHemlock** [python-discord/bot#665]
There should be an anti-spam filter which checks message history across several channels. This should catch users who send messages in multiple channels which are duplicates and/or sent in quick succession. I'm not sure on the implementation. It seems complicated since history can only be retrieved on a per-channel basis, and we have a lot of channels.

Original message:

> So for context, we just had an incident where someone was auto spamming a channel.  The bot caught the initial spam, gave them the 10 minute mute, as expected.  However, after they were unmuted, the spam continued, at the same rate and enough that it should have triggered a second mute.  It didn't.  This needs to be investigated.

**Comment by sco1** [comment]
> at the same rate and enough that it should have triggered a second mute

Are you sure this is true? There really isn't enough information here to diagnose what, if anything, needs to be changed here.

**Comment by SebastiaanZ** [comment]
I checked and they did not seem to have had activity after their first mute that would trigger an AntiSpam rule normally. Currently, AntiSpam rules look at activity in a single channel, not activity spread out over multiple channels.

**Comment by LordHemlock** [comment]
And I think that's worth looking into as a tweak, at the very least.

**Comment by SebastiaanZ** [comment]
In addition to checking the rules for a relevant chunk of channel history, we could also check the rules against a chunk of user history. Downside is that we'd need another `async for` history call, but it would catch people spamming messages across channels.

**Comment by MarkKoz** [comment]
Is something still being investigated?

Can someone clarify what exactly needs to be actioned for this issue? Has the goal been changed to adjust filters to detect spam across channels?

**Comment by VRArt1** [comment]
Considering this is closed does that mean it's now supported? If so can someone suggest a bot that has this feature in it?

**Comment by HassanAbouelela** [comment]
@VRArt1 The current antispam system collects all messages within a time frame using a custom cache, regardless of the channel. You can see the code for that here:
https://github.com/python-discord/bot/blob/main/bot/exts/filters/antispam.py#L179-L182

That file is generally where most of the overhead of the antispam filtering exists.

**Comment by NelsonBlvd** [comment]
I know this is closed, but it’s listed under python, is it a useable open source bot? Because THIS is what I’ve needed for so long. Or is this a sever specific bot?

**Comment by MarkKoz** [comment]
@NelsonBlvd Yes, this code is open source. See https://github.com/python-discord/bot/blob/main/LICENSE The bot is designed for our community's needs. So in that sense, it is server-specific. However, you're welcome to run your own instance of it.

**Comment by NelsonBlvd** [comment]
Oh I would absolutely love to but I have no idea where to even begin

-Dylan Nelson
________________________________

**Comment by HassanAbouelela** [comment]
@NelsonBlvd we have a [guide on our website](https://www.pythondiscord.com/pages/guides/pydis-guides/contributing/bot/), but it requires that you set up other services, and set up your server in a very particular way.

If you don't want to do that, that leaves you with taking the relevant parts of the code that you want to use (linked above), and write a thin wrapper which just calls them.
