### ISSUE TITLE
Display time delta for infraction expiration

### ISSUE THREAD

**Issue by fiskenslakt** [python-discord/bot#668]
# Abstract

In addition to showing the expiration datetime in infraction searches, display the time delta between the expiration and creation of the infraction.

This is optional, but it would also be useful knowing how much time is left until the infraction expires. I may create a separate issue for this, and if so, link it here. EDIT - #669

EDIT2 - I would also like to see this time delta in the bot message confirmation after an infraction has been given out.
Example:
:incoming_envelope: :ok_hand: applied mute to @lemon until 2019-12-01 21:20 (7 days; 42 infractions total).

That last thing though is not mandatory for this issue to be closed. But I think it would be nice, because you could confirm immediately whether your duration was parsed as you expected.

# Specification

Current implementation:
```
Created: 2019-11-23 20:09
Expires: 2019-11-30 20:15
```
Suggested implementation:
```
Created: 2019-11-23 20:09
Expires: 2019-11-30 20:15 (7 days, 6 minutes)
```

The actual granularity of this can vary as durations get longer. For example, if a duration is longer than 30 days, we could put `(1 month)` rather than the exact amount of days. Same goes for years.

If the exact implementation of this doesn't warrant discussion, the one who implements this feature should use their best judgement on when to use the following units of time: (years, months, days, hours, minutes).

For fun, we could put `(∞)` next to permanent infractions.

# Rationale

Confirming the infraction duration should take little effort. If the infraction spills over multiple months, days, or hours for example, it requires more than a second of thinking to determine if the duration is right.
Examples:
```
Created: 2019-11-23 20:58
Expires: 2019-11-23 21:03  <-- 5 minutes, not 1 hour
```
```
Created: 2019-11-23 23:59
Expires: 2019-11-24 00:00 <-- 1 minute, not 1 day or 1 hour
```

# Motivation

I'm lazy.

**Comment by ikuyarihS** [comment]
This sounds interesting, I would like to work on this.

Should we make this a helper function to return the difference between any two given datetime objects in that format? That way we can choose where and when we apply this.

**Comment by ikuyarihS** [comment]
Here's a quick example of what I thought of:
```py
TIME_MARKS = (
    (60, 'second'),  # 1 minute
    (60, 'minute'),  # 1 hour
    (24, 'hour'),  # 1 day
    (7, 'day'),  # 1 week
    (4, 'week'),  # 1 month
    (12, 'month'),  # 1 year
    (1, 'year')  # dumb the rest as year
)

def get_duration(date_from: datetime, date_to: datetime) -> str:
    div = abs(date_from - date_to).total_seconds()
    results = []
    for unit, name in TIME_MARKS:
        div, amount = divmod(div, unit)
        if amount > 0:
            results.append(f"{int(amount)} {name}{'s' if amount > 1 else ''}")
    return ', '.join(results[::-1][:2])
```
When ran against this
```py
for a, b in (
    (datetime(2019, 12, 12, 0, 1), datetime(2019, 12, 12, 12, 0, 5)),
    (datetime(2019, 12, 12), datetime(2019, 12, 11, 23, 59)),
    (datetime(2019, 11, 23, 20, 9), datetime(2019, 11, 30, 20, 15)),
    (datetime(2019, 11, 23, 20, 58), datetime(2019, 11, 23, 21, 3)),
    (datetime(2019, 11, 23, 23, 59), datetime(2019, 11, 24, 0, 0)),
):
    print(a, b, '->', get_duration(a, b))
```
Will give these as results:
```py
2019-12-12 00:01:00 2019-12-12 12:00:05 -> 11 hours, 59 minutes
2019-12-12 00:00:00 2019-12-11 23:59:00 -> 1 minute
2019-11-23 20:09:00 2019-11-30 20:15:00 -> 1 week, 6 minutes
2019-11-23 20:58:00 2019-11-23 21:03:00 -> 5 minutes
2019-11-23 23:59:00 2019-11-24 00:00:00 -> 1 minute
```

**Comment by fiskenslakt** [comment]
@ikuyarihS this looks promising, and I agree a helper function is the right direction to go in. Let me know if you have any questions along the way.

I've assigned you this issue, and deferred #669 until this issue is fleshed out by you. I look forward to reviewing your progress.

**Comment by ikuyarihS** [comment]
@fiskenslakt I have a question, where would you want to apply this to? Currently I will add it to the embed showing the Expiration ( Expires: date ( duration ) ) like in your example, but I found that there are more than one place with this information - The embed sent to user for example.

In that case, should I also show the user how long ( in human readable format ) their mute / ban will be for, not just when it will expire?
