### ISSUE TITLE
Display time left until expiration of infraction

### ISSUE THREAD

**Issue by fiskenslakt** [python-discord/bot#669]
# Abstract

In addition to the creation and expiration datetimes displayed in an infraction search, display how much time is currently left until the infraction expires at the time of invocation.

# Specification

Proposal:
```
Created: 2019-11-23 20:09
Expires: 2019-11-30 20:15
Remaining: 5 days, 1 hour
```

In regards to granularity, my proposal is to only show the 2 largest units. So if it expires in more than a year, show only years and months. If over a month, show only months and days. If over a day, show days and hours. If over an hour, show hours and minutes. And finally, if over a minute, show only minutes, don't show seconds.

If it expires in less than a minute, either display "less than a minute" or just "1 minute" if that's too verbose.

If the infraction has already expired, show "Expired".
If the infraction never expires, perhaps this field should be omitted entirely.

# Rationale

Similar to #668, confirming how long until an infraction expires should require as little effort as possible.

# Motivation

See my motivation in #668.

**Comment by fiskenslakt** [comment]
Putting a pause on this issue until #668 is fleshed out.

**Comment by ikuyarihS** [comment]
Since #668 is done, can I work on this?

**Comment by scragly** [comment]
Sure thing. I'll assign you.
