### ISSUE TITLE
!ping command

### ISSUE THREAD

**Issue by Akarys42** [python-discord/bot#697]
## Abstract
For now, we don't have any way to know when the bot is laggy if it is the bot, the site or discord API that is laggy. This command can be used to report the latency of all of them. 

## Specification
When the command `!ping` is entered, the bot should respond with an embed containing the following information : 
* Bot latency : delta between the message `!ping` creation time and the moment the bot start processing the command. 
* Site latency : time taken by the bot to reach the site API. The implementation details needs to be determined : do we just run a ping to the site, or we use a special route?
* Discord latency : API latency [reported by discord](https://status.discordapp.com/)
In case the bot fail to gather any information, the command should gracefully fall back and display a red cross instead of the missing data, and still display the other data.

**Comment by Akarys42** [comment]
Forgot to mention @biskette's note : the embed should be named `Pong! `

**Comment by MarkKoz** [comment]
I'm fine with everything here, but just one comment:

>  do we just run a ping to the site, or we use a special route?

I wonder, are the site and bot on the same machine? In that case, I'd imagine there really wouldn't be any significant network latency between them.

**Comment by Xithrius** [comment]
The website and bot are on the same machine. It is probably still worthwhile to ping the website, as it does goes through CloudFlare. I'll be taking this issue if yall don't mind.
