### ISSUE TITLE
Eval shouldn’t strip non-blank lines

### ISSUE THREAD

**Issue by AG4lyf** [python-discord/bot#699]
As talked in https://discordapp.com/channels/267624335836053506/635950537262759947/639484028012986369

Bot strips out /n lines 
example can be 

```python
def reformat_(a):
    len_a = 8 - len(a)
    a = " " * int(len_a / 2) + a + " " * int(len_a / 2)
    return a
print(reformat_("Hii"))
```

**Why change it?**

Changing it can lead to a better precise output.  also bot already limit the output to 10ish lines . so no harm in adding whitespaces.

**Comment by AG4lyf** [comment]
expected output - `     Hii         `
output - `Hii`

**Comment by Akarys42** [comment]
Hi, can I work on this?

**Comment by AG4lyf** [comment]
sure
