### ISSUE TITLE
Prevent the role syncer from wiping the database table during API latency

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/bot#704]
## Summary
The role synchronization utility occasionally starts before the bot's role cache has been filled resulting in all the roles being deleted from the database table.

## Background
Since we frequently add and delete roles from our guild, we have an automated synchronization utility that keeps the database up to date with the actual roles on our guild. Currently, the mechanism waits for the `READY` signal to be dispatched by `discord.py` after the bot starts, as that typically signals that the bot's caches have been synchronized with the actual state of the guild.

However, we've observed that in rare cases, the `READY` event may be dispatched before this has happened. The most likely cause is high latency between the bot and the Discord API, resulting in the guild information only being received after the maximum delay period `discord.py` uses to wait for this information. Unfortunately, if `discord.py` does not receive the information in time, it instantiates the cache with an empty list, making it appear as if the guild has no roles.

## Related issues
I think the mechanism behind this issue also caused a number of other bugs we have observed in the past, such as channels not being available after `READY` had been dispatched resulting in `get_channel` returning `None` (e.g., part 2 of #390; which was solved by #380). I can't find individual issues other than the Reddit channel/#390, but I've observed the same bug with the watch channels as well. These instances were solved by replacing the `get_channel` method with the `fetch_channel` method, which fetches the channel directly from the API (see #380).

(*Note: all of these simple channel relays have been replaced by webhooks since.*)

## Proposed solution
While the related issues above were solved at the cost of an additional API call (`fetch_channel`), we may be able to do better. After a lot of digging by @MarkKoz and some experimentation by myself, I would like to propose a two-fold solution to prevent this from happening again:

#### 1. Use `GUILD_AVAILABLE` instead of `READY`
Instead of relying on the potentially misleading `READY` event, we should instead rely on the `GUILD_AVAILABLE` signal using the appropriate event listener. In theory, this event should only fire after the guild's data has become fully available to the bot. I think it's still a good idea to have this event listener validate the relevant caches as well. This event fires separately for every guild the bot is a member of, but since we only care about one guild anyway, a simple guild ID check could serve as the sentinel.

Now, I do think this event may also fire after the guild has become temporarily unavailable due to issues with the Discord API. (Similar to what we've all probably experienced in our clients.) However, I think this would be a useful feature, not a bug: If our bot lost the connection to Discord temporarily, it's probably a good idea to synchronize the database after the connection has been re-established to catch up with changes that have happened in the meantime. 

#### 2. Require human intervention for large diffs
Since I can't guarantee that the first part of this solution will prevent an empty role cache in all circumstances, I'd like to introduce a barrier that prevents the bot from sending a request that deletes all the roles from the database. The idea is simple: We rarely add, modify, or delete a huge number of roles within a short time period, so we could have the bot ask for confirmation before sending a very large diff to the API.

The mechanism could be fairly simple: Have the bot ping the core-dev role with a message/embed detailing the diff and make it wait for confirmation in the form of a reaction by a core-dev. Since a "freak" occurrence may happen during both the automatic synchronization and a manually invoked synchronization, I think we should add this check to both forms of synchronization.

Obviously, we'd have to think about the thresholds for these diffs, balancing the false negatives and the false positives. I think these thresholds are reasonable:

- Always ping when the diff would signal that our guild has no roles at all
- Ping when the synchronization would involve changes to 10 roles simultaneously

For the latter, it's important to realize that adding, altering, or deleting a lot of roles manually one-by-one (e.g., when reordering role positions or adding/removing code jam team roles) will trigger individual synchronization events per role. This means that such a relatively common action should not trigger the human intervention mechanism. That said, if it would, I don't think it's a huge sacrifice to make to prevent more malicious synchronizations.

## Implementation details

The implementation details still have to be discussed. For a start, even if we implement the two solutions mentioned above, I don't it's a bad idea to do an explicit `fetch_roles` to request the latest list of roles from the API before doing a bulk synchronization. It's not an option for now, but that method will be introduced in `discord.py 1.3.0` (although its release may take a while).

In addition, since we've seen related bugs in the past, we could opt for a custom `bot.wait_until_guild_available()` as a sibling to the `bot.wait_until_ready()` to implement the first part of our solution. Now that we've subclassed `discord.commands.ext.Bot`, it's trivial to add such a waiting mechanism that waits until `guild.available` is `True` and the core caches have been validated as non-empty. (I think roles, members, channels would do.) This would give us an easy way of delaying tasks that rely on the guild's information being available in a similar way to what `wait_until_ready` does.

**Comment by MarkKoz** [comment]
> Now, I do think this event may also fire after the guild has become temporarily unavailable due to issues with the Discord API.

Possibly yes since it is dispatched after the `ready` event, which is known to be dispatched when reconnecting.

> Have the bot ping the core-dev role with a message/embed detailing the diff and make it wait for confirmation in the form of a reaction by a core-dev.

Wait indefinitely or have a time out and abort? Also concerned a reaction may not be explicit enough.

>  Now that we've subclassed discord.commands.ext.Bot, it's trivial to add such a waiting mechanism that waits until guild.available is True

Why do it that way? Using `on_guild_available` and then dispatching a custom event from it is probably simpler.

**Comment by SebastiaanZ** [comment]
> Possibly yes since it is dispatched after the `ready` event, which is known to be dispatched when reconnecting.

Typically. it's dispatched as soon as the bot receives and has processed the guild information from the API, which is normally before the `READY` event (unless the latency issues happen).

```
Dec 18 19:26:12 Bot: |                           bot.api |    DEBUG | Scheduled 33 pending logging tasks.
Dec 18 19:26:12 Bot: |                 bot.cogs.sync.cog |    DEBUG | Guild Bot Test Python has become available.
Dec 18 19:26:12 Bot: |                 bot.cogs.sync.cog |    DEBUG | Guild Pythonic has become available.
Dec 18 19:26:14 Bot: |                  bot.cogs.logging |     INFO | Bot connected!
Dec 18 19:26:14 Bot: |     bot.cogs.moderation.scheduler |    TRACE | Rescheduling infractions for Infractions.
Dec 18 19:26:14 Bot: |     bot.cogs.moderation.scheduler |    TRACE | Rescheduling infractions for Superstarify.
Dec 18 19:26:14 Bot: |                 bot.cogs.sync.cog |     INFO | Starting `roles` syncer.
Dec 18 19:26:14 Bot: |                 bot.cogs.sync.cog |    DEBUG | On ready signal given.
```

I'm not sure if it ever happens without a reconnect/ready event, but the docs suggest that it may. (As there's also an event for a guild becoming unavailable; my guess this is the same unavailable status you sometimes get in the client during connection issues.)

> Wait indefinitely or have a time out and abort? Also concerned a reaction may not be explicit enough.

Why would a reaction not be explicit enough? Do you fear misclicks?

My preference would be a time-out since we can always restart the synchronization process with a command.

> Why do it that way? Using `on_guild_available` and then dispatching a custom event from it is probably simpler.

Maybe. I was considering the fact that we use the `bot.wait_until_ready` a lot and an analogue is handy for things that only need to be done once.

**Comment by MarkKoz** [comment]
Sorry, we're technically both right. I should have clarified I meant it comes after the webhook `READY` but as we've discussed this gets delayed by discord.py until the guilds are processed. I mean that if we know the ready event is dispatched during reconnect, this means guilds are processed during reconnect (unless the `READY` already gives guilds as available but I believe they are always unavailable in `READY` and must come from `GUILD_CREATE`) and consequently `on_guild_available` is dispatched on reconnect. It could also be the case that a guild goes unavailable and back to available without any reconnect but I've not seen this. Regardless, that it's fine if it happens.

> Maybe. I was considering the fact that we use the bot.wait_until_ready a lot and an analogue is handy for things that only need to be done once.

Sorry I misread and thought you were talking about a custom event instead of a `wait_until`-style coroutine. That type of coroutine would still be implemented using `on_guild_available` I think.

```py
def __init__(self):
    self._guild_available = asyncio.Event()

async def on_guild_available(guild: discord.Guild):
    if guild.id != CONSTANT:
        return

    if not guild.roles or not guild.members or not guild.channels:
        # What do we do here? I doubt it'll dispatch another guild_available.
        # Kind of screwed and something is probably really broken if this ever happens
        # (assuming there wasn't an exodus and no one purged channels/roles)
        return

    self._guild_available.set()

async def on_guild_unavailable(guild: discord.Guild):
    self._guild_available.clear()

async def wait_until_guild_available():
    await self._guild_available.wait()
```

**Comment by SebastiaanZ** [comment]
> Sorry I misread and thought you were talking about a custom event instead of a wait_until-style coroutine. That type of coroutine would still be implemented using on_guild_available I think.

Right, this was pretty much exactly what I had in mind.

**Comment by MarkKoz** [comment]
I think it'd be better to ask to run the sync command manually rather than using reactions. Partially to avoid misclicks but mainly because it's _much_ simpler to implement.

**Comment by SebastiaanZ** [comment]
> I think it'd be better to ask to run the sync command manually rather than using reactions. Partially to avoid misclicks but mainly because it's much simpler to implement.

The main thing is that I'd also want an excessive diff check for manually invoked synchronizations and have the bot respond with "This is what I'm about to do, is it okay?". When you run a manual synchronization command after that, you don't know if things have significantly changed after that last warning.

As an example, when Joe ran the user synchronizer manually a couple of days ago, it promptly updated 20k+ members. That's the sort of thing I'd like detected with a confirmation option before the bot goes ahead and does it. That gives us the chance to check the database table and/or at least consider what's going to happen. (In this case, it was *probably* caused by a combination of restoring the roles tabled, which meant it had to add back roles to everyone, and the broken user update detection, which ignored username, discriminator, and avatar hash changes.)

**Comment by MarkKoz** [comment]
It slipped my mind that the command could have the same problems as the automatic syncing. So reactions it is. The syncer code may need to be restructured to facilitate this. I'll be looking into it.
