### ISSUE TITLE
Implement automated change of names for the staff main channel

### ISSUE THREAD

**Issue by manusaurio** [python-discord/bot#708]
The same way our off topic channels change their name every day, the staff one (`464905259261755392`, **_whatever its name is now_**) could do the same.

This should have the same interface of commands [as the off topic channels](https://github.com/python-discord/bot/blob/master/bot/cogs/off_topic_names.py), giving the possibility to add names, delete them, search them, and everything else, so most of the code should be _shared_ (beware #658). But the name pools for each category, _off topic_ and _staff_, should not. This requires a bit of work with the site.

The staff channel should probably have a prefix for its name, so it can be easily identifiable (maybe `stf-`?)

**Comment by manusaurio** [comment]
I could try this if that's okay.

**Comment by MarkKoz** [comment]
Hello @manusaurio, have you made any progress on this?

**Comment by manusaurio** [comment]
I haven't, and I should have said something earlier, my apologies. I'm also afraid I won't be able to do so for now and the following months, so this could be assigned to anyone else.

**Comment by Senjan21** [comment]
In consensus, we have decided that we don't want automatic renaming of the lounge name.
