### ISSUE TITLE
Snekbox !eval output of exactly 11 lines is truncated

### ISSUE THREAD

**Issue by bast0006** [python-discord/bot#709]
If snekbox would return an output of exactly 11 lines, with 10 newline characters, it will truncate the final returning line without sending the output to be uploaded. 

The source is a mismatch in the snekbox cog, within `format_output`--the number of lines to output is set to `output.count("\n")`and checked against `> 10` but later output is sliced with `output.split("\n")[:10]`. 

.split() returns up to 11 items if there are exactly 10 `\n`'s which results in the loss of the final line of output.

Testcase:
!e ```py
print(*range(11), sep="\n")
`\``
The final element (10) is missing.

**Comment by Akarys42** [comment]
Hi, can I work on this?
