### ISSUE TITLE
Suggest a list of available commands in case of typos

### ISSUE THREAD

**Issue by ikuyarihS** [python-discord/bot#742]
When we try to invoke a command, we can make little typos, for example
`!muet @shirayuki 72H oh come on, cant you make a proper issue?`

In this case, the bot can then steps in and do a friendly suggestions:
`did you perhaps mean`
`!mute @shirayuki 72H oh come on, cant you make a proper issue?`

The typo in this example was `!muet` when trying to do `!mute`

This will greatly relieve the stress of typing every command rights, and thus enhancing the experience with the bot much further.

**Comment by SebastiaanZ** [comment]
We should include a [`Command.can_run`](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.Command.can_run) check to make sure the individual is actually allowed to run the command within the given context.

**Comment by Denayder** [comment]
I can work on this if no one (@ikuyarihS) wasn't planning on doing it :)

**Comment by F4zii** [comment]
We could also include misspelt arguments, but that's another different way of handling typos since it is different for every command

**Comment by F4zii** [comment]
I would love to work on this in the future :+1:
