### ISSUE TITLE
Add thousand separators to Members count in !server

### ISSUE THREAD

**Issue by ikuyarihS** [python-discord/bot#744]
Right now, some numbers in the embed result of `!server` do not have thousand separators, here is a screenshot of it:

![image](https://user-images.githubusercontent.com/19921765/74096767-ad3c9500-4b35-11ea-9c9a-03e40d3e338f.png)

Like this part, it does add separators:
![image](https://user-images.githubusercontent.com/19921765/74096770-b6c5fd00-4b35-11ea-8d6d-36b2fa45f8df.png)

But this part it does not:
![image](https://user-images.githubusercontent.com/19921765/74096772-be85a180-4b35-11ea-9db5-2afdab5a7ee5.png)

The command can be found here in [bot/cogs/information.py](https://github.com/python-discord/bot/blob/552048da27e8bf3d45a77b13e7e1920e3309ada5/bot/cogs/information.py#L100) and the part that is responsible for adding thousand separators is here
```py
        embed = Embed(
            colour=Colour.blurple(),
            description=textwrap.dedent(f"""
                **Server information**
                Created: {created}
                Voice region: {region}
                Features: {features}
                **Counts**
                Members: {member_count:,}
                Roles: {roles}
                Text: {text_channels}
                Voice: {voice_channels}
                Channel categories: {category_channels}
                **Members**
                {constants.Emojis.status_online} {online}
                {constants.Emojis.status_idle} {idle}
                {constants.Emojis.status_dnd} {dnd}
                {constants.Emojis.status_offline} {offline}
            """)
        )
```

**Comment by Denayder** [comment]
Hi - I currently have #741 open - I can add this into the refactor really easily, if you guys would like me too :)

**Comment by sco1** [comment]
Yes, that makes sense
