### ISSUE TITLE
Add ability to remove bot tag responses.

### ISSUE THREAD

**Issue by Numerlor** [python-discord/bot#745]
With the new fuzzy tags, there's a chance an user may think something which is not a tag is one; resulting in a similar tag being fetched 
(`!t def` as an example resulting in a tag through the whole page)

Adding the ability to remove them (perhaps when it was fuzzy matched) would solve this and perhaps some others when a tag's purpose is misremembered.

**Comment by sco1** [comment]
What's the proposed mechanism to accomplish this?

**Comment by Numerlor** [comment]
I was thinking about deleting it on detecting the trash can reaction, like eval's output for example.

**Comment by MarkKoz** [comment]
I'm fine with that approach. Simple and familiar. Let's just always do it rather than only when using fuzzy matching.

**Comment by ks129** [comment]
I'll work on it.
