### ISSUE TITLE
Pagniation breaks when skipping to last page

### ISSUE THREAD

**Issue by mosguinz** [python-discord/bot#746]
Using the ⏭️ reaction to skip to the last page causes an exception.

![image](https://user-images.githubusercontent.com/20041393/74332220-dbd19e80-4dc7-11ea-82dd-05ab17f593dd.png)

The prime suspect appears to be this line:

https://github.com/python-discord/bot/blob/7dbd4d41d8dd00d73a63195b4a83c728d40fb042/bot/pagination.py#L413

Should probably instead be:
```py
current_page = len(paginator.pages) - 1

**Comment by SebastiaanZ** [comment]
Thanks! Good spot, although your suggested fix is currently equal to the bug:

> Should probably instead be:
> 
> ```python
> current_page = len(paginator.pages - 1)
> ```

I suspect you mean this:

https://github.com/python-discord/bot/blob/7dbd4d41d8dd00d73a63195b4a83c728d40fb042/bot/pagination.py#L229

(This is from the LinePaginator, which does work)

Do you want to make a PR for this?

**Comment by mosguinz** [comment]
> ~~although your suggested fix is currently equal to the bug~~
Yeah, I only saw it after posting haha.

> Do you want to make a PR for this?
And sure thing.
