### ISSUE TITLE
Upgrading to Python 3.8

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/bot#758]
## Summary
We should upgrade the Python version of the bot to Python 3.8

## Rationale
Python 3.8 offers significant improvements in the area of writing unittests for asyncio; in fact, you could say that Python 3.8 finally brings proper asyncio-support to Python's built-in unittest framework. By upgrading to Python 3.8, we'd no longer have to implement custom mock classes and decorators to make our test suite compatible with the plentiful asynchronous features of the bot that we're trying to test.

## Considerations
One reason to potentially hold back an upgrade is the relative young age of Python 3.8. However, with the release of Python 3.8.1, I'm not convinced we have to wait longer with an upgrade; I'd consider Python 3.8 to be mature enough at this point.

Another obvious consideration is whether or not all of our dependencies support Python 3.8. After upgrading my virtual environment to Python 3.8 locally, I can say that I haven't discerned any issues both in creating the dependency graph as well as running the bot. The test suite, while not showing major issues (i.e., some tests fail due to minor issues), does need to be updated to make use of the now built-in asyncio support in everything unittest.

Edit: The minor issue seen in the test suite was caused by an upstream bug in discord.py instead. I've submitted a PR to fix it: Rapptz/discord.py#2570.

**Comment by scragly** [comment]
Agreed, now that there's a .1 release, I don't have any qualms with updating properly.

**Comment by MarkKoz** [comment]
For reference, [here](https://docs.python.org/3.8/whatsnew/changelog.html) are bugs that have been fixed since the 3.8.1 release. At a glance, I see only one fix which may be relevant to us:

* bpo-39082: Allow AsyncMock to correctly patch static/class methods

**Comment by SebastiaanZ** [comment]
Thanks, that's something to keep in mind. We could wait for 3.8.2 although I don't think this is currently a blocking issue for us. Our current Python version, 3.7, barely has any async unittest support.

**Comment by MarkKoz** [comment]
discord.py 1.3.2, which fixes the aforementioned upstream bug, was released recently. I see nothing else blocking this any further.

**Comment by MarkKoz** [comment]
Once it is updated, separate issues should be made for making changes to utilise features new to 3.8 (like updating the test mocks).

**Comment by MarkKoz** [comment]
Would we want to pin an exact version or let the patch version go up?

**Comment by sco1** [comment]
Patch version should be fine
