### ISSUE TITLE
Filters should not apply to staff members

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/bot#767]
Currently, we have certain channels whitelisted for certain filters and some filters apply to all members, even Owners cannot post filetypes that aren't on the whitelist!

Please change this so that absolutely all filters will ignore all staff members. It is not necessary to whitelist staff channels or to keep any other kind of exceptions to the filters once this very simple exception has been added, so please clean up any such exceptions while you're at it.

**Comment by lemonsaurus** [comment]
This was not resolved by #790, which only makes the AntiMalware filter ignore staff.

We want AntiSpam and Filtering to also ignore staff.

@ks129, would you mind opening a new pull request to address the remaining two cogs?

**Comment by ks129** [comment]
https://github.com/python-discord/bot/blob/master/bot/cogs/antispam.py#L151 https://github.com/python-discord/bot/blob/master/bot/cogs/filtering.py#L131 @lemonsaurus There is already checks.

**Comment by lemonsaurus** [comment]
Looks like you're right. It appears for AntiSpam, this is already solved, but on Filtering we have a config option with a role whitelist where not all staff members are on the whitelist.

I kind of feel like this is logic duplication, though. We probably be using the same whitelist for all three of these cogs, rather than solving the problem in three different ways. Perhaps we should refactor the approach taken in AntiMalware and AntiSpam to use the same role whitelist that Filtering does, and then add *HELPERS to that whitelist.

@SebastiaanZ What do you think of this approach?

**Comment by lemonsaurus** [comment]
Either way, I've added the Helpers now to the Filtering whitelist which should resolve this issue, but I still think we should consider refactoring this so that we use the same approach for all three of these related cogs.
