### ISSUE TITLE
Add pep8-naming to linting toolchain

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/bot#775]
We've decided to use this plugin in our linting toolchain, which allows us to test things like variable name casing (no camelCase please!) and whether classes and methods use `cls` and `self`.

## Implementation
Here are the errors it can catch:

code | sample message
-- | --
N801 | class names should use CapWords convention
N802 | function name should be lowercase
N803 | argument name should be lowercase
N804 | first argument of a classmethod should be named 'cls'
N805 | first argument of a method should be named 'self'
N806 | variable in function should be lowercase
N807 | function name should not start and end with '__'
  |  
N811 | constant imported as non constant
N812 | lowercase imported as non lowercase
N813 | camelcase imported as lowercase
N814 | camelcase imported as constant
N815 | mixedCase variable in class scope
N816 | mixedCase variable in global scope

We have not decided exactly which of these we should ignore, so it will be up to the person who handles this issue to discuss this with the core devs and come to a consensus on whether we should ignore some of these. It will probably be easier to see which ones here are not necessary after actually running a lint with this plugin on our current codebase.

The person implementing this will also need to fix all the linting errors that occur once this has been added to the toolchain.

## Steps
- [ ] Add the plugin to the toolchain
- [ ] Run it and look through the errors that are created. Are any of them out of touch with our style guidelines, and should we ignore some of these rules? Discuss with the core developers if you think so.
- [ ] Fix all the linting problems.

**Comment by sco1** [comment]
I'll add this in with #811 since we're already making other linting changes.

Running against the branch in its current state yields the following errors:

```bash
$ flake8 .
.\bot\utils\__init__.py:57:40: N803 argument name 'F' should be lowercase
.\tests\base.py:34:10: N802 function name 'assertNotLogs' should be lowercase
.\tests\base.py:84:10: N802 function name 'assertHasPermissionsCheck' should be lowercase
.\tests\bot\cogs\test_snekbox.py:92:56: N803 argument name 'mock_Signals' should be lowercase
.\tests\bot\cogs\test_snekbox.py:99:54: N803 argument name 'mock_Signals' should be lowercase
.\tests\bot\cogs\sync\test_base.py:87:10: N802 function name 'test_send_prompt_returns_None_if_channel_fetch_fails' should be lowercase
```

I think we're fine to add `pep8-naming` without ignoring any of its error codes.

The `utils\__init__.py` issue is with one of the methods of a [`CaseInsensitiveDict` class](https://github.com/python-discord/bot/blob/master/bot/utils/__init__.py#L13); this isn't actually used anywhere (it was a Snake cog thing) so it can just be fragged.

Otherwise, the remaining errors can either be fixed or `noqa`ed, where applicable.
