### ISSUE TITLE
Tags overhaul

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/bot#777]
## Abstract

After much deliberating, we've decide to change the way that tags are added, removed and edited. This has been a controversial issue, but the executive staff has voted to go for this solution and we're not going to be discussing it further for the time being. 

In the new system, tags will simply be markdown files stored in this repository. This means we will need to simplify the way the bot handles tags. This will democratize the tags management process, allowing anyone (including non-staff) to make pull requests to add, remove, or edit the tags. It will also allow us to have a review process for this content, which is useful.

## What needs to be done?
Currently, all the tags are supposed to be at https://github.com/python-discord/meta/tree/master/tags, but this folder is not quite in sync with the actual tags in our database. The first task will be to grab these tags from meta to your local drive,

- [ ] Grab the tags in https://github.com/python-discord/meta/tree/master/tags and update the ones that aren't in sync with the database. This means calling all our tags and double checking them against these files.
- [ ] Once you have a complete set of tags, create a folder at `/bot/bot/resources/tags` and store all the tag files in this folder.
- [ ] We no longer need to call the API in order to retrieve a tag. Rewrite the cog so that all attempts to get tags fetch from the folder instead.
- [ ] It should not be possible to edit, set or delete tags without making pull requests to `bot`. Remove these features from the bot completely.

**Comment by sco1** [comment]
Are there any significant differences in markdown implementation between Discord-flavored and other flavors?

If there are, where should this validation occur? I’m assuming we eventually don’t want to have to do this manually.

**Comment by RohanJnr** [comment]
I would like to work on this.
