### ISSUE TITLE
Role restricted tags

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/bot#778]
## Abstract
We may want to restrict certain tags to certain roles. For example, we may want tags that are only available to moderators and higher, which explain moderation guidelines, bot commands, stuff like that. We may want tags that are only available to Contributors that explain certain details related to our bot and site repos.

## How do we do that?
Well first of all, **we should probably wait until https://github.com/python-discord/bot/issues/777 is solved.**

Once that has been done, well, I'm not entirely sure how we do it. Off the top of my head, my suggestion would be to simply structure it so that tags restricted to a specific role are put into a subfolder inside the `tags` folder with a name that corresponds with the role. For example, tags inside `/bot/bot/resources/tags/helpers` are available to all Helpers.

Because we have cascading staff roles (every Moderator is also a Helper, every Owner is an Admin, a Moderator and a Helper), we do not necessarily need to support tags that are available to a certain subset of roles - but if you can think of an elegant way to do that, then by all means, let's discuss it.

## Just tell me what to do!
**This is an issue that is intentionally left open-ended.** If you want to handle this, you should be comfortable making changes to the above proposal if, while handling this, you find a major problem with this proposal, or if you come across a better way of solving it. Please discuss this issue with us in #dev-contrib as you work on it, and try to arrive at a good solution.

**Comment by RohanJnr** [comment]
I would like to work on this.

**Comment by ks129** [comment]
I think one way to solve this is using Markdown Metadata. There should something like `required_role: moderator` or something and bot should check this.

**Comment by RohanJnr** [comment]
markdown metadata wouldn't really fit as we will have a problem with segregating the tags. I mean we will have to look into a file to know to whom it is restricted.

**Comment by ks129** [comment]
@RohanJnr But there is possible to read an MD file on tags getting and cache it.

**Comment by sco1** [comment]
Nobody is arguing whether it is or isn't possible. The point is that adding metadata for the sake of adding it is unnecessary. If this can be done without having to add our own markdown processing then that's how it should be done.
