### ISSUE TITLE
Validate Channel Constants on Bot Startup

### ISSUE THREAD

**Issue by sco1** [python-discord/bot#780]
Related to https://github.com/python-discord/seasonalbot/issues/335, the bot's channel constants can occasionally get out of sync, resulting in `#deleted-channel` references in some of the error responses.

In order to alert staff that this desync has occurred, a utility function should be added to the bot's startup routine that validates the channel constants & logs a warning if any of the channels do not exist so the constants file can be updated appropriately.

**Comment by Numerlor** [comment]
I'd like to give this a try if you weren't planning for the same assignee as on the seasonalbot issue.
For the logging, should it also send a message somewhere to notify or just log as a warning/error?

**Comment by sco1** [comment]
Go for it. With Sentry now integrated, logging a warning is sufficient.
