### ISSUE TITLE
Add a way to close bot messages

### ISSUE THREAD

**Issue by Wim-De-Clercq** [python-discord/bot#79]
If a user enters code without formatting, the bot will reply with the message on how to format python code in discord.
I feel like it would be nice if there's a way to close this message either by helpers/admins/moderators or by the person who typed the wrongly formatted message him/herself by reacting with some emoji (like how you can do paging)

It would keep the discord chat flowing nicely instead of scrolling back over bot interruptions.

We would then also need to find a way to keep the mod-log clean though.

**Comment by gdude2002** [comment]
I could get behind this. Could be a great PR, too!

**Comment by 1mn** [comment]
mod log wouldn't be a problem, actions taken by Python are now being ignored by rowboat.

**Comment by 1mn** [comment]
Nix wanted to do a PR with more changes for this feature anyway, perhaps this could be part of it?

**Comment by hargoniX** [comment]
Ok I'll add it to my list, if no one takes it until I did the other changes.
