### ISSUE TITLE
Formatting issue for empty topic in channel update log

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#793]
The old and new topics should each be in separate in-line code blocks. The arrow should be between and outside the two code blocks.

![bild](https://user-images.githubusercontent.com/1515135/75304983-a2525780-57f9-11ea-8056-eb066e1dfa2b.png)

**Comment by eivl** [comment]
@ks129 could you explain what your fix does? I think I'm not getting what it does. Why does adding `None` fix this issue? maybe screenshots before and after could help me understand it.
