### ISSUE TITLE
Command for fetching package information from PyPi

### ISSUE THREAD

**Issue by ks129** [python-discord/bot#796]
These should `!package <name>` command, that fetch information from [PyPi JSON API](https://wiki.python.org/moin/PyPIJSON). This should go under `Utils` cog.

## Information that will be shown in embed

- Name
- Summary
- Author
- Maintainer
- Project URL (PyPi)
- Homepage
- Required Python version
- Latest version
- License
- Downloads (last month)
- Quick installation copy paste string

I can work with this after my current PR get merged.

**Comment by Numerlor** [comment]
For the project descriptions, there may be some problems picking up the relevant data out of them; some start with an introduction, others with an install guide etc. There's always the option to not include the description or just cut it off before the char limit but something to take into consideration.

Also I think this should probably have its own cog if the above parsing gets involved

**Comment by ks129** [comment]
@Numerlor My idea is showing only short summary, author, supported Python versions, license, home page, PyPi page and latest version there, due READMEs may REALLY big.

**Comment by sco1** [comment]
The implementation details of this needs a lot more thought put into it & provided in the description before this can move forward.

The amount of information present in a project's PyPI page ranges from very little to a whole lot, so it needs to be identified which information is always present and what is optionally present and, out of those, decide what we want to display in the embed while respecting the embed's various character limits.

**Comment by ks129** [comment]
@sco1 I added information about what would be in embed.

**Comment by Akarys42** [comment]
Since this command will only pull data from PyPi, I feel like `!pypi` is a better name for it. It sounds like a good command to have.

**Comment by ks129** [comment]
@Akarys42 Or maybe: `!pypi` as main name, `!package` as alias?

**Comment by Anubhav1603** [comment]
I wnt to work on this :)

**Comment by Anubhav1603** [comment]
yeh

**Comment by Anubhav1603** [comment]
I was waiting for getting this approved which got approved 5 day ago so now i started working on this
