### ISSUE TITLE
Eval command: Bot keeps typing after time.sleep(), No input is shown

### ISSUE THREAD

**Issue by F4zii** [python-discord/bot#799]
## Description
When invoking the eval command with a code that includes a time sleep, the bot doesn't send any output and triggers the typing even after sending the output message.

this only happens when you sleep for more than 5 seconds.

## Example
![pydisbug](https://user-images.githubusercontent.com/44242259/75522502-cf2d8700-5a12-11ea-9e14-bd21be773137.gif)

**Comment by Akarys42** [comment]
The issue seems that the typing error is caused by the fact that the eval timed out, because using a 3 seconds sleep doesn't cause the bug, but using asyncio also cause the bug to appear. Also, this seems like an heisenbug since this bug seems to randomly appear. This behavior is even more peculiar knowing that the typing functionality is triggered by a context manager. 

https://github.com/python-discord/bot/blob/aa5c905d5dc368e4132c37656be504548578aac4/bot/cogs/snekbox.py#L206-L225

**Comment by F4zii** [comment]
Yeah, this only happens when you sleep for more than 5 seconds.

**Comment by scragly** [comment]
This has been resolved from the snekbox repository.

**Comment by scragly** [comment]
Here I'll provide a small explanation as what was happening to cause this behaviour.

The [part of the eval command when waiting for a response](https://github.com/python-discord/bot/blob/master/bot/cogs/snekbox.py#L206-L225) is contained in the context manager of [`ctx.typing`](https://discordpy.readthedocs.io/en/latest/api.html?highlight=typing#discord.abc.Messageable.typing).

Internally, the typing event is resent to the Discord API every 5 seconds so long as the code has not existed the context manager. Once it has exited, it'll either stop showing "Python is typing" in the channel after 5 seconds of it's last resend, or it stops early on it's next registered message that Python botto sends in the channel.

Our snekbox was recently changed to timeout any evals after 5 seconds.

Thanks to the odd timing of snekbox timing out, sending it's message in the channel saying so, but also the `typing` context resending the typing event right at that moment, the new message was seemingly not registered as after the refreshed typing event, making it display "Python is typing" for another 5 seconds before disappearing.

The snekbox has now been changed to 6 seconds to avoid this synchronisation of message sending and `typing` event resending, so the timeout message correctly registers as being after the last typing event and disappears accordingly.
