### ISSUE TITLE
tag-search command to search tags via their contents instead of names.

### ISSUE THREAD

**Issue by CharlieADavies** [python-discord/bot#804]
Currently, it can be difficult to find the specific command for a tag even if you know it exists. A command to allow you to search through tag bodies would help with finding the right tags. For example doing `!tag-search backtick` would return `!code-block` (and any other tags that include the word backtick).

**Comment by ikuyarihS** [comment]
This is an intersting idea, and this is very feasible since we already fetch all tags into a dictionary of `Dict[str, str]` for `tag['title'].lower(): tag` - and so we can make a command to search on the contents of the tag instead of just purely the name of the tag ( incase we forgot the name! )

**Comment by ikuyarihS** [comment]
I will be working on this!
