### ISSUE TITLE
Tag Suggestions

### ISSUE THREAD

**Issue by sco1** [python-discord/bot#810]
PyDis' Python bot uses `!tags` to provide brief, canonical explanations for common questions, programming pitfalls, and other Python related topics.

Use this issue to suggest additional tags, bonus points if you help out with the body of the tag as well!

edit: Since there's often an overlap between what's desired for a tag vs. the ability for a wiki article to be more comprehensive, I've expanded the scope of this to also include suggestions for Wiki articles (implemented soon) so you don't have to decide whether or not this belongs as a tag or as a Wiki article.

**Comment by aeros** [comment]
I can work on the async and concurrency tags when I get the chance. It would potentially save me the trouble of answering some commonly repeated questions in the `#async` channel.

**Comment by F4zii** [comment]
We should add an explanation for the difference between a class and an instance in the `!class` tag

**Comment by Shivansh-007** [comment]
> ### putting these here so i remember to do them
> anyone is welcome to beat me to it (please )
> 
> * [x]  REPL
> * [x]  `exit()`
> * [x]  `if __name__ == '__main__'`
> * [x]  off-topic
> * [x]  metasyntactic variables (foo, bar, etc)
> * [x]  paste (link to paste.pydis.com, explain about saving and url changing)
> * [x]  xy problem
> * [x]  parameters vs. arguments
> * [x]  codeblock [UPDATED] (added info about backticks and other bad formatting)
> * [x]  self
> * [x]  classes
> * [x]  star imports
> * [x]  inline codeblock
> * [x]  operator precedence
> * [x]  bankers rounding
> * [x]  difference between single and double quotes (talk about consistency and escapes)
> * [x]  positional and keyword arguments
> * [x]  `*args` and `**kwargs`
> * [x]  calling function name vs. referencing function name (common gotcha)
> * [x]  mutable default arguments
> * [x]  `pathlib`
> * [x]  return statement (how it works, it's purpose, etc)
> * [x]  scope
> * [x]  indentation (its importance, syntax, etc) [suggested by martmists]
> * [x]  variables (how references work, link to ned's stuff about this)
> * [x]  opening files (how open() and its modes work)
> * [x]  seek (how seeking through a file works)
> * [x]  relative paths (what they are, how cwd works)
> * [x]  typing (info on type hints)
> * [x]  magic methods (in general)
> * [ ]  namespaces
> * [ ]  floating-point arithmetic (precision errors, `.1 + .2`)
> * [ ]  mutability
> * [ ]  bytecode
> * [ ]  variable swapping
> * [ ]  explicit and implicit line joining
> * [ ]  `yield`/`yield from`
> * [ ]  concurrency (multi-threading/processing, asynchronous)
> * [ ]  bitwise arithmetic
> * [ ]  bare asterisk in function signature (keyword only arguments)
> * [ ]  bare forward slash in function signature (positional only arguments)
> * [ ]  integer caching
> * [ ]  properties (`@property` decorator)
> * [ ]  comparing strings (lexicographical order)
> * [ ]  ternary
> * [ ]  arrays vs lists
> * [ ]  current directory (explain that interpreter looks for files in directory it was invoked in)
> * [ ]  `lambda`
> * [ ]  generators
> * [ ]  iterators
> * [ ]  `__init__`
> * [ ]  `__str__`
> * [ ]  `__repr__`
> * [ ]  inheritance
> * [ ]  Method Resolution Order
> * [ ]  global interpreter lock
> * [ ]  `import` (where it looks, packages vs modules, `from` syntax, etc)
> * [ ]  `super()`
> * [ ]  bytecode (compilation, interpretation, .pyc files, `dis` module, etc)
> * [ ]  circular imports
> * [ ]  freezing (pyinstaller and the like, how it works maybe, etc)
> * [ ]  performance (how to speed up your code, `timeit` module, `profile` module, more efficient algs, better data structures, multi-threading/processing, C extensions, Cython, pypy)
>   this one will obviously have to be fairly brief, mostly providing links for more information
> * [ ]  debugging (pdb, `-i` flag, `assert`, well placed `print`'s)
> * [ ]  `eval`/`exec`
> * [ ]  IDLE (why it sucks, any other relevant info, etc)
> * [ ]  shebang (sharp bang line `#!` in source code)
> 
> I <3 tags

This are the tags which are left right? so I can work on them...

**Comment by SuperStormer** [comment]
@fiskenslakt bytecode is duplicated twice in your list: once at the top and once below import and super.

Suggestion: why you should use parameterized queries instead of string formatting in sql queries to avoid sql injections.

**Comment by decorator-factory** [comment]
[ ] Various approaches to implementing ADTs (`dataclass`/`NamedTuple`, `Union`)
[ ] Enums

**Comment by mudkipdev** [comment]
> * [ ]  Enums

Would [this](https://paste.pythondiscord.com/icaqayedot.properties) be good? I'm not really sure if this is helpful enough.

**Comment by jb3** [comment]
Discussion superseded by python-discord/meta#86
