### ISSUE TITLE
!zen command not working as intended

### ISSUE THREAD

**Issue by eivl** [python-discord/bot#827]
if you do
```
!zen explicit
```
it returns 
```
**The Zen of Python (line 10):**
Unless explicitly silenced.
```

while I do believe that the intent was to have it return line two
```
**The Zen of Python (line 1):**
Explicit is better than implicit.
```

**Comment by Akarys42** [comment]
I think the issue could be solved by simply checking if the exact query word is inside one of the zen lines (`explicit` in that case) and returning it, if it is not found, try the fuzzy matching.

**Comment by ikuyarihS** [comment]
Which is what it is doing:
https://github.com/python-discord/bot/blob/190ff0fd2422459674320fa0e096921e38872f2d/bot/cogs/utils.py#L234
Even if we check for word in string, `explicit` will still be found in two lines and not one, so perhaps we need a better way to handle this case

**Comment by SebastiaanZ** [comment]
The current matching strategy is a bit simplistic in more than one way, but the specific case eivl mentions is more difficult to tackle. We could prioritize matches that contain the word as-is (except for capitalization), which would solve the "explicit" versus "explicitly" problem when looking explicitly for "explicit".

The next bit is that the current fuzzy matching tactic will always return a match; there's no lower bound/threshold below which it simply doesn't return anything. I don't really mind that, but we could add such a lower bound to prevent things like random slurs from returning a line anyway.
