### ISSUE TITLE
Code markdown suggestion behavior triggers in clearly incorrect scenarios

### ISSUE THREAD

**Issue by bast0006** [python-discord/bot#829]
At the moment, the code in bot/bot/cogs/bot.py that handles when people post code blocks without language tagging them--that says "It looks like you're trying to paste code into this channel." uses pythons AST module to determine whether a code block is valid python or not. 

However, it doesn't make sure that a language has already been specified before doing this. The following discord message demonstrates incorrect behavior:

\`\`\`ini
[test_block]
test_value=1
test_value_two=2
\`\`\`

(Must be at least three lines to trigger code block parsing behavior)

Despite it being both a valid code block, language, and content, the bot will reply with a message suggesting that you use the formatting you already are. This is because here:
https://github.com/python-discord/bot/blob/0d56b0ae08f809fb9efebd5e5d011bf68b5940c7/bot/cogs/bot.py#L346
there is an assumption that non-python code will throw a syntax error, which is not always the case. 

The bot first checks to see if there was a mistake made when quoting, and will give a special message in that (unrelated) case. Otherwise, it parses the contents out of the code block. If it starts with the correct formatting (\`\`\`py or \`\`\`python, then an immediate newline) it will return out correctly. If the formatting isn't quite correct or a language other than python is specified, it falls back to default behavior (parsing the contents as python and if it is valid python syntax triggering a response). 

As shown above, if the language happens to be parseable as valid python syntax (eg.. ini files), then the message triggers even if the code block has valid syntax.

This could be easily corrected by instead of parsing for python code blocks parsing for code blocks in general, which always follow the same syntax except with a different identifying word. If the word is present and not in the python language list (py or python), then the bot shouldn't respond.

https://github.com/python-discord/bot/blob/0d56b0ae08f809fb9efebd5e5d011bf68b5940c7/bot/cogs/bot.py#L97 Seems a good place to fix this by changing the regex and filtering results appropriately

**Comment by abmyii** [comment]
Can't reproduce with the given example.
