### ISSUE TITLE
Command for editing bot authored messages. 

### ISSUE THREAD

**Issue by scragly** [python-discord/bot#853]
In order to assist staff being able to send bot-authored commands to avoid restricting the ability to edit it's contents to a single person, a command to edit a target message without resorting to int eval could make the experience a little friendlier. 

There's a possibility that we have other message-related commands that could be appropriately grouped together, so a consideration might be to add a `message`|`msg` parent group for these utilities.

**Comment by Den4200** [comment]
This doesn't seem relevant anymore, I haven't seen anyone int evaling to edit bot messages in the past few months.
