### ISSUE TITLE
Ban command failed with reason has more than 512 letters, but still add to DB

### ISSUE THREAD

**Issue by ikuyarihS** [python-discord/bot#861]
## What's wrong?
Right now, when issuing a ban ( `!tempban` for example ) if the reason is greater than 512, it will fail because discord only allow 512 letters.
However, the bot will still add the infraction to our DB and register it as an active ban, and thus subsequent ban will fail, saying that user is already banned.

## Expected behaviour:
When the reason is greater than 512, either send a warning / confirmation that the reason is greater than 512 and so reason will be cut off to be used for `.ban()`.

Or at the very least, `.ban()` should be wrapped inside a `try` `except` and will actually show the error.

## Suggestion
The order of actions should be revised: ban first, then post to DB only if it succeeded.

The code can be found here:
https://github.com/python-discord/bot/blob/44b33d570642905d4eeb64300a3a2d3d0cb80b72/bot/cogs/moderation/infractions.py#L231-L262

**Comment by ks129** [comment]
I don't understand: Should this fail when reason is longer than 512 chars or should this cut this to 512 chars when applying ban?

**Comment by ikuyarihS** [comment]
It is up to debate:

The 512 chars limit is only applied to discord, in reality it should not affect us if we ever want to make a thorough ban reason, and limiting ourselves to 512 just because of Discord does not feel right, right?

However, if we decide to open the limit to more than 512, we might want to truncate the message to be used as reason for discord. In that case, a confirmation / warning that the reason will be truncated will be nice.

**Comment by sco1** [comment]
I don’t think we care if the ban reason sent to Discord’s API is truncated, I can only think of maybe a handful of situations where we’ve ever read the reason in the audit log vs. what we have stored on site, and 512 characters should give us a good enough understanding of why the member was banned.

**Comment by ks129** [comment]
@ikuyarihS One thing about this reordering actions: I think this is not a good idea, because after this when banning success, but adding to DB not, the situation is not good. I think better is when order stay like it is. The only change should that this cut reason.
