### ISSUE TITLE
Feature: !undo command

### ISSUE THREAD

**Issue by thomaspet** [python-discord/bot#862]
# Why
Simplicity of being able to undo a command that was done

# Task
Add a command that tracks the last commands used (that are reversible), and by whom used it.  If done right this could be great tool for undoing mistakes like a typo in an ot-name.

It would achieve this by having a look up of the reversible command, and keep track of the input given. So if you undoed a ot add, it would keep track of the name added, and call ot remove with it.

It could undo a ban, if that was by mistake. 
etcetc, feel free to edit the issue, it was just to put the idea out there

**Comment by sco1** [comment]
Thanks for the proposal! Theoretically it's a great concept but I don't think it can be robustly implemented within our framework.

While many of the commands have a simple "undo" mapping, others are not so straightforward. The moderation commands, for example, are one where the opposite action is not always going to be the same; we might want to edit the infraction that was just created, or pardon it, or even void it (when this functionality is added). This would require the undo command to have some method for conditional, command-specific inputs which, along with all of the mappings for every available command to undo, would likely be quite fragile.

**Comment by thomaspet** [comment]
Infractions could map to edit, and i can see the command becoming a moster real fast.  It was mostly for simple add/remove concepts.  Like ot-add/remove

**Comment by Den4200** [comment]
I don't think we need this command, it just adds more unnecessary complexity. If we want to undo a command, we can just use the corresponding command for it.
