### ISSUE TITLE
Unfurling shortened URLs, following redirects and trust checking URLs

### ISSUE THREAD

**Issue by fractalpenguin** [python-discord/bot#863]
In order to avoid circumvention of the existing URL filters by using a link shortener, or a redirect, unfurling shortened URLs and following redirect checks should be implemented into the existing URL filter.

The proposed APIs for unfurling and following redirects are:
- https://wheregoes.com/ (primary preference)
- https://unshorten.me/api

In addition, although URLs posted might not be in the blacklist, they might lead to sites with explicit content, malware, or other content that can be deemed inappropriate.

Proposed APIs for checking the trustworthiness of a site include:
- https://urlscan.io/about-api/
- https://cloud.google.com/web-risk/
- https://www.mywot.com/
- https://www.virustotal.com/gui/home/upload 
- https://www.scamdoc.com/
- https://spoopy.oceanlord.me/

### Implementation
 
When checking an URL against the blacklist, it should check both before it is unfurled/followed and after, in order to avoid a URL that is in the blacklist being allowed through if it redirects to a reliable domain.

**Comment by fractalpenguin** [comment]
Regarding URL unfurling, are there any security concerns with having the bot follow the shortened link itself, rather than using an API?

**Comment by HassanAbouelela** [comment]
Closing this for the same reason mentioned in python-discord/meta#88. Feel free to reopen if you believe this is different.
