### ISSUE TITLE
Make !dormant available to original claimant, and delete invocation.

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/bot#867]
By far the most requested feature in **#help-channel-feedback** is to allow the original claimant in a help channel to mark the channel as `!dormant`. After considering the drawbacks vs the benefit, we have agreed that we should do this.

We'd also like to make one small related change in the same pull request - Whenever `!dormant` is called, the bot should delete the invocation message. This keeps our help channels from filling up with `!dormant` invocations, which prevents unfamiliar users from constantly trying to use the command just to see what it does.

This issue asks you to make two small changes to the help channel system:

## Original claimant should be able to mark a channel as dormant

- [ ] When a channel is first claimed, store the ID of the user who claimed it and the ID of the channel in a cache. This can just be a simple dictionary.
- [ ] When `!dormant` is invoked, allow it if the original claimant (or a staff member) is the caller.
- [ ] Don't worry about persisting across reboots - we'll deal with that later.

## Remove the invoking message when `!dormant` is called.
- [ ] Whenever `!dormant` is called, the bot should delete the invocation message (the message that says `!dormant`).

## When the `!dormant` command is invoked, remove the cooldown from the channel owner

- [ ] Whenever `!dormant` is called, the person who owns that help channel should have any outstanding cooldown they have pardoned, so that they can claim a new channel. This should happen both if a staff member and the channel owner invokes the command.

**Comment by Numerlor** [comment]
Can jump at this unless you had someone familiar with the system in mind

**Comment by MarkKoz** [comment]
Something to note: if the command is used, their cooldown for claiming a channel should also prematurely end.

**Comment by lemonsaurus** [comment]
@Numerlor You're welcome to it, as long as you're able to address it quite soon. We'd like this merged maybe within a day or two, since there's an ongoing evaluation of this system going on.

If that's a bit sooner than you were thinking, we'll handle it among the core devs.

**Comment by Numerlor** [comment]
Resetting the cooldown completely seems to be a bad idea because it would allow users to repatedly make one channel at a time in use and put it back into the dormant state.

I think cancelling the initial task and creating a new one that will reset the permissions in a (potentially) shorter time would be fitting here, does a minute sound like a good cooldown if this is wanted? And should that be in the config or just a literal/module const?

**Comment by lemonsaurus** [comment]
@Numerlor we've discussed that hypothetical edge case among the core devs, and feel like it's not really necessary to solve it here and now. If someone does that, it'll be plainly visible (lots of subsequent embeds in some channels), it won't really disrupt anything, and we'll moderate it. If it happens a lot, we'll come back to implementing a solution for this, and yeah, a short cooldown would probably be the right move.

For now, let's just reset the cooldown to zero for the channel owner when anyone uses that command, whether it's staff or the user himself. That keeps this simple and we don't need to introduce any more config variables.

**Comment by lemonsaurus** [comment]
I added this third task to the original issue description, too.

**Comment by MarkKoz** [comment]
We'll need to update the guide on the site once this feature is ready.
