### ISSUE TITLE
Enhancement: Reverse deleting !dormant command message

### ISSUE THREAD

**Issue by kosayoda** [python-discord/bot#880]
The current dormant message reads like this:

> This help channel has been marked as dormant, and has been moved into the Help: Dormant category at the bottom of the channel list. It is no longer possible to send messages in this channel until it becomes available again.
<-- snip -->

Thus, there is no way of knowing whether it was manually made dormant, or automatically made dormant due to inactivity.
If a user mentions that a channel was mistakenly made dormant when they were not done with it, it would be nice to see if it's an issue with the bot or a human error.

**Updated solution:** Reverse the deletion of the message containing the `!dormant` command. It would be clear at a glance if the channel was made dormant manually or automatically.

~~**Proposed messages:** (Relevant sections highlighted)~~

~~*Automatic invocation*:~~
~~> This help channel has been marked as dormant **due to inactivity**, and has been moved into the Help: Dormant category at the bottom of the channel list. It is no longer possible to send messages in this channel until it becomes available again.
<-- snip -->~~

~~*Manual invocation*:~~
~~> This help channel has been marked as dormant **by staff**, and has been moved into the Help: Dormant category at the bottom of the channel list. It is no longer possible to send messages in this channel until it becomes available again.
<-- snip -->~~

**Comment by SebastiaanZ** [comment]
I think an easy way of communicating that a channel was marked as dormant manually and making obvious by whom it was marked so is by reversing the bit that deletes the invocation message. That will also make it far more obvious than having to scan an embed message.

**Comment by kosayoda** [comment]
> <--snip --> reversing the bit that deletes the invocation message. That will also make it far more obvious than having to scan an embed message.
I second that idea.
