### ISSUE TITLE
Handling of Discord message upload as text.

### ISSUE THREAD

**Issue by ikuyarihS** [python-discord/bot#889]
## Problem
Right now, Discord have implemented a new feature where if a user pastes something over the 2000 character limit a text file is created and uploaded.
![image](https://user-images.githubusercontent.com/19921765/79689147-13a00b00-827d-11ea-89a2-b64a3f861082.png)
## Solution
After a staff meeting, the consensus was that, for this special case ( when attachment is of type text in general ) we will add a bit in the message that gets posted by this filter about how text should be posted to our paste site, similar to how we are treating `.py` files.

The code responsible for this embed can be found here https://github.com/python-discord/bot/blob/3fe0f5cba6d3f8ba7016fc651ea12a0da7f9e5c5/bot/cogs/antimalware.py#L35-L48

**Comment by ks129** [comment]
How should this detect this special case? And should this in same Antimalware cog?

**Comment by ikuyarihS** [comment]
Similar to how the cog is detecting if the file ends with `.py` you can add a list of extensions for text files and then check if the current attachments' types is in this list.

**Comment by Savant-Dev** [comment]
Not sure how to assign myself, but for reference, I would like to work on this issue

**Comment by ikuyarihS** [comment]
Closed as https://github.com/python-discord/bot/pull/925 addressed this issue.
