### ISSUE TITLE
Allowing eval in help channels

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/bot#893]
With the new help channel system in effect, we want to change the rules for where the `!eval` command is permitted to be used. However, because our help channels are dynamically created on demand and because we also need to allow it for a few non-help channels, and for certain roles, we need a new decorator and some new constant groups to handle this.

## When should the command be allowed?
- In all help channel categories, including **Topical Help**, **Dormant**, **Available**, and **In Use**.
- In **#esoteric-python** and **#bot-commands**
- For **Helpers**, **Moderators**, **Admins**, **Owners**, **Python Community** and **Partners**.

## Where do we put all these IDs?
In the `default-config.yml`, we can create a new group called `eval` where we have `category_whitelist`, `channel_whitelist` and `role_whitelist` which all contain lists of IDs.

## Okay, but how do we check this?
Let's create a new decorator that will check all of the above.

This decorator, maybe `is_whitelisted`, should take a list of roles, channels and category IDs and also a `redirect_channel`, which is where it will tell the user to go if they try to run the command in a channel where it is not permitted.

**Comment by MarkKoz** [comment]
I think the existing decorator could be used. Channel objects have a type attribute which can be checked. Remember, a category is just a specific type of channel.

**Comment by lemonsaurus** [comment]
Perhaps technically a category is just a channel, but I think most people will intuitively make the distinction between the two, and that it feels a bit hacky to send category IDs into a `channel_list`. It just feels like poor UX on our API.

**Comment by SebastiaanZ** [comment]
I agree about the API part and Mark's edit also plays into that:

As Mark's edit suggests, we'd still need to know if the ID passed relates to a channel itself or a category the channel could be in for the permissions check. This makes the implementation slightly less convenient. It means we'd have to "get" the channel object in the predicate from `Context.guild` to determine whether or not it belongs to a `TextChannel` or a `CategoryChannel`.

If we explicitly pass the IDs as separate kwargs, we don't have to "get" those objects and it's clear to the user that you can use both channels and categories to whitelist a command just from the names of the parameters.
