### ISSUE TITLE
Only punish users once to prevent a race condition in AntiSpam

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#902]
If a user manages to take part of multiple filter violations, the cog will attempt to `punish()` them for each of those violations. While `punish()` does check for the muted role before applying the infraction, the asynchronous nature of the code can mean a second `punish()` is called and passes the role check before the first `punish()` has gotten a chance to apply the mute. This would result in an attempt to apply a second mute infraction, which will ultimately fail and display a message stating the user already has such infraction.

I believe the fix is to keep track of which members were already punished so that they can be skipped when processing members for the rule violation. One has to consider this globally, not just for the current deletion context. Maybe using locks for each member would just be easier.

**Comment by SebastiaanZ** [comment]
I'm going to take a stab at this. It led to some serious issues last week, and I think we should tackle this relatively soon-ish.

I'm not quite sure about what the best implementation for this would be, yet. If we go with a global lock and making sure the "deletion context"-specific infractions only happen once, the infractions from other contexts will still go through after the lock is released. Granted, this should already reduce to a single fail/success message per context, but I don't actually think we need "failure" messages showing up in the context. 

My proposal would be to implement the "single infraction per user per context" and hiding failures for existing infractions for automated anti-spam infractions. If infractions fail for another reason, which probably means that something is happening but the bot can't deal with it, I think it's best to send those automated failures to mod-alerts using a webhook (to avoid rate limits in raid events). (I don't think I've seen those "other" failures yet, though, but silencing them completely sounds bad.)

Obviously, this involves some refactoring and redesigning of some of the moving parts, as we have no support for the things I've mentioned.
