### ISSUE TITLE
Identify and fix potential forbidden errors due to role hierarchy

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#905]
Sometimes `discord.Forbidden` errors are raised due to the bot being lower in the role hierarchy than the user they are trying to edit. An example of this is joe trying to superstarify himself (see [BOT-3C](https://sentry.io/organizations/python-discord/issues/1621105430/?referrer=github_integration)). 

Depending on which groups of users this affects, we should try to gracefully handle such error. If this only affects the server owner (as in, true ownership, not just the role we have), the we could ignore it. If it affects roles like admins and mods, then I think we should address this error.

Unfortunately, I don't think Discord's API distinguishes between someone being too low in the hierarchy and the bot not having permissions granted. If we want to log the latter as much as possible, then we couldn't do a blanket ignore (or lower log level) on all `discord.Forbidden` exceptions. However, if we think it's safe to assume the bot will always have the right permissions, then maybe such an ignore is a valid solution. Otherwise, potential errors specifically do to hierarchy will need to be handled individually. For those errors, we'd have to assume that it's due to role hierarchy and not the bot missing permissions.

**Comment by mbaruh** [comment]
The PR is merged and now it just fails to apply the infraction, which is something we handle in `apply_infraction`.
