### ISSUE TITLE
Use appropriate log level for exceptions from event listeners

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#911]
From @SebastiaanZ:

> Finally, `discord.py` currently "hides" errors/tracebacks that happen in event listeners as we only have a custom error handler for commands. This isn't too bad locally, since `d.py` **prints** those exceptions to stderr, but it obviously means they'll never show up in Sentry, as they are **not actually logged** with the appropriate level.

**Comment by SebastiaanZ** [comment]
Right, thanks. I should have added this myself.
