### ISSUE TITLE
Forbid emoji reaction when a channel is shhhh-ed 

### ISSUE THREAD

**Issue by Akarys42** [python-discord/bot#915]
We recently had an issue with users reaction spamming the `!silence` message, in my opinion it would be smart to also disable emojis when a channel is silenced. The following lines might be of interest:
https://github.com/python-discord/bot/blob/fe325adc66e9621ea970abd83db58df4b792caa5/bot/cogs/moderation/silence.py#L121
https://github.com/python-discord/bot/blob/fe325adc66e9621ea970abd83db58df4b792caa5/bot/cogs/moderation/silence.py#L141

**Comment by Numerlor** [comment]
What is the proposed solution for this?
Removing the permissions is fairly easy, but then they can't be restored reliably with some channels allowing them and others forbidding them (or following the category)

**Comment by Akarys42** [comment]
I think we should store the previous state (no override or allow) in memory to put it back exactly how it was, and in case of shut down when the cog is silenced, note the previous state in the alert and allow the unsilencer to specify the emoji reaction state, through and ID or something

**Comment by Numerlor** [comment]
Depending on how needed this is from a moderating standpoint, I think it'd be better to wait for persistence on the bot

**Comment by Akarys42** [comment]
Silenced channel will now be stored in the database? Well I guess we should
better wait then. I cannot find any corresponding issue or PR though, have
I missed it?

**Comment by Numerlor** [comment]
Don't think there's an issue for it and don't know how near it is but there were a few messages in dev contrib for using something like redis as a persistent cache.

Not a fan of expanding the command for manually specifying allowing/forbidding emoji perms as an arg for when the bot restarts

**Comment by Akarys42** [comment]
Yes in that case I agree with you, we would be better using a permanent
storage for that

>

**Comment by ks129** [comment]
Maybe we should use `bot-settings` endpoint to storage permissions (`int` of permission code) during channel is shhh-ed. After deactivating, this should delete this. When this is OK, I'd like to work on it.

**Comment by Akarys42** [comment]
I don't think it is a good idea to store it on `bot-settings` since it isn't really a setting, it is generated at runtime and is meant to disappear after a few minutes. Also, I'd like to work on this myself if you don't mind 😁

**Comment by ks129** [comment]
@Akarys42 But then maybe we should hold permission values in dictionary during channel is shh-ed and then restore same perms? And this is your issue, so no problem

**Comment by Akarys42** [comment]
We would still have to drop the permissions somewhere to recover it later if the bot reboots in the meantime, I think we should have a new database model for that, maybe we could also use this opportunity to make a more general model to store small data that need to persist across reboots.

**Comment by ks129** [comment]
Basically `bot-settings` is exactly this. This name don't refer to it, but this still is. Python News will use it to storage already sent news.

**Comment by jos-b** [comment]
> Basically `bot-settings` is exactly this. This name don't refer to it, but this still is. Python News will use it to storage already sent news.

The long term solution for this will be persistent storage using Redis. I've setup Redis on our host server and I believe @lemonsaurus wanted to tackle the idea soon. In the meantime though, bot settings does work (however be careful of race conditions, it can easily overwrite itself)
