### ISSUE TITLE
Remove Python formatting from !eval result codeblock

### ISSUE THREAD

**Issue by wookie184** [python-discord/bot#916]
Currently when calling the !eval command the bot formats the result from the command as a python formatted codeblock. This can lead to a badly coloured result if the result is not python code (which it rarely would be). 

For example, if the result had an apostrophe:

![image](https://user-images.githubusercontent.com/22353562/80588666-aa549080-8a10-11ea-9cce-5831de762dcd.png)

The proposed solution would just to make it return a code block without python formatting. 
Here is the relevant line:
https://github.com/python-discord/bot/blob/fe325adc66e9621ea970abd83db58df4b792caa5/bot/cogs/snekbox.py#L204

(If this gets the go ahead I would be happy to do this but it's such a small fix I wouldn't mind if somebody else just did it. This is my first GitHub Issue and I'm learning as I go along so excuse me If I don't properly understand how things work straight away.)

**Comment by Numerlor** [comment]
The `.txt` suffix could also be added to the output url from when the code gets uploaded to [https://paste.pythondiscord.com](https://paste.pythondiscord.com), it has its own engine for guessing what format the contents are but for simple text it'll mostly detect a few keywords and then highlight it semi randomly with for example SQL syntax highlight

**Comment by MarkKoz** [comment]
On the right of this issue, you can assign yourself if you'd like to work on it @wookie184. Numerlor's suggestion is also a good idea if you want to throw it in.

**Comment by Numerlor** [comment]
I've included my suggestion in https://github.com/python-discord/bot/pull/927/commits/077a1ef1eb4eb07325dde5b6b625a84ccb5669ee when moving the upload logic, the PR should be ready to go after an another review so you can skip that if you'd like
