### ISSUE TITLE
Cannot permanently ban someone who is being tempbanned.

### ISSUE THREAD

**Issue by ikuyarihS** [python-discord/bot#917]
## Problem
When issuing a `!tempban`, the bot will not allow banning the user again with a `!ban` and will return an error saying `According to my records, this user already has a ban infraction. See infraction`

![image](https://user-images.githubusercontent.com/19921765/80605446-4906de80-8a5d-11ea-8470-31d3ac3f6bc6.png)

## Solution
The bot should overwrite the current tempban and upgrade it to a permanent ban instead.

The code responsible for checking if user has an active infraction can be seen here
https://github.com/python-discord/bot/blob/687f2c4c5875e9de2abeeb122eeee529816ee204/bot/cogs/moderation/utils.py#L100-L121
The code responsible for applying the ban can be seen here
https://github.com/python-discord/bot/blob/44b33d570642905d4eeb64300a3a2d3d0cb80b72/bot/cogs/moderation/infractions.py#L232-L262
When doing a `tempban` there will be a keyworded argument for the duration as seen here
https://github.com/python-discord/bot/blob/44b33d570642905d4eeb64300a3a2d3d0cb80b72/bot/cogs/moderation/infractions.py#L112

**Comment by LordHemlock** [comment]
Quick question on this.  Are we only wanting the behavior to be overridden when we're wanting to replace a temporary with a perma ban?  Or can it/should it go the other way as well?
