### ISSUE TITLE
Increase snekbox re-eval timeout

### ISSUE THREAD

**Issue by Akarys42** [python-discord/bot#920]
We recently had some complains about people not managing to make their re-eval working because of the very short window for editing your code, which is set to 10 seconds right now. I think it wouldn't hurt to increase it to something like 30 seconds, as it has a very low footprint, and making substantial changes to the code in 10s is almost impossible. 

Here is the line where it is hardcoded for now :
https://github.com/python-discord/bot/blob/cfc5720925b6bbc40c45507f8579145a0014a6eb/bot/cogs/snekbox.py#L230

**Comment by Numerlor** [comment]
How about making the reaction appear right away (maybe on the output message ?), right now without seeing it work or going through `!help` there's nothing to indicate the feature exists which is a bit more confusing when the message is edited after the timeout

**Comment by Akarys42** [comment]
I think putting the reaction everywhere will be noisy, and could lead to people spamming the reaction, without it doing anything, which would be even more confusing imo. The best way to make people know about it would be a message in #announcements tbh, would it be possible to get one (without pinging anyone of course)?

**Comment by jos-b** [comment]
Putting the refresh on the output message would work (and removing it after 30 seconds), but we need to keep track of the invocation message in that case.

We already put the trashcan emoji on there so an additional 1 emote would not be disastrous.

To inform users we could put a little note at the end, like in the following mockup (we could remove the note from the end when we remove reactions):

<img width="845" alt="image" src="https://user-images.githubusercontent.com/20439493/80746480-dd367b80-8b19-11ea-9304-e69c8bd0fcd2.png">

This is my view but I'd like to hear from others.

**Comment by MarkKoz** [comment]
Currently, users need to either need to read the help description for the command or have the intuition to edit their message in order to discover the feature. It's a good idea to always react with the emoji since it will make the feature more prominent. However, I believe reacting on the user's message rather than the bot's output will be more intuitive.

Joe's suggestion of including a message at the end would be effective but I am concerned it may detract from the results so I am against it.

In any case, increasing the timeout for re-evaluation is good. I am fine with the proposed 30 seconds.

**Comment by Numerlor** [comment]
I was thinking of putting the reaction on the output message to keep the vertical space a bit tidier, but would need to see some real examples or user feedback to know which one would be better there.

I think it should be clear with both of the positions that the option is there to reevaluate the invoking message (with edits)

**Comment by Akarys42** [comment]
I mean, we would have a reaction that does basically nothing until the message is edited, it sounds pretty misleading to me

**Comment by Numerlor** [comment]
I've opened a PR to increase the timeout while a more noticeable and clearer interface is agreed upon here; but as @SebastiaanZ pointed out in #dev-contrib there's really no downside to increasing the timeout beyond the 30s suggested here.

Any thoughts on a longer timeout? Two minutes were proposed in the #dev-contrib convo but I feel like that may be a bit long if the code would be re-evaled at the end of the timeout when a channel is a bit more active; although that shouldn't happen that often

**Comment by MarkKoz** [comment]
I'm going to close this because the PR was merged. Feel free to open a separate issue if you still think the reaction should be moved.
