### ISSUE TITLE
Shorten time till dormant after claimer deletes their message(s)

### ISSUE THREAD

**Issue by Senjan21** [python-discord/bot#939]
Idea behind this issue is to lower the time until a channel becomes dormant/closed when original claimer deletes their messages if there are no replies to their question.
Currently channel will only go dormant after 30 mins of inactivity or when someone closes it manually.

There are cases in which some people will claim a channel and find a solution to their problem before anyone will even reply and due to not knowing they can close channel manually, they might delete their messages which makes channel appear as if it was still available, yet it is claimed and is in `Python Help: Occupied` category, and stays so for 30 minutes of inactivity or until staff member closes it.

Ideally, the bot could check if the messages were deleted and shorten the time till channel closes automatically. Shortening time to 5-10 minutes sounds like a good time in such case as it gives the claimer possibility to send the message again (in case they deleted it to format it better) and if that's not the case, the channel would become dormant sooner, which can be good thing to have in peak hours of help channels usage.

**Comment by MarkKoz** [comment]
I like this idea because it will still give them some time to send a new message if that was their intention. It would work well with #898 too.

**Comment by ks129** [comment]
Can I work with this + #898 at once?
