### ISSUE TITLE
Ban discord.gift links

### ISSUE THREAD

**Issue by jos-b** [python-discord/bot#958]
Within the community several discord.gift links are shared, half of them are trolls and this isn't worth keeping.

We'd like to add discord.gift links to the filter system so they are automatically deleted.

Links look like `discord.gift/AABBCCDDEEFF` and should be handled in a similar way to the way Discord invites are.

A lot of the code from the Discord invite filters can most likely be reused or refactored into a DRY approach to things to handle all links in this way.

An example of a (valid) troll link is: `discord.gift/wtwe5QSbtmz63xnY8XFpd6ue` which renders to 
<img width="581" alt="image" src="https://user-images.githubusercontent.com/20439493/82764275-7600a400-9e05-11ea-837b-411e32f4d677.png">

**Comment by lemonsaurus** [comment]
can't we just add discord.gift to the URL blacklist? Does this really need any code at all?

**Comment by jos-b** [comment]
@lemonsaurus I believe so actually, I was under the misconception that the URL blacklist only checked for actual links (e.g. starting with a protocol), but that should work.
