### ISSUE TITLE
Re-think approach for creating sessions in the Bot

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#959]
### How sessions are currently created

There are things the `Bot` needs to create which rely on a running event loop like aiohttp `ClientSession`s. This is done in `Bot._recreate()`:

https://github.com/python-discord/bot/blob/b25619567d5d1ceee939d4b17c1a90ae9ac337bf/bot/bot.py#L87-L117

Because discord.py manages the event loop, we currently hook into `Bot.login()` and create everything in there. This is done indirectly by calling `_recreate()` within `login()`:

https://github.com/python-discord/bot/blob/b25619567d5d1ceee939d4b17c1a90ae9ac337bf/bot/bot.py#L81-L85

#### Closing

A `discord.Client` instance is designed to be re-usable. The client can be closed with [`close()`](https://github.com/Rapptz/discord.py/blob/1ee1b7feea81a70488b1fc2d89a700109c84f8fc/discord/client.py#L524-L533), which also closes the internal `ClientSession` and sets the client's internal state to "closed". 

#### Logging in

One can still `login()` again in this closed state. When logging in, discord.py will [re-create](https://github.com/Rapptz/discord.py/blob/1ee1b7feea81a70488b1fc2d89a700109c84f8fc/discord/http.py#L254-L256) its internal `ClientSession`. Keep in mind that not all of discord.py functionality requires a running bot; for some API interactions, merely logging in is sufficient.

#### Running the bot & using `clear()`

While logging in will work in a closed state, running the bot will not. Hence, to run again after closing, `clear()` needs to be called to reset to an open state. This function also re-creates the internal `ClientSession`. Note that this function is _not_ a coroutine, so aiohttp will complain that a session is being created outside a coroutine if `clear()` is called outside a coroutine. 

If the `Bot` subclass is to maintain support for `clear()`, it has to re-create its own sessions when `clear()` is called. This is why it [calls](https://github.com/python-discord/bot/blob/b25619567d5d1ceee939d4b17c1a90ae9ac337bf/bot/bot.py#L60) `_recreate()`. Since `clear()` is not a coroutine, `_recreate()` also cannot be a coroutine.

### Scheduled tasks in cogs

Some cogs schedule tasks on the event loop in their `__init__`s. The scheduling happens before the bot is started, but the tasks won't actually be executed until discord.py starts the event loop (which will happen when we call `bot.run()`). 

## Problem

There is a race condition between scheduled tasks and the creation of the sessions upon which they depend. When a task is scheduled like this, the time or order in which it completes is not guaranteed. It's possible that a scheduled task could try to make a request via a `ClientSession` before the `Bot` has managed to create that session!

### Current solution: events

To solve this, the `APIClient` has an `asyncio.Event` which is set when the `ClientSession` is created:

https://github.com/python-discord/bot/blob/b25619567d5d1ceee939d4b17c1a90ae9ac337bf/bot/api.py#L63-L72

All methods of `APIClient` wait for this event to be set before sending any requests to ensure the session is available. This pattern works but is cumbersome.

https://github.com/python-discord/bot/blob/b25619567d5d1ceee939d4b17c1a90ae9ac337bf/bot/api.py#L109-L111

Only `APIClient` uses an event. Neither `Bot.http_session` nor `Bot.stats` have events associated with them, and therefore they are open to potential race conditions.

## A better solution?

In https://github.com/python-discord/bot/pull/947#discussion_r429603565, @aeros suggested using `loop.run_until_complete` to create sessions and @SebastiaanZ had a similar idea. This is better because it blocks the event loop and guarantees the sessions will be created before the loop is unblocked. We would have to do this sometime before discord.py starts the loop [here](https://github.com/Rapptz/discord.py/blob/1ee1b7feea81a70488b1fc2d89a700109c84f8fc/discord/client.py#L622). @SebastiaanZ had concerns of whether the object created would be fine with the fact that the loop would temporarily stop running after they're created. There'd be a gap in which the loop is stopped between when the objects are finished being created and when discord.py starts the loop back up to run the bot.

This suggestion should be investigated further.

### Merits of supporting `clear()`

While it's sort of nice to say that our subclass still maintains the API discord.py provides, we never actually use the bot like this. We never try to re-use the client after it's been closed. If it's proving complicated to maintain support for it while still properly creating our sessions, then we should probably just drop support for `clear()`.

**Comment by aeros** [comment]
> @SebastiaanZ had concerns of whether the object created would be fine with the fact that the loop would temporarily stop running after they're created. There'd be a gap in which the loop is stopped between when the objects are finished being created and when discord.py starts the loop back up to run the bot.

Although I have not specifically tried this w/ aiohttp, I don't believe this will be an issue as long as the event loop is not closed during the "gap". It's definitely worth some experimenting and testing it though to verify it works as intended.

**Comment by MarkKoz** [comment]
This was somewhat addressed in #1333. Basically, I dropped support for `clear()`, which made it possible to await things instead of scheduling background tasks. There shouldn't be any more race conditions of that kind. 

However, there could still be issues where cog `__init__`s have `create_task`s that rely on one of the clients. The client will be `None` until the bot logs in but tasks get scheduled before `client.run()` is even called. The solution would be to have those tasks wait for the ready/guild available events. The idea of using `loop.run_until_complete` for these stills stands.

**Comment by wookie184** [comment]
I don't think this is an issue any more, as all the clients used are guaranteed to be created before they are used:
- For the Discord one: Extensions are loaded from [discord.Client.setup_hook](https://discordpy.readthedocs.io/en/stable/api.html?highlight=setup_hook#discord.Client.setup_hook) which is called after the client is made
- For the main bot one: It's passed in before the bot instance is even made https://github.com/python-discord/bot/blob/e5bab98908f57686a71cae91da13655d56be1f66/bot/__main__.py#L55-L58
- For the site API one: It's created in the `__init__` so can't be used before that https://github.com/python-discord/bot-core/blob/07f517225fc59157233f74edb136ee39046fda00/pydis_core/site_api.py#L69
- For the stats one: It's also created in the setup_hook, https://github.com/python-discord/bot-core/blob/07f517225fc59157233f74edb136ee39046fda00/pydis_core/_bot.py#L272, and this is before the extensions are loaded https://github.com/python-discord/bot/blob/e5bab98908f57686a71cae91da13655d56be1f66/bot/bot.py#L50-L51
