### ISSUE TITLE
Update `!free` tag

### ISSUE THREAD

**Issue by ikuyarihS** [python-discord/bot#960]
## Problem
With the introduction of `#how-to-get-help` - we can safely update the content of the `!free` tag, right now the content is this:

![image](https://user-images.githubusercontent.com/19921765/82914829-2e5f5100-9f9a-11ea-8ee6-4337dd2bcf43.png)

## Proposal
Let's include the id of the `#how-to-get-help` into the tag

The tag can be found here:
https://github.com/python-discord/bot/blob/master/bot/resources/tags/free.md

**Comment by kwzrd** [comment]
That's a good idea. I'll try to figure something out.
