### ISSUE TITLE
Emoji in help channel name sometimes doesn't change when it becomes occupied

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#963]
For example:

![bild](https://user-images.githubusercontent.com/1515135/83082459-6b7a2080-a038-11ea-9872-d66cc4660a66.png)

This needs to be investigated. Current cause is unknown.

**Comment by Numerlor** [comment]
I believe the channel also didn't get moved to the end of the channel list, but started at the top instead if that could be related

**Comment by MarkKoz** [comment]
Fixed by #966
