### ISSUE TITLE
!purge should take an optional set of channels, for mass-purging multi-channel spam.

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/bot#968]
some people will spam several channels. Let's make all !purge commands default to current channel only, but optionally take a list of channels to purge.

**Comment by wookie184** [comment]
An option to clear messages from all channels would also be helpful, so if somebody joins just to spam in a ton of channels we can easily clear it without having to specify all channels individually.

**Comment by j03b** [comment]
Only issue I foresee with multiple channels is that we need to fetch history from multiple channels or store a cache or the last X messages, though I agree it would be useful.

**Comment by lemonsaurus** [comment]
@wookie184 I don't see how this would work. We have 100+ channels, how is it supposed to know which ones you want? Are you gonna delete messages from log channels, announcements, staff channels? Do we have to maintain a list of which channels we should purge from?

I think just specifying them is fine for now.

**Comment by wookie184** [comment]
@lemonsaurus That makes sense, I didn't really think that through fully.
Maybe accepting category names/ IDs as well as channels would allow for clearing from, for example, all topical channels would be possible, but I also agree that just channel names is fine for now, definitely much better than what we had before.

**Comment by lemonsaurus** [comment]
Accepting category IDs wouldn't be too bad, I agree. I don't think I'm gonna do it in #974 though.
