### ISSUE TITLE
Simplify the help system by removing the cooldown when the channel is closed

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#994]
I get the sense that few members appropriately make use of the ability to claim multiple channels. This feature made more sense when the system was first designed because members couldn't close their own channel. Now, it just adds complexity to the code that isn't worth keeping around if no one is relying on this feature. It would be simpler to remove the cooldown when the channel goes dormant rather than having a separate task scheduled for a different time.

Should this ability be removed to simplify the code? I am in favour of removing it. The amount of members claiming multiple channels could be tracked as a stat. However, the removal may be uncontroversial, so that stat may be unnecessary.

I'm setting this to high priority since I foresee this to be very helpful to get out of the way before tackling some of the race condition issues in the system.

**Comment by SebastiaanZ** [comment]
I like the idea proposed, but we need to take a new issue into account that we observed twice in the last two days: Trolls opening and closing channels at a rapid rate. This may have happened before as well, as it was more or less "luck" that we observed the last event; the observation made us look into the logs, which revealed another event from another members just 1.5 day earlier. Both times, a user opened and closed about 20 channels within a few minutes. 

This is obviously not only disruptive, with channels moving quickly all over the place, it will also cause the bot to make a lot of Discord API requests in a very short time frame. Taken together, I think we should no longer automatically removal of the `Help Cooldown` role when someone closes their own channel. The initial idea I had, before I read this issue, was just to always have a 15 minute cooldown for claiming help channels. No exception.

@lemonsaurus added the idea of implementing the channel resurrection command we had in mind to still allow people to continue a previous conversation they had in a channel they closed to rapidly after thinking they had a solution, but didn't.

Anyway, with this in mind, removing the role whenever a channel goes dormant while still allowing the close command to be used would still result in the possibility of doing such a rapid claim->close denial of service attack on our help channel system. We can obviously add some logic to detect this, but I'd rather just make it impossible in the first place.

**Comment by Numerlor** [comment]
I did raise this issue in https://github.com/python-discord/bot/issues/867#issuecomment-609511788, I think the cooldown should remain after going dormant with the new additional api calls involved and a higher influx of new users that potentially may want to do something distruptive.
I think it'd be better to decrease the cooldown to 5 minutes when a channel goes dormant to cover the cases where someone gets an issue solved quickly but then gets a new one after their channel is closed. If that is feasible to implement, decreasing the cooldown when closed would make it more user friendly while keeping the open/close spam away

**Comment by Inheritanc-e** [comment]
But one thing with having a consistent 15-minute cooldown is the question might have had a short answer, and they close the channel.
If they encounter another problem then this makes it so that they can't claim a help channel and might keep on asking their question in other channels
