### ISSUE TITLE
Empty data for watched user

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#999]
Sentry Issue: [BOT-3A](https://sentry.io/organizations/python-discord/issues/1613515206/?referrer=github_integration)

There are over 500 events of this in Sentry. The events tend to be clumped within a relatively small time range of several hours, and these clumps occur weeks or months apart.

My theory is that a user was unwatched but there was a consumption ongoing for them. So despite being popped from the watched_users dictionary, by other methods (like send_header) attempting to retrieve data for the user, the unwatched user got reintroduced into the dictionary (because it is a `defaultdict') with empty data.

```
KeyError: 'actor'
  File "bot/cogs/watchchannels/watchchannel.py", line 189, in consume_messages
    await self.relay_message(msg)
  File "bot/cogs/watchchannels/watchchannel.py", line 226, in relay_message
    await self.send_header(msg)
  File "bot/cogs/watchchannels/watchchannel.py", line 268, in send_header
    actor = guild.get_member(self.watched_users[user_id]['actor'])

The message queue consume task has failed with:
```

**Comment by wookie184** [comment]
I agree with your theory. It looks like there's no need for it to be a defaultdict, so I'll try just making it a dict
